{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.2.0-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.2.0-fabric.jar",
          "size": 268950,
          "sha512": "fd1d37a90f7d9bdc4627d3797afc75be61fa2ebdd931aaa0f4a0a08bd53bd32a4d37cf2565b10f0fccdb1f26dc86bcfe99c3156b88faee075b19afccc726a6e0",
          "sha256": "ba5e6f4d58b0a6a283762f1159f1717efbcfaa2b58bd7cb0d33ba458df460f8e",
          "sha1": "af9e04c3589a97bbdda4fa886e723aa4f10060db",
          "md5": "a4892f570d62afc4451b0852b2c6413c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.2.0-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.2.0-fabric.jar",
          "size": 268950,
          "sha512": "fd1d37a90f7d9bdc4627d3797afc75be61fa2ebdd931aaa0f4a0a08bd53bd32a4d37cf2565b10f0fccdb1f26dc86bcfe99c3156b88faee075b19afccc726a6e0",
          "sha256": "ba5e6f4d58b0a6a283762f1159f1717efbcfaa2b58bd7cb0d33ba458df460f8e",
          "sha1": "af9e04c3589a97bbdda4fa886e723aa4f10060db",
          "md5": "a4892f570d62afc4451b0852b2c6413c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.2.0-sources.jar",
          "url": "horseman-1.20.1-fabric-1.2.0-sources.jar",
          "size": 47177,
          "sha512": "046288cc3d970cb7ca2328f728812a5567160386cd2d3057d9d18b5b10b22ee639989f9933b5972ac8101ebb10233bdc9c192b897aa33aee0dbb99e7aa9b1d11",
          "sha256": "97ad02ab36546600588700b5772574e1f9833a73b6297466311ad7b31973bcc6",
          "sha1": "0dcecda37e299d18b2e9d116d6cdffa5dcea7a91",
          "md5": "a3527f937a689b020ff8eefc6caa6c9d"
        }
      ]
    }
  ]
}
