{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.16-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.16-forge.jar",
          "size": 328666,
          "sha512": "027013b0250c0ab94c81ff8cb56d2c91971f8d24c23d7be64b88dda9392f04c567a7eb4894f2371539588ad7f7854f391ab292b8c1353e82ec3e2fb19789da20",
          "sha256": "9ec528d05e9b56481770efb101cd06639b5ff794f0b69f0e0aeb3f9b68a1e000",
          "sha1": "c169cacedb5ac36d2cc9e37b90f8b7aed8283da3",
          "md5": "dc39d598aff896c2a4746f46ecd48515"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.16-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.16-forge.jar",
          "size": 328666,
          "sha512": "027013b0250c0ab94c81ff8cb56d2c91971f8d24c23d7be64b88dda9392f04c567a7eb4894f2371539588ad7f7854f391ab292b8c1353e82ec3e2fb19789da20",
          "sha256": "9ec528d05e9b56481770efb101cd06639b5ff794f0b69f0e0aeb3f9b68a1e000",
          "sha1": "c169cacedb5ac36d2cc9e37b90f8b7aed8283da3",
          "md5": "dc39d598aff896c2a4746f46ecd48515"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.16-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.16-sources.jar",
          "size": 88357,
          "sha512": "75291d699dd2a34ff70163672756aa8ecb06d74b13cb6f0a6893bbefbd852007ea34af9d5b6d1b369ea3ef3f484fa16e592b2d42b97f7a64ee11b9ef1efb882b",
          "sha256": "4ea5d48c5a4eb5426ec33c67bcfb5a39e67deee34e4b7f1d5b0dcd5f5cf9e7ce",
          "sha1": "326fdbcb3434b8799435761504406838eddb41e9",
          "md5": "337a55beeae6499716d170bd516a925f"
        }
      ]
    }
  ]
}
