{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.19.jar",
          "url": "exposure-1.21.1-neoforge-1.9.19.jar",
          "size": 2206392,
          "sha512": "b6b18638d61196c3b579dcb5cd977b125586c848822ffa3bb247b3d34dc019e3ca53629303cbb57c0875f7e29be30ae036e81d90dd8feb5dd87090b2b81c08b7",
          "sha256": "c3579a314f77a9368c8312a1ace1dc8d510590869f7589b8ab3df24c42adca2f",
          "sha1": "181d328a0328523fa99dd310937c40d917e91029",
          "md5": "1a71e20f6551adf0780f61037d6cefac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.8-168"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.64"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "essentialsmod",
          "version": {
            "requires": "y6XzoYMQ"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "crossroads",
          "version": {
            "requires": "EgSYNn26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "refined-storage",
          "version": {
            "requires": "lHHiI26k"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.19.jar",
          "url": "exposure-1.21.1-neoforge-1.9.19.jar",
          "size": 2206392,
          "sha512": "b6b18638d61196c3b579dcb5cd977b125586c848822ffa3bb247b3d34dc019e3ca53629303cbb57c0875f7e29be30ae036e81d90dd8feb5dd87090b2b81c08b7",
          "sha256": "c3579a314f77a9368c8312a1ace1dc8d510590869f7589b8ab3df24c42adca2f",
          "sha1": "181d328a0328523fa99dd310937c40d917e91029",
          "md5": "1a71e20f6551adf0780f61037d6cefac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.19-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.19-sources.jar",
          "size": 39269,
          "sha512": "a39d6b6a1995e25b253c888805c579aff4b5bec8c0579edf27e56574454ea6a9328eff5afdb5cd05a488d57ddef4c935a1bc4c58e14de0b38092c8f479a31720",
          "sha256": "52ab509124ffc37208df09a89b3aa2385430d1b85001e19a77d028e0cbdbb21f",
          "sha1": "a7ff01d91d79090bd58a7cca60c9fc380d739fb4",
          "md5": "bb667ebc6f168aab52abdc6e597ee42d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.19-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.19-dev-shadow.jar",
          "size": 1988154,
          "sha512": "2b43428d1b37e11c371b14c446f800cf566b05f1abd12aa0cbff72081eeb47cdffccf64bf98035628a86bae51bae2e3d1c55543ab8cb26f63c59272b421457de",
          "sha256": "da03488184819cbcdfaf083027c8ef15ed3bb33776da43003c5907674c00a023",
          "sha1": "ed3959add5e61f6890c787884d413e9d0bf24eab",
          "md5": "cae724df3e8db4d130cf0809769466be"
        }
      ]
    }
  ]
}
