{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-neoforge",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0.jar",
          "url": "sootychimneys-neoforge-1.3.0.jar",
          "size": 168546,
          "sha512": "ff7bde5900e866fa4a1d61c6eb6ec5c9a41c4bde4b2fb73a4e3b762cdcbf363458f6e10090a6fefd37b505ec851d828ade671fe321f778956a75cca08a2dd4b8",
          "sha256": "0f8cf859131af212b22109f678f3fb8d94ed7a088dde6a39a6f798730931dbd4",
          "sha1": "433bdf25da07ef07960239a0b5383c59a9cdd253",
          "md5": "81067680d00f906ea73691fd58242243"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0.jar",
          "url": "sootychimneys-neoforge-1.3.0.jar",
          "size": 168546,
          "sha512": "ff7bde5900e866fa4a1d61c6eb6ec5c9a41c4bde4b2fb73a4e3b762cdcbf363458f6e10090a6fefd37b505ec851d828ade671fe321f778956a75cca08a2dd4b8",
          "sha256": "0f8cf859131af212b22109f678f3fb8d94ed7a088dde6a39a6f798730931dbd4",
          "sha1": "433bdf25da07ef07960239a0b5383c59a9cdd253",
          "md5": "81067680d00f906ea73691fd58242243"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0-sources.jar",
          "url": "sootychimneys-neoforge-1.3.0-sources.jar",
          "size": 9435,
          "sha512": "4c79eb190e134905f111a6574eb13c42d7c77476bef8bb06fcad6ba880058f41bcab3d503bee8e3c4195891ae53faf12fd2d0427f0ac76e530ed77547a91d039",
          "sha256": "654503eae592e5de808f0a5cd69825c91e5554dc1f6dc760034fb7954f883ad1",
          "sha1": "8dfdcc6770694ede415a0c3da40226e177070775",
          "md5": "99a42014e66075bf43cbeb8cbca5cc0c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0-dev-shadow.jar",
          "url": "sootychimneys-neoforge-1.3.0-dev-shadow.jar",
          "size": 163666,
          "sha512": "72dbfa61705458fb2b13129b36f4baa4e0a96a3b0970a23ac6cd85d202fc5995c45e1799d3286d7a4edf0360dd40083c44316307a1ec6937549495c3f46c634f",
          "sha256": "959e4a0a64242690ad3c3772984a3b9d07915cdf8bec6863b4af3b45d853fb41",
          "sha1": "cc4dd11da7803eb05aa184110cc0b44b53f97521",
          "md5": "0dc824b814c2321e25267b5a7d04fa93"
        }
      ]
    }
  ]
}
