{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-neoforge",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0.jar",
          "url": "sootychimneys-neoforge-1.3.0.jar",
          "size": 168546,
          "sha512": "ff7bde5900e866fa4a1d61c6eb6ec5c9a41c4bde4b2fb73a4e3b762cdcbf363458f6e10090a6fefd37b505ec851d828ade671fe321f778956a75cca08a2dd4b8",
          "sha256": "0f8cf859131af212b22109f678f3fb8d94ed7a088dde6a39a6f798730931dbd4",
          "sha1": "433bdf25da07ef07960239a0b5383c59a9cdd253",
          "md5": "81067680d00f906ea73691fd58242243"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0.jar",
          "url": "sootychimneys-neoforge-1.3.0.jar",
          "size": 168546,
          "sha512": "ff7bde5900e866fa4a1d61c6eb6ec5c9a41c4bde4b2fb73a4e3b762cdcbf363458f6e10090a6fefd37b505ec851d828ade671fe321f778956a75cca08a2dd4b8",
          "sha256": "0f8cf859131af212b22109f678f3fb8d94ed7a088dde6a39a6f798730931dbd4",
          "sha1": "433bdf25da07ef07960239a0b5383c59a9cdd253",
          "md5": "81067680d00f906ea73691fd58242243"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0-sources.jar",
          "url": "sootychimneys-neoforge-1.3.0-sources.jar",
          "size": 9435,
          "sha512": "4690cd6abdeae42507bef0baef90fd59d2b59246ac367d6860a2c8e4f174794ea178d4bf07db6ad8547d13860bd586380e0022445edd63af216e5895922f5ff4",
          "sha256": "0cb679306c7c3ce16a3b5974e4c2fbce556b0bacee6fbacbaec70a5b027936e2",
          "sha1": "3962a91a9c80f344bfaee2dae9c92bf61c0a9bf5",
          "md5": "c391d1e81b230547dfc73d29a49bcc4b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.0-dev-shadow.jar",
          "url": "sootychimneys-neoforge-1.3.0-dev-shadow.jar",
          "size": 163666,
          "sha512": "cb755cebd0f1b04c9d6cc51b2b421b268fa14b34950c116a7135878ea674999a2b6aabb2d22acc477171dc2251d7b083bf64a682b137837a04378996a477860e",
          "sha256": "70a2f8c54f764de958a5da6bfcb72ed52aa825af219fce22871346c6b7549fc0",
          "sha1": "1c28fbd50c5396ee6fe0b52041c0449114401805",
          "md5": "238c114e172a1aaa792c88d5b8ccd0a9"
        }
      ]
    }
  ]
}
