{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.chalk",
    "module": "chalk-1.21.1-common",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.25.0.322"
          }
        }
      ],
      "files": [
        {
          "name": "chalk-1.21.1-common-2.0.2.jar",
          "url": "chalk-1.21.1-common-2.0.2.jar",
          "size": 411030,
          "sha512": "1b40fc59ad51615f421cf74821773179df3db61cde298cdb921d6d2f09765a04b7cb0092980de85f6662fa3638e3af6616272263fa1d0c5140e3d1553e3f199c",
          "sha256": "0ab562dbeb86b2abf21a92d034fd7ec37add5e1fb0418a688125ee594282b07f",
          "sha1": "e6770336b25152f81e022187776180f3df613911",
          "md5": "53983fdb8ddf81a14ddd0f40215aabcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "chalk-1.21.1-common-2.0.2.jar",
          "url": "chalk-1.21.1-common-2.0.2.jar",
          "size": 411030,
          "sha512": "1b40fc59ad51615f421cf74821773179df3db61cde298cdb921d6d2f09765a04b7cb0092980de85f6662fa3638e3af6616272263fa1d0c5140e3d1553e3f199c",
          "sha256": "0ab562dbeb86b2abf21a92d034fd7ec37add5e1fb0418a688125ee594282b07f",
          "sha1": "e6770336b25152f81e022187776180f3df613911",
          "md5": "53983fdb8ddf81a14ddd0f40215aabcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chalk-1.21.1-common-2.0.2-sources.jar",
          "url": "chalk-1.21.1-common-2.0.2-sources.jar",
          "size": 284628,
          "sha512": "f03d5278eab70a436ee62f8fb40f46bd3ba54df75120cf318d7f7b45d39edfe6f2afb8ecf5b925a9349c1a7d1f0a3d52dd815015b03fb9817fc2e5926ebce01e",
          "sha256": "ddad3b5676754087f5bd28034d9460e881948047048680b1a0d59c27b04eee81",
          "sha1": "e2cda9b236329866aad64bf249a041cb823866ab",
          "md5": "bb7722c0893d1e4b04e8cdbaee766169"
        }
      ]
    }
  ]
}
