{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.2-fabric.jar",
          "url": "horseman-fabric-1.1.2-fabric.jar",
          "size": 261722,
          "sha512": "c63c412a40ab31d00cfbb39454872f7da9ad7d391b45a6ab59a964cfd4076e81cbb9c240e0a3866096323d4c52a082fe0e39c135ef4d133066a0004527ce946a",
          "sha256": "2c31ce77f580ddfc246d6c1bacd18d60d2767ca5d1f6c976fc0ce2c7d6d7cea6",
          "sha1": "1efb9c1cd4bec6a7a6b312de0498f50339fb1875",
          "md5": "8e8b645606bc0c998cc641d320a000b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.2-fabric.jar",
          "url": "horseman-fabric-1.1.2-fabric.jar",
          "size": 261722,
          "sha512": "c63c412a40ab31d00cfbb39454872f7da9ad7d391b45a6ab59a964cfd4076e81cbb9c240e0a3866096323d4c52a082fe0e39c135ef4d133066a0004527ce946a",
          "sha256": "2c31ce77f580ddfc246d6c1bacd18d60d2767ca5d1f6c976fc0ce2c7d6d7cea6",
          "sha1": "1efb9c1cd4bec6a7a6b312de0498f50339fb1875",
          "md5": "8e8b645606bc0c998cc641d320a000b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.1.2-sources.jar",
          "url": "horseman-fabric-1.1.2-sources.jar",
          "size": 43068,
          "sha512": "6cefd626e2fec3a6d7622572cb016c6f51f68566a4f6362858e5e809385e0f1275181cfe9317e4fa81c331838fdeaf95f092e3ba78de68e0e1d117b85f102dbf",
          "sha256": "91d4b8833fbafb03608a7ee152688f2e91ce8222d6c59c4851b09a57a8670bea",
          "sha1": "ea8fc715d1b5554ed6d467cbbfabdf88e0ea87d9",
          "md5": "b656251430b7ed18e196bbb9bf0265ff"
        }
      ]
    }
  ]
}
