{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.8-fabric",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.8-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.8-fabric-1.3.4.jar",
          "size": 169824,
          "sha512": "abdac9f5542acdcbe97a4e3b42f421f6aa40f1f27da1a3a85d4f139013c135555de8bac32eb65b12db13943060139e5b0a0ffb9dff389b57c2198635f06b9f55",
          "sha256": "3826344178f7ed2e38183505f2660551ce51b7710869b1ce9be6574042d65bb1",
          "sha1": "4c5a725deb4598054caf0f6e72c425bf23faf8c7",
          "md5": "3f6656fd85995c2ba9cf6d44085955c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.136.1+1.21.8"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.8-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.8-fabric-1.3.4.jar",
          "size": 169824,
          "sha512": "abdac9f5542acdcbe97a4e3b42f421f6aa40f1f27da1a3a85d4f139013c135555de8bac32eb65b12db13943060139e5b0a0ffb9dff389b57c2198635f06b9f55",
          "sha256": "3826344178f7ed2e38183505f2660551ce51b7710869b1ce9be6574042d65bb1",
          "sha1": "4c5a725deb4598054caf0f6e72c425bf23faf8c7",
          "md5": "3f6656fd85995c2ba9cf6d44085955c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.8-fabric-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.8-fabric-1.3.4-sources.jar",
          "size": 7433,
          "sha512": "23d1b90b7731bad461f946b5a3d56ac7659b7d37b748dd1f738b512c1a6732b2fc792421997f738e1145f4fdb066ac4aa306180e31a02d5695c61b7848e68e46",
          "sha256": "98c0b1401b110620eb7b2784432d1ba8000e8f36d7e1f7e22c0ecb823baea1d0",
          "sha1": "1eb92f4c0d2ef5269a4bcdbb504316de018f1d08",
          "md5": "a54e3536b47b54932e58963eaccdb34e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.8-fabric-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.8-fabric-1.3.4-dev-shadow.jar",
          "size": 166118,
          "sha512": "794408fd215bcca4322e7e9689f994d17510e2fe0cb138499e776d8476d0a8a6f0516b46acc46ed8a45fe225f1c5255bd32634932e677014c91516039bad7f9e",
          "sha256": "372ffff36e882646d082efa313585cbb408aaad291edcbde39a92e6b0d617044",
          "sha1": "64d6c90a7834608d0ff223b73e3251022bf15494",
          "md5": "bba883530ddde38c2361353c1c264d75"
        }
      ]
    }
  ]
}
