{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.4-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.4.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.4-common-api",
          "version": {
            "requires": "20.0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-common-1.3.4.jar",
          "url": "sootychimneys-1.21.4-common-1.3.4.jar",
          "size": 164661,
          "sha512": "e035bb7b143885a67a43ab7e19e19907dfa2829d0267327e4446a85da2bc509b09ff7fb96c441e42f5304545dce66675bb35f7e6c8df368fadfea68651b26ed1",
          "sha256": "253f5b3f91a1cf53f0c1c4057df6b939e8ccbe20c5efd6d70a074f612157cf26",
          "sha1": "9ec7f18ac59a0de987a90dfe6480951d0efe0eea",
          "md5": "116bb29f6b2a767321b07d05cda568a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-common-1.3.4.jar",
          "url": "sootychimneys-1.21.4-common-1.3.4.jar",
          "size": 164661,
          "sha512": "e035bb7b143885a67a43ab7e19e19907dfa2829d0267327e4446a85da2bc509b09ff7fb96c441e42f5304545dce66675bb35f7e6c8df368fadfea68651b26ed1",
          "sha256": "253f5b3f91a1cf53f0c1c4057df6b939e8ccbe20c5efd6d70a074f612157cf26",
          "sha1": "9ec7f18ac59a0de987a90dfe6480951d0efe0eea",
          "md5": "116bb29f6b2a767321b07d05cda568a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.4-common-1.3.4-sources.jar",
          "size": 106868,
          "sha512": "88ccb3e0d15124875a584f538cd94fc02a8f418ae4cfd21e12a3f51feacb0403d51a5816e3cd3ec593c5df38b6e20280134c9a7d0d54551f23889fc4764e2e9a",
          "sha256": "5512016408e771133045f4f7f82d6303d1d045651468e17bfac81d76d5909483",
          "sha1": "2daeb92292fe503fe3a2b2c4f43b0f3d38a067d5",
          "md5": "ebf03c88ec7f852d530899b8ce56e763"
        }
      ]
    }
  ]
}
