{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-forge",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exposure_catalog-forge-1.0.1-forge.jar",
          "url": "exposure_catalog-forge-1.0.1-forge.jar",
          "size": 145114,
          "sha512": "14195e201d8dffccf84e3e810920d431ee2928841bcb45369a3d6246c03552120059c839e7a6c831d7903bd235357ee998b4af51410853f3fc670b63eb21b0fa",
          "sha256": "ae8729a06b7c36f8f32692bbf3a96182cc5eed661945dfd0346ab28288dd6090",
          "sha1": "eac6a0db158a98b1e269031e8c8aae3a11e0e3c2",
          "md5": "4a77826f1c3e226ea8c0bc733e8f6403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-forge",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-forge-1.0.1-forge.jar",
          "url": "exposure_catalog-forge-1.0.1-forge.jar",
          "size": 145114,
          "sha512": "14195e201d8dffccf84e3e810920d431ee2928841bcb45369a3d6246c03552120059c839e7a6c831d7903bd235357ee998b4af51410853f3fc670b63eb21b0fa",
          "sha256": "ae8729a06b7c36f8f32692bbf3a96182cc5eed661945dfd0346ab28288dd6090",
          "sha1": "eac6a0db158a98b1e269031e8c8aae3a11e0e3c2",
          "md5": "4a77826f1c3e226ea8c0bc733e8f6403"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-forge-1.0.1-sources.jar",
          "url": "exposure_catalog-forge-1.0.1-sources.jar",
          "size": 74021,
          "sha512": "fe332bc57c13f031350f120360bad30db59ad88afc21d5ccd164508a34a3ad23acc4b12f5103cdf0c23346f853f61fb60c47dfdb8da4e39b6a7e4a77ddc51b52",
          "sha256": "9adc0a25f4a76349fb25951930f2f11c72eb43f2d8e74853533530c3b2d9be01",
          "sha1": "2bd9840d13e94d3e96bed4fd658105bdec1f52b6",
          "md5": "0e06e5751b4abc762e88a66044451bcd"
        }
      ]
    }
  ]
}
