{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-common",
    "version": "1.21.1-1.1.1-snapshot1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exposure_catalog-common-1.21.1-1.1.1-snapshot1.jar",
          "url": "exposure_catalog-common-1.21.1-1.1.1-snapshot1.jar",
          "size": 131607,
          "sha512": "2857940d2b74e1246e2851b584c4e08f942817639543f3921b1e7badf754a59585e018d6ce13e5db847224a843bf983e23cec02d382622838119f1db2b88e4a3",
          "sha256": "335457e0ea5b7554ad6abebfa9ef5a0c8dbc66d14d7ad49abe6e9921c3a44539",
          "sha1": "a13fdac6fa27c26c89748ce492dc6200065e58f5",
          "md5": "aecf9e9e46aed5b468768b21f3b84885"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-common",
          "version": {
            "requires": "1.21.1-1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-common-1.21.1-1.1.1-snapshot1.jar",
          "url": "exposure_catalog-common-1.21.1-1.1.1-snapshot1.jar",
          "size": 131607,
          "sha512": "2857940d2b74e1246e2851b584c4e08f942817639543f3921b1e7badf754a59585e018d6ce13e5db847224a843bf983e23cec02d382622838119f1db2b88e4a3",
          "sha256": "335457e0ea5b7554ad6abebfa9ef5a0c8dbc66d14d7ad49abe6e9921c3a44539",
          "sha1": "a13fdac6fa27c26c89748ce492dc6200065e58f5",
          "md5": "aecf9e9e46aed5b468768b21f3b84885"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-common-1.21.1-1.1.1-snapshot1-sources.jar",
          "url": "exposure_catalog-common-1.21.1-1.1.1-snapshot1-sources.jar",
          "size": 74037,
          "sha512": "e8d8ec93c469871dd40319b58394ec5931f83b894bf1baf7141a7c1aae98f0f9cf3233ace5258f1e4759dd1f09d5e0ffd364c7b37d557baffe2567cca31f4348",
          "sha256": "b6299ef5e37153198474c8617af93515434259f23e2b6af3c9d8118b367b8b4a",
          "sha1": "1a02b03cd3467fbb738028d9b7a0185086bfdb70",
          "md5": "93733fbc1002e7e4a2ef97e060ddd610"
        }
      ]
    }
  ]
}
