{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.0.0.jar",
          "url": "thief-1.20.1-common-1.0.0.jar",
          "size": 111211,
          "sha512": "e32ffd8df5025de295265205919f4ad7330bfae2f87ea0a0c63408afa73e4a394bcf4b27ca88d86f045f1b2a9156f8da0cdbea582d5a5b7a26679dc8793aafbf",
          "sha256": "89e227c5db5dd86e67b0bb728802d5ef6f7f8f7faa0809fa4b60ce1cab8468a5",
          "sha1": "1ee15f471cba0a8a3f1053013c15a59ef1b31df6",
          "md5": "109ae983471694825308e1ac47d154a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.0.0.jar",
          "url": "thief-1.20.1-common-1.0.0.jar",
          "size": 111211,
          "sha512": "e32ffd8df5025de295265205919f4ad7330bfae2f87ea0a0c63408afa73e4a394bcf4b27ca88d86f045f1b2a9156f8da0cdbea582d5a5b7a26679dc8793aafbf",
          "sha256": "89e227c5db5dd86e67b0bb728802d5ef6f7f8f7faa0809fa4b60ce1cab8468a5",
          "sha1": "1ee15f471cba0a8a3f1053013c15a59ef1b31df6",
          "md5": "109ae983471694825308e1ac47d154a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-common-1.0.0-sources.jar",
          "url": "thief-1.20.1-common-1.0.0-sources.jar",
          "size": 62838,
          "sha512": "602d95768c903b51303acba91b43a736773e99a096a41677e7b5bb607c7a04aa85152a0527151fc80f9279d5add1c5fe97f93db7121126490257e3efe0ae855d",
          "sha256": "bec16e2aa00b20df8bbe9baffa5b9ba89087f18ca8cdc16baf4128ee432d1e59",
          "sha1": "c8461026808a4af1f832316253ee3a1caba7c40c",
          "md5": "0d4f8f44fb994f554be3aef0497795fa"
        }
      ]
    }
  ]
}
