{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.9-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.9-forge.jar",
          "size": 329038,
          "sha512": "f1293cf139c94f924725dc586aa8122eda6959ba6bfaec6c21a1a0afd1a6b388e93e45cb4d90128f58658f4f197fdbb19d5c0dbb81d99ca30abc89d5d267aeb9",
          "sha256": "6e1a7b99d76ad01779df1d43d28eb80763883d9624e21970c4af2cdcbf48d364",
          "sha1": "28451b06cc66b1e6aff7d08604affdce4ab1276d",
          "md5": "1baebfd9ff89103bad66ef03ef2f935f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.9-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.9-forge.jar",
          "size": 329038,
          "sha512": "f1293cf139c94f924725dc586aa8122eda6959ba6bfaec6c21a1a0afd1a6b388e93e45cb4d90128f58658f4f197fdbb19d5c0dbb81d99ca30abc89d5d267aeb9",
          "sha256": "6e1a7b99d76ad01779df1d43d28eb80763883d9624e21970c4af2cdcbf48d364",
          "sha1": "28451b06cc66b1e6aff7d08604affdce4ab1276d",
          "md5": "1baebfd9ff89103bad66ef03ef2f935f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.9-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.9-sources.jar",
          "size": 88835,
          "sha512": "d03393ec603ffd95e3001749dcb08dd4f6185280136c66d47a174abf24a7a15fc22cd52b6c2752b7015cca6733a9ef464f0d9bb4b0c29eb0c76bebb3a0989f7e",
          "sha256": "21f5bd6bed499481c6dcc4ccc5297ded16f6512f6c995535ba9ca6a751f882ab",
          "sha1": "57d7b0803a27902d39a728e960b2d077fd115943",
          "md5": "e7a53fe1b7da847e97b861bb175dedde"
        }
      ]
    }
  ]
}
