{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.5-snapshot4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot4.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot4.jar",
          "size": 1917859,
          "sha512": "be52b7d0cff63c8b5206ab808bbd3f8633644c55fdde5f76f754ce09151f1f01d8588fea1645657b9c8a55fa9c1782bff36f3ed1dc7a9824be0c1cc465d4c434",
          "sha256": "438cb5b02b29e4c9175a00484839750aa7fa1a02ff9e170a3ec097ab9ad797d2",
          "sha1": "4bec802da1ad7a104e9460808b95d7f0974a8dee",
          "md5": "08e238b0b265d71d0c7c1b0416a516ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot4.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot4.jar",
          "size": 1917859,
          "sha512": "be52b7d0cff63c8b5206ab808bbd3f8633644c55fdde5f76f754ce09151f1f01d8588fea1645657b9c8a55fa9c1782bff36f3ed1dc7a9824be0c1cc465d4c434",
          "sha256": "438cb5b02b29e4c9175a00484839750aa7fa1a02ff9e170a3ec097ab9ad797d2",
          "sha1": "4bec802da1ad7a104e9460808b95d7f0974a8dee",
          "md5": "08e238b0b265d71d0c7c1b0416a516ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot4-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot4-sources.jar",
          "size": 36413,
          "sha512": "e057adb6f9472d2da4b0f5053a532be1bd2694c2dcbc3ef67f95e502ff41b79c0ff89783ee8304ba151828fe4d4471b3c16b102c859710251323bdba79b9c46d",
          "sha256": "38478fdf5b0ec64b75bb32cd0bc535fc5e076253f0703dddae0886fc5ae908a0",
          "sha1": "7c7ffc850ec1a5cabfbc4406141e17820576f725",
          "md5": "e9a59cdb511116a88736ae60e4d02156"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot4-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot4-dev-shadow.jar",
          "size": 1704545,
          "sha512": "5677af907a8f7f7659f73e36e1d8172fd9399b0dde768f398cb5316deea32e166f47affe1f79297b64d2693b5d675eb4ebb78f236e101dbcbdc0cc57bb22e913",
          "sha256": "eb74387c10483b776f8a62680c906291f20bc8cc84a2602189a56b783216f957",
          "sha1": "aa9a9c4d78f38be93627fa7cb428242324befc1c",
          "md5": "b8ff34c9555f79b0071e17e663ca8f43"
        }
      ]
    }
  ]
}
