{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.17-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.17-forge.jar",
          "size": 328678,
          "sha512": "1c1bc38cbce907604b8039f0385390215a9a23db89c0ba6e9cbc9ef8c40fea65f3bb7de329317ddb8b7da4ebbe4e357b3c72639104920b75d8342904318d0427",
          "sha256": "51ed74329bce5091bbb7969d08156190d590290d9caff2999ed167a146458af0",
          "sha1": "1fb13dc7c49e23fb4253c63186dcf956b25edd13",
          "md5": "e654cd19c2e85dd3d596f87ce219e5f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.17-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.17-forge.jar",
          "size": 328678,
          "sha512": "1c1bc38cbce907604b8039f0385390215a9a23db89c0ba6e9cbc9ef8c40fea65f3bb7de329317ddb8b7da4ebbe4e357b3c72639104920b75d8342904318d0427",
          "sha256": "51ed74329bce5091bbb7969d08156190d590290d9caff2999ed167a146458af0",
          "sha1": "1fb13dc7c49e23fb4253c63186dcf956b25edd13",
          "md5": "e654cd19c2e85dd3d596f87ce219e5f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.17-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.17-sources.jar",
          "size": 88364,
          "sha512": "18080996867e8e0d2e2fd9ebe0e3caa72a3b09a00668d04063d978f3da331f7b01c87dd699f6dea0c618a5676265674da99f22b260dde77ae9db006376d382a5",
          "sha256": "97631fb90e80e1feab1ed751194214c32060aa2adbc1294f36442425ab931b48",
          "sha1": "90c6d4deae390e590aea6f856614527d00bc1c5d",
          "md5": "8c602f6e76565d5f4eb7057c6fcfeb6c"
        }
      ]
    }
  ]
}
