{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.5.1.jar",
          "url": "horseman-1.21.1-fabric-1.5.1.jar",
          "size": 247963,
          "sha512": "1276db53a911a7fd348c61b6e1fff121be2b67d65198c1623acc4d080ef3cc3026e2af4cfab16595156d7d7d568fe4d941a276ec4f3444e1932d47dd5152de2d",
          "sha256": "f1759e8d7c33a99f9da2f47a52aefb23c295bf8fc127d4432693933b3d18b9ff",
          "sha1": "7b8a2f65aa767a10441701d4fb5b96f5327c752e",
          "md5": "ec1aeaebf234a5d08a0732199d615ae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.5.1.jar",
          "url": "horseman-1.21.1-fabric-1.5.1.jar",
          "size": 247963,
          "sha512": "1276db53a911a7fd348c61b6e1fff121be2b67d65198c1623acc4d080ef3cc3026e2af4cfab16595156d7d7d568fe4d941a276ec4f3444e1932d47dd5152de2d",
          "sha256": "f1759e8d7c33a99f9da2f47a52aefb23c295bf8fc127d4432693933b3d18b9ff",
          "sha1": "7b8a2f65aa767a10441701d4fb5b96f5327c752e",
          "md5": "ec1aeaebf234a5d08a0732199d615ae1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.5.1-sources.jar",
          "url": "horseman-1.21.1-fabric-1.5.1-sources.jar",
          "size": 18569,
          "sha512": "049f2579819acd8bf8e871df4c6b45b9869d1819e9b38a39829ba6671c65766d9d1322d80f3d468c8207e3699ac7629d16faca412586c36eb0dcca486a0367fc",
          "sha256": "36f342983c8873dac6d83a289aa350cd05151a33ae57272406597c7becded8aa",
          "sha1": "f3c1bb6e5fce3a22793a16e711842483c807fef2",
          "md5": "5c15e4218a9d087181ba523a9ba0c563"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.5.1-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.5.1-dev-shadow.jar",
          "size": 245936,
          "sha512": "42e94d3e15c0f549f4d08e74e15922fc867287b7bc50f496dec5decdb964cd1b77c48ca34533c32149647e09ae4473e649f1925d263e170562a9bc7a4b4d000d",
          "sha256": "3419318a231bed846b3c60f8a6317ad07469f4075c05e70cbb65b9571207b483",
          "sha1": "48b4efc5674df20e3b0413ca1f69628dc0a2dd26",
          "md5": "c18669829f164359a093ea4f164b74ed"
        }
      ]
    }
  ]
}
