{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.4-fabric",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.4-fabric-1.3.4.jar",
          "size": 169919,
          "sha512": "2cd35bc1fe5f27eee14390dac953077a061a5b9bbbd76da6e515b086e062f9ff92778a840704f90c427f6f1664b7a21216923f7c910114ca7df54ef726341224",
          "sha256": "788fa7873d39faf86246c7d6688b199c9bf2cc715d46185df47f4466f2e62bbf",
          "sha1": "9c0d46c97992370522ca1d82a386a2b27263d3ac",
          "md5": "7a7d3563e668c10ba47f3b9d2ca92402"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.3+1.21.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.4-fabric-1.3.4.jar",
          "size": 169919,
          "sha512": "2cd35bc1fe5f27eee14390dac953077a061a5b9bbbd76da6e515b086e062f9ff92778a840704f90c427f6f1664b7a21216923f7c910114ca7df54ef726341224",
          "sha256": "788fa7873d39faf86246c7d6688b199c9bf2cc715d46185df47f4466f2e62bbf",
          "sha1": "9c0d46c97992370522ca1d82a386a2b27263d3ac",
          "md5": "7a7d3563e668c10ba47f3b9d2ca92402"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-fabric-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.4-fabric-1.3.4-sources.jar",
          "size": 7452,
          "sha512": "eb530a47faebdc6c3ea1bebf7429685bf6fd0912972d3057c127e664f79cbe73d40006759dc40e571cd378fe0e92d32b05383b354772c4b9d5813c8e580cfd6c",
          "sha256": "fd22e8e94d4cc33066b789349f2330f3a0a9fc384e345165e51812800198c8dd",
          "sha1": "6e4c7a724b2a940d6d118f8c2cb8a3c52ccfcff1",
          "md5": "f1c00e6cf8dfc03d94c4ff260ee3a3b3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-fabric-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.4-fabric-1.3.4-dev-shadow.jar",
          "size": 166229,
          "sha512": "782a1cffa9b62c441e4b8accdb9561921acbb85aa0360cc885d70bacafed40b811bd1bba4376d18c67d6a65770db8c8610d17040ff9b1c5c63aba9e1d70736db",
          "sha256": "4a0aaac945f5a0bd5f91f452d5538997bbbd0d92c9a4fda080fb1ae6873d97d0",
          "sha1": "87e1d81f47c2338f67c89ff531c5b087db0ab1bf",
          "md5": "263cd3d381ccee961e98f0e1b42bd963"
        }
      ]
    }
  ]
}
