{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.10.jar",
          "url": "exposure-common-1.7.10.jar",
          "size": 1287062,
          "sha512": "7d8569b23a17a2c11ac639f20bb889241a34bf37702ebf765c34d5619adb4982721f472a48656d5d96e04ec7a43f435b4cb4976578aa52563a0e13e02647039a",
          "sha256": "981e5d6be33bef6b69b976d04eb93a30622aee1af537e1c0ae1e3fe8094b48e5",
          "sha1": "d9351a64a0c67ab2196c9001d61a73fdc31cb415",
          "md5": "e193ac6ff4ca428b9f6ab5e02a724833"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.10.jar",
          "url": "exposure-common-1.7.10.jar",
          "size": 1287062,
          "sha512": "7d8569b23a17a2c11ac639f20bb889241a34bf37702ebf765c34d5619adb4982721f472a48656d5d96e04ec7a43f435b4cb4976578aa52563a0e13e02647039a",
          "sha256": "981e5d6be33bef6b69b976d04eb93a30622aee1af537e1c0ae1e3fe8094b48e5",
          "sha1": "d9351a64a0c67ab2196c9001d61a73fdc31cb415",
          "md5": "e193ac6ff4ca428b9f6ab5e02a724833"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.10-sources.jar",
          "url": "exposure-common-1.7.10-sources.jar",
          "size": 929528,
          "sha512": "97d9199ffd0ab1f16d73fdf74e21a19ef3ca712159888e9ec13c6695053294c6189e70838948f7a9d5d474fd889e3027006fbb245bc4a3f9f7131219eb517e21",
          "sha256": "1dcb8236a0c1aa8fd3e796524e2e24d27e96a38dbc368ad13f8903b5caf77bc6",
          "sha1": "3826f2e9f19164d980bfd7ff5218a40bf6222932",
          "md5": "2403544a20f9baf3267af20e3291c981"
        }
      ]
    }
  ]
}
