{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-neoforge",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.4.jar",
          "size": 176352,
          "sha512": "64b80a09362aaf7bf08362b5d78a5c12491123509c265420c9f6613c821bbb7bc062e3793353ca03039ab0979fdb3ce050835056fcd7ccf900ee4b44a9d62977",
          "sha256": "039c2bec63c5ea59961edb18d7beb308eb673d742e7f4f94e687fd188027cb79",
          "sha1": "84f1ed36006d8ea77d6c7df1be3f6a8779a09779",
          "md5": "a7a89223b6b0d349a2086e76547e5e20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.3-47"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.45"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.4.jar",
          "size": 176352,
          "sha512": "64b80a09362aaf7bf08362b5d78a5c12491123509c265420c9f6613c821bbb7bc062e3793353ca03039ab0979fdb3ce050835056fcd7ccf900ee4b44a9d62977",
          "sha256": "039c2bec63c5ea59961edb18d7beb308eb673d742e7f4f94e687fd188027cb79",
          "sha1": "84f1ed36006d8ea77d6c7df1be3f6a8779a09779",
          "md5": "a7a89223b6b0d349a2086e76547e5e20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.4-sources.jar",
          "size": 13231,
          "sha512": "d468a56bba1c090555844763a39a21e7403a83afb9f750a2830941e48c5df31d9adf8c6e782e5b6e921746822b773cd80895e5a101f9ee62147d410e68f9ea88",
          "sha256": "be04c5bb6c5ccb3a2202ab9cf2c72c3e2703b8af8b403b2b259403bef714a701",
          "sha1": "493e81adf94a1fb124475b20985793aefc9a83ea",
          "md5": "04e8d916cf5c7733cb076cd9c2180a1d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.4-dev-shadow.jar",
          "size": 171375,
          "sha512": "bd903990a5e12dba9f76d8ec6db321ab0629999d47ff7f30bc0872309093c20e86ccb361848adb2a1128cc8fc69de4768f4a4d32ac1c87a893193a3e5035e26d",
          "sha256": "d0c398beb677e7ffddb847839b0d60df7ea64fc8b9298111203b0a7f1ffbcb92",
          "sha1": "f62da64780cd7fee569e1dbb3df5c80f2fdc5731",
          "md5": "56eb8387db44238efb695330fdbc100e"
        }
      ]
    }
  ]
}
