{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.13-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.13-forge.jar",
          "size": 329125,
          "sha512": "214a9e73c21f8db32442b04f7e4ca5e5aee0e6f6dd62388c4d66633d62adbb9c9f6b89a059f01be8c483393accc10640739fd53a75f143a8a5add1efb76f4293",
          "sha256": "ad89383da83c7fda690e68f4e8ea264b53123a4258f026915c89083900ea4f3a",
          "sha1": "b9ca0b15a609c4c6b4da9928326b205ddf2b3acc",
          "md5": "920727866271b1b28a849c5240e7e882"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.13-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.13-forge.jar",
          "size": 329125,
          "sha512": "214a9e73c21f8db32442b04f7e4ca5e5aee0e6f6dd62388c4d66633d62adbb9c9f6b89a059f01be8c483393accc10640739fd53a75f143a8a5add1efb76f4293",
          "sha256": "ad89383da83c7fda690e68f4e8ea264b53123a4258f026915c89083900ea4f3a",
          "sha1": "b9ca0b15a609c4c6b4da9928326b205ddf2b3acc",
          "md5": "920727866271b1b28a849c5240e7e882"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.13-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.13-sources.jar",
          "size": 88861,
          "sha512": "295a24803e7362b66f1cc19e003f497baee6a3650bbeb9e8faf470017a61b92162a0f7b03bb2941f21ce915b9a103a47f05b19be4ad7aa69e047171c4bb7158a",
          "sha256": "f135753f133c59577a4930eb63535da126ca2fbcea2b344484454f33f8e56342",
          "sha1": "bd541478d704bc371016683e24ce312c42e41ab6",
          "md5": "e3de2d90d3c15af69226923ef954fadd"
        }
      ]
    }
  ]
}
