{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-common",
    "version": "1.9.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-common-1.9.17.jar",
          "url": "exposure-1.20.1-common-1.9.17.jar",
          "size": 1989795,
          "sha512": "0d678b54c12c06364454ad02b3ca765531e4e85fb3fa7eddfc649d7829ac4da3fda03bcc65439dfe0aa5db1e1bf3ad267558f7b9297ad4f665fded9c82ad2e19",
          "sha256": "0ed8033a6ec67471e5f74dfc389591151f9dedf7252fa6aee0625ba9d9647431",
          "sha1": "b95348a1a24ec3013e353f5d9871d62c751bae27",
          "md5": "8bf1325b72379985990696cd7b16d6e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-common-1.9.17.jar",
          "url": "exposure-1.20.1-common-1.9.17.jar",
          "size": 1989795,
          "sha512": "0d678b54c12c06364454ad02b3ca765531e4e85fb3fa7eddfc649d7829ac4da3fda03bcc65439dfe0aa5db1e1bf3ad267558f7b9297ad4f665fded9c82ad2e19",
          "sha256": "0ed8033a6ec67471e5f74dfc389591151f9dedf7252fa6aee0625ba9d9647431",
          "sha1": "b95348a1a24ec3013e353f5d9871d62c751bae27",
          "md5": "8bf1325b72379985990696cd7b16d6e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-common-1.9.17-sources.jar",
          "url": "exposure-1.20.1-common-1.9.17-sources.jar",
          "size": 1346647,
          "sha512": "226a1cb6e10c815a7b5358e47176e60743326c53ad6e1521b22429fd660b401eceac172521db197ff06de6483396b78bec03983ea8196b48ca4212ac0d712c48",
          "sha256": "0931b953a49cb172d5a885807214be04cc9762e4e71fd0b7b8180d8ce016fc65",
          "sha1": "180502a46c780e882be4f927b6bd320e6440f5ae",
          "md5": "9ac793f63938cbbcb7cec61166c537e8"
        }
      ]
    }
  ]
}
