{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.16-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.16-fabric.jar",
          "size": 313734,
          "sha512": "07c2616fba2ebee69904aa2016f1d524c986e662a6fd752004c94b0b5d156e2098d5c77b94b7aebb39dc130d05b86d734d833946557287b06d2f3fc85f38b1ed",
          "sha256": "4c55cfab1816a8d6964ab16fe16779225db976742afed46b265507970e90f855",
          "sha1": "639e31f211c26f1728549bf838a7b2632deaee6d",
          "md5": "0fe0fad1c673a092ddb8a7b3fb5ccf71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.16-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.16-fabric.jar",
          "size": 313734,
          "sha512": "07c2616fba2ebee69904aa2016f1d524c986e662a6fd752004c94b0b5d156e2098d5c77b94b7aebb39dc130d05b86d734d833946557287b06d2f3fc85f38b1ed",
          "sha256": "4c55cfab1816a8d6964ab16fe16779225db976742afed46b265507970e90f855",
          "sha1": "639e31f211c26f1728549bf838a7b2632deaee6d",
          "md5": "0fe0fad1c673a092ddb8a7b3fb5ccf71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.16-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.16-sources.jar",
          "size": 81789,
          "sha512": "8b43cefd586e88c0fcb1c3f7ecea304df894aa68a4db4c3831af9486a0322edad3997b43561f27758991be3c5dadbd8da4ad5b3d903a057e9f629e46df8a4da5",
          "sha256": "91aa67d0aea0e1b6d5ef219832f1366a1025e6397dc038b487aec858afc2b248",
          "sha1": "c603c4aa6e2dc904b88c3b5090696cdb40ef2785",
          "md5": "e3f036ca66a64641c357962ac576ac61"
        }
      ]
    }
  ]
}
