{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.5-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.5-forge.jar",
          "size": 334978,
          "sha512": "7a6f4272463c765371782f0e38a721d05b6b9c3b09d4a73853f47e9427a69083245930930d8445d80e71c3848a096137cb5872d9c7ae543cb8143dcd18760214",
          "sha256": "ec8a7a12f8f4713ea1bc9a5a9901fcd5f4ac7ace87a68c3a950cc57cf4d5100b",
          "sha1": "f3ed68a7b296a98d0b68e900b434273e474b4f47",
          "md5": "37b7d10751fec023cb0d624270210a9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.5-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.5-forge.jar",
          "size": 334978,
          "sha512": "7a6f4272463c765371782f0e38a721d05b6b9c3b09d4a73853f47e9427a69083245930930d8445d80e71c3848a096137cb5872d9c7ae543cb8143dcd18760214",
          "sha256": "ec8a7a12f8f4713ea1bc9a5a9901fcd5f4ac7ace87a68c3a950cc57cf4d5100b",
          "sha1": "f3ed68a7b296a98d0b68e900b434273e474b4f47",
          "md5": "37b7d10751fec023cb0d624270210a9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.5-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.5-sources.jar",
          "size": 90551,
          "sha512": "64e75946663c39a9064a23c93370d7acefd1670f2841aee231690e6e89047ed004926cc8495833f683d61593087d37dae332ec609dacfff98f82f68f9f5babfa",
          "sha256": "4a125b5fcd737e5e2fa2dbc43c503e002b3e929e9a690dc33b38f459257b7c50",
          "sha1": "21d0375842f2c58da2c5650c68698b19aea790c0",
          "md5": "be1864637fc05db810c8b8eb39f4e743"
        }
      ]
    }
  ]
}
