{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.4-fabric.jar",
          "url": "horseman-fabric-1.1.4-fabric.jar",
          "size": 260929,
          "sha512": "dfdfd9e54fb363a5af16ac5a24111138e303c3ab09c77de25797dd01d0a9bc30dfac26a1cf94f7bb79702946cd586a0db5b22ddb034d5da01fffc4f7e46b4e2e",
          "sha256": "cab30b201d9dcfe9b7730c50675e42bb845c7ae1df6c25e1877c7f171c7119a9",
          "sha1": "c59e080a3e8be639e6519999e2ea763f73b7ed0e",
          "md5": "6ff7871792061733497b529b3b478e1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.4-fabric.jar",
          "url": "horseman-fabric-1.1.4-fabric.jar",
          "size": 260929,
          "sha512": "dfdfd9e54fb363a5af16ac5a24111138e303c3ab09c77de25797dd01d0a9bc30dfac26a1cf94f7bb79702946cd586a0db5b22ddb034d5da01fffc4f7e46b4e2e",
          "sha256": "cab30b201d9dcfe9b7730c50675e42bb845c7ae1df6c25e1877c7f171c7119a9",
          "sha1": "c59e080a3e8be639e6519999e2ea763f73b7ed0e",
          "md5": "6ff7871792061733497b529b3b478e1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.1.4-sources.jar",
          "url": "horseman-fabric-1.1.4-sources.jar",
          "size": 44127,
          "sha512": "e7faad875960cd230a58ceb9bd62dd6dd23b9eedfa1d2097c231493302d853111d22a06fe53de97e5c3b937663844043a2d34b3ad1a4771480ccaa2ce0d7b150",
          "sha256": "1bb6438043081b52ac86a3945542915b2591e81be804e3f7a572b0ea20be04f2",
          "sha1": "e1d5fe3354e493c40103968a157efdadcfbeb3de",
          "md5": "0157c2574822269c8b58be010ca9748e"
        }
      ]
    }
  ]
}
