{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.1-common",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.3.jar",
          "url": "scholar-1.21.1-common-1.1.3.jar",
          "size": 282650,
          "sha512": "8a5412def446a3af8309c66b41f74e32983c3434e8caacd36f59145844ca803684945a5b006759c030db802d426669c6beda6e2768591e11928c11741ccfe0cf",
          "sha256": "f96073f12323029ea3e7bc7a04509ebe290ca9af80629379888e7fafff1ffb73",
          "sha1": "bfe96c36977ca10baf393db66008fb8b3cc6c340",
          "md5": "d3d536caee8491d8a136bc48685d5c73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.3.jar",
          "url": "scholar-1.21.1-common-1.1.3.jar",
          "size": 282650,
          "sha512": "8a5412def446a3af8309c66b41f74e32983c3434e8caacd36f59145844ca803684945a5b006759c030db802d426669c6beda6e2768591e11928c11741ccfe0cf",
          "sha256": "f96073f12323029ea3e7bc7a04509ebe290ca9af80629379888e7fafff1ffb73",
          "sha1": "bfe96c36977ca10baf393db66008fb8b3cc6c340",
          "md5": "d3d536caee8491d8a136bc48685d5c73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.3-sources.jar",
          "url": "scholar-1.21.1-common-1.1.3-sources.jar",
          "size": 199266,
          "sha512": "b6705301aa301107f35dbac5ced08b576ad9724ff66714767841333ba35cfd595483d3646a1a35309aaba4c79d896231213137e1bf0de8b8c69d01c9d94df268",
          "sha256": "54d69ed32907ed46062316d61200e5c0860f0b247ee6a6c4105b7c0a5a8bef8d",
          "sha1": "295eac71d3c4f9cb114519be4ace9d7299048485",
          "md5": "6f4ad64a41c16e4ee597c655e9125c62"
        }
      ]
    }
  ]
}
