{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.envelope",
    "module": "envelope-1.21.1-neoforge",
    "version": "0.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.2-build.353"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.3.jar",
          "url": "envelope-1.21.1-neoforge-0.7.3.jar",
          "size": 2195980,
          "sha512": "975a7a1e71b8d4f77de5b43fd364bd7ec83f711f634e4fca1224e0026c2ab2f6b57446c18a277270b37065379b3c62e329be990c6f0cd4a46da64391f6825291",
          "sha256": "89321e94bfd9b7d8ed917725fbb39d5b341332942c112786249106508bd6677d",
          "sha1": "0e6d7a40dcbd8c7ab5555a7256f09c97d005e148",
          "md5": "3050d22148b141be84a81642ea0a256b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.3.jar",
          "url": "envelope-1.21.1-neoforge-0.7.3.jar",
          "size": 2195980,
          "sha512": "975a7a1e71b8d4f77de5b43fd364bd7ec83f711f634e4fca1224e0026c2ab2f6b57446c18a277270b37065379b3c62e329be990c6f0cd4a46da64391f6825291",
          "sha256": "89321e94bfd9b7d8ed917725fbb39d5b341332942c112786249106508bd6677d",
          "sha1": "0e6d7a40dcbd8c7ab5555a7256f09c97d005e148",
          "md5": "3050d22148b141be84a81642ea0a256b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.3-sources.jar",
          "url": "envelope-1.21.1-neoforge-0.7.3-sources.jar",
          "size": 47028,
          "sha512": "2d6d9b5cf721b77d3a3e6befed5191b7691d1b1b1ac4cabe89d35bd4b76043bf09a957cc9d7d7958d7a8354bbbeb0a631e05164748cef2b9079c9b5d7e34aeba",
          "sha256": "b22a06f16974e0ac9d3ad2621fe69c737b59ec3655176ef843a06b3ebfc20b38",
          "sha1": "8b59489d97130e2ebd70afeacfe96e0d19ae5cbe",
          "md5": "11722db26ae393145feef0ce3af01cee"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.3-dev-shadow.jar",
          "url": "envelope-1.21.1-neoforge-0.7.3-dev-shadow.jar",
          "size": 1946439,
          "sha512": "a392317bdd1e91f5f83ec394235362c5c17c4bbd682753e68bc1295d7d523e6c44ead2890d08e5ef6f260030034e852f581f4bf39a00bbc0acdea78aa20edb05",
          "sha256": "c4c33ad3082dbbfdb2701e62132db3d779629bc2a6e331d0224786dce09b4290",
          "sha1": "da80c128ebf3397d483d60f5032066f4748c9a1f",
          "md5": "9c40c99012c485ce4118e89758a81949"
        }
      ]
    }
  ]
}
