{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-26.1.2-common",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.2-common-1.2.4.jar",
          "url": "thief-26.1.2-common-1.2.4.jar",
          "size": 126473,
          "sha512": "6665f09a894f70a0a2f1b5dd18e2aa006733303dd98e448c02a5abaad012fff3da3f051c52025e9947ff8faa038927d284982f0eb5c114bcd0648e6ad9e42e84",
          "sha256": "e0e6dbf939aecc4dd04577420a4d20da69788843e7631555888c32921f412f8f",
          "sha1": "d6d8d193c09a05a544132e5e34c553090e7479d8",
          "md5": "cfd22a2b0fc7897e0acb54bd6844fa8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.2-common-1.2.4.jar",
          "url": "thief-26.1.2-common-1.2.4.jar",
          "size": 126473,
          "sha512": "6665f09a894f70a0a2f1b5dd18e2aa006733303dd98e448c02a5abaad012fff3da3f051c52025e9947ff8faa038927d284982f0eb5c114bcd0648e6ad9e42e84",
          "sha256": "e0e6dbf939aecc4dd04577420a4d20da69788843e7631555888c32921f412f8f",
          "sha1": "d6d8d193c09a05a544132e5e34c553090e7479d8",
          "md5": "cfd22a2b0fc7897e0acb54bd6844fa8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.2-common-1.2.4-sources.jar",
          "url": "thief-26.1.2-common-1.2.4-sources.jar",
          "size": 69478,
          "sha512": "b57259dcb29baa347838314728fea421fd101758e7e7bc932927524a8d035feee646657cfc3345cf45569ec7ca57c26f6187f16772accf8d51256f74beb696f7",
          "sha256": "184c28524cd57b85757196b1ce9a4974310bdbdc152efca000838254871dc26d",
          "sha1": "1c207c6a6b0dd4f5ea624bfee5c1c3a1494ec3db",
          "md5": "92958df50a656ff66a414487ba88831a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.2-common-1.2.4.jar",
          "url": "thief-26.1.2-common-1.2.4.jar",
          "size": 126473,
          "sha512": "6665f09a894f70a0a2f1b5dd18e2aa006733303dd98e448c02a5abaad012fff3da3f051c52025e9947ff8faa038927d284982f0eb5c114bcd0648e6ad9e42e84",
          "sha256": "e0e6dbf939aecc4dd04577420a4d20da69788843e7631555888c32921f412f8f",
          "sha1": "d6d8d193c09a05a544132e5e34c553090e7479d8",
          "md5": "cfd22a2b0fc7897e0acb54bd6844fa8c"
        }
      ]
    }
  ]
}
