{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.3.jar",
          "url": "horseman-1.20.1-common-1.3.3.jar",
          "size": 121309,
          "sha512": "daa02efb484b541ffa42a21382891d052bb4d98ace56ea14f275a8fb2d62f95872632a948ad8624a3c3fa076161a400cec68b4cd2de3b1a36dfc3c3e28955fd3",
          "sha256": "0fbf51879431b32ae86a2142e33b1559178728caeab2e2d28ec001f121b2e660",
          "sha1": "3f19cf79d10436ebaaab3a1f6527f5e750f14873",
          "md5": "0adf6066e553db6f92b6c602ad1bfdb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.3.jar",
          "url": "horseman-1.20.1-common-1.3.3.jar",
          "size": 121309,
          "sha512": "daa02efb484b541ffa42a21382891d052bb4d98ace56ea14f275a8fb2d62f95872632a948ad8624a3c3fa076161a400cec68b4cd2de3b1a36dfc3c3e28955fd3",
          "sha256": "0fbf51879431b32ae86a2142e33b1559178728caeab2e2d28ec001f121b2e660",
          "sha1": "3f19cf79d10436ebaaab3a1f6527f5e750f14873",
          "md5": "0adf6066e553db6f92b6c602ad1bfdb6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.3-sources.jar",
          "url": "horseman-1.20.1-common-1.3.3-sources.jar",
          "size": 71412,
          "sha512": "1fea364d5bbbbdba435211b9db45473ea4198e6f20b1698d9454efb860cfead9c88c676c99b7398bb249b24b1ef30a5f7f3bb8dd0ab2cbfb53b3b2e2af371692",
          "sha256": "f0a5b46a871e10665492ce2c54e87e0842c81392ff5351c2a2755c158ca3885b",
          "sha1": "db6c5f7bc2c360284bbcf7c68e94ed4b3f76137c",
          "md5": "6f27de615e6f0cd987e552b71ed7c572"
        }
      ]
    }
  ]
}
