{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.2.jar",
          "url": "horseman-1.20.1-common-1.3.2.jar",
          "size": 119662,
          "sha512": "ed9ea58839a22be2bdcc60819e47ee7ffa933a6f35da6a68e029a4e9d2c4c16f4183b90e2162eb6f0153f5d932a91aab4639b7908c01d4dd222f76c0d2b601a1",
          "sha256": "d8455e5d75172059563098c482d50848541a85b31481c3af66a8fd19c2b0fc14",
          "sha1": "a3b64baa21b369c1bee7a0ff0b9f8b0465d29c22",
          "md5": "8cf92df0e90edcbab4a6d6c7768914b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.2.jar",
          "url": "horseman-1.20.1-common-1.3.2.jar",
          "size": 119662,
          "sha512": "ed9ea58839a22be2bdcc60819e47ee7ffa933a6f35da6a68e029a4e9d2c4c16f4183b90e2162eb6f0153f5d932a91aab4639b7908c01d4dd222f76c0d2b601a1",
          "sha256": "d8455e5d75172059563098c482d50848541a85b31481c3af66a8fd19c2b0fc14",
          "sha1": "a3b64baa21b369c1bee7a0ff0b9f8b0465d29c22",
          "md5": "8cf92df0e90edcbab4a6d6c7768914b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.2-sources.jar",
          "url": "horseman-1.20.1-common-1.3.2-sources.jar",
          "size": 70265,
          "sha512": "285e8a612ada7ea1def06e6a674455d8b5e4d43b967ae621a53686eef12ff314896bc3640e44ee4d56764af6d99fb2da5cd99e0346be0e12f1ff23e855bbeb23",
          "sha256": "f2313c7f5af8faf52acf92167b1705ff9a3eec4936e588ff82fa3e31a977dc13",
          "sha1": "35140cdbf76f3db693a6675d5e186720a213d600",
          "md5": "0fff8adca79975d5531937e6bd41ceaf"
        }
      ]
    }
  ]
}
