{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.9-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.9-fabric.jar",
          "size": 315607,
          "sha512": "976bc8210b985442a4ed96c3e2c275a08cbfe91f9b547332dcbdcb39022cfbdaf8b3af3b0d8b0fe40401d417f3ad1022ff604465a1feffbd15703e4b9cbe8af4",
          "sha256": "4689c24552ac2c6ebb6fe6a14550c0512b847b311bacd11daddf4aedb6ca445d",
          "sha1": "0c85544a402d7b9adbd3a228d873ee4fe8153d4a",
          "md5": "a716b389a1277a0139cb7931b6cd96cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.9-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.9-fabric.jar",
          "size": 315607,
          "sha512": "976bc8210b985442a4ed96c3e2c275a08cbfe91f9b547332dcbdcb39022cfbdaf8b3af3b0d8b0fe40401d417f3ad1022ff604465a1feffbd15703e4b9cbe8af4",
          "sha256": "4689c24552ac2c6ebb6fe6a14550c0512b847b311bacd11daddf4aedb6ca445d",
          "sha1": "0c85544a402d7b9adbd3a228d873ee4fe8153d4a",
          "md5": "a716b389a1277a0139cb7931b6cd96cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.9-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.9-sources.jar",
          "size": 82346,
          "sha512": "dcb62b52e6f8ba6c2a5a7d26581ab1fb7a545c6b6dfe2383208a1cfc04d35631ba72e2924f1d521d9378004c852ee29cd45e1e5fdaa5f7526d9c1254f3143a7c",
          "sha256": "ea59e3843f66d6ad057b286384ddc3556f9ab6afaa2d44f522fd6a492af9c2cb",
          "sha1": "b5dd2baf5346f6eef2d874a90aa017f031826ea7",
          "md5": "2a6903a04866d5427ddd001839c07061"
        }
      ]
    }
  ]
}
