{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.11-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.11-forge.jar",
          "size": 329057,
          "sha512": "714ce3ddc587f95ed860925e6ac28e814f827e6491c5bcf40350f40c36750acc9c3d5f130da9fdcc9a7a848883d5b461a27ac9b9494c655fae493ff6e77ea762",
          "sha256": "a3633197fb063b74f1eae5f0a6b634a56eca72231b495ae13dc1a5daec14e57c",
          "sha1": "6409d236699985747f50e219a383c5297e67b546",
          "md5": "3a30d97401ea09de40a284d2d8d31667"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.11-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.11-forge.jar",
          "size": 329057,
          "sha512": "714ce3ddc587f95ed860925e6ac28e814f827e6491c5bcf40350f40c36750acc9c3d5f130da9fdcc9a7a848883d5b461a27ac9b9494c655fae493ff6e77ea762",
          "sha256": "a3633197fb063b74f1eae5f0a6b634a56eca72231b495ae13dc1a5daec14e57c",
          "sha1": "6409d236699985747f50e219a383c5297e67b546",
          "md5": "3a30d97401ea09de40a284d2d8d31667"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.11-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.11-sources.jar",
          "size": 88847,
          "sha512": "3f5172510d6644593b1f72e30f2724698640b8916d99020fe89b41203b5d669fb2e11d4571dea3c34f819fca5f8cc492f20b323b7c0ae1f7fd4f7b804f814513",
          "sha256": "5e493b8525d40bae12a9793c08f42c25d99a50f7b7bf0c8614773dcaa9be813e",
          "sha1": "c954a731472564d7a86c57b8368fa785432d18fb",
          "md5": "830a7e0373367b69a1a3fe676e5db98d"
        }
      ]
    }
  ]
}
