{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.3-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.3-fabric.jar",
          "size": 319830,
          "sha512": "2d20ede29997a936caace527cc4097bd595a2a489507b8132c1bbba18fafc466e618d7758159e65516a41839e45d9c95071e9b2d1b0f38cccd80c157f525ed31",
          "sha256": "643e8ad8d17e6e714dc95ab03df9bceb1b86ff7ddaedcb1c0eed91325b792df8",
          "sha1": "af071fa2e0831b3316c0694457b4e5e31e003a61",
          "md5": "71a5d62bc80e4831658eac69b7669881"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.3-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.3-fabric.jar",
          "size": 319830,
          "sha512": "2d20ede29997a936caace527cc4097bd595a2a489507b8132c1bbba18fafc466e618d7758159e65516a41839e45d9c95071e9b2d1b0f38cccd80c157f525ed31",
          "sha256": "643e8ad8d17e6e714dc95ab03df9bceb1b86ff7ddaedcb1c0eed91325b792df8",
          "sha1": "af071fa2e0831b3316c0694457b4e5e31e003a61",
          "md5": "71a5d62bc80e4831658eac69b7669881"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.3-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.3-sources.jar",
          "size": 83127,
          "sha512": "f928f493e99b30a22cc2c55838b01cb07ba828f3e663af2f86547c92b299ebd5143579b0a10d236a6a841197cc97845cc697159ade1648fa580b8022049146c2",
          "sha256": "56e01fce88532a89cfaec56d0c10623348c01b87a74c0e2d6eeb3df3d6a48d18",
          "sha1": "8bfa886f8ecc5d57a48c31eaadf334c535c3ff2f",
          "md5": "63c93a2b9f42fbad0ea9bb926b901472"
        }
      ]
    }
  ]
}
