{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.8.jar",
          "url": "horseman-1.21.1-common-1.3.8.jar",
          "size": 117801,
          "sha512": "8155bf4d0a21b6845839e0b5097ec603dd076f269e3e1fde3d0a4d5ee4421fb6275fcad480e94c55a1ce8ec0dea1349cb024c89e933b769fb4a662ab208d3ec5",
          "sha256": "dee16cae3091a94a22d24b6e402c4c2635745a82a5bf596cb1b991fdf7c974b1",
          "sha1": "2b631147f7b449bdcc03b0ff34a6f6892cb1fde9",
          "md5": "12241fc99f9daafdbb2f98fb5c5697e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.8.jar",
          "url": "horseman-1.21.1-common-1.3.8.jar",
          "size": 117801,
          "sha512": "8155bf4d0a21b6845839e0b5097ec603dd076f269e3e1fde3d0a4d5ee4421fb6275fcad480e94c55a1ce8ec0dea1349cb024c89e933b769fb4a662ab208d3ec5",
          "sha256": "dee16cae3091a94a22d24b6e402c4c2635745a82a5bf596cb1b991fdf7c974b1",
          "sha1": "2b631147f7b449bdcc03b0ff34a6f6892cb1fde9",
          "md5": "12241fc99f9daafdbb2f98fb5c5697e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.8-sources.jar",
          "url": "horseman-1.21.1-common-1.3.8-sources.jar",
          "size": 70103,
          "sha512": "ecd0c4d6dbdc8427886f8b9347d4f186755539125a0729e82c6e5b8ac8e49103cae1ca4f0d28908ad4746d988ab6b79be6c68432441dcd342e59e6afedb2d91f",
          "sha256": "a9d682887927d83026de1957a02c9df13bfdfc2808d7e10390543276958f6c50",
          "sha1": "4c237819d5aefadd753f7ef9f19be456bec4da34",
          "md5": "fdc35e741236fcbb080b4baa963b51dd"
        }
      ]
    }
  ]
}
