{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.4-neoforge",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.4-neoforge-api",
          "version": {
            "requires": "20.0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.4.jar",
          "size": 179036,
          "sha512": "f745954731fc292140732521ca06edfd7ff8c0e6bbc7ab29527c2e8663b7a4879a21c6a5c957acee53a2fbd9f50679fb74276c895bab0b516d223a1d33689e11",
          "sha256": "55f0ee8b2fc5bd1640dec929719c4a0d284d78536268a934f054e42b2c0af54d",
          "sha1": "50788a3bbec10c2472ea2ced26e8144625f747a0",
          "md5": "b7cb1d1dc4aff3c3ef415dfaf08476f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.4-neoforge",
          "version": {
            "requires": "20.0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.4.jar",
          "size": 179036,
          "sha512": "f745954731fc292140732521ca06edfd7ff8c0e6bbc7ab29527c2e8663b7a4879a21c6a5c957acee53a2fbd9f50679fb74276c895bab0b516d223a1d33689e11",
          "sha256": "55f0ee8b2fc5bd1640dec929719c4a0d284d78536268a934f054e42b2c0af54d",
          "sha1": "50788a3bbec10c2472ea2ced26e8144625f747a0",
          "md5": "b7cb1d1dc4aff3c3ef415dfaf08476f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.4-sources.jar",
          "size": 13751,
          "sha512": "83d4bab5ab826217b2bfacd8a9fcfd33c62737101aacb1c1267dd4703519f8e740b257c100388a9665e81004d9a86b3a206601044ba51a29825afd6989cff422",
          "sha256": "76443d36df3143339eee74b58603ca37b6f7e8866e08f15f534c5e75e6f66c4c",
          "sha1": "7c682aa6c4243b39ce45ae2d6b0ffa7b4b6b6639",
          "md5": "b06cca1707b15ed8085787e065ed1a51"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.4-dev-shadow.jar",
          "size": 173810,
          "sha512": "fbfadfbc49a582ba17ea304b5069b5fcc3c901d2af4da1b64bf7d1741a0924dc05f97e83384ddcb23d5b40b3b34b83fdf4e6873738dd6d1b27b69b9807a5303c",
          "sha256": "507fc83ce4c6f806b9a161009ea526729e745abf7c89f89f93568f0f78d5f1f7",
          "sha1": "034e0652ea5ced1c2320a12dbebf6bbf061d3b2a",
          "md5": "5a38e12b7bc46e6d3b7f1c2d5f88589d"
        }
      ]
    }
  ]
}
