{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.15-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.15-forge.jar",
          "size": 329030,
          "sha512": "4dabe5907c28122e9920cbf7feb147674db368322a6168e655706d2468067ef0dfd7e6d63d34ccfd2ebba276ab0975b3d38a515f93d9df060ecc1ef2e0306ffb",
          "sha256": "e4e068c6848791ea378c855e7f0471f077f112847c4318a5fdd5efe1bf805b96",
          "sha1": "5c62b3fb6a9a3c91f3dddb78541497d5bbcd777b",
          "md5": "fa43502c093d2655d89cb7ac74fb96a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.15-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.15-forge.jar",
          "size": 329030,
          "sha512": "4dabe5907c28122e9920cbf7feb147674db368322a6168e655706d2468067ef0dfd7e6d63d34ccfd2ebba276ab0975b3d38a515f93d9df060ecc1ef2e0306ffb",
          "sha256": "e4e068c6848791ea378c855e7f0471f077f112847c4318a5fdd5efe1bf805b96",
          "sha1": "5c62b3fb6a9a3c91f3dddb78541497d5bbcd777b",
          "md5": "fa43502c093d2655d89cb7ac74fb96a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.15-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.15-sources.jar",
          "size": 88808,
          "sha512": "2df368190a33a6b7dca7341c79146324308ef9afab3340a831cd1feb923aa59171a09f5f63eb95db8d928436159ebd07d65290593f8811c4d5a7496399e17030",
          "sha256": "27851b041b254fb9039df281011b9645420dac06ac2c052d74d23b178971ee6e",
          "sha1": "7d903bcfd6bf8dd917f7a91997ab8ef2fa288910",
          "md5": "e4b0b3c2faa2e6984e1444ad32a6ea38"
        }
      ]
    }
  ]
}
