{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.1-neoforge",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.25.0.322"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.25.0.322"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.2.3.jar",
          "url": "scholar-1.21.1-neoforge-1.2.3.jar",
          "size": 922019,
          "sha512": "30c236096ad48b7c3fe51e6def2d8c81965ede8dbe588cf8be8537751a42b197904d37958fb711fabeffdf9064c194f9f91d3a080d74a8a04b357a2ea120509c",
          "sha256": "b8f5aa89e7e8d84b4a0a9d56637af5a6e3e1bc97189987bf2f85385024df0794",
          "sha1": "0177a835b9d1d885a7f83a30fa70988e0d1f77c5",
          "md5": "719f3208c20b1956dc86cd0b3f546e75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "woodster-869951",
          "version": {
            "requires": "6425772"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.2.3.jar",
          "url": "scholar-1.21.1-neoforge-1.2.3.jar",
          "size": 922019,
          "sha512": "30c236096ad48b7c3fe51e6def2d8c81965ede8dbe588cf8be8537751a42b197904d37958fb711fabeffdf9064c194f9f91d3a080d74a8a04b357a2ea120509c",
          "sha256": "b8f5aa89e7e8d84b4a0a9d56637af5a6e3e1bc97189987bf2f85385024df0794",
          "sha1": "0177a835b9d1d885a7f83a30fa70988e0d1f77c5",
          "md5": "719f3208c20b1956dc86cd0b3f546e75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.2.3-sources.jar",
          "url": "scholar-1.21.1-neoforge-1.2.3-sources.jar",
          "size": 14462,
          "sha512": "8933a77e0cc0a009d98e148f84befb8bf12a06084fd4fa00b6ea3cb4acf818d81543d608c619e8371447493a815697258665e858b29dd7b56430b5cd5b707096",
          "sha256": "808d14988dcc9cd065666f8c4f69bf7da2500cea67a62090e86f1a9bbc6689e9",
          "sha1": "1041d6fb51116a9a78b6a28188b3de4f399c6042",
          "md5": "0bcb4b4cb12657f810cec4f9a4722bc8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.2.3-dev-shadow.jar",
          "url": "scholar-1.21.1-neoforge-1.2.3-dev-shadow.jar",
          "size": 727117,
          "sha512": "d3c79238a8ceb42780a9884aa3b94cda468992e31b8216977283d0c1e5cdad78abaa65575384d4ba83fd3e606772ae90b67d4f92be0211fba1f9302e8dcf7f47",
          "sha256": "15ace87893025f85564a28f4d0c648a7c18bfb575f97b50247f5f6fd0db00bdc",
          "sha1": "da908ccb002312b7d017d56f77b47a637c49c34f",
          "md5": "8d7878359a0e8be9992d1821dbea9202"
        }
      ]
    }
  ]
}
