{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.1-common",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.7.jar",
          "url": "scholar-1.21.1-common-1.1.7.jar",
          "size": 532615,
          "sha512": "353593cc69d146365096051e99e27a103a2a8a3c9dc7ac51598276742799954208866e85d111da84b0cefcfa223b05ab5d135ddfc416b06f9b2831cd62f6340f",
          "sha256": "592b51244bde0e321453b02560ca07132da62dd69d99027b9b217a13aef08248",
          "sha1": "c8f64d21ec58b3691a78ed57699f59322cd14129",
          "md5": "ac0274d4454f237f5ad1f2c48c7f27a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.7.jar",
          "url": "scholar-1.21.1-common-1.1.7.jar",
          "size": 532615,
          "sha512": "353593cc69d146365096051e99e27a103a2a8a3c9dc7ac51598276742799954208866e85d111da84b0cefcfa223b05ab5d135ddfc416b06f9b2831cd62f6340f",
          "sha256": "592b51244bde0e321453b02560ca07132da62dd69d99027b9b217a13aef08248",
          "sha1": "c8f64d21ec58b3691a78ed57699f59322cd14129",
          "md5": "ac0274d4454f237f5ad1f2c48c7f27a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.7-sources.jar",
          "url": "scholar-1.21.1-common-1.1.7-sources.jar",
          "size": 451301,
          "sha512": "e14874e69e4d8c512f205a83f1f765ee3cfb6055452012c22f5eef485f6a36a2f74a22b72ee3232f32e07bf6cc493204737ee7f56926464ba9b95c958393e30d",
          "sha256": "65dd690c3993129eae318f9e6c88d80fe3af72d07aa0914bcd9193ff40a7775d",
          "sha1": "1fb2861f1d07f34d9fd57615ee282401977248d5",
          "md5": "74e895dc26a86f1eb76b169b842ab476"
        }
      ]
    }
  ]
}
