{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.1.jar",
          "url": "scholar-1.20.1-common-1.2.1.jar",
          "size": 649339,
          "sha512": "ededbc2e638a1c0a0c7f2dd55599edc72b556f1e7586a0405c3ed0fea6b36d7f92070b93c1badfbe6798dac2152dbfc16332320a39c54753b21bd3fd1586c01d",
          "sha256": "144de335e0fcf73eb05c53f54d811d458e540553c70e6f853c43134d2641592d",
          "sha1": "768a45a1355ff46e3e6bb155ee3015644c115ba9",
          "md5": "b1e58af8b537924f1dc3ce8020f1ea81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.1.jar",
          "url": "scholar-1.20.1-common-1.2.1.jar",
          "size": 649339,
          "sha512": "ededbc2e638a1c0a0c7f2dd55599edc72b556f1e7586a0405c3ed0fea6b36d7f92070b93c1badfbe6798dac2152dbfc16332320a39c54753b21bd3fd1586c01d",
          "sha256": "144de335e0fcf73eb05c53f54d811d458e540553c70e6f853c43134d2641592d",
          "sha1": "768a45a1355ff46e3e6bb155ee3015644c115ba9",
          "md5": "b1e58af8b537924f1dc3ce8020f1ea81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.1-sources.jar",
          "url": "scholar-1.20.1-common-1.2.1-sources.jar",
          "size": 508288,
          "sha512": "3f48a2cc99e1be50099d3bdd1336b0d225ca6a33f231bb3742be3d8b865c7897d58914909f23df6ddc5dc4714866c7a71ddd5d2720205ecb490fec237b4abf63",
          "sha256": "ded613b4a6ff486a7226325f6c0fc117726550fdd65aa414c7a3c9997e1a9b79",
          "sha1": "cbc2ce4a9d18557f6356e929de756e2fd24417a9",
          "md5": "29e651452bee8f30ed813811f857e92e"
        }
      ]
    }
  ]
}
