{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.5.1.jar",
          "url": "scholar-1.20.1-common-1.1.5.1.jar",
          "size": 462976,
          "sha512": "58b50f81a25bd050248edaae06270f71600c3a0dec9a1dcbbb95d1d6c23f42e24f89a5c869a1c957795c6f1faf13a0c437c9e0115e0c4e2ad96fc757e28cd124",
          "sha256": "5b3e9eaf7e7d61e76af02e3708189b945cb70f017c74906bcb626afa6dcd752a",
          "sha1": "c2180e11c255bb902b4c2a075e901163d337b7db",
          "md5": "2bf810fcd8e781e83f3187d5546877f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.5.1.jar",
          "url": "scholar-1.20.1-common-1.1.5.1.jar",
          "size": 462976,
          "sha512": "58b50f81a25bd050248edaae06270f71600c3a0dec9a1dcbbb95d1d6c23f42e24f89a5c869a1c957795c6f1faf13a0c437c9e0115e0c4e2ad96fc757e28cd124",
          "sha256": "5b3e9eaf7e7d61e76af02e3708189b945cb70f017c74906bcb626afa6dcd752a",
          "sha1": "c2180e11c255bb902b4c2a075e901163d337b7db",
          "md5": "2bf810fcd8e781e83f3187d5546877f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.5.1-sources.jar",
          "url": "scholar-1.20.1-common-1.1.5.1-sources.jar",
          "size": 368682,
          "sha512": "172348c10e99230059da3fec761d46c2cabb95f5cde80567a19d461db63fab3f4039f7651e905ef114176d5f650087e9d0a469bde5fb391097c45aab9bec9880",
          "sha256": "cd4753dcd822ca9a43ae315dd2dbab1a90ffa711db1abae598a0196d1323478a",
          "sha1": "01cbb103dac7a67663c232683977bd3f6e838b0a",
          "md5": "54b6b01cacb3663e057a212ff67f6e00"
        }
      ]
    }
  ]
}
