{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.5.jar",
          "url": "horseman-1.21.1-neoforge-1.3.5.jar",
          "size": 318939,
          "sha512": "bd5bd82793232233614d15dc37af41e8c8fe4b7588bb0234a1bc1376fddb795d205fc0352471f82aa6927d61b9ae9b09d5d486f9aee61c88e7ad7213b7945650",
          "sha256": "8f110117903f8eea940ad4b95d31ffb4ce4bdfb6a14a59a023f2edc3dda80b7a",
          "sha1": "1d103da37674c61fdc5c29fc2ef67152dbe7de48",
          "md5": "e89e2fdfdae9f18209883710ef33cdf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.5.jar",
          "url": "horseman-1.21.1-neoforge-1.3.5.jar",
          "size": 318939,
          "sha512": "bd5bd82793232233614d15dc37af41e8c8fe4b7588bb0234a1bc1376fddb795d205fc0352471f82aa6927d61b9ae9b09d5d486f9aee61c88e7ad7213b7945650",
          "sha256": "8f110117903f8eea940ad4b95d31ffb4ce4bdfb6a14a59a023f2edc3dda80b7a",
          "sha1": "1d103da37674c61fdc5c29fc2ef67152dbe7de48",
          "md5": "e89e2fdfdae9f18209883710ef33cdf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.5-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.5-sources.jar",
          "size": 13830,
          "sha512": "6a692f0313078227b49a72f9367af071c7debfb110bd49ebecc9db43e0872952a38911c749c16333587e8f53fe736e2813fd57cf62be5d363d111d939d534363",
          "sha256": "58a25c530745f620ea8d1800610b20bc28fd7784ee9655dd485cd20523d36d65",
          "sha1": "b8bb6b26bf73d61293a3e1067709ea7ad04a5205",
          "md5": "7d1291a3aab1ca7ce5aa95e4f5bf36cd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.5-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.5-dev-shadow.jar",
          "size": 133862,
          "sha512": "80cdc9384eae1a03281dbd7bb8bfb6f7cde6443c6b8f040a6fd79eadee3792d84651dc22b05413c0dd73478e17558483c0940986a5e6d0d887041aca6ff20e6e",
          "sha256": "d37ece947d275a78b475579591ae483285b96e2c9c63fca08b9d7efe8788bec1",
          "sha1": "1a74db633067bda2ab48076ed9557d0878f6924a",
          "md5": "5a7ba8ce519f57daf540465c28695127"
        }
      ]
    }
  ]
}
