{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.0.1.jar",
          "url": "horseman-common-1.0.1.jar",
          "size": 62832,
          "sha512": "aaf5d2cb81dc1a8218d4b884eebf63f4d9034e8b3d5b4185ca39fe8dd1c20bc84e7628e21aade0d9fd60f9adaea2ad5e6d00aa78f5134cb925f548b5a179d98a",
          "sha256": "a0203c32227db73c5e23fa6b78f4135d4400449a0c7ab01358a4cd80ca5e2e33",
          "sha1": "28e9e47460c312ae4a8cf488c55b966d95919e26",
          "md5": "fec44d71bfc9a44fc1fdda20d3104464"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.0.1.jar",
          "url": "horseman-common-1.0.1.jar",
          "size": 62832,
          "sha512": "aaf5d2cb81dc1a8218d4b884eebf63f4d9034e8b3d5b4185ca39fe8dd1c20bc84e7628e21aade0d9fd60f9adaea2ad5e6d00aa78f5134cb925f548b5a179d98a",
          "sha256": "a0203c32227db73c5e23fa6b78f4135d4400449a0c7ab01358a4cd80ca5e2e33",
          "sha1": "28e9e47460c312ae4a8cf488c55b966d95919e26",
          "md5": "fec44d71bfc9a44fc1fdda20d3104464"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.0.1-sources.jar",
          "url": "horseman-common-1.0.1-sources.jar",
          "size": 34117,
          "sha512": "597ee30b54003aef544da84119bcb2c90a8b2e748d18ceb620f54ffe1d88bd27f11f748e86d87251fd3252cf9fe4380d0800f8b177063240608532e2af742510",
          "sha256": "d2c5d94a8bea52949fa0476e86f75745515871df33d2e278299344a7bea17cdb",
          "sha1": "38aec8f9bb054b6ee2398307674aa7ee03fc5b53",
          "md5": "bdb089f740ebc948151baa0b947c2545"
        }
      ]
    }
  ]
}
