{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.11.jar",
          "url": "exposure-common-1.7.11.jar",
          "size": 1286990,
          "sha512": "4786c3a32fb4bed3f8b9949049e27460f5e6a097534294d6ae04c6e6ef91b72f19766f2f8aa8d67df55ee4bf5f85dfd868864db4d47e6eaffc7221333209ae9b",
          "sha256": "2689d368ddf1ebaab6f7e39d0018f4977a27f482ec495834798ede9600fb579f",
          "sha1": "3a152dadb72c0bb1057ba572fa4a3c085ea3628a",
          "md5": "4451dd277f4391eae2e24a2507d5bcf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.11.jar",
          "url": "exposure-common-1.7.11.jar",
          "size": 1286990,
          "sha512": "4786c3a32fb4bed3f8b9949049e27460f5e6a097534294d6ae04c6e6ef91b72f19766f2f8aa8d67df55ee4bf5f85dfd868864db4d47e6eaffc7221333209ae9b",
          "sha256": "2689d368ddf1ebaab6f7e39d0018f4977a27f482ec495834798ede9600fb579f",
          "sha1": "3a152dadb72c0bb1057ba572fa4a3c085ea3628a",
          "md5": "4451dd277f4391eae2e24a2507d5bcf5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.11-sources.jar",
          "url": "exposure-common-1.7.11-sources.jar",
          "size": 929516,
          "sha512": "c3968d187d43b7e92e174b941788d0033d0cca48928cbdb7a463fdf170ae84a953ddc5724041fab0488c6a96f57d0ceb8c87cffcbb10c41d23a692bb1697db33",
          "sha256": "99acf04e256b1ba1bd74fc23b7bde82e486dd26dec20543a9811295e5ddefb01",
          "sha1": "811543a52037da566373888cb3323bec3c1a2f89",
          "md5": "3350a379db34c90c71092d1d69396daf"
        }
      ]
    }
  ]
}
