{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.15.jar",
          "url": "horseman-1.20.1-common-1.3.15.jar",
          "size": 115072,
          "sha512": "fda881acae77eb2b74181cb9a61cb52f004411c2cf151d4660d0f489da5a921e8f1e7be2f062951cb6074857c52cbb2a541a37a1a3226fcf17911aa99dabebef",
          "sha256": "8faa9def08fc44d556988b2e1aa9799a92b3dc8fc14ada816636874bbd1e2c14",
          "sha1": "5a1eda2030335e309a71268fb1fd7e9375392ddb",
          "md5": "8cc7b6c93eb195e2357bed8e57916411"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.15.jar",
          "url": "horseman-1.20.1-common-1.3.15.jar",
          "size": 115072,
          "sha512": "fda881acae77eb2b74181cb9a61cb52f004411c2cf151d4660d0f489da5a921e8f1e7be2f062951cb6074857c52cbb2a541a37a1a3226fcf17911aa99dabebef",
          "sha256": "8faa9def08fc44d556988b2e1aa9799a92b3dc8fc14ada816636874bbd1e2c14",
          "sha1": "5a1eda2030335e309a71268fb1fd7e9375392ddb",
          "md5": "8cc7b6c93eb195e2357bed8e57916411"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.15-sources.jar",
          "url": "horseman-1.20.1-common-1.3.15-sources.jar",
          "size": 69675,
          "sha512": "948a057da180f7243def30591dbd1c9e5c1f0017aa24a24dbbfd3e8897ee98c5f2afb26502ea77961a760394f7ab5cdaf4a52c66526fc2d8d45f2bf5def16b48",
          "sha256": "523dd02cdb42b222d17f52532fe4b2f44987e988cd5b6dc9f17aada020eb9e8f",
          "sha1": "fc6b5cb3650f7870f27e716e8ef12cc857ecd19b",
          "md5": "a6dac7cfe97cefed68f1ebdfd5210310"
        }
      ]
    }
  ]
}
