{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-common",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.3.jar",
          "url": "sootychimneys-1.21.1-common-1.3.3.jar",
          "size": 160432,
          "sha512": "5734d02bdadf176cedaec1dfb9a4983b3b453e75566f3c140d5325dfb0bc944d909e4078fce80f0fd8b9015f42463c634c55c4ad59eda69d441b65a2e810d15b",
          "sha256": "cc197bee0b57a0cdbf5a348d9c149a6d1a70cd908d5c85993d506a9519cc6087",
          "sha1": "8dcbd5786589fb9a23cec9133914ca33c358a82c",
          "md5": "13103e9478d62c966d0e8fc3c3b500d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.3.jar",
          "url": "sootychimneys-1.21.1-common-1.3.3.jar",
          "size": 160432,
          "sha512": "5734d02bdadf176cedaec1dfb9a4983b3b453e75566f3c140d5325dfb0bc944d909e4078fce80f0fd8b9015f42463c634c55c4ad59eda69d441b65a2e810d15b",
          "sha256": "cc197bee0b57a0cdbf5a348d9c149a6d1a70cd908d5c85993d506a9519cc6087",
          "sha1": "8dcbd5786589fb9a23cec9133914ca33c358a82c",
          "md5": "13103e9478d62c966d0e8fc3c3b500d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.3-sources.jar",
          "url": "sootychimneys-1.21.1-common-1.3.3-sources.jar",
          "size": 116406,
          "sha512": "a04b093d834a17d60f06c6833d6d25ce9703a939ca2b1a8a367dec86d39ce0d1295f734643e215d4e143a0ac040bd5a86ca16c4675e3fa3aa0d6c337e003b2b5",
          "sha256": "2941f83a0eb88ba772f752ee5bd09108dd93f059dec7d3d1224f0c719394c7a7",
          "sha1": "d79486d3adbee59db365bf110830c7076a583078",
          "md5": "aea150bf12615e36f32e128d1994e9d3"
        }
      ]
    }
  ]
}
