{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.1-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.1-fabric.jar",
          "size": 317900,
          "sha512": "09a07cf699451182fdd1fc25df9f1000b549d42f345faa22030248bbbe65a6b576ac789519c38c8444cde122958a8b5ac5de673eb389d6c2149c9a9d5c3b5943",
          "sha256": "e3a23e9229be45ed47746e870c5c77631c0957f6205548aa64e50f2e64d0a974",
          "sha1": "083622ad3feb98051fba8edf98febfe40195fe26",
          "md5": "20d76887cfbcbf225719dd32dcc2d6b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.1-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.1-fabric.jar",
          "size": 317900,
          "sha512": "09a07cf699451182fdd1fc25df9f1000b549d42f345faa22030248bbbe65a6b576ac789519c38c8444cde122958a8b5ac5de673eb389d6c2149c9a9d5c3b5943",
          "sha256": "e3a23e9229be45ed47746e870c5c77631c0957f6205548aa64e50f2e64d0a974",
          "sha1": "083622ad3feb98051fba8edf98febfe40195fe26",
          "md5": "20d76887cfbcbf225719dd32dcc2d6b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.1-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.1-sources.jar",
          "size": 81891,
          "sha512": "094c592d852f3fe30a383d6038509364711bcd341531380673959e522ba3ef4e46fb9ca8c923e048cd7bd40061fc29162ed8e0f6c9ea03bff94a79ba67a4cd1a",
          "sha256": "db4ec56a5458d15f9b2ef1f676b9e9746aa020e0ec6cb0cc2587becb262bc38f",
          "sha1": "3f4297ca31291c319f0c9329cf6d18ddf4e93341",
          "md5": "fb598e1c7c28c116e66f5f919bae1d4e"
        }
      ]
    }
  ]
}
