{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.7.jar",
          "url": "horseman-1.21.1-common-1.3.7.jar",
          "size": 117224,
          "sha512": "73a8f16fa090b159937719cffb86292ab824a15622b3b4c57983d93188c4620aaafbf5601073e83393281802f2e6d5c0d1999c6b1b6347ae53c1b5f5f1117c51",
          "sha256": "40977de542165387e3ba89840bda006956ebda189505b74e9c54f9a0537d27ed",
          "sha1": "24410ffbfc6459eb5afd49dc80953325b458e4ea",
          "md5": "e6b3e09cf4f57dada373f6bbf63299e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.7.jar",
          "url": "horseman-1.21.1-common-1.3.7.jar",
          "size": 117224,
          "sha512": "73a8f16fa090b159937719cffb86292ab824a15622b3b4c57983d93188c4620aaafbf5601073e83393281802f2e6d5c0d1999c6b1b6347ae53c1b5f5f1117c51",
          "sha256": "40977de542165387e3ba89840bda006956ebda189505b74e9c54f9a0537d27ed",
          "sha1": "24410ffbfc6459eb5afd49dc80953325b458e4ea",
          "md5": "e6b3e09cf4f57dada373f6bbf63299e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.7-sources.jar",
          "url": "horseman-1.21.1-common-1.3.7-sources.jar",
          "size": 69670,
          "sha512": "1a32d1f5376682c6174923f87a1aa1a10ffff05f29d92ae39fdde7a54d5c830dafd2415ed23118560a27443d893ddfd57be3129e88e296ee35ea940293240d47",
          "sha256": "1308b058701a721fc98c783618b1b8c4efaa174129bc78d486ab7a6bb114583c",
          "sha1": "ec89805c7fb21091f6fbe81da74b2669baf0b1e2",
          "md5": "75d324e5fd98f94fe75aea502bee8abd"
        }
      ]
    }
  ]
}
