{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-common-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.3.0.jar",
          "url": "sootychimneys-common-1.3.0.jar",
          "size": 160060,
          "sha512": "20119a964300a42fcc8d34990cfed2a7dc5aebcc721bb34c98b9ff04733013a7a5cc508a0df11a37435e54f51a46b5caf99a34550cca873921f80079c4f8bdff",
          "sha256": "940b0711b1f665b1d51198c5dbaa28949fe571edd18ffe7009c0bd569b7d1ae3",
          "sha1": "5b770b36025f9867139888eb9d2fe2ab0456d685",
          "md5": "896cd95e67a6fd0b835e9cdd4d19a78c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.3.0.jar",
          "url": "sootychimneys-common-1.3.0.jar",
          "size": 160060,
          "sha512": "20119a964300a42fcc8d34990cfed2a7dc5aebcc721bb34c98b9ff04733013a7a5cc508a0df11a37435e54f51a46b5caf99a34550cca873921f80079c4f8bdff",
          "sha256": "940b0711b1f665b1d51198c5dbaa28949fe571edd18ffe7009c0bd569b7d1ae3",
          "sha1": "5b770b36025f9867139888eb9d2fe2ab0456d685",
          "md5": "896cd95e67a6fd0b835e9cdd4d19a78c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-common-1.3.0-sources.jar",
          "url": "sootychimneys-common-1.3.0-sources.jar",
          "size": 116125,
          "sha512": "9ce1bc17c90047a211bba742f3b5ad2b75d9b116711f1c9daa7aa90ca1c479bb7a2e5479250b4aaebb2f273008ead7d2d64a2793166afde410d76443ac24ea31",
          "sha256": "07cdbc984865f1ef0c6fd7a6c4cdb1e0425db2289ae6377aa53db2d05b103a26",
          "sha1": "50d199d1285d3f548758b9ac038af890b48645e3",
          "md5": "39066071dedc2c87ecc7d0829a4ac0d0"
        }
      ]
    }
  ]
}
