{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-common-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.3.0.jar",
          "url": "sootychimneys-common-1.3.0.jar",
          "size": 160060,
          "sha512": "6136bcd484695f34ab4584e4c465a20e5e7d51cc4989b0b824b410833969d7d16d521a259410fd4b4b7f73022929c1d6be92844d4319e47ef0eaaac28d308e0f",
          "sha256": "192b7e37268493d28b5be445b888892bbc3037448b68b18f17f76addd04478c0",
          "sha1": "cb5eb79fe9f394b9385c22b3b1eef5d825637d5f",
          "md5": "5f0afe6c55e598eaeb3804462a505af8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.3.0.jar",
          "url": "sootychimneys-common-1.3.0.jar",
          "size": 160060,
          "sha512": "6136bcd484695f34ab4584e4c465a20e5e7d51cc4989b0b824b410833969d7d16d521a259410fd4b4b7f73022929c1d6be92844d4319e47ef0eaaac28d308e0f",
          "sha256": "192b7e37268493d28b5be445b888892bbc3037448b68b18f17f76addd04478c0",
          "sha1": "cb5eb79fe9f394b9385c22b3b1eef5d825637d5f",
          "md5": "5f0afe6c55e598eaeb3804462a505af8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-common-1.3.0-sources.jar",
          "url": "sootychimneys-common-1.3.0-sources.jar",
          "size": 116115,
          "sha512": "44679662c67a71c9124f0d4a63ffa2b2101b1c4374c074db6aed5c51bd3517262fe794e9b8f75a963abea8399e6d97e01f86e3f6eaa5e848442055e0e5bcd022",
          "sha256": "96198ea29ee6d9c5687e71928f7e1b6b2564ef8eec8303168b40e9925f8866f8",
          "sha1": "84ce000bc7a720a32a6bded3a7eb60b0a1f550c7",
          "md5": "79e4717c28ce54553dc06e0961de32fa"
        }
      ]
    }
  ]
}
