{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-common",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.2.jar",
          "url": "thief-1.20.1-common-1.2.2.jar",
          "size": 135302,
          "sha512": "1c2afd979fc182f0d200c1a02907f09ae80a909a80b7a8cc3e9bcdc5a3356975f87c16e8ae29d749916f055f1eddcb9942360f9d5bff924e1c6b138df7afabd9",
          "sha256": "6ad9bbcaee2e57f7ac5e05e99002dd9ad2e2969ba0bc0178ac04f607f8c46e50",
          "sha1": "a04fcbfb9c4fc09c67e0d4c6353d95cc5e10a6c9",
          "md5": "4caadcb86c0670484b261e86708e0b6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.2.jar",
          "url": "thief-1.20.1-common-1.2.2.jar",
          "size": 135302,
          "sha512": "1c2afd979fc182f0d200c1a02907f09ae80a909a80b7a8cc3e9bcdc5a3356975f87c16e8ae29d749916f055f1eddcb9942360f9d5bff924e1c6b138df7afabd9",
          "sha256": "6ad9bbcaee2e57f7ac5e05e99002dd9ad2e2969ba0bc0178ac04f607f8c46e50",
          "sha1": "a04fcbfb9c4fc09c67e0d4c6353d95cc5e10a6c9",
          "md5": "4caadcb86c0670484b261e86708e0b6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.2-sources.jar",
          "url": "thief-1.20.1-common-1.2.2-sources.jar",
          "size": 76639,
          "sha512": "0370a19a58b86a014906daa3b069bb47797374fa0ee661e986c329cdf6ee4bd29eed7cec7eb0048fde250ec0e2725837d943c4d7dc7c883ab0e831331c3f35d4",
          "sha256": "c9ff22d977244ec06367394d656c27bf1aacf13bb76e95ee8bcc95f0e602dbf2",
          "sha1": "2dfa17662e990f03fec4bdaab1bf0d1c645c158c",
          "md5": "775839506cd4e82ad57bfff90467b9f2"
        }
      ]
    }
  ]
}
