{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_polaroid",
    "module": "exposure_polaroid-1.20.1-forge",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-forge-1.1.3.jar",
          "url": "exposure_polaroid-1.20.1-forge-1.1.3.jar",
          "size": 346668,
          "sha512": "1acbda42982f69c522150cd26d5cfbc3feccc05352c9eebac8cbf530a4204a431fcfb7764362c68d96bc13e66b6752a18c41f40b30a842c15431f16d8fd25bdc",
          "sha256": "3a2e97ee6f5d16c5b3092ddc8bb7bee361a001fc8fab316ff33904b49e065cc7",
          "sha1": "c36e71c3a88077373171d61d64a4d6d8af2276f9",
          "md5": "0a084c6508a7db802b0197aa626a7d6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-1.20.1-forge",
          "version": {
            "requires": "1.9.14"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-forge-1.1.3.jar",
          "url": "exposure_polaroid-1.20.1-forge-1.1.3.jar",
          "size": 346668,
          "sha512": "1acbda42982f69c522150cd26d5cfbc3feccc05352c9eebac8cbf530a4204a431fcfb7764362c68d96bc13e66b6752a18c41f40b30a842c15431f16d8fd25bdc",
          "sha256": "3a2e97ee6f5d16c5b3092ddc8bb7bee361a001fc8fab316ff33904b49e065cc7",
          "sha1": "c36e71c3a88077373171d61d64a4d6d8af2276f9",
          "md5": "0a084c6508a7db802b0197aa626a7d6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-forge-1.1.3-sources.jar",
          "url": "exposure_polaroid-1.20.1-forge-1.1.3-sources.jar",
          "size": 9596,
          "sha512": "ecc17cdd89cd385b9b04bdd344384431a8cdf0802cc46bc63421a3abc68d52b267e0864bab851c14e5722c241c2c4219096f4c985191a329bf968c9cc4d60401",
          "sha256": "7434de0fbc8e933175ecce504350a54275bab1bc80e409baa10d3dcf63e37ff8",
          "sha1": "ac230339cb70ea00bd9ab2f65a61459331765709",
          "md5": "8003547c2ea31e64d720483410f320be"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-forge-1.1.3-dev-shadow.jar",
          "url": "exposure_polaroid-1.20.1-forge-1.1.3-dev-shadow.jar",
          "size": 159464,
          "sha512": "b5e96b183ee4dd4360d87588073f56549c5f997cea6ee0f0d78c907206b2092289677d755ebae3d5fb18cc9438079a15c0f04351c0ebd363e826db0d3846f8de",
          "sha256": "4371bdf7b26b1b6e0348651973cf60b372008445505ce87d614666efe26418ff",
          "sha1": "760d69004b5979859501a1894ec46007f03f59df",
          "md5": "a87c2b32cdec65f70fa232ad979d32c8"
        }
      ]
    }
  ]
}
