{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-neoforge",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.5.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.5.jar",
          "size": 175697,
          "sha512": "137d5342af92bb00dc5ec6c8b15cfa48dfb5c09cab52dc7a8d932c40e90afc7fbd72850de04992c789642169809a20a9d163fbd06b3c41fc067f704d175e5b82",
          "sha256": "e492f89c632b423c60f2a6f91386133f3a31e6e02ea9970f9ef30ece5fce41d4",
          "sha1": "be15102bd2468a224fb02e4d243b54bfca2c9c49",
          "md5": "93e3607e043ec68b9f946f532ec050cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.3-47"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.45"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.5.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.5.jar",
          "size": 175697,
          "sha512": "137d5342af92bb00dc5ec6c8b15cfa48dfb5c09cab52dc7a8d932c40e90afc7fbd72850de04992c789642169809a20a9d163fbd06b3c41fc067f704d175e5b82",
          "sha256": "e492f89c632b423c60f2a6f91386133f3a31e6e02ea9970f9ef30ece5fce41d4",
          "sha1": "be15102bd2468a224fb02e4d243b54bfca2c9c49",
          "md5": "93e3607e043ec68b9f946f532ec050cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.5-sources.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.5-sources.jar",
          "size": 13261,
          "sha512": "ec1f5d32703e3f007cdb8f105d7c3ad305fd3f926fd8015f6d74ffe226868bcc28adc82e963329d223198508f5a5e3ebebf33b0871a61e53c65f9d255de6ad9c",
          "sha256": "74775e0bc139c75521727074cc5f01e7d0b33d775f0b142fa7f90f8bbfc8330a",
          "sha1": "a2de80ff3663355d2a2e869e1cdafcc3b5c1bb75",
          "md5": "6eef27a5f924e81a320caac83a6a10cd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.5-dev-shadow.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.5-dev-shadow.jar",
          "size": 170747,
          "sha512": "0e217f6b9358a9c334302e6d4035b966c2769ffc5b8d6d357dd137c2901d6a49a5933e73adb140763214710c653324780258a42c92e6778be6afe1c78ee9b8ce",
          "sha256": "62a57b77c3ba0ef3f651391740713dc19bf00dbff8c9a00a5af59d8899e1bc33",
          "sha1": "59f5609be482ae0e4399181e101e73622107d0c1",
          "md5": "dea9a137f70366f5160f20e599e88e9f"
        }
      ]
    }
  ]
}
