{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.envelope",
    "module": "envelope-1.21.1-neoforge",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.2-build.353"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.1.jar",
          "url": "envelope-1.21.1-neoforge-0.6.1.jar",
          "size": 1639372,
          "sha512": "3069237e39fddd4f58a08f997ca0d387b24cf0d3441a9301b33ab46276c8c9aa986c38562fe791198719ec247b0617fabd9889e05ec2ae98fedc7c0c19367d12",
          "sha256": "7d209054ed40b24960610b74672343458f3cda91e0d023707eacfb11ae9481d5",
          "sha1": "30e3918f447f7b9d680894b9c38c3d8da58311f4",
          "md5": "87d56fee90a3520fb67b38fec326ab5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "foundry.veil",
          "module": "veil-neoforge-1.21.1",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.25.0.322"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "15.10.2+neoforge"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "tschipp.carryon",
          "module": "carryon-neoforge-1.21.1",
          "version": {
            "requires": "2.2.3.3"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.10-280"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.82+mc1.21.1"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "dev.ryanhcode.sable",
          "module": "sable-neoforge-1.21.1",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "dev.simulated_team.simulated",
          "module": "simulated-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.eriksonn.aeronautics",
          "module": "aeronautics-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.ryanhcode.offroad",
          "module": "offroad-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.1.jar",
          "url": "envelope-1.21.1-neoforge-0.6.1.jar",
          "size": 1639372,
          "sha512": "3069237e39fddd4f58a08f997ca0d387b24cf0d3441a9301b33ab46276c8c9aa986c38562fe791198719ec247b0617fabd9889e05ec2ae98fedc7c0c19367d12",
          "sha256": "7d209054ed40b24960610b74672343458f3cda91e0d023707eacfb11ae9481d5",
          "sha1": "30e3918f447f7b9d680894b9c38c3d8da58311f4",
          "md5": "87d56fee90a3520fb67b38fec326ab5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.1-sources.jar",
          "url": "envelope-1.21.1-neoforge-0.6.1-sources.jar",
          "size": 33020,
          "sha512": "b3ae90db977e744ba6d9b787b30f969179da662f2460d93a5706812b1e25fa14c083f20ef41e7df160b461ac6afd80d1d4142d9c48fa86304b0451509b2b4c6c",
          "sha256": "c324db37d3823b23f988f08f84d5e45b18d46b3922764d4b76dc2e9248e6a280",
          "sha1": "5657c0a14d2e6538dfd0ff24b1383f738ae2c517",
          "md5": "494ac09fbfc13c5a6692119bd1e1d903"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.1-dev-shadow.jar",
          "url": "envelope-1.21.1-neoforge-0.6.1-dev-shadow.jar",
          "size": 1396123,
          "sha512": "3d78d0149cab4d9eef59d48f43f09229c3ceb1f186fe3849cc5e52c5a1321bb1766be01805cc5e6ff52b3cbdd0000833fa59e535a78470bb3d79d5c6ac62463c",
          "sha256": "9d0959daaf8e926903780a06bc41665b09fd06d5615673039f26e173d632d24a",
          "sha1": "bf8ab5530e1017f6e53093ffa58efff18d2648f3",
          "md5": "d9a9edb72116130e8ad7d13fcdcde91b"
        }
      ]
    }
  ]
}
