{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.14-fabric.jar",
          "url": "exposure-fabric-1.7.14-fabric.jar",
          "size": 1324866,
          "sha512": "ba6996e2758acc85b197a9e8edfdc106d96a33fcd37c0324c16efda11b0a6af3b2f9d102762bb2ef5b5a2769c3d29001a0cd84092e2e4e3bb7a4ec10b8fd2344",
          "sha256": "4f30db862702455ddda3a2c51b6366e8bb170b81b62f545061ceedfce3225230",
          "sha1": "44a27ecc9320c91ed8e3a5cb192c09e37809f717",
          "md5": "5aff58d51e3ead45618c8f296c2c6dde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.20.1-0.5.13-fabric"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.14-fabric.jar",
          "url": "exposure-fabric-1.7.14-fabric.jar",
          "size": 1324866,
          "sha512": "ba6996e2758acc85b197a9e8edfdc106d96a33fcd37c0324c16efda11b0a6af3b2f9d102762bb2ef5b5a2769c3d29001a0cd84092e2e4e3bb7a4ec10b8fd2344",
          "sha256": "4f30db862702455ddda3a2c51b6366e8bb170b81b62f545061ceedfce3225230",
          "sha1": "44a27ecc9320c91ed8e3a5cb192c09e37809f717",
          "md5": "5aff58d51e3ead45618c8f296c2c6dde"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.14-sources.jar",
          "url": "exposure-fabric-1.7.14-sources.jar",
          "size": 969115,
          "sha512": "304222e4c831a6e816e5dd5ce292d562b4b4d26c43206f8d55f81233815c5e5e7e5208da4fc74032cef208698b4768e63b7bf7b1cb89de8410dfe8553f8aebe3",
          "sha256": "ce796e296bebfffc1dc3d43f524c0d9db8f43eb20e333242509ec2d2a1953643",
          "sha1": "6a435d2eaff8b3af1805c9ec3194c83a0c2207f7",
          "md5": "31878c2ba8784def1d19d51418231011"
        }
      ]
    }
  ]
}
