{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.4.jar",
          "url": "horseman-1.21.1-neoforge-1.3.4.jar",
          "size": 318903,
          "sha512": "1e2341f98adf63a73aef994ec50dbe0c71be864493c1441c4bb23dd33f019ddd91c7cebca5fc2c953aa424d6f3f56064eb07e97d3161f7ac08c3b59c0ace9548",
          "sha256": "eecececd75fff87f99b886799839fe820e20d32a396fe088872c410e8c295642",
          "sha1": "e955848521178f20aa6bfc820ce28d144934bf6b",
          "md5": "7001ac02afc8bff238d6be53bafa00ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.4.jar",
          "url": "horseman-1.21.1-neoforge-1.3.4.jar",
          "size": 318903,
          "sha512": "1e2341f98adf63a73aef994ec50dbe0c71be864493c1441c4bb23dd33f019ddd91c7cebca5fc2c953aa424d6f3f56064eb07e97d3161f7ac08c3b59c0ace9548",
          "sha256": "eecececd75fff87f99b886799839fe820e20d32a396fe088872c410e8c295642",
          "sha1": "e955848521178f20aa6bfc820ce28d144934bf6b",
          "md5": "7001ac02afc8bff238d6be53bafa00ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.4-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.4-sources.jar",
          "size": 13830,
          "sha512": "1731fb6a5184b92b3c24b7346ebf519b76085443af740d3de19a356a4998d90fad3cf822f0a335c2ab6a95184d82989a9def8010db6855c8f64d1a9549e38eec",
          "sha256": "6444327d9f62ee4afb5a8ca61325f0732e6d8505998eb2a0ee72330afd747668",
          "sha1": "a170e7b8a22f6ea30a71681f96475ec0d0b085f0",
          "md5": "c7756c56c2e0d9504a22aaa12f198a94"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.4-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.4-dev-shadow.jar",
          "size": 133825,
          "sha512": "8352d4e4ffa96bf8ea329032a130a423cac417a92a53833cc861011db93919dfaf76ee000cfe5c615dea21981c1ad68e0fcf8acab3353f7c22c218a762dcf1fa",
          "sha256": "00ac00e50bc13a43d5b9eb7382a320bb2c700886beca5f5290b172acf0cfdb49",
          "sha1": "7626450c9344bdb6a40b010a008f0a1548c9b3de",
          "md5": "d43d3a42ab2bacc0ea60145e6ed47d9d"
        }
      ]
    }
  ]
}
