{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.5.1-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.5.1-forge.jar",
          "size": 680674,
          "sha512": "902aa0f6e7222cb97f117ba6d5165308a7bdabf08b79df4256bd3d6cbb4980cd53840f2c635d112f6e93fd036b11221299aa0de2a7889038e5aa9401b346e855",
          "sha256": "65e9b0ed8b5cba7a31d8b1fb5ac03f428ca57c75d4aad6218cf3f592c0d80a77",
          "sha1": "a87fcf7627abc5f13380558bafa4f621b149105f",
          "md5": "19c046483090a4f30e509857082d5154"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.5.1-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.5.1-forge.jar",
          "size": 680674,
          "sha512": "902aa0f6e7222cb97f117ba6d5165308a7bdabf08b79df4256bd3d6cbb4980cd53840f2c635d112f6e93fd036b11221299aa0de2a7889038e5aa9401b346e855",
          "sha256": "65e9b0ed8b5cba7a31d8b1fb5ac03f428ca57c75d4aad6218cf3f592c0d80a77",
          "sha1": "a87fcf7627abc5f13380558bafa4f621b149105f",
          "md5": "19c046483090a4f30e509857082d5154"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.5.1-sources.jar",
          "url": "scholar-1.20.1-forge-1.1.5.1-sources.jar",
          "size": 403028,
          "sha512": "90b8cf88dcd548c99ef893801252d71084c510591c3bab86e2c11dcc47dbf8c150a8a24d8b43c5bfee134a555a15be54a64f18c3830d2b6dcc97f244455b2782",
          "sha256": "0db7ceb28980890a03667a890f536dfc964d033fbeafa1245170891a0341f296",
          "sha1": "a54535f4e322e4532edca163280ce483399d1875",
          "md5": "f8480d4ba923732cd84b0d228e2cb231"
        }
      ]
    }
  ]
}
