{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.mortaar",
    "module": "mortaar-1.21.1-fabric",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.2.3.jar",
          "url": "mortaar-1.21.1-fabric-1.2.3.jar",
          "size": 80107,
          "sha512": "f3de0b90da14bff779b435ed8b2c20808b6c2ce668e0a287b2195d1eaf4272f72f76bc78d867f772298194e850b568d6e44fded04fcea0bc677ac2332969de19",
          "sha256": "3a210c2c042c8d2464a770cd2892ce2492d6ce0b0416f4df0349c0b67ea4531b",
          "sha1": "db3d74f30f0f6576b0194171137417425254f1ff",
          "md5": "b9309e8edacec80c818d1681ac0193be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.2.3.jar",
          "url": "mortaar-1.21.1-fabric-1.2.3.jar",
          "size": 80107,
          "sha512": "f3de0b90da14bff779b435ed8b2c20808b6c2ce668e0a287b2195d1eaf4272f72f76bc78d867f772298194e850b568d6e44fded04fcea0bc677ac2332969de19",
          "sha256": "3a210c2c042c8d2464a770cd2892ce2492d6ce0b0416f4df0349c0b67ea4531b",
          "sha1": "db3d74f30f0f6576b0194171137417425254f1ff",
          "md5": "b9309e8edacec80c818d1681ac0193be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.2.3-sources.jar",
          "url": "mortaar-1.21.1-fabric-1.2.3-sources.jar",
          "size": 5411,
          "sha512": "92195acead78d8950672e8f777b110bfc02be57227a0277ab25c9a08fc4509ddbe51cebe714c88b965b595be9fbff947c01989ec1ef788d85991a3939d1eb80e",
          "sha256": "df436edb9e026957b2b6b6ebc02259bded19f3d2a815f9683cb3c06538d18bb5",
          "sha1": "4f65e01e2d329915a8fb460bf2ef292b819a77cf",
          "md5": "2405311e92be1c1647c7b3bed7181b8c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.2.3-dev-shadow.jar",
          "url": "mortaar-1.21.1-fabric-1.2.3-dev-shadow.jar",
          "size": 78487,
          "sha512": "cf8aca79131cdd6131bf50345f596cc55251983c23cf53f63830bcc10bd4c981f2a9bd220b5c3b7126d43c034b82577f0f5d995f24b212181e571fa6c42e15f4",
          "sha256": "ef226ff0a89499bd8ad85bdeeefadc1a3df84e54f48e683b299a05c070ba199d",
          "sha1": "f40502b43bd2e1c8025b6b43227f3fe669dba608",
          "md5": "77d29cc1b6c7d2d353faa36e477d959c"
        }
      ]
    }
  ]
}
