{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.8.jar",
          "url": "horseman-1.21.1-neoforge-1.3.8.jar",
          "size": 319700,
          "sha512": "ea72a7ca2d7f589b5ad924a244ff1da1766d70c65f79df456701af97189bfac0ce1e4b612cbdce2790f4bb38db559c6c7fe699004b052c34a8d9855a3cb792a1",
          "sha256": "b6e0e6574499725ffa0d8097bbdf56f94cc793e1fe8dd7dbe0d1f68a509a2cc2",
          "sha1": "fb5ea902a9379bcc0c3f908fb5c0b8966b9caccc",
          "md5": "a03b82c376cb234b13106992b40712cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.8.jar",
          "url": "horseman-1.21.1-neoforge-1.3.8.jar",
          "size": 319700,
          "sha512": "ea72a7ca2d7f589b5ad924a244ff1da1766d70c65f79df456701af97189bfac0ce1e4b612cbdce2790f4bb38db559c6c7fe699004b052c34a8d9855a3cb792a1",
          "sha256": "b6e0e6574499725ffa0d8097bbdf56f94cc793e1fe8dd7dbe0d1f68a509a2cc2",
          "sha1": "fb5ea902a9379bcc0c3f908fb5c0b8966b9caccc",
          "md5": "a03b82c376cb234b13106992b40712cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.8-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.8-sources.jar",
          "size": 13830,
          "sha512": "f12760cc31398363f13b40accc8b82c789e254cc8295e919f7df88ce8af3b31006773da5463703f48fbc0b9489a3da288329170ebcb686fc9f3e16e52d34f4fa",
          "sha256": "733ce94a68a03492fcab6fa4b7d8d90d0a87719e8db33e60beb81656158e5508",
          "sha1": "68df1436c4fc7b553300ed903144cbbeba4e7cf7",
          "md5": "aafdd44d5386c3113a83ea7749c6d761"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.8-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.8-dev-shadow.jar",
          "size": 134590,
          "sha512": "800f40d2d77ddf5d4e714682b4155c54552a9483c72405ce76df7aef2c4eb7138347107eee672ff35f40201af26303ad58057358e76d2e22ae19fbb7a46e9052",
          "sha256": "61373823e99bca90134b8e6cec3df56b29a0a9c5d84674b09955f1681142f8a3",
          "sha1": "42530feaca9252fdeaa14aa3cfcf7c4b78137a5a",
          "md5": "d08c4af26f1240ab75c89d06a0a03c18"
        }
      ]
    }
  ]
}
