{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.5-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.5-common-api",
          "version": {
            "requires": "21.4.0.25"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.5-common-1.3.4.jar",
          "url": "sootychimneys-1.21.5-common-1.3.4.jar",
          "size": 164662,
          "sha512": "5f2770f90b2efce4bc896f5722c77b702dd870bb43d5d5ba690b1b9304b29a429df86b1c11a1462d739bd859685691d8453d14dcbec07d4ac577d35b31ff8f7f",
          "sha256": "786b53462929ba28257111ef3c3458f1812f1bfb2e13178ab2f6316fa911ef25",
          "sha1": "6ba2a8e230d963515a9a21eb44771938189ac95c",
          "md5": "630fb7340c45885cd71ae4943c324834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.5-common-1.3.4.jar",
          "url": "sootychimneys-1.21.5-common-1.3.4.jar",
          "size": 164662,
          "sha512": "5f2770f90b2efce4bc896f5722c77b702dd870bb43d5d5ba690b1b9304b29a429df86b1c11a1462d739bd859685691d8453d14dcbec07d4ac577d35b31ff8f7f",
          "sha256": "786b53462929ba28257111ef3c3458f1812f1bfb2e13178ab2f6316fa911ef25",
          "sha1": "6ba2a8e230d963515a9a21eb44771938189ac95c",
          "md5": "630fb7340c45885cd71ae4943c324834"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.5-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.5-common-1.3.4-sources.jar",
          "size": 106868,
          "sha512": "a43673562f1f6331dc781196b22c325f26258842ae69cd5cd472366484a28a2b2b737334c0d61e4afda50500bbe5e795e11a6d037feb7eebd1a885b651259e40",
          "sha256": "76e98dcc803879121f649e6c29227666402b316c86f4c025333ffa7e6936b028",
          "sha1": "cb910ae513813245e3cfc00faf5b0f9acc8056ff",
          "md5": "370026c5622a14e44cdcf1c994ee818d"
        }
      ]
    }
  ]
}
