{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.3.jar",
          "url": "horseman-common-1.1.3.jar",
          "size": 67647,
          "sha512": "6a9ec458834b8db43df2006bef940e1eef35efb3a7d41493b664f5a53119281e3e67a620ca59c003cbdde1dcd70962ae6cf1dc6d89efa88538b288bf4051d18f",
          "sha256": "39a045f19bae2212bf0d0edfc56a78470a78533c03e7a1279dae3da296dffb34",
          "sha1": "75058af6e11ddacd78654d4953f5a8e8debc49a3",
          "md5": "e6dcd745e5c05b2aff7dbf711cf009df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.3.jar",
          "url": "horseman-common-1.1.3.jar",
          "size": 67647,
          "sha512": "6a9ec458834b8db43df2006bef940e1eef35efb3a7d41493b664f5a53119281e3e67a620ca59c003cbdde1dcd70962ae6cf1dc6d89efa88538b288bf4051d18f",
          "sha256": "39a045f19bae2212bf0d0edfc56a78470a78533c03e7a1279dae3da296dffb34",
          "sha1": "75058af6e11ddacd78654d4953f5a8e8debc49a3",
          "md5": "e6dcd745e5c05b2aff7dbf711cf009df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.1.3-sources.jar",
          "url": "horseman-common-1.1.3-sources.jar",
          "size": 37408,
          "sha512": "b730fb183d5d9f1249d5b122802c29cafbfeefefed9650ad9a7016cdc9d65cb75c0a615cfd4131feb1ab06702be0a75d39e64f319c6fbddc50bb563d01a35cbd",
          "sha256": "37bf46741b10bfd109411ee8889a39b7d4c3ca9fcd4cafb2ed5cfa4527847074",
          "sha1": "83d9a6fc4286581af57b3bad1fcf4e3a97c48419",
          "md5": "44abc4039853b62ab65f927fa9e972ba"
        }
      ]
    }
  ]
}
