{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-fabric",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-fabric-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.0.jar",
          "url": "sootychimneys-fabric-1.3.0.jar",
          "size": 165676,
          "sha512": "d9587df4bdd15792e5db29b06e1cbd45ae9dd9b9bb2f564bb327d163735709eacf3f2c1c8745c78d17d2265ce340f49b77303dca274940a66c9589bcaa73d1dd",
          "sha256": "623fd87d18567fc79c0cdfdb5c72e4796ef92e8fd3815cae6e4e27c283028af4",
          "sha1": "245b11f48d4d8b9d55bef3b6893a233d32ebb80b",
          "md5": "a3468f252b8dc1cc867b76d1055d50f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.21"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-fabric",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.0.jar",
          "url": "sootychimneys-fabric-1.3.0.jar",
          "size": 165676,
          "sha512": "d9587df4bdd15792e5db29b06e1cbd45ae9dd9b9bb2f564bb327d163735709eacf3f2c1c8745c78d17d2265ce340f49b77303dca274940a66c9589bcaa73d1dd",
          "sha256": "623fd87d18567fc79c0cdfdb5c72e4796ef92e8fd3815cae6e4e27c283028af4",
          "sha1": "245b11f48d4d8b9d55bef3b6893a233d32ebb80b",
          "md5": "a3468f252b8dc1cc867b76d1055d50f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.0-sources.jar",
          "url": "sootychimneys-fabric-1.3.0-sources.jar",
          "size": 8670,
          "sha512": "592d1a3886b2fbeb7905430238cf445515b483ff85d08971100e6aaa23739cb417a3bc6bfcbee4f3125f40919a138185e8bb9a3804ab76f095579c295c069f09",
          "sha256": "95efd7280972cb97de1ea7d16ddbc572ecbb650a379dad036124b727910170ab",
          "sha1": "f3eef43fef5c17b60e747092b8417d5530c56a46",
          "md5": "ec540b9f9dbb9efecf9d7491c9288b65"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.0-dev-shadow.jar",
          "url": "sootychimneys-fabric-1.3.0-dev-shadow.jar",
          "size": 162145,
          "sha512": "b659255f0768dabeea223caf4d29b6b1c1b1fcbe00757027b9c96a52714acfc9cfc165b38d5c57061bc42d1b060b3c84aeaec721166afb4871f76e64dc48f02a",
          "sha256": "f38d9736b846192a73b005c2da6723fbc4167e58c54d346ce64532436cdd18e3",
          "sha1": "0b96f2ac9013fd03b58786daefab874db290d1f3",
          "md5": "33314c667608d17a4dfca8af443edeb7"
        }
      ]
    }
  ]
}
