{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.0.2-fabric.jar",
          "url": "horseman-fabric-1.0.2-fabric.jar",
          "size": 257813,
          "sha512": "34cd78623f819d5ec5ca25032d7531d6acc848060cf5e0ef033310476e318ce4b779780aab4bf9d6d6f96f728771533c9972665dc380bb2e816e7e9d42d7cad7",
          "sha256": "51c77a59129df3f68ce020c501515cfaae629f8c50a0b90ce6dc57c087780033",
          "sha1": "13d61eaa1da9c06b90eb9d895a68a997f8a21e91",
          "md5": "aa554d6213a9d996de74b60a17911784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.0.2-fabric.jar",
          "url": "horseman-fabric-1.0.2-fabric.jar",
          "size": 257813,
          "sha512": "34cd78623f819d5ec5ca25032d7531d6acc848060cf5e0ef033310476e318ce4b779780aab4bf9d6d6f96f728771533c9972665dc380bb2e816e7e9d42d7cad7",
          "sha256": "51c77a59129df3f68ce020c501515cfaae629f8c50a0b90ce6dc57c087780033",
          "sha1": "13d61eaa1da9c06b90eb9d895a68a997f8a21e91",
          "md5": "aa554d6213a9d996de74b60a17911784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.0.2-sources.jar",
          "url": "horseman-fabric-1.0.2-sources.jar",
          "size": 40496,
          "sha512": "2cb4065d038b39fa8e24528e93e9f4fdba292a81eb991a4521b129c8a1cc8c79809cf0df7da19e99c175eef31f248764c1937c305c0ac9fccb27a456731bd9fd",
          "sha256": "c1fbb8d18b6bb07d12ce2f9f2377702ee3437c47b9c2de2fd64f65091fa253e5",
          "sha1": "612b553e6b5b508411b74f50babdb08905f1ae2b",
          "md5": "f3109752d5d49166bb340368053e0ba1"
        }
      ]
    }
  ]
}
