{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.2.jar",
          "url": "horseman-1.21.1-fabric-1.3.2.jar",
          "size": 135946,
          "sha512": "513e945e3b2576695ab5f25b13a63edc72d88e632d117997ea33c940b44b600afe3b3f80c76fa3946bc4fe0db4e3dfa19aad35a0bcc5fed610cb69f13f842f5f",
          "sha256": "945da3600d0052c65216501b62d2302a56dd266927e16d463eb0684e605cf15a",
          "sha1": "dc1597f0cc9fa72052b0fa6cf6c81149337927b5",
          "md5": "f19f81dc2900a5f18c8765db773f6670"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.9-neoforge"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.2.jar",
          "url": "horseman-1.21.1-fabric-1.3.2.jar",
          "size": 135946,
          "sha512": "513e945e3b2576695ab5f25b13a63edc72d88e632d117997ea33c940b44b600afe3b3f80c76fa3946bc4fe0db4e3dfa19aad35a0bcc5fed610cb69f13f842f5f",
          "sha256": "945da3600d0052c65216501b62d2302a56dd266927e16d463eb0684e605cf15a",
          "sha1": "dc1597f0cc9fa72052b0fa6cf6c81149337927b5",
          "md5": "f19f81dc2900a5f18c8765db773f6670"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.2-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.2-sources.jar",
          "size": 13820,
          "sha512": "bcba22de15ecc08f0e140fe00dc5403a02730525ce9ec65d8605fcbd6041b3d7a144bec3df8415746aafa29bc7a0acfacb26dff390a0a6cd04ab44030f606a8e",
          "sha256": "e7980203fea85fc110f47654f40307e28e77b1241979e02e16d3ec601cb01406",
          "sha1": "75aefcbb53c82fffdee613a0c315a8530f0ca3bd",
          "md5": "ceb85df4d850ed2736de98b90829a37c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.2-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.2-dev-shadow.jar",
          "size": 134517,
          "sha512": "d65eaa4d0c80bb282bb5c23582216264641f370403dcbc7599e95b4aa10b08b05e90fd07b8079eba1d1a7f8effa70e7f41e8030e73c5dbe10881d8f1241636f9",
          "sha256": "9f771e79ac1a56ee320627c2e57d2de0efd36f0a14a300ab9b5122a7f8f0a07f",
          "sha1": "2772d12b5fde5fbc4b22c38c433f0715d59d7ac2",
          "md5": "82a98ebe129a9595bb6ad86acb6e7f41"
        }
      ]
    }
  ]
}
