{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_polaroid",
    "module": "exposure_polaroid-1.20.1-common",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-common-1.1.4.jar",
          "url": "exposure_polaroid-1.20.1-common-1.1.4.jar",
          "size": 151599,
          "sha512": "966564c6e18d1613c8fcfda6fa5fa82a8447d25efb6ab7f9c4c8ec86c14dc9c228eac3fea3b2399924adb0afab082f80aec0505813a3b6e593dbca2bbd0a65a4",
          "sha256": "d22c1ac1f57c28994e921d2f11e9643ab793e63ec100aa99d3c6d0ddcef7e395",
          "sha1": "bc89527d6aae2a9e07111837e5de1d6bbc92e4ea",
          "md5": "3ea45eea7d2b465230532a8e1762eb06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-1.20.1-common",
          "version": {
            "requires": "1.9.14"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-common-1.1.4.jar",
          "url": "exposure_polaroid-1.20.1-common-1.1.4.jar",
          "size": 151599,
          "sha512": "966564c6e18d1613c8fcfda6fa5fa82a8447d25efb6ab7f9c4c8ec86c14dc9c228eac3fea3b2399924adb0afab082f80aec0505813a3b6e593dbca2bbd0a65a4",
          "sha256": "d22c1ac1f57c28994e921d2f11e9643ab793e63ec100aa99d3c6d0ddcef7e395",
          "sha1": "bc89527d6aae2a9e07111837e5de1d6bbc92e4ea",
          "md5": "3ea45eea7d2b465230532a8e1762eb06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-common-1.1.4-sources.jar",
          "url": "exposure_polaroid-1.20.1-common-1.1.4-sources.jar",
          "size": 130783,
          "sha512": "d31e854c8731de34ecadae77ad57fda38be75186a6bbd2f103e8172632e6efb7b5173a5531191c961a70ade98176c69bdaf32df50cf3e2eaffa6dccc9ef1224a",
          "sha256": "8fd81d151cfab6fc87f49722204c2bc92e07710b41094cc9e644d813da4953c2",
          "sha1": "cffca65292b70e4731c35fdab213af3ff0207ce6",
          "md5": "37544b8f215842186143b6dd1a1b23f7"
        }
      ]
    }
  ]
}
