{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.2.0.jar",
          "url": "horseman-1.20.1-common-1.2.0.jar",
          "size": 75202,
          "sha512": "e4c719b42d28c575624f432740961d77f0f4b21e67525668c4d983740e4294d5e0907ddb236b85e399514ff8ab3116c3ec2c526f26092e5052a716aca0da5755",
          "sha256": "965efaf515b759e0e33e68527248679416626eef6af1bcb0ae655d8600f01077",
          "sha1": "58c0569823f4d736e4f04043b7694c318a0f6696",
          "md5": "5591295ef4d0560dfa9cd9bdfca28cf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.2.0.jar",
          "url": "horseman-1.20.1-common-1.2.0.jar",
          "size": 75202,
          "sha512": "e4c719b42d28c575624f432740961d77f0f4b21e67525668c4d983740e4294d5e0907ddb236b85e399514ff8ab3116c3ec2c526f26092e5052a716aca0da5755",
          "sha256": "965efaf515b759e0e33e68527248679416626eef6af1bcb0ae655d8600f01077",
          "sha1": "58c0569823f4d736e4f04043b7694c318a0f6696",
          "md5": "5591295ef4d0560dfa9cd9bdfca28cf2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.2.0-sources.jar",
          "url": "horseman-1.20.1-common-1.2.0-sources.jar",
          "size": 40134,
          "sha512": "e7976e661dfac486a22394a25ac0e208a1ef7ec414cb2009d06cdc4a76779bf7a3d6df85b943bc9fe8f5f4e7d91c6cae16801032a0dd7750f84cf076c9a7a7f1",
          "sha256": "1ff1c6a94612521ca9044cedfaa085693b843cd19158512bb177f3551285bedc",
          "sha1": "1624c072ea4f4ca0f52059342b611824a84aec2c",
          "md5": "86e5f85bbbe0d00e29b1fdec6deff642"
        }
      ]
    }
  ]
}
