{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.18.jar",
          "url": "exposure-1.20.1-forge-1.9.18.jar",
          "size": 2243901,
          "sha512": "e287ba199e4689d3dd28e32ae8592f7ad880feca77dd42e79f3f2428b3a837ac33c3ebd08dc72a34a49b3a221be801086f442478c8e1df267f328e50beca89e1",
          "sha256": "3535a1653297729c3e119fc9c151beb0dd2e52e4beff63be09c0d41b62e4ad1d",
          "sha1": "3623be41832194e1e76125cc7a32b39a02cd7da0",
          "md5": "ca5a634ff34e5a5074c4dc79d5a29988"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.18.jar",
          "url": "exposure-1.20.1-forge-1.9.18.jar",
          "size": 2243901,
          "sha512": "e287ba199e4689d3dd28e32ae8592f7ad880feca77dd42e79f3f2428b3a837ac33c3ebd08dc72a34a49b3a221be801086f442478c8e1df267f328e50beca89e1",
          "sha256": "3535a1653297729c3e119fc9c151beb0dd2e52e4beff63be09c0d41b62e4ad1d",
          "sha1": "3623be41832194e1e76125cc7a32b39a02cd7da0",
          "md5": "ca5a634ff34e5a5074c4dc79d5a29988"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.18-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.18-sources.jar",
          "size": 52286,
          "sha512": "0ec4ee666a44672339fe7147cced7b8a80520e5bda82dacaf639ca279f4d25c6ada50fada0e7497f09a784238b369d5d13d6d5c705e8ad0c7c9e58023666a83c",
          "sha256": "be52ea47823cc45346930c86175c5ce230dbb0945317caf9747555e2a7ec9d96",
          "sha1": "dd70a3f0a096876235056af65441d42130ecb124",
          "md5": "7725fbff86d18c1191fbcf89fb585257"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.18-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.18-dev-shadow.jar",
          "size": 2017045,
          "sha512": "f32a506747a88125cc103ed27ad52e2c1a81e69f7e59ecf02469846c8ced364342ace3a5b5acc24e6d40885323c01fe6c22a8208af28262e26f751eee23086b6",
          "sha256": "48dfe7c0ea1f3ac1fe6d5c0ea537439bbf8306b42532c97159604397126a3fb3",
          "sha1": "66bdf4217da761dc8dbfd954509e27e476e38072",
          "md5": "c53a20a8c6e9a8ffd53c9a66eda1547b"
        }
      ]
    }
  ]
}
