{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.2.jar",
          "url": "horseman-1.21.1-fabric-1.4.2.jar",
          "size": 205481,
          "sha512": "70db3f0a86336dce49cbfd90e6da3ef469a63013ca314c180e307bbbecfd2e97c9994ab26e482ea2f8d2e5e0ad1625147c97dca125c568a06fae7e056aceb107",
          "sha256": "2766fbdffa07cb6efd5de8286fb806918ee8f42dfab204a4d89030ec5e495a5a",
          "sha1": "aad14de1ca55a11039b5290d2744c778023c070e",
          "md5": "986433b58e58dc6d3caeb90aa042ff09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.2.jar",
          "url": "horseman-1.21.1-fabric-1.4.2.jar",
          "size": 205481,
          "sha512": "70db3f0a86336dce49cbfd90e6da3ef469a63013ca314c180e307bbbecfd2e97c9994ab26e482ea2f8d2e5e0ad1625147c97dca125c568a06fae7e056aceb107",
          "sha256": "2766fbdffa07cb6efd5de8286fb806918ee8f42dfab204a4d89030ec5e495a5a",
          "sha1": "aad14de1ca55a11039b5290d2744c778023c070e",
          "md5": "986433b58e58dc6d3caeb90aa042ff09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.2-sources.jar",
          "url": "horseman-1.21.1-fabric-1.4.2-sources.jar",
          "size": 18450,
          "sha512": "2564337d4cc3da5ea9a9af2b4fedaca6ab42f0166bd7ff0cb0bee23b717b0cbcf25992e53e1f7a2ca8497c58e2621af5514083b96b23c7760fbaeea1f98c7065",
          "sha256": "f27f85189701e62e5ae13028b3ee8b199c9b5820a3ff642af54704072ef5f40f",
          "sha1": "496c87555d494be77f2f51003e9015f1676e2386",
          "md5": "9b8f96971de894a20fdae0f138b3fe62"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.2-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.4.2-dev-shadow.jar",
          "size": 203747,
          "sha512": "c97c67d0523367d077c1b9317cebbe64a09d90f6c48f71625b12b0f0b041d8842deb55af19593585bff85afe1a875aeb952db12ca04d9ed0bc77e94b30d33100",
          "sha256": "4e8571b3319bd426e0832b3d21ad4b6867e5cb0f45513a0e7654d91d4076d95e",
          "sha1": "eba60863fdb14cac2363cc8f5158e786c52e4cf8",
          "md5": "e83c537475d6c982e29ad291f9a129d3"
        }
      ]
    }
  ]
}
