{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.12.jar",
          "url": "exposure-common-1.7.12.jar",
          "size": 1291545,
          "sha512": "da1aca9c7d38d38ce07fab3ddf570162984fca7324669da770986c27789edf7db45d089d276540cdea280fce09f083e613ba8696ec6b42bd8e39ea6e0619e826",
          "sha256": "694cb980157fbe0ea8e9d21efa03f963fc409c4c184ef7e7a4848145d1a0f5f3",
          "sha1": "5eae88e043ecce6a82aa8fdae489eb10bce2a44e",
          "md5": "e5cde85429b6c943defb505b13cea181"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.12.jar",
          "url": "exposure-common-1.7.12.jar",
          "size": 1291545,
          "sha512": "da1aca9c7d38d38ce07fab3ddf570162984fca7324669da770986c27789edf7db45d089d276540cdea280fce09f083e613ba8696ec6b42bd8e39ea6e0619e826",
          "sha256": "694cb980157fbe0ea8e9d21efa03f963fc409c4c184ef7e7a4848145d1a0f5f3",
          "sha1": "5eae88e043ecce6a82aa8fdae489eb10bce2a44e",
          "md5": "e5cde85429b6c943defb505b13cea181"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.12-sources.jar",
          "url": "exposure-common-1.7.12-sources.jar",
          "size": 934107,
          "sha512": "bc799db8de16ff0ab4cf9fe152f135e4ffe004d517ad6d3b9abc2b15c297a59cdd8cba9a6839c55f522c50713c00dfbec64d63d0718e316ae46990ffc371dfc4",
          "sha256": "16483980945e500f4e68c453358af3abf772115ef3f0c5f9e09264243e3f023f",
          "sha1": "b7cab456ffef76d20c9d71575b7a8b3eeb809adb",
          "md5": "3b658a6722ab19318533071053b5d0eb"
        }
      ]
    }
  ]
}
