{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-26.1.1-common",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-common-api",
          "version": {
            "requires": "29.3.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.5.jar",
          "url": "sootychimneys-26.1.1-common-1.3.5.jar",
          "size": 160913,
          "sha512": "775805fc5b799cf5a6f2e27f934db28ab94485d7ed1f1d541a10b6e486cdaef9ba5ee1c3eb3f6f26f766065e4714571ce56a62d66ed87da388812c916c3a4115",
          "sha256": "7586aa289dacc55b85bd7adf645991b8da0200385443d9152557394c77995369",
          "sha1": "f9d9d09ef1806d6e167dd2a623fa978d09fa1617",
          "md5": "a5ae51fee741664968f48c6b0f80cf06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.5.jar",
          "url": "sootychimneys-26.1.1-common-1.3.5.jar",
          "size": 160913,
          "sha512": "775805fc5b799cf5a6f2e27f934db28ab94485d7ed1f1d541a10b6e486cdaef9ba5ee1c3eb3f6f26f766065e4714571ce56a62d66ed87da388812c916c3a4115",
          "sha256": "7586aa289dacc55b85bd7adf645991b8da0200385443d9152557394c77995369",
          "sha1": "f9d9d09ef1806d6e167dd2a623fa978d09fa1617",
          "md5": "a5ae51fee741664968f48c6b0f80cf06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.5-sources.jar",
          "url": "sootychimneys-26.1.1-common-1.3.5-sources.jar",
          "size": 109008,
          "sha512": "ce7b6b559cb25e17b5b0dc76a38b2e2b23c976d2ad31561a590203f4d448cbb1dc0838201d9e544e4a074d625229567915012da90ab91dc6306f5ab6e3c990d1",
          "sha256": "8e5f4bac903874d46a854f795ce79546f46d0522c592ce223e894ea948f02d38",
          "sha1": "4b3b27038c9e398368ff1899321fb1d923606aa1",
          "md5": "e639f471605dc2f654d07f135317050e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.5.jar",
          "url": "sootychimneys-26.1.1-common-1.3.5.jar",
          "size": 160913,
          "sha512": "775805fc5b799cf5a6f2e27f934db28ab94485d7ed1f1d541a10b6e486cdaef9ba5ee1c3eb3f6f26f766065e4714571ce56a62d66ed87da388812c916c3a4115",
          "sha256": "7586aa289dacc55b85bd7adf645991b8da0200385443d9152557394c77995369",
          "sha1": "f9d9d09ef1806d6e167dd2a623fa978d09fa1617",
          "md5": "a5ae51fee741664968f48c6b0f80cf06"
        }
      ]
    }
  ]
}
