{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.1-fabric",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-fabric-1.1.3.jar",
          "url": "scholar-1.21.1-fabric-1.1.3.jar",
          "size": 339336,
          "sha512": "af10c4951e77a2d1bd74b34e17118489fbffd0a3a603c2859f40bbaf3929c07825c025e935d66c6caebc14ef2f9d12686d91ca06dc90cac7d7410910e70cf9cd",
          "sha256": "bcfec0be7afc3e5213018ed558b5380de8f7982dd40aec56d3758b3f6d9ba5ed",
          "sha1": "ff15c72b4c9927c29f413d3a4f9280aae224df98",
          "md5": "4867518469c3412ab0cf2bde24756c02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.9-neoforge"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "Mv3952ns"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-fabric-1.1.3.jar",
          "url": "scholar-1.21.1-fabric-1.1.3.jar",
          "size": 339336,
          "sha512": "af10c4951e77a2d1bd74b34e17118489fbffd0a3a603c2859f40bbaf3929c07825c025e935d66c6caebc14ef2f9d12686d91ca06dc90cac7d7410910e70cf9cd",
          "sha256": "bcfec0be7afc3e5213018ed558b5380de8f7982dd40aec56d3758b3f6d9ba5ed",
          "sha1": "ff15c72b4c9927c29f413d3a4f9280aae224df98",
          "md5": "4867518469c3412ab0cf2bde24756c02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-fabric-1.1.3-sources.jar",
          "url": "scholar-1.21.1-fabric-1.1.3-sources.jar",
          "size": 59860,
          "sha512": "4d87c02c63f027554337a3223cbaa93d054877f74940aed5e7183c1014091bcceeb686d9ed4e406ea2b01ce0ecff13b94e424e3fc47d4088ab01473a9f8588ee",
          "sha256": "fd4d55a33669cf8fd40708a7c3d5191847f60537655cf8b3e450d1f7756992f9",
          "sha1": "e97d2b3fb0f5575b4f95584a4c403319b051ae2c",
          "md5": "fff04c3628c36030c34dca73b606d278"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-fabric-1.1.3-dev-shadow.jar",
          "url": "scholar-1.21.1-fabric-1.1.3-dev-shadow.jar",
          "size": 334897,
          "sha512": "6fcd083e8b5ef8fa46a31b8d52f52857f95ee850879f5a58efc44fa0ca9f8ee246b7b9920bf91bcddaf7c03c46d5da88bc264ea73031c04c580b95850747dd17",
          "sha256": "1b37cb8e1dd4672ed53a8574c56e4b80c18708fd691b1b0f39b8c0342c3f2e05",
          "sha1": "e34c6fdd8a39e75dcda05a159d5000fde9f350c0",
          "md5": "c165650a173bc5f82cd250bf5ffa17a3"
        }
      ]
    }
  ]
}
