{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.4-neoforge",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.4-neoforge-api",
          "version": {
            "requires": "20.0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.3.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.3.jar",
          "size": 179134,
          "sha512": "83808105f8a556bcca897696efd7986d735c806ef6b96e6d7956773145de6ad513fd7f46fba3acaa33c1f3096be17f850b4b599db10b0375f308f40f9fa80e5b",
          "sha256": "efdb050e917664c9f6244a7abb3e7f5e4920d7e9cc5b835d7f970f50c7bf15df",
          "sha1": "74f3b2a95863c3aaf3aa80427e9522c248aa5d5c",
          "md5": "0da835ec33c89568e8f33204ee24d079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.4-neoforge",
          "version": {
            "requires": "20.0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.3.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.3.jar",
          "size": 179134,
          "sha512": "83808105f8a556bcca897696efd7986d735c806ef6b96e6d7956773145de6ad513fd7f46fba3acaa33c1f3096be17f850b4b599db10b0375f308f40f9fa80e5b",
          "sha256": "efdb050e917664c9f6244a7abb3e7f5e4920d7e9cc5b835d7f970f50c7bf15df",
          "sha1": "74f3b2a95863c3aaf3aa80427e9522c248aa5d5c",
          "md5": "0da835ec33c89568e8f33204ee24d079"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.3-sources.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.3-sources.jar",
          "size": 13751,
          "sha512": "83d4bab5ab826217b2bfacd8a9fcfd33c62737101aacb1c1267dd4703519f8e740b257c100388a9665e81004d9a86b3a206601044ba51a29825afd6989cff422",
          "sha256": "76443d36df3143339eee74b58603ca37b6f7e8866e08f15f534c5e75e6f66c4c",
          "sha1": "7c682aa6c4243b39ce45ae2d6b0ffa7b4b6b6639",
          "md5": "b06cca1707b15ed8085787e065ed1a51"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.4-neoforge-1.3.3-dev-shadow.jar",
          "url": "sootychimneys-1.21.4-neoforge-1.3.3-dev-shadow.jar",
          "size": 173897,
          "sha512": "6f71f9c3201800cea6c7ee6f0851d6baf9d95604a5881249ed6884deede8f533d8c31dcf0d27d71a14b8f4bbbcb8c992dd6ee3b32c520a9bd08f9efcf5e78600",
          "sha256": "d6bd1424c75228f70eab929a611231fad74568a4b8f0fd627b018500686e318d",
          "sha1": "fc56aa6dd8ecc457ecf57842c287fca6adc4bbd5",
          "md5": "de7d7fa4d5deea0abf3ad3c4c59adbf4"
        }
      ]
    }
  ]
}
