{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-26.1.2-fabric",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.0.jar",
          "url": "scholar-26.1.2-fabric-1.2.0.jar",
          "size": 735406,
          "sha512": "0bdb17a6d09824d56caf5763de5ddd97db9796a229aedd6e27457b0d998f0cdd975be0acb92c040e66563501c70e57f449b44dba16d0ff3b8821aa25eec3fb05",
          "sha256": "b5595ae7c6638020b63e5145296df195ce7523f9c5df817e78c358821966a1d9",
          "sha1": "947ddaa2795b0dd5db075792098661cd6d34d37f",
          "md5": "00247cb3665c7a58a47fc6dae6f9efe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.0.jar",
          "url": "scholar-26.1.2-fabric-1.2.0.jar",
          "size": 735406,
          "sha512": "0bdb17a6d09824d56caf5763de5ddd97db9796a229aedd6e27457b0d998f0cdd975be0acb92c040e66563501c70e57f449b44dba16d0ff3b8821aa25eec3fb05",
          "sha256": "b5595ae7c6638020b63e5145296df195ce7523f9c5df817e78c358821966a1d9",
          "sha1": "947ddaa2795b0dd5db075792098661cd6d34d37f",
          "md5": "00247cb3665c7a58a47fc6dae6f9efe8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.0-sources.jar",
          "url": "scholar-26.1.2-fabric-1.2.0-sources.jar",
          "size": 564547,
          "sha512": "fb44c059c2c086559bdb38501f40bd0bc4f567f57fca63464c079c33b6a71209aaf5294b0500929ed7506b72f415cc54362dbc5f883207a64446085c84a59720",
          "sha256": "2b495ee97b8f95f5e22657c17622650caa8b02f67d9eade9fa6f7c0126e730f5",
          "sha1": "354239febbf37aca3acb9c1c35606cf39ed01e6d",
          "md5": "52937a3df74abc637ac36d61c053fbce"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.0.jar",
          "url": "scholar-26.1.2-fabric-1.2.0.jar",
          "size": 735406,
          "sha512": "0bdb17a6d09824d56caf5763de5ddd97db9796a229aedd6e27457b0d998f0cdd975be0acb92c040e66563501c70e57f449b44dba16d0ff3b8821aa25eec3fb05",
          "sha256": "b5595ae7c6638020b63e5145296df195ce7523f9c5df817e78c358821966a1d9",
          "sha1": "947ddaa2795b0dd5db075792098661cd6d34d37f",
          "md5": "00247cb3665c7a58a47fc6dae6f9efe8"
        }
      ]
    }
  ]
}
