{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-26.1.1-fabric",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.1-fabric-1.2.3.jar",
          "url": "thief-26.1.1-fabric-1.2.3.jar",
          "size": 153083,
          "sha512": "52ab4cb3ee07d85e4527c617442e5ef3903c2365afe680a01b082abe057b2c2bdbbe667213bae61c4cce25df41d7529ed7e82d7f7f4370dcef222767c3d2b151",
          "sha256": "6c0c994889dc4ed9e1ce8cdea5c1f263354b00e537ad64c2485e1bb2fbf76d89",
          "sha1": "0c5af84e85ef2e1a7ec18db610dd36d33d395e03",
          "md5": "20f587ccefeb683f89793c6fdd51b5da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.1-fabric-1.2.3.jar",
          "url": "thief-26.1.1-fabric-1.2.3.jar",
          "size": 153083,
          "sha512": "52ab4cb3ee07d85e4527c617442e5ef3903c2365afe680a01b082abe057b2c2bdbbe667213bae61c4cce25df41d7529ed7e82d7f7f4370dcef222767c3d2b151",
          "sha256": "6c0c994889dc4ed9e1ce8cdea5c1f263354b00e537ad64c2485e1bb2fbf76d89",
          "sha1": "0c5af84e85ef2e1a7ec18db610dd36d33d395e03",
          "md5": "20f587ccefeb683f89793c6fdd51b5da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.1-fabric-1.2.3-sources.jar",
          "url": "thief-26.1.1-fabric-1.2.3-sources.jar",
          "size": 82386,
          "sha512": "e1edd9e73d158fdfb119a4ee035e8b485afaca7797e56af57f82f3f397cb2f23cde2272924d14cbba06c8f3c5ad8931ef3a063783e51b017c4be0a625cf76403",
          "sha256": "2c2f994f9e0a6941f583f40e8dc3f089cd38551c8e7605d6fe000969be7f99f3",
          "sha1": "b7811d436d88e970f91279c66c58b75f5f03fed1",
          "md5": "8180438fe46efe5171ba396abb83a7b2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.1-fabric-1.2.3.jar",
          "url": "thief-26.1.1-fabric-1.2.3.jar",
          "size": 153083,
          "sha512": "52ab4cb3ee07d85e4527c617442e5ef3903c2365afe680a01b082abe057b2c2bdbbe667213bae61c4cce25df41d7529ed7e82d7f7f4370dcef222767c3d2b151",
          "sha256": "6c0c994889dc4ed9e1ce8cdea5c1f263354b00e537ad64c2485e1bb2fbf76d89",
          "sha1": "0c5af84e85ef2e1a7ec18db610dd36d33d395e03",
          "md5": "20f587ccefeb683f89793c6fdd51b5da"
        }
      ]
    }
  ]
}
