{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-26.2-neoforge",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "thief-26.2-neoforge-1.2.7.jar",
          "url": "thief-26.2-neoforge-1.2.7.jar",
          "size": 144164,
          "sha512": "68bb976fdba0bdf9cfcc2ed6dc2542a59f32e5687cdd296a0a4d1e414c69a0244b72685c180a8e6861503c258287f461f68fc567f6fcf0fb8a445923441621c4",
          "sha256": "9ff6c77f63af926a49139eb76038562c4ec63334c44b7ac5a4ab52b219d88052",
          "sha1": "ffce31c65573b43fe35101bddb3c22074594a5fa",
          "md5": "83e3ba4112d6aab51f4e7f535bbdd91a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.2-neoforge-1.2.7.jar",
          "url": "thief-26.2-neoforge-1.2.7.jar",
          "size": 144164,
          "sha512": "68bb976fdba0bdf9cfcc2ed6dc2542a59f32e5687cdd296a0a4d1e414c69a0244b72685c180a8e6861503c258287f461f68fc567f6fcf0fb8a445923441621c4",
          "sha256": "9ff6c77f63af926a49139eb76038562c4ec63334c44b7ac5a4ab52b219d88052",
          "sha1": "ffce31c65573b43fe35101bddb3c22074594a5fa",
          "md5": "83e3ba4112d6aab51f4e7f535bbdd91a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.2-neoforge-1.2.7-sources.jar",
          "url": "thief-26.2-neoforge-1.2.7-sources.jar",
          "size": 75157,
          "sha512": "29a62838bd804cf0789c114a2d6e497c2808911c62b752b6a066a2118deaf459a4390a2582d087e57b678bb759fb1e8b089042da785b60d29b731d1d7bfaaea5",
          "sha256": "b852b8cb37e7f0301bda029f038f4b4f30a326a9a5981e4e41fe4f4fd0dcdb15",
          "sha1": "f75a6bfce7ef8e0c15bc3f2228a34a4f376d3d77",
          "md5": "af6f553fa4967d39b98377eab7d1a311"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.2-neoforge-1.2.7.jar",
          "url": "thief-26.2-neoforge-1.2.7.jar",
          "size": 144164,
          "sha512": "68bb976fdba0bdf9cfcc2ed6dc2542a59f32e5687cdd296a0a4d1e414c69a0244b72685c180a8e6861503c258287f461f68fc567f6fcf0fb8a445923441621c4",
          "sha256": "9ff6c77f63af926a49139eb76038562c4ec63334c44b7ac5a4ab52b219d88052",
          "sha1": "ffce31c65573b43fe35101bddb3c22074594a5fa",
          "md5": "83e3ba4112d6aab51f4e7f535bbdd91a"
        }
      ]
    }
  ]
}
