{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.9.jar",
          "url": "exposure-1.21.1-neoforge-1.9.9.jar",
          "size": 2167113,
          "sha512": "c3ea494fef7497663257fc20762c818b6d6dd1c429ce6450964c04ee835735a1a3710a2a0ec61ade285687973ebd07e9de5a56df3f6262644cce1fda0ec414b1",
          "sha256": "9f2854cd87f8514f3f6d4868c823cb4aa3c08888be2262ec642b6fc1be38db67",
          "sha1": "8e66bf788e44aacd3b71414249c7e23cf552d1e8",
          "md5": "09259cc639d9294e9e5395cdb94ef321"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.9.jar",
          "url": "exposure-1.21.1-neoforge-1.9.9.jar",
          "size": 2167113,
          "sha512": "c3ea494fef7497663257fc20762c818b6d6dd1c429ce6450964c04ee835735a1a3710a2a0ec61ade285687973ebd07e9de5a56df3f6262644cce1fda0ec414b1",
          "sha256": "9f2854cd87f8514f3f6d4868c823cb4aa3c08888be2262ec642b6fc1be38db67",
          "sha1": "8e66bf788e44aacd3b71414249c7e23cf552d1e8",
          "md5": "09259cc639d9294e9e5395cdb94ef321"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.9-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.9-sources.jar",
          "size": 38629,
          "sha512": "8717c9d3fdad3655ad418bafaca24b505428ce1a318bd214375409a36ad85ce7b1415ce33c72bcb594258e9a29bf915c813b11be49e0aaa334d5d0b8a15ceb27",
          "sha256": "c3ee1338db11998fe6d4282e13ca56e729aa6f8a436cb12d684e175aedd10130",
          "sha1": "0d562a45b772af464a3e1358fec9059566bb5765",
          "md5": "9a4712ba31c2d00d8d2b64dc65fc2afa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.9-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.9-dev-shadow.jar",
          "size": 1949218,
          "sha512": "3f2ed1d14c0373e5e023cb50341068fde070b57fcc578ac427d14b97477be95e55902c54923ad074788d81937dfe4768b2980d2bdc849aaab5e505ba12d8f37c",
          "sha256": "8a6da63ed16ee763953a92e625d6b726dde818c657ee2445189978f9662eee69",
          "sha1": "377d8028b7e45800774b9b3f3c90edb5776273d1",
          "md5": "4e64647c0f87b64078fa9e5ae3aea5eb"
        }
      ]
    }
  ]
}
