{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.2-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.2-fabric.jar",
          "size": 475936,
          "sha512": "3bb92a121687b54fbfb69173446b5068defeb4926425c525869de12140c4c680b651ac1aa5645bc26c3fb63fe6a407bf2e6cd159e6e1e1ea17cfae7ba6017646",
          "sha256": "5697e2296ed75d5c7a03e7947cbd4ba0d718bfe7909745e7636c0ca7eeec7353",
          "sha1": "ad0090929c6f731bdc40d852f31f300f2da1a261",
          "md5": "52274f10d6648ee9dcb2bcddc8f0e727"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.25"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.2-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.2-fabric.jar",
          "size": 475936,
          "sha512": "3bb92a121687b54fbfb69173446b5068defeb4926425c525869de12140c4c680b651ac1aa5645bc26c3fb63fe6a407bf2e6cd159e6e1e1ea17cfae7ba6017646",
          "sha256": "5697e2296ed75d5c7a03e7947cbd4ba0d718bfe7909745e7636c0ca7eeec7353",
          "sha1": "ad0090929c6f731bdc40d852f31f300f2da1a261",
          "md5": "52274f10d6648ee9dcb2bcddc8f0e727"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.2-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.2-sources.jar",
          "size": 198668,
          "sha512": "507a27e497f894ef554a3f3f6bf2f1cabd2ec119b1a206f68bcf265337bc098afafc66ca37b9d51654fd925ccb72abd8413033a65a6c76c03c7f4b26297deaa4",
          "sha256": "9d2e594a9c4a1a86291a946a91c686ee3781b4c7f4a17c60fe2a36cf809b5d95",
          "sha1": "bfb956c2dddc3bb184de014dc5e60f004a589ee6",
          "md5": "ed8e495fd10078791feb5d10a361cd88"
        }
      ]
    }
  ]
}
