{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.7.jar",
          "url": "exposure-common-1.7.7.jar",
          "size": 1279315,
          "sha512": "b740a7a5cd384cc4af16ad587d1986c912208282f03ab9ac97fd1b3260ef97434a8d84330dc9bb1276a9093d55f9a6b66b81f0ac2a4a9896b42db3767b75b1cd",
          "sha256": "77e45a4cf65910502de4351327b7a3c7e2d3c58e3a7183c092c5b6cac6810921",
          "sha1": "505b86cb20fada4dbeac30f3bc953d305d355cca",
          "md5": "9a1c14c01a99ff42a00455312a378ed7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.7.jar",
          "url": "exposure-common-1.7.7.jar",
          "size": 1279315,
          "sha512": "b740a7a5cd384cc4af16ad587d1986c912208282f03ab9ac97fd1b3260ef97434a8d84330dc9bb1276a9093d55f9a6b66b81f0ac2a4a9896b42db3767b75b1cd",
          "sha256": "77e45a4cf65910502de4351327b7a3c7e2d3c58e3a7183c092c5b6cac6810921",
          "sha1": "505b86cb20fada4dbeac30f3bc953d305d355cca",
          "md5": "9a1c14c01a99ff42a00455312a378ed7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.7-sources.jar",
          "url": "exposure-common-1.7.7-sources.jar",
          "size": 922952,
          "sha512": "97741fdb77976a675e891e5870069b0fc01d1acd094165056f3543d552659f10dd4d3fa9c801b1cf15bc57cfbfd8d4e11aea39a58f9b3ba253cf9207fde0a11e",
          "sha256": "b2fdbd45a2d72f3c10b973d2aa8adf2ea9aa5f0d268354b075384f9b0339000e",
          "sha1": "e2c68ddbb8dae660d0f5d657ee63a9dbca51464d",
          "md5": "4e077610ce19167d6a661296b042ccea"
        }
      ]
    }
  ]
}
