{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-fabric",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.0.1-fabric.jar",
          "url": "exposure_catalog-fabric-1.0.1-fabric.jar",
          "size": 155298,
          "sha512": "f7a0893c3e77dcc7da0e1f7022989d3b83b3d02a22caf5c7125d6c45af86a0686a2e2bb73dd5b61d28017ec84794c1b06a97664d7894573896a94d1a7836c5bb",
          "sha256": "85ca70140628395256fa0edfdf560489b7927d1a733f40fc10369d1aad00aeb2",
          "sha1": "44235920dad473cbebcd4d07bd205bf145ee3ecc",
          "md5": "a4d836553b00777a33f9df17de6200e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-fabric",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.0.1-fabric.jar",
          "url": "exposure_catalog-fabric-1.0.1-fabric.jar",
          "size": 155298,
          "sha512": "f7a0893c3e77dcc7da0e1f7022989d3b83b3d02a22caf5c7125d6c45af86a0686a2e2bb73dd5b61d28017ec84794c1b06a97664d7894573896a94d1a7836c5bb",
          "sha256": "85ca70140628395256fa0edfdf560489b7927d1a733f40fc10369d1aad00aeb2",
          "sha1": "44235920dad473cbebcd4d07bd205bf145ee3ecc",
          "md5": "a4d836553b00777a33f9df17de6200e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.0.1-sources.jar",
          "url": "exposure_catalog-fabric-1.0.1-sources.jar",
          "size": 73180,
          "sha512": "057cb00b256726d628e451899c83866a036f14005f78b58bf1b32dabb35ed2995a86eed43832f4553530248e9e8abb7a9e75a97d62a176236450972b0f386707",
          "sha256": "148c290873d0c1cd467a2e0e1074b4275371056c9e626a8dec801fcad38b68f8",
          "sha1": "cc47b765058505231a77a3c3d7a2c5ffabbb87da",
          "md5": "87c5947508c8426c100ce94ebb5fc5e1"
        }
      ]
    }
  ]
}
