{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10.jar",
          "size": 319692,
          "sha512": "78d326c71d6d5fc47ff94879602510669c0c6a0d6b617eaa65f032f646805b31e9d8295a6aad7b747b365cd2aeab89dc8b47f749a5f94dbc6c71442a0da15fe2",
          "sha256": "70de0d9d484d110a0b00fb44f39f13118a5870a2e0a6d397bdf0136c853901bd",
          "sha1": "7e41a51010ef8743d0aca8e9ca8d67f5112ef363",
          "md5": "3516ce72d40a391f0c0da908ef2c5304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10.jar",
          "size": 319692,
          "sha512": "78d326c71d6d5fc47ff94879602510669c0c6a0d6b617eaa65f032f646805b31e9d8295a6aad7b747b365cd2aeab89dc8b47f749a5f94dbc6c71442a0da15fe2",
          "sha256": "70de0d9d484d110a0b00fb44f39f13118a5870a2e0a6d397bdf0136c853901bd",
          "sha1": "7e41a51010ef8743d0aca8e9ca8d67f5112ef363",
          "md5": "3516ce72d40a391f0c0da908ef2c5304"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10-sources.jar",
          "size": 13830,
          "sha512": "c8782a343493511beb4c35318b6641d2f75a2ae3144a7be734beceb8a2ae31ee4a7d557ef9b73cf9ec9fca0eac6af988b91517127779de2889f0c1c5a233d42e",
          "sha256": "1d13e7a6c4f406276176431e4a5785c3bc10711229f44257d907bb3c601b1400",
          "sha1": "889a88b72fa43a362da8092f4821141b8ce7e370",
          "md5": "d6d7e0cf74ea221c2f3539358e45e123"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10-dev-shadow.jar",
          "size": 134576,
          "sha512": "01c44e3ba99c35a2afe8fa23aad24e7d26030cdc20e1bdf5598b018dbe4c81c1462bf850ac5f8b6ccad66f10ece58ae3f029fc76a6c9a3824b0144af944e4eb0",
          "sha256": "b04dcc7227e7471ac7f4438c81f81481a86a1a5e13aec9b9080adfcdae45a57d",
          "sha1": "75d216da53b40d84109ecee624ebf516fb414659",
          "md5": "522478b317e38a5e5c42ba6a9e6c2854"
        }
      ]
    }
  ]
}
