{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10.jar",
          "size": 379811,
          "sha512": "732d03f0683f9d5a78818be69bf40cefa3459f0ed67a38e722ba467e1b9e5306a229504fdad4e3a7a0c5eec35a35d53a74f66dbf7e92c12e85cd5b641e8bb47d",
          "sha256": "f152fd39ac0b5de56707927cd61c363fec3c80f946cf31d962bb10ac58bd3387",
          "sha1": "e373662561871715ae2c8699d0552418983ad2cc",
          "md5": "987f03ca31aff84f548dc549fc1222c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10.jar",
          "size": 379811,
          "sha512": "732d03f0683f9d5a78818be69bf40cefa3459f0ed67a38e722ba467e1b9e5306a229504fdad4e3a7a0c5eec35a35d53a74f66dbf7e92c12e85cd5b641e8bb47d",
          "sha256": "f152fd39ac0b5de56707927cd61c363fec3c80f946cf31d962bb10ac58bd3387",
          "sha1": "e373662561871715ae2c8699d0552418983ad2cc",
          "md5": "987f03ca31aff84f548dc549fc1222c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10-sources.jar",
          "size": 14581,
          "sha512": "404337b9dcf34f81d4b773c4ee970f318160205f5c11f97900446694b7f57f2c08900007464c9cdd1abeb2a02c15440c31861f7adfa3bdb454231f02b65b7933",
          "sha256": "be77063c8d4343a87ad6691304bb0138e156eeda1f3108d385e5b31ae776199c",
          "sha1": "70a8328b36c5daa938b452e2411879b1bcccf0f3",
          "md5": "1ae1617c2064eb5e51be54e55376f931"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.10-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.10-dev-shadow.jar",
          "size": 193211,
          "sha512": "e7fecc1bcda38ca2975781d26d0edbc13f5ba0d1f8bc32eff72e149ce86f7e159d8d79e9e11ccbd8b73e3e554ec6816fd8c7f5d496b2e9ce5d43836f81fe844d",
          "sha256": "2432497919386a577e816eede8152357c50bf1498e1cefe2cba4c3de8e409e40",
          "sha1": "1fb1b16a19d32b30122fd941e85c090b9f500b61",
          "md5": "16584cffe8895aa0f4f80e7fb575a5b0"
        }
      ]
    }
  ]
}
