{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.9-fabric.jar",
          "url": "exposure-fabric-1.7.9-fabric.jar",
          "size": 1311241,
          "sha512": "302a5b229c36471d8e28317d5e5c46b9a76855db2ef0603200e3250959a6ce5cfbf4b092de8c517ab263f962228ffdee9139f68589f2897308b5a59c9db3a47f",
          "sha256": "a7246b756b72efa6683909653eaf59ab57ca88d29262cf728759f5c7ac0ed50a",
          "sha1": "98d8c58f08aba2f26a30ff665cf539ba87a967f9",
          "md5": "d23f7e90ee4ca91defb59e6efdec37f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.9-fabric.jar",
          "url": "exposure-fabric-1.7.9-fabric.jar",
          "size": 1311241,
          "sha512": "302a5b229c36471d8e28317d5e5c46b9a76855db2ef0603200e3250959a6ce5cfbf4b092de8c517ab263f962228ffdee9139f68589f2897308b5a59c9db3a47f",
          "sha256": "a7246b756b72efa6683909653eaf59ab57ca88d29262cf728759f5c7ac0ed50a",
          "sha1": "98d8c58f08aba2f26a30ff665cf539ba87a967f9",
          "md5": "d23f7e90ee4ca91defb59e6efdec37f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.9-sources.jar",
          "url": "exposure-fabric-1.7.9-sources.jar",
          "size": 955237,
          "sha512": "8755cfd5c1ff8c8ca7eafbf6c4a3972751ecfae3b24ded42192681c81a2e11f553decd06321e66e2bdf7a68f1ab1e30dc3901a82f911e8b2f765ba7732095c09",
          "sha256": "58717554b908b265d25025f73caf7d28ad46708740d9e5545381d893390ac9cc",
          "sha1": "a55a77b4ad30b66e5ba75ea344e5a122e7da08f6",
          "md5": "8c2d58679d629f95f4191f66487e4de1"
        }
      ]
    }
  ]
}
