{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.12-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.12-forge.jar",
          "size": 329053,
          "sha512": "8ad638210a79a021122356e4564117457e86027b4c0b43cb94c95cb5a150bc30b59d56c81b3136eef8675789abca1217dcfb0414db548677194b9abc55b4f4eb",
          "sha256": "a985705b78a318890c08f3a952699ed2fd1a63eda83b3f756aafcddd306a1d79",
          "sha1": "c92f2fdb2d2e0a3717d055abd928fcce9952ec5b",
          "md5": "d0a6f9a77b9882b11334b689efdb01bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.12-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.12-forge.jar",
          "size": 329053,
          "sha512": "8ad638210a79a021122356e4564117457e86027b4c0b43cb94c95cb5a150bc30b59d56c81b3136eef8675789abca1217dcfb0414db548677194b9abc55b4f4eb",
          "sha256": "a985705b78a318890c08f3a952699ed2fd1a63eda83b3f756aafcddd306a1d79",
          "sha1": "c92f2fdb2d2e0a3717d055abd928fcce9952ec5b",
          "md5": "d0a6f9a77b9882b11334b689efdb01bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.12-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.12-sources.jar",
          "size": 88842,
          "sha512": "c3208d35a28e4db2cb4eae775ebd6aa80175c1a44ef56ebc6604fdf0d6900cc409a70ff4386959312b54a97b04732bc3bc77e60fa98772d7c52532c1cce814ed",
          "sha256": "09b4d7100697436f72187fbb5de7f9abed2dae485a16ae209a58d55c27142226",
          "sha1": "b8f593feb61291752d827eaea3b2ad6a1905cded",
          "md5": "03717f4887af8aea0fa2019ae764bc86"
        }
      ]
    }
  ]
}
