{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.3.jar",
          "url": "exposure-1.21.1-neoforge-1.9.3.jar",
          "size": 2133926,
          "sha512": "0bd5d7584bcbb92d2ffad9951cd8cfc025b5658bc630f704a7223caf2b8f497af64505d57c1c48d845e986e216930bc25e47cab0f991f0193aa8d2e976f8f1de",
          "sha256": "587ce6c6cdae3e00276520344b9f3e6bc87f375fd27404379660494d35a13a81",
          "sha1": "c3ad17b8f2ed4f674129afa16175ab22bd0262b8",
          "md5": "acacc747a109524c4d467fa18a89076e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.3.jar",
          "url": "exposure-1.21.1-neoforge-1.9.3.jar",
          "size": 2133926,
          "sha512": "0bd5d7584bcbb92d2ffad9951cd8cfc025b5658bc630f704a7223caf2b8f497af64505d57c1c48d845e986e216930bc25e47cab0f991f0193aa8d2e976f8f1de",
          "sha256": "587ce6c6cdae3e00276520344b9f3e6bc87f375fd27404379660494d35a13a81",
          "sha1": "c3ad17b8f2ed4f674129afa16175ab22bd0262b8",
          "md5": "acacc747a109524c4d467fa18a89076e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.3-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.3-sources.jar",
          "size": 38941,
          "sha512": "47095c56300e50789f7f22ba903404ae41d1af904e54e9766108c88972c4b599d822480999e508f04a48774ddfb4f1c8dba5c89ac706b3a1463c9751540e282a",
          "sha256": "3dfaaceb564076081795f03a169d271ce91bf02512c723966494e577db03d2e7",
          "sha1": "3de866ea5afca8c4f6e535ab7162c7a92e7486e8",
          "md5": "0d97023ab14905735c7d960ecc453975"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.3-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.3-dev-shadow.jar",
          "size": 1916656,
          "sha512": "978b88895c7ce904693192008e279704c619f4317eed36185d61b3da4c61f03308ecae4dd2ae5634e25e76799a73ebf7a12fa7547a98fd3a3f317752026588ac",
          "sha256": "aea0a63e98cb26bcb09d1664faed409f2921fea88e2bb87b16b48742ff44929f",
          "sha1": "573784f1b4c605edd3efb8e1c4aa66f5d5a2e71c",
          "md5": "c35f5d8de6b8be2fd8c4087e5ec1a438"
        }
      ]
    }
  ]
}
