{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-fabric",
    "version": "1.9.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-fabric-1.9.17.jar",
          "url": "exposure-1.20.1-fabric-1.9.17.jar",
          "size": 1991695,
          "sha512": "324edd90ce9d402654525a7ad7a4a4cde1f53b17b1314bb6c2fbc184f4217b4548b31e9bd83ef6a35f4893bea4ac31babeae8d539d2e307e5f66b1fa377e2f68",
          "sha256": "ea6b3dbf67598dca30c26fafe0f912dffefb2306c1cf2656739427e3868ab1da",
          "sha1": "08a525a53b9e4d0ffc99ed2671edca19df0c62ff",
          "md5": "fb799f024f2c858ae9ac3cb14b0746e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "lEkperf6"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-fabric-1.9.17.jar",
          "url": "exposure-1.20.1-fabric-1.9.17.jar",
          "size": 1991695,
          "sha512": "324edd90ce9d402654525a7ad7a4a4cde1f53b17b1314bb6c2fbc184f4217b4548b31e9bd83ef6a35f4893bea4ac31babeae8d539d2e307e5f66b1fa377e2f68",
          "sha256": "ea6b3dbf67598dca30c26fafe0f912dffefb2306c1cf2656739427e3868ab1da",
          "sha1": "08a525a53b9e4d0ffc99ed2671edca19df0c62ff",
          "md5": "fb799f024f2c858ae9ac3cb14b0746e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-fabric-1.9.17-sources.jar",
          "url": "exposure-1.20.1-fabric-1.9.17-sources.jar",
          "size": 29511,
          "sha512": "2fe3d4ee8330897491d6f6f8f79cee56b3de5278bf4bf30b7ca315b51db0e7f74f7256d8dfc34f2b644ef573ca9d0cd66d5c884f5c55aa929973a878f1d8621f",
          "sha256": "16be4287d100734859f4ce8cdf5dab6b5995009094eba8c16e623da6ac05f507",
          "sha1": "47ea2bb56d81636f02817cfcb20c131a5f0a8b40",
          "md5": "9ace75b10b9b7029d6786589785d2cc1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-fabric-1.9.17-dev-shadow.jar",
          "url": "exposure-1.20.1-fabric-1.9.17-dev-shadow.jar",
          "size": 1969482,
          "sha512": "0297dc16ce2930b01c07652e2a08a5641c7718c3ffb910b2300a4d37edcb38d708a790512370236443d83b8e2fb07c1d46d0f8dfe20a6ed2096c1d9a58a20513",
          "sha256": "8549a64576f33dd943e1bea841167bb62e0b3ed432c773c6507be7a06150922e",
          "sha1": "4aea6382747f1a6633d56e54f30362ef8392ca91",
          "md5": "6a6c429cb7f63efa2b432f6215daadb8"
        }
      ]
    }
  ]
}
