{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-common",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.0.jar",
          "url": "thief-1.20.1-common-1.2.0.jar",
          "size": 133656,
          "sha512": "895273fe35be9e76dc7f203463389b3f687c4ee3f21de727567afd16b23f4203cac31415ee55d4da015ce60548428024d5f185f28cd506cd2c847137b64c17d7",
          "sha256": "64ae99b5bdf52e67aaacd12f304edf8b3b841a2dae7b41ff5f7133f0409cb38e",
          "sha1": "76db5941d3f4e99692b3fcdb98bffe84816c4b0a",
          "md5": "830358f7205509fa432bfa62ef814623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.0.jar",
          "url": "thief-1.20.1-common-1.2.0.jar",
          "size": 133656,
          "sha512": "895273fe35be9e76dc7f203463389b3f687c4ee3f21de727567afd16b23f4203cac31415ee55d4da015ce60548428024d5f185f28cd506cd2c847137b64c17d7",
          "sha256": "64ae99b5bdf52e67aaacd12f304edf8b3b841a2dae7b41ff5f7133f0409cb38e",
          "sha1": "76db5941d3f4e99692b3fcdb98bffe84816c4b0a",
          "md5": "830358f7205509fa432bfa62ef814623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.0-sources.jar",
          "url": "thief-1.20.1-common-1.2.0-sources.jar",
          "size": 74957,
          "sha512": "49c89b37de0a2438e495071b8ff1c14064f9feab982e82b307a87a17722d00520d4ceb68df6a94ff540d077e2b42cb852e688326a94a8e6bc330d055c820c4d2",
          "sha256": "8475bad7ffe5404dcf8b53a8a0ae2c6ba0db035b410239d2f1a057672d6cf079",
          "sha1": "4df1a28dff1babcbb1acc55c4dede614eb7724cb",
          "md5": "501017db06583106997f53e681ec7742"
        }
      ]
    }
  ]
}
