{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.2.jar",
          "url": "exposure-1.21.1-neoforge-1.9.2.jar",
          "size": 2115586,
          "sha512": "aeed6c9efb9146295813ac9db5e376527c5b1484776df3e618c826a5ca8a259715902e082438b9adaf5ba7ed9cc4befb6ce211c794e8c0c74af6ce333aab0bf1",
          "sha256": "aa0f782ffc65e7f2a6478502d6742d5dbbd104c834aa41d1398c71499f9a5910",
          "sha1": "d5392c07621bdc3f8a3defae3a736baa9f9a1bca",
          "md5": "93bbf1a09fe3d21fed53e355a26051ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.2.jar",
          "url": "exposure-1.21.1-neoforge-1.9.2.jar",
          "size": 2115586,
          "sha512": "aeed6c9efb9146295813ac9db5e376527c5b1484776df3e618c826a5ca8a259715902e082438b9adaf5ba7ed9cc4befb6ce211c794e8c0c74af6ce333aab0bf1",
          "sha256": "aa0f782ffc65e7f2a6478502d6742d5dbbd104c834aa41d1398c71499f9a5910",
          "sha1": "d5392c07621bdc3f8a3defae3a736baa9f9a1bca",
          "md5": "93bbf1a09fe3d21fed53e355a26051ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.2-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.2-sources.jar",
          "size": 38941,
          "sha512": "41e398d42407390299dd59299ec0d44030f98bc0aa2ef096d81ff5fb8e4a9c7395b8a029cb316477cb2df00224e9440ca74778af2e5fe62a587a825313984347",
          "sha256": "ace2aff583a9c46f76ac41e8e2987d80059d885ae9cc18b17266b185c17ef9a2",
          "sha1": "96b5b2fcd0f1dd77930f0975041b6e146950c94e",
          "md5": "93065657d4d3af39cc526861210f7c02"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.2-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.2-dev-shadow.jar",
          "size": 1898364,
          "sha512": "75b5e1facc24b65b24a7b9af3710a6022faa524d22cafebeaacb00d3e23d98c846aa6821fdd2424adc1980637499d417238d0e0d0ed5c3ce10c42a329323671c",
          "sha256": "6bd28edd97da9f3bb02269e239e28e0efaa7ceda27d70ffcf10d2b98b6fd47d7",
          "sha1": "dbfcaf3757ef53a038f33a82698d6af0c33ab366",
          "md5": "ff4633a11a76703d38253edfff63d809"
        }
      ]
    }
  ]
}
