{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.10.jar",
          "url": "exposure-1.21.1-neoforge-1.9.10.jar",
          "size": 2170201,
          "sha512": "1f24226ce4dce073335a2598d3b63bc3aec72f7d0933e4d215060c3b25eca3b240a7063ee4c623a4d6cb1d6d2cfc33560fbed3f17eb7c21c2ca0f0b07615c86b",
          "sha256": "f9808703d7b58bde6a9797fd1898fa4c19096670bd040c066379cdba195250bb",
          "sha1": "76abf0c3f41fb508932bf78042fd0dc2ce02950c",
          "md5": "fa6e54e067774e81f131a0c674d8f705"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.10.jar",
          "url": "exposure-1.21.1-neoforge-1.9.10.jar",
          "size": 2170201,
          "sha512": "1f24226ce4dce073335a2598d3b63bc3aec72f7d0933e4d215060c3b25eca3b240a7063ee4c623a4d6cb1d6d2cfc33560fbed3f17eb7c21c2ca0f0b07615c86b",
          "sha256": "f9808703d7b58bde6a9797fd1898fa4c19096670bd040c066379cdba195250bb",
          "sha1": "76abf0c3f41fb508932bf78042fd0dc2ce02950c",
          "md5": "fa6e54e067774e81f131a0c674d8f705"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.10-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.10-sources.jar",
          "size": 39287,
          "sha512": "318e7b295e4cc8af3e64f24d8c09092c21e2b4f4d6ab609a5d8c33db2dab537de6b628ba4beeaa5abfd4b760620b28e52e2aff39002728cf1a7388e997922881",
          "sha256": "c99a1dc047fa25ad82dfd8fd9405d6f3eeb5b259fb3cdc480018d18034ed3e8b",
          "sha1": "b69c56f80599d4b2f15782cfdc040639b16481dd",
          "md5": "5bed32dd7af0aabe0aa2519d6f9da30e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.10-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.10-dev-shadow.jar",
          "size": 1952232,
          "sha512": "9407ec90b7704bed382716a11a276400e4090f93f3cf48c1c25e082ef115235fb3cd777a82a7165116b105de855cca09a5e3e051609a4d54790f54919629a597",
          "sha256": "b5ee8dc26d11604ffda0503151f8574610b9aac06183e2593abc2de6e1cba425",
          "sha1": "9294d4fc1108f18a4408c2b1d320b4416bb3ca65",
          "md5": "ab22481957a1ac7b79c35ff906ac5547"
        }
      ]
    }
  ]
}
