{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.4.jar",
          "url": "horseman-1.21.1-common-1.3.4.jar",
          "size": 117035,
          "sha512": "513802000afc828a5e9440883cc30325ccb2802145748860f3a5866181913d6f737193604d5a06c9043932d6c0ee57afe74cc8278dc42a60b06404adb9f8120e",
          "sha256": "44d5858afc30de67c2cd047b89fe086ffa79a17777fbec9ce489eeee14ab0156",
          "sha1": "3b8ae22177baf01af76b95294aeeebd692200bca",
          "md5": "ef5a01a95c4b984c65ee5e4b7960ad03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.4.jar",
          "url": "horseman-1.21.1-common-1.3.4.jar",
          "size": 117035,
          "sha512": "513802000afc828a5e9440883cc30325ccb2802145748860f3a5866181913d6f737193604d5a06c9043932d6c0ee57afe74cc8278dc42a60b06404adb9f8120e",
          "sha256": "44d5858afc30de67c2cd047b89fe086ffa79a17777fbec9ce489eeee14ab0156",
          "sha1": "3b8ae22177baf01af76b95294aeeebd692200bca",
          "md5": "ef5a01a95c4b984c65ee5e4b7960ad03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.4-sources.jar",
          "url": "horseman-1.21.1-common-1.3.4-sources.jar",
          "size": 69607,
          "sha512": "312ef66eee9ffea06ae7030dcf0a1df87e708522c6f1323067fead08bf6e29082dee199305cf9cd0e6786735920dccc8cdd88fba8c2a93a52dfbd9216e0777fb",
          "sha256": "8641f6d985b4c5b804452d6214599a5865f8fbe0d1a53e87f473ea59826dfddd",
          "sha1": "50c4bcfc75286b2f0b0a31c73507f5871fd79a4a",
          "md5": "fc0422e7cef4d3b6bedd18920e7313f0"
        }
      ]
    }
  ]
}
