{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.3.jar",
          "url": "horseman-1.21.1-fabric-1.3.3.jar",
          "size": 137100,
          "sha512": "1ec829d231a75f000ccb87e6941431e8c2f7d64aee909f17a5cc9fb591147d8c0b08581ca850451e289e0334419f7b76c78af047a7125c67fe6efe69cd38c998",
          "sha256": "48b4b7c254bf50b6552721a8d6f7c98cc9b99a94a6edc39a7950bc29f5b20d5a",
          "sha1": "5ba4a7d1c4c76d58e1cab719da2547b5b679262c",
          "md5": "d9ac6868b8af48824cfdf1d5e61d4589"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.3.jar",
          "url": "horseman-1.21.1-fabric-1.3.3.jar",
          "size": 137100,
          "sha512": "1ec829d231a75f000ccb87e6941431e8c2f7d64aee909f17a5cc9fb591147d8c0b08581ca850451e289e0334419f7b76c78af047a7125c67fe6efe69cd38c998",
          "sha256": "48b4b7c254bf50b6552721a8d6f7c98cc9b99a94a6edc39a7950bc29f5b20d5a",
          "sha1": "5ba4a7d1c4c76d58e1cab719da2547b5b679262c",
          "md5": "d9ac6868b8af48824cfdf1d5e61d4589"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.3-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.3-sources.jar",
          "size": 13820,
          "sha512": "6fc97c0dabb1d0249db060aec70adf1efb7b6300902826ba850aed307bb74cdee93262d38e93adbc52e259dd0f4429384b1626d92f52ac3b94de49d160cd3e70",
          "sha256": "ec9098b360be1d97d94a9df399a53b6b2aa73b6605112828c25b48de74a39d60",
          "sha1": "1be93586248c7ad96d69abeb64392c869b1929c3",
          "md5": "50b88cb4ed29c170ab6ef9b674dd4f67"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.3-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.3-dev-shadow.jar",
          "size": 135747,
          "sha512": "cc626f3780eb0c9d09106941e76a2c4a74f72a298014fd3b9abcc6f6484e136afcd4e35ee82a5f7a37afbcbaaddd1d00139a627c325621b87d55a5a12740420f",
          "sha256": "4b1af82dc41569cc37f5c6720b28b8faad71de1803644fbc47cb26b21b03a7e4",
          "sha1": "4210df2234fbf1c5467de03f0bce60b5ba75a557",
          "md5": "7ff9b93d1a1b767aacc8d2b2999fc338"
        }
      ]
    }
  ]
}
