{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.0.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.0.1-fabric.jar",
          "size": 338292,
          "sha512": "681df7532f61cf2488e5d141574a2733859cafb1bac629661226f6fc4aafb5dfe7fdb8897b3ba694424c9c804bc4c8d3e6dad3f2edcd8a901f633f34de874c10",
          "sha256": "e0b465e19b784aa250f83ed20a87c582dae4a0da09d984f4e32a4a8032824a34",
          "sha1": "52924150bef83c9ae8824f62d8a7b9bb3c89db6e",
          "md5": "ed17cf49cb63e19d9c2e306992977c29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "probejs-585406",
          "version": {
            "requires": "5227391"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.0.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.0.1-fabric.jar",
          "size": 338292,
          "sha512": "681df7532f61cf2488e5d141574a2733859cafb1bac629661226f6fc4aafb5dfe7fdb8897b3ba694424c9c804bc4c8d3e6dad3f2edcd8a901f633f34de874c10",
          "sha256": "e0b465e19b784aa250f83ed20a87c582dae4a0da09d984f4e32a4a8032824a34",
          "sha1": "52924150bef83c9ae8824f62d8a7b9bb3c89db6e",
          "md5": "ed17cf49cb63e19d9c2e306992977c29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.0.1-sources.jar",
          "url": "thief-1.20.1-fabric-1.2.0.1-sources.jar",
          "size": 89897,
          "sha512": "1783f2f7e895cf054c0229cdba7db820289675c4217051d3066bc6e0223fbbe94a76e49dd85d5a327bc5ea0e8e6fe5e27aeb69cfc52f5e4a188250adb6d3455e",
          "sha256": "bd9ce83ccfcb4dc556cadabba5e7afdd59d6083b6686161858620bf5fa6ccc53",
          "sha1": "e1b3c9f2a143fed70e7e05798df0f0c3a51dc38b",
          "md5": "90a8cf7cb59fdf1a84167627658c8b7c"
        }
      ]
    }
  ]
}
