{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.mortaar",
    "module": "mortaar-1.21.1-fabric",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.4.jar",
          "url": "mortaar-1.21.1-fabric-1.5.4.jar",
          "size": 155032,
          "sha512": "def23d4aff201cc2d4059bfaff62e0c0287b8ab55736bd5790a5864fd50c029825fcfa036153e2192c1be7d7ace4a0512abd17547062fd11a7c992093b0644ac",
          "sha256": "99177c5fc8d14f56f593e74f54e53fd7721dd8dac0282491710b08f6d30779b8",
          "sha1": "9c619b03b124ffc688bd642845ce656e1cbafd6a",
          "md5": "8e1b1c6a14a132aab025223ab3f73f53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.4.jar",
          "url": "mortaar-1.21.1-fabric-1.5.4.jar",
          "size": 155032,
          "sha512": "def23d4aff201cc2d4059bfaff62e0c0287b8ab55736bd5790a5864fd50c029825fcfa036153e2192c1be7d7ace4a0512abd17547062fd11a7c992093b0644ac",
          "sha256": "99177c5fc8d14f56f593e74f54e53fd7721dd8dac0282491710b08f6d30779b8",
          "sha1": "9c619b03b124ffc688bd642845ce656e1cbafd6a",
          "md5": "8e1b1c6a14a132aab025223ab3f73f53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.4-sources.jar",
          "url": "mortaar-1.21.1-fabric-1.5.4-sources.jar",
          "size": 8061,
          "sha512": "44c897410b151ca31f4cac0f6e39b6187bc60ac537f77030245d5b3cdf0c2c9aea2e511fc586360cbe8c5868e56ffee640aeecdbabfb6c9449a165851ebb5a86",
          "sha256": "a5bce663080904ad517a18f385644f4f494a0d8a56be7677e7d4a1ca77d4ddf2",
          "sha1": "696997baa7648837569c2f1ac66d8a112ff5a4ba",
          "md5": "2478eaf00e7c2861f3b331f0789afa83"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.4-dev-shadow.jar",
          "url": "mortaar-1.21.1-fabric-1.5.4-dev-shadow.jar",
          "size": 152451,
          "sha512": "8ba613e57ae976bdbc0384075fc528fd19ee67d204b2651c8e28ea7ec6bb17db488444ed450b564e7fd90fd0b7f6fee9460d3c38a94df517b1e92f7642a24672",
          "sha256": "466739bbba04e1246cd369cc287d0357589cdc2af2ca083b313e23d83c197949",
          "sha1": "022069bbe6dbae92ff35e011693c5758879257ee",
          "md5": "2c9521c7c06a1953da379b91963e3cc2"
        }
      ]
    }
  ]
}
