{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-fabric",
    "version": "1.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.8.jar",
          "url": "exposure-1.21.1-fabric-1.9.8.jar",
          "size": 1956944,
          "sha512": "b806f3077c16c7d76ef6b07949b463c388b79d89229b015a68b70b437894d6dc908a610218581f06fa83c0d4541f7890c8cde239ef533fb0c826db02b940c4e5",
          "sha256": "ce119acbac06cb41d8d2d51d2a0f938978b9c9d6b396a10843a5de2ef8a2537c",
          "sha1": "11ff82fb250c8abfd70cdb50a4203af616e73ad2",
          "md5": "2c41c732bead69709157aaeb7719d2eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.8.jar",
          "url": "exposure-1.21.1-fabric-1.9.8.jar",
          "size": 1956944,
          "sha512": "b806f3077c16c7d76ef6b07949b463c388b79d89229b015a68b70b437894d6dc908a610218581f06fa83c0d4541f7890c8cde239ef533fb0c826db02b940c4e5",
          "sha256": "ce119acbac06cb41d8d2d51d2a0f938978b9c9d6b396a10843a5de2ef8a2537c",
          "sha1": "11ff82fb250c8abfd70cdb50a4203af616e73ad2",
          "md5": "2c41c732bead69709157aaeb7719d2eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.8-sources.jar",
          "url": "exposure-1.21.1-fabric-1.9.8-sources.jar",
          "size": 30905,
          "sha512": "59017a9c420d8e9a6142d1f7b8dbad332d0035a2b81d20fd79822ee83f9fbd55ce41695a4e5be7fdf351c90944d74ec0623e4afe11ea135a473cf4cb4f1c395b",
          "sha256": "b0cb9e23537521052a14a775750b8214af84357b2efc02328ff04b8160723385",
          "sha1": "24490db83d981a13987b3359404d786628a651c0",
          "md5": "59583f362534e208a6881f3cb967e7fe"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.8-dev-shadow.jar",
          "url": "exposure-1.21.1-fabric-1.9.8-dev-shadow.jar",
          "size": 1937621,
          "sha512": "c84ef96165e82ea7aea393e15c5e7185fd73b9a115908081e59b2b3c12da01180bb42eeb3abccfe6328eae247c43e6b15c8cb0191c5ef0f2ec5df0e35b81c72c",
          "sha256": "4718007f24e98ac6e38b132a66b6adcc39c06b7f7dcb497a800d14be530675ed",
          "sha1": "9cd4891f8b7edbe43686df741334ebf2afe6b49c",
          "md5": "993542381c6d493b1fada7166d523c89"
        }
      ]
    }
  ]
}
