{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-common",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-common-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.3.1.jar",
          "url": "sootychimneys-common-1.3.1.jar",
          "size": 160197,
          "sha512": "b89c06851c969bb2257dc249e2a14b5f7df874787c2df049e2b7244028ef35310ade1f063804985729a10b3c0b05bfa5f6dceac962e11c57db033f469c7252dc",
          "sha256": "656694c8d75869aa09b4c2be08b593da29bcc2b286aca95bfe095407a39a9f3e",
          "sha1": "22fa6fd0526ec44d8b64f6e68e706514167630a5",
          "md5": "411cb149eac11e6e18cca43b488b4487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.3.1.jar",
          "url": "sootychimneys-common-1.3.1.jar",
          "size": 160197,
          "sha512": "b89c06851c969bb2257dc249e2a14b5f7df874787c2df049e2b7244028ef35310ade1f063804985729a10b3c0b05bfa5f6dceac962e11c57db033f469c7252dc",
          "sha256": "656694c8d75869aa09b4c2be08b593da29bcc2b286aca95bfe095407a39a9f3e",
          "sha1": "22fa6fd0526ec44d8b64f6e68e706514167630a5",
          "md5": "411cb149eac11e6e18cca43b488b4487"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-common-1.3.1-sources.jar",
          "url": "sootychimneys-common-1.3.1-sources.jar",
          "size": 116169,
          "sha512": "0c4b722636352de9ca26733cb33a400daeebeb1251ce45e7a1fcd962341473c1b8e55dc0dbe529558e5629ed0a485f893a11a838c4dd6979ca01571640519b8a",
          "sha256": "d4b9141fafed058679b2d75eb462fd21c33e9609771ff79b3820702f7050dc8c",
          "sha1": "98772e19013afa7fc3a630cd3faf9cf9c7bebb77",
          "md5": "6bfc4a9dceb9be8ffb435330492f407c"
        }
      ]
    }
  ]
}
