{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot.jar",
          "size": 2080129,
          "sha512": "e70475fab0e1556d6e4e8154c7e3e9cfd3816eaa636d1377a1f0bc5075c230e8e6f96134b6345b0312a52976fbb9f2f1b33fee486c56aebd8049b1e64a7c52a9",
          "sha256": "8364188aa4535a1da8aeccf756c4d0c28c6388c2c7bf6e21e12cadb6cebe3f49",
          "sha1": "61bed6b6db8834c7c9f18168464e9c13e1d8d034",
          "md5": "4dfd64bf510b2cd0dfee27b76b318751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot.jar",
          "size": 2080129,
          "sha512": "e70475fab0e1556d6e4e8154c7e3e9cfd3816eaa636d1377a1f0bc5075c230e8e6f96134b6345b0312a52976fbb9f2f1b33fee486c56aebd8049b1e64a7c52a9",
          "sha256": "8364188aa4535a1da8aeccf756c4d0c28c6388c2c7bf6e21e12cadb6cebe3f49",
          "sha1": "61bed6b6db8834c7c9f18168464e9c13e1d8d034",
          "md5": "4dfd64bf510b2cd0dfee27b76b318751"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot-sources.jar",
          "size": 37636,
          "sha512": "74bdebeaee8cfff71a6e62436702f758315315f86f71be25429df75541c390a7fba8bb168365ff61c8a3715f13b05aad78321af8f948692de306c56c3d7f048e",
          "sha256": "be54cbf76afec5d144882a1c9765d08f3eab4eda03eef5328634ff6e88175ea7",
          "sha1": "87a92dab254c9fc67a132b5a333870d16c803a12",
          "md5": "b71d85a4ffc80255022fa3dbedc5143f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot-dev-shadow.jar",
          "size": 1863724,
          "sha512": "95239086d596f77db4231acc959414ec519debbf75a9c5352526b1c8e201beaf1ca9698eaee484b8e749de57396647546c6894dbf750c3946c68d88d1869590d",
          "sha256": "ee0c0181f0252157e00b48a88070173b610ce69ba151cf106ea84a03bfdfc23d",
          "sha1": "9be26302bddeafc569b076dc19115b8f65e4f9ea",
          "md5": "431ddfe1726ec5cc5a01a809a2141097"
        }
      ]
    }
  ]
}
