{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.20.jar",
          "url": "exposure-1.20.1-forge-1.9.20.jar",
          "size": 2249505,
          "sha512": "f8f761f087b8d36fd6ac8a5830c31ba01799e5784f0d6736a69c50daef6ae2cc0b99425fa64be2481907371202e541c9aaf995591466d3e5caa72ccf46dd9ebc",
          "sha256": "103b416e7f78b7b27cc5ff025db9e602ccc9caaa7fb54606f2fdb483f2277bc1",
          "sha1": "043407042adf752c896f5be123676d702a843457",
          "md5": "b4adbdc1368921a238a039d28ad83d7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.20.jar",
          "url": "exposure-1.20.1-forge-1.9.20.jar",
          "size": 2249505,
          "sha512": "f8f761f087b8d36fd6ac8a5830c31ba01799e5784f0d6736a69c50daef6ae2cc0b99425fa64be2481907371202e541c9aaf995591466d3e5caa72ccf46dd9ebc",
          "sha256": "103b416e7f78b7b27cc5ff025db9e602ccc9caaa7fb54606f2fdb483f2277bc1",
          "sha1": "043407042adf752c896f5be123676d702a843457",
          "md5": "b4adbdc1368921a238a039d28ad83d7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.20-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.20-sources.jar",
          "size": 52286,
          "sha512": "40d24c543b88915bd8ba7a4c89ccc86abe306e6bd760a4a1dc7d485c856a29e676a24a1549de19018e7d109872aad02e89237062a723fb4e7e732a4b62f67a4e",
          "sha256": "c1573f4883c33cf2e3ee24a7d1fa9f59d54a70c4174d9c0fa0605146f3700029",
          "sha1": "7002296a83ed739aae5745c7c6b9818ba5046890",
          "md5": "d638c7ee01602c5ca21c5ae40220115f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.20-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.20-dev-shadow.jar",
          "size": 2022623,
          "sha512": "c4afd7808fd17595ec3ae999ed7770192b4285f9048b692594a10853dacc62dc0f0a869acd8f3b823ba9d77bd1140a57203ce6e838b99bc0a482f53775412a7a",
          "sha256": "d54209fa2ddd306ed9c0002ad002d8f54509e419aebd981ae1806ba45e458c82",
          "sha1": "55ec478aaf8d5653d12de13dfaf493daf5a00e6c",
          "md5": "ff8dabed7d147326fe5d68da5bb390eb"
        }
      ]
    }
  ]
}
