{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.3-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.3-fabric.jar",
          "size": 338180,
          "sha512": "8b51f22f388f806490e89550fe79cd9e36fca016a41fd34ee6f4324c71fce5e56cba4979be03c9862d42cd0f958bfc0a4c1066ff562c08af15e856b4d7e4f396",
          "sha256": "7c7a658d27433eff3949f366838c99f32dbbd140def24d99e2064478c6310579",
          "sha1": "299e39cc589bad14391be9c5af53df4100949e74",
          "md5": "6507a431145dddb0b034495cfe961ccb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "probejs-585406",
          "version": {
            "requires": "5227391"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "carry-on",
          "version": {
            "requires": "Mkla4B3q"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.3-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.3-fabric.jar",
          "size": 338180,
          "sha512": "8b51f22f388f806490e89550fe79cd9e36fca016a41fd34ee6f4324c71fce5e56cba4979be03c9862d42cd0f958bfc0a4c1066ff562c08af15e856b4d7e4f396",
          "sha256": "7c7a658d27433eff3949f366838c99f32dbbd140def24d99e2064478c6310579",
          "sha1": "299e39cc589bad14391be9c5af53df4100949e74",
          "md5": "6507a431145dddb0b034495cfe961ccb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.3-sources.jar",
          "url": "thief-1.20.1-fabric-1.2.3-sources.jar",
          "size": 90134,
          "sha512": "66cfb930d01a39d283480276f9128fcd63843e61dbda1e8ee3263803335197e4cde5a2472ac83096613a2b45c4602435b7466df8fe25fabbf97d6fb2fd0820c5",
          "sha256": "1bf1f443ad65216d6b2d8d3fd8bb50f3dc5fb6c7314900f5c89be82f5e038507",
          "sha1": "fb0296a51cd25bd355bbd7a3f237357f74243d53",
          "md5": "ad843634052a2ec64d5dd82055b5e6de"
        }
      ]
    }
  ]
}
