{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-common",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.3.jar",
          "url": "thief-1.20.1-common-1.2.3.jar",
          "size": 135301,
          "sha512": "955908dbec41fd572f383eaa57af84ad13bdce8c741f0f511446a6195f24887d4df47e3d5a7669928784ddb457d6fb791cc0c23559344cecc94fd30ffb2c6d7d",
          "sha256": "1b40dc37e03dcd6cafac33c5bc62123b813026fe8dd5bd22f0c7e7ed08ebc13d",
          "sha1": "1b0ec5ab72493a0a095daa72c60402e1c2ead125",
          "md5": "94e5a26adf9d140001bc3aea9aef013e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.3.jar",
          "url": "thief-1.20.1-common-1.2.3.jar",
          "size": 135301,
          "sha512": "955908dbec41fd572f383eaa57af84ad13bdce8c741f0f511446a6195f24887d4df47e3d5a7669928784ddb457d6fb791cc0c23559344cecc94fd30ffb2c6d7d",
          "sha256": "1b40dc37e03dcd6cafac33c5bc62123b813026fe8dd5bd22f0c7e7ed08ebc13d",
          "sha1": "1b0ec5ab72493a0a095daa72c60402e1c2ead125",
          "md5": "94e5a26adf9d140001bc3aea9aef013e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-common-1.2.3-sources.jar",
          "url": "thief-1.20.1-common-1.2.3-sources.jar",
          "size": 76889,
          "sha512": "deab4d07e196b08834b652fc09b3ce3df9a5b1f58e29342daca8b6109a78fc52f9f771243dd05704ce479bdc0f2f624fefe608e014bfb3c431cb2ae1c2b4b591",
          "sha256": "52884182fdc5915084a74180eaaaacd526b7ad786e5e80cb5f39daa8538cfa12",
          "sha1": "7525a7ec8d893f6c6438f52e516886b00c6451b7",
          "md5": "f4ed24a74d542a815578f65280c81532"
        }
      ]
    }
  ]
}
