{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.14-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.14-fabric.jar",
          "size": 316185,
          "sha512": "af13d2b6581981eb4c3aedba14482230b99e1654487a5f9fec31db4d639f5f444c0b495657c6ffc71ceef8714ad50ff78d1185a097f336d839eda315a74886e6",
          "sha256": "ee424b4eb090b7a9f23b0d1121d99ea3081be8c7967abdd730e57870258afaf9",
          "sha1": "83aebb0e4648f9ea72702fb9a37ec7e07f83f64e",
          "md5": "1721fc2e1e482fd20bc67ff84ea07e7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.14-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.14-fabric.jar",
          "size": 316185,
          "sha512": "af13d2b6581981eb4c3aedba14482230b99e1654487a5f9fec31db4d639f5f444c0b495657c6ffc71ceef8714ad50ff78d1185a097f336d839eda315a74886e6",
          "sha256": "ee424b4eb090b7a9f23b0d1121d99ea3081be8c7967abdd730e57870258afaf9",
          "sha1": "83aebb0e4648f9ea72702fb9a37ec7e07f83f64e",
          "md5": "1721fc2e1e482fd20bc67ff84ea07e7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.14-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.14-sources.jar",
          "size": 82622,
          "sha512": "2fe51ba74ced917fa134747d5895df3b9d2f8fa7f1c6abb72301ac4a62a0bc84a5901c78ec52d93abf3c70acbf7971470776bcd79becf46d0658f6cc36ada472",
          "sha256": "c33c7fbf0858f26e20bc3e9ffcd0cdd9c6fbbdc274feb438562b97a10b2a35ab",
          "sha1": "543761ce61e63f3e8ee2601323be07580a3f607e",
          "md5": "49343cf0f5c5f96cec86762204c995da"
        }
      ]
    }
  ]
}
