{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.11-neoforge",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge-api",
          "version": {
            "requires": "27.4.0.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.11-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.11-neoforge-1.3.4.jar",
          "size": 179412,
          "sha512": "349bba08a2b708fba2ddf49843988c6efea2281314e4b13b43306f6bc8c178f9d348766168868d47acee770fadc05c66be2386d81eb2a88eeeca70629dd68073",
          "sha256": "1df0121285ca3eeccca5152e76cc9c04f36dec376f3377b5987166574b62794a",
          "sha1": "b932c5d48c67bc3aefcd875d562687ffd40515e3",
          "md5": "53955f43a1c6cea7188e6d7cc34fdc58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge",
          "version": {
            "requires": "27.4.0.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.11-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.11-neoforge-1.3.4.jar",
          "size": 179412,
          "sha512": "349bba08a2b708fba2ddf49843988c6efea2281314e4b13b43306f6bc8c178f9d348766168868d47acee770fadc05c66be2386d81eb2a88eeeca70629dd68073",
          "sha256": "1df0121285ca3eeccca5152e76cc9c04f36dec376f3377b5987166574b62794a",
          "sha1": "b932c5d48c67bc3aefcd875d562687ffd40515e3",
          "md5": "53955f43a1c6cea7188e6d7cc34fdc58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.11-neoforge-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.11-neoforge-1.3.4-sources.jar",
          "size": 13710,
          "sha512": "47bf112758626bef2dda0dd9ecf17097f0257627de24c51cccaa11d53ebc70f8ccebb9f6bd0fa1b4e37609f4f008a54c016fa80b9fb10653ca48146660eaa7c4",
          "sha256": "d2b6d14e115e4303841e6cc7084c3492da0e6afc3eb9e5ab2ecb373917272274",
          "sha1": "16b31b8a446aa7c4ba85e87ca2242af8d130f88c",
          "md5": "7a4aadc73810ffa317e91c24f5298259"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.11-neoforge-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.11-neoforge-1.3.4-dev-shadow.jar",
          "size": 174180,
          "sha512": "1d91066418a71558e6e08c1871874e51ff2037d29cb3c120612896a140dee3ade0e3439a7ae059eac4468a28c84fe22407c71e0376f31a2418fdf31e7561e306",
          "sha256": "96f6be16a80f9d4f129f450a554a7bd75241d931829a50db70ccbaa1adccb3c6",
          "sha1": "d34a6c5a7fab89ef3f687d3a84d396515873f5be",
          "md5": "9b082d70f55e59320ce2dbde8a33deaa"
        }
      ]
    }
  ]
}
