{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.1.jar",
          "url": "exposure-1.21.1-neoforge-1.9.1.jar",
          "size": 2113823,
          "sha512": "c81b92b60f78237cfc5c6e51df1a272a918e76bec512f852ed505d6470f59202b3e4676e42e2ef5b766eee74ce84f9a37d19f850a48e298d82f5f5a0742c6b73",
          "sha256": "6b217d3c665d4acc94bdcd147e088ea835b5a0ba95b73948e14e192a75045731",
          "sha1": "be9ca21676c120dda2b60692876141f30245c37d",
          "md5": "25fcd71150cfc8ccf7dc692d02b00db3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.1.jar",
          "url": "exposure-1.21.1-neoforge-1.9.1.jar",
          "size": 2113823,
          "sha512": "c81b92b60f78237cfc5c6e51df1a272a918e76bec512f852ed505d6470f59202b3e4676e42e2ef5b766eee74ce84f9a37d19f850a48e298d82f5f5a0742c6b73",
          "sha256": "6b217d3c665d4acc94bdcd147e088ea835b5a0ba95b73948e14e192a75045731",
          "sha1": "be9ca21676c120dda2b60692876141f30245c37d",
          "md5": "25fcd71150cfc8ccf7dc692d02b00db3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.1-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.1-sources.jar",
          "size": 37647,
          "sha512": "f866b0838072d802d24654743138d6b8437f6db9c3ee315fae307c09bad4d5c4ab826662269da20752284fb0f4865a002bae101bf246f9a1c48ee78e60b24ad9",
          "sha256": "f7ad8a81f7e7b1f7cea43efc257507502e942d3360f4b72ceb500d03353fe4d9",
          "sha1": "071d49f326e253cc587717b4c871472a4a799372",
          "md5": "c4f84e331e5cdebfdaee820202e99cda"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.1-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.1-dev-shadow.jar",
          "size": 1896665,
          "sha512": "5c88ea7a5ad7c9bef66a0e614ddb0e7e323dbb17c900ae924d9aa8372ca164fb99f125881a5110349a6ab5552e1dbe01707bc190fd25c4bb1ac19c64a0a31346",
          "sha256": "be54190b4c589f2f80979905633b968e5c26a9b3b02d3c934192e57eff1daafc",
          "sha1": "925bd23056e910468875c1d2bd6e42debb82c286",
          "md5": "0c32a43ea7d750998cea35a9b6d2d14c"
        }
      ]
    }
  ]
}
