{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.21.1-1.8.5-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-fabric-1.21.1-1.8.5-snapshot.jar",
          "size": 1873671,
          "sha512": "d0daa30893ee3f483c21e6fe54aba2d1f00c2afb575b344bc6d95611f0950812f85f0de804a6e1ec29af5a9a3ff02e8c894aa553cc3819127b60883f6b61f5fb",
          "sha256": "8ecb7dbfa6e217034335332196554ab79c6efee841d8b371ed7d7ccd8650cdd1",
          "sha1": "1a610698868474ac0fd4f5ee077fab1055f9f71f",
          "md5": "46100619acca348c0e803a02d08c1c10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-fabric-1.21.1-1.8.5-snapshot.jar",
          "size": 1873671,
          "sha512": "d0daa30893ee3f483c21e6fe54aba2d1f00c2afb575b344bc6d95611f0950812f85f0de804a6e1ec29af5a9a3ff02e8c894aa553cc3819127b60883f6b61f5fb",
          "sha256": "8ecb7dbfa6e217034335332196554ab79c6efee841d8b371ed7d7ccd8650cdd1",
          "sha1": "1a610698868474ac0fd4f5ee077fab1055f9f71f",
          "md5": "46100619acca348c0e803a02d08c1c10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.21.1-1.8.5-snapshot-sources.jar",
          "url": "exposure-fabric-1.21.1-1.8.5-snapshot-sources.jar",
          "size": 28385,
          "sha512": "63582388c7740ba11c1e1b2ed29e46530b51a448fc70e3c07c2d86f23fe6c6dd0bea5d8a0423f6a0368ff90b1dc283816414ee03778c56403b33d56d3696fea6",
          "sha256": "cd9b0822bbfb37832817267163029d071035bacc2b68d5eb825abd01a8d6f7f6",
          "sha1": "f2894fda8fde2419abec5da00fbcae63a85b8f88",
          "md5": "182d6ff1e887f305dba496bbc5d7ab5f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.21.1-1.8.5-snapshot-dev-shadow.jar",
          "url": "exposure-fabric-1.21.1-1.8.5-snapshot-dev-shadow.jar",
          "size": 1676040,
          "sha512": "88c72ed794278de6c40f9673abf785bcc7f966f2937d447691adc28c46c81e7dbfe173c2dc38cf9424ec22dd588b2f5c6dd33d367f9a16b10cc358ade229ea49",
          "sha256": "8f347b45d079162a8c7d6463424a7951c1d92164cc5bb155115afb0b04b6002d",
          "sha1": "18344c229203ce7e7c22943ea97d1ce832745a9d",
          "md5": "c5c6ce10ac20f8b74127ced89a8372b5"
        }
      ]
    }
  ]
}
