{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-26.1.1-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-common-api",
          "version": {
            "requires": "29.3.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.4.jar",
          "url": "sootychimneys-26.1.1-common-1.3.4.jar",
          "size": 160855,
          "sha512": "a9f37c750794db265e61196dd4cbfb9891d07fb5176989c0e8a6b18c4195521f75397e5c69fd477af2307d29a08d83641b6f154c37c2488273e5a2bb3bf52356",
          "sha256": "5b165e0179d85e0d3f614ee97663c1ee7b47d792c69064f88715630176bba2b1",
          "sha1": "eeae0f84791f12ab61fafa0a2af96c1b37a07304",
          "md5": "46cdc8cc9fd64cf8044ba21e2667b879"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.4.jar",
          "url": "sootychimneys-26.1.1-common-1.3.4.jar",
          "size": 160855,
          "sha512": "a9f37c750794db265e61196dd4cbfb9891d07fb5176989c0e8a6b18c4195521f75397e5c69fd477af2307d29a08d83641b6f154c37c2488273e5a2bb3bf52356",
          "sha256": "5b165e0179d85e0d3f614ee97663c1ee7b47d792c69064f88715630176bba2b1",
          "sha1": "eeae0f84791f12ab61fafa0a2af96c1b37a07304",
          "md5": "46cdc8cc9fd64cf8044ba21e2667b879"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.4-sources.jar",
          "url": "sootychimneys-26.1.1-common-1.3.4-sources.jar",
          "size": 108971,
          "sha512": "59afbb33956cf23a39c8be2172c3e9df31c0d49f5bcece6b2c545ca9139d04fcf397e538a4970d6d5fec843c38d7c19d2664a057937c73d2212e6b6764187903",
          "sha256": "f9d670150c4b00160d97bfa7c77d067cfc0bf363d324a84ec534f988b1091715",
          "sha1": "30086e419eafefc734aa10ba929d1a8342fa6eee",
          "md5": "0d4f5a421f8a4345b0ba920125de17a5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-26.1.1-common-1.3.4.jar",
          "url": "sootychimneys-26.1.1-common-1.3.4.jar",
          "size": 160855,
          "sha512": "a9f37c750794db265e61196dd4cbfb9891d07fb5176989c0e8a6b18c4195521f75397e5c69fd477af2307d29a08d83641b6f154c37c2488273e5a2bb3bf52356",
          "sha256": "5b165e0179d85e0d3f614ee97663c1ee7b47d792c69064f88715630176bba2b1",
          "sha1": "eeae0f84791f12ab61fafa0a2af96c1b37a07304",
          "md5": "46cdc8cc9fd64cf8044ba21e2667b879"
        }
      ]
    }
  ]
}
