{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot8.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot8.jar",
          "size": 2090814,
          "sha512": "bc3688e909b7c6fb13452831ece85f229a2b301e260aec8f9de212efcbaceec04ed6efd940d4d0f929da148aeab0e87182c2b85d12df410d41dfb0adf33414a1",
          "sha256": "758525f56c89caebfeb1d68170f785026a3c146be794dd9be8f2e8aa658c2ed6",
          "sha1": "a4a48cc6919487490bbad116fb8f095ee917d197",
          "md5": "47a75ebdc81afab64b452afe0c98c696"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot8.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot8.jar",
          "size": 2090814,
          "sha512": "bc3688e909b7c6fb13452831ece85f229a2b301e260aec8f9de212efcbaceec04ed6efd940d4d0f929da148aeab0e87182c2b85d12df410d41dfb0adf33414a1",
          "sha256": "758525f56c89caebfeb1d68170f785026a3c146be794dd9be8f2e8aa658c2ed6",
          "sha1": "a4a48cc6919487490bbad116fb8f095ee917d197",
          "md5": "47a75ebdc81afab64b452afe0c98c696"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot8-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot8-sources.jar",
          "size": 37636,
          "sha512": "c9ba6aabe37c64d88fa786d3eb7bbb96895275151c31afd6a954de0dc73e88d95baa2e7560cf590eb99e1a81a0a1a5ce7afac651d325da8bad5a0db1139345ec",
          "sha256": "70e9c60a22c6daf2d8fa2df1a281d832884f9a189ed37557b2f3ba832710306f",
          "sha1": "f271fc66df6224f2d2cd5311052a13f9b2cd7ea6",
          "md5": "d8f2e94d8c57042a668d993cef2a8e30"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot8-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot8-dev-shadow.jar",
          "size": 1874158,
          "sha512": "07c393f7640788a9e6b883852c72cfd682f7113654381dee91c93652172b725daf73a8e091902367f9207f72a90eb2af1f561d0c9b340858b8091dbb4081cd6a",
          "sha256": "4f0ae7f2a7c5154c89daa220883ae0ecebc10bd171b00a4b2e9f10ebd3eab2de",
          "sha1": "f8833b0261219489872f23820a186783b0259901",
          "md5": "71ccb08184d3d6c59567e03a042bc63f"
        }
      ]
    }
  ]
}
