{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-forge",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-forge-1.2.1-forge.jar",
          "url": "thief-1.20.1-forge-1.2.1-forge.jar",
          "size": 339279,
          "sha512": "20b944282fdcef43469ae91918bcc2bb37d28ef8732a3b3d90eacea61f8e6bd9cf95ec9572596408e56d72d9dbc81a184a4741fb211e166325defdb7605e44bf",
          "sha256": "0dbeb222aaabbb487ec7d26da0dbc66a53a43ff49fdc81a997fe50ff264e3742",
          "sha1": "c39cf19318f96859394cc4659e86ebbd90e51635",
          "md5": "74039ada97c659bb35ed0751f3d50549"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "probejs-585406",
          "version": {
            "requires": "5227399"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-forge-1.2.1-forge.jar",
          "url": "thief-1.20.1-forge-1.2.1-forge.jar",
          "size": 339279,
          "sha512": "20b944282fdcef43469ae91918bcc2bb37d28ef8732a3b3d90eacea61f8e6bd9cf95ec9572596408e56d72d9dbc81a184a4741fb211e166325defdb7605e44bf",
          "sha256": "0dbeb222aaabbb487ec7d26da0dbc66a53a43ff49fdc81a997fe50ff264e3742",
          "sha1": "c39cf19318f96859394cc4659e86ebbd90e51635",
          "md5": "74039ada97c659bb35ed0751f3d50549"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-forge-1.2.1-sources.jar",
          "url": "thief-1.20.1-forge-1.2.1-sources.jar",
          "size": 89666,
          "sha512": "2b09e5f7b7aa5132ec21deff5530c2ae2140296427b9ce9c90e3897f6e89755cf8209832192c6d00e030df2467e7ba9573043f42e78e845b2fc4e9fca658ba64",
          "sha256": "41848ba79ec6126fb0bd39e11894870cbb4110aa70dc737e77fe79c58a992a99",
          "sha1": "cee361c381fec65ab5240ed8824d338e821790fd",
          "md5": "d0af98c52d9d920dc2cb6639f6e6ed1d"
        }
      ]
    }
  ]
}
