{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.1-common",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.6.jar",
          "url": "scholar-1.21.1-common-1.1.6.jar",
          "size": 532446,
          "sha512": "465b89a083c38a5b82e2280f40ae84f737e71249b0d75ab5a60c62a57c7a302a480701d0e4277d90731bafd5a5d7c209b5ecb0cff396052f46c1ecdb91fdac37",
          "sha256": "cfde24ecc45157562968c2857c916ddbc6812fa627d0a8f08aa0b3fb8b3d5982",
          "sha1": "b98ebb577c4617449a259130c685ff42d30139c8",
          "md5": "b263713e8d77ff75a966b0b17a777e2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.6.jar",
          "url": "scholar-1.21.1-common-1.1.6.jar",
          "size": 532446,
          "sha512": "465b89a083c38a5b82e2280f40ae84f737e71249b0d75ab5a60c62a57c7a302a480701d0e4277d90731bafd5a5d7c209b5ecb0cff396052f46c1ecdb91fdac37",
          "sha256": "cfde24ecc45157562968c2857c916ddbc6812fa627d0a8f08aa0b3fb8b3d5982",
          "sha1": "b98ebb577c4617449a259130c685ff42d30139c8",
          "md5": "b263713e8d77ff75a966b0b17a777e2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-common-1.1.6-sources.jar",
          "url": "scholar-1.21.1-common-1.1.6-sources.jar",
          "size": 451235,
          "sha512": "290088aea6d848ee500090d3dbb8cfc6a455a1b4ac87160a208ae5362ff393343fb4482073c7ca7a5131d72f46dcb525d96a9d3c25b6c34a518cac93433e5188",
          "sha256": "a65fec6b7fab6265b34a658068c2f89762c1e6c0e5c1c42238225c65c4a2edc6",
          "sha1": "8afdcdc89c39fab8a241c24730e2959a4908c45d",
          "md5": "bf00f54c63151b718517d78e733076ba"
        }
      ]
    }
  ]
}
