{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.1-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.2.1-fabric.jar",
          "size": 834039,
          "sha512": "63ea7afda223e9de8410180e2e2a370c49036c969cbdd689b534737c01b1854e2fa37e14397c6144058bc82227e29e2a8ea2d9ee18d466b560466e1db0ea7d76",
          "sha256": "0fb50d405a85c85b84073fcc47b98e95dc0b552d1b60047581260da8f0d459f8",
          "sha1": "15f8c2dd5795aa64ea9356237f6458349e01fadf",
          "md5": "f63f1849e4ebc8482e08626da78743b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.1-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.2.1-fabric.jar",
          "size": 834039,
          "sha512": "63ea7afda223e9de8410180e2e2a370c49036c969cbdd689b534737c01b1854e2fa37e14397c6144058bc82227e29e2a8ea2d9ee18d466b560466e1db0ea7d76",
          "sha256": "0fb50d405a85c85b84073fcc47b98e95dc0b552d1b60047581260da8f0d459f8",
          "sha1": "15f8c2dd5795aa64ea9356237f6458349e01fadf",
          "md5": "f63f1849e4ebc8482e08626da78743b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.1-sources.jar",
          "url": "scholar-1.20.1-fabric-1.2.1-sources.jar",
          "size": 516956,
          "sha512": "8d7294c730c9ab986dd55df447cc0bcffd7eb92f0f71d9b8139ea46b28f9cef7c8062126494d7193b7475eea70e44ac060193113270ef940de4ed54cc2e21018",
          "sha256": "ea528e0899a0cafaaad6829666c75fa398c2c538f5455048260257ad13dea225",
          "sha1": "d6af5582322d63a00db9c8160db9ef01da929c7b",
          "md5": "955b8c72ce9b8b97b1e940027c94734f"
        }
      ]
    }
  ]
}
