{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot1.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot1.jar",
          "size": 2080712,
          "sha512": "36c9e3f919355961a128fea028db8add8d09f06be6198b3e5f317e43d8cd09d63b424c473c55dc6be2d8ef08becc8f98e4d4f94cdecbc86bfbdbbcdbebf4826a",
          "sha256": "0774b7b94bffb7abebc5fa9df49a7890ed165ecca72fc8fd3370137fe500c176",
          "sha1": "14ccc3b4403bcec83248ad836dac3119cfd657d4",
          "md5": "1cfc330f26d980a1dd7c9a914f5182b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot1.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot1.jar",
          "size": 2080712,
          "sha512": "36c9e3f919355961a128fea028db8add8d09f06be6198b3e5f317e43d8cd09d63b424c473c55dc6be2d8ef08becc8f98e4d4f94cdecbc86bfbdbbcdbebf4826a",
          "sha256": "0774b7b94bffb7abebc5fa9df49a7890ed165ecca72fc8fd3370137fe500c176",
          "sha1": "14ccc3b4403bcec83248ad836dac3119cfd657d4",
          "md5": "1cfc330f26d980a1dd7c9a914f5182b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot1-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot1-sources.jar",
          "size": 37636,
          "sha512": "66390d701ef75423b625eaec740018c4fecf5d7106fdb55f8eda0ce279760b354fc4514e6388338f0d413dd5c2b211b12cdf57ee22b41b120d7dcb8b8dace526",
          "sha256": "5d8380ebf1a88d2956ebc5c1576c09b463a51f8bdb4ec6c2c1ac1cdf66e95970",
          "sha1": "24f83ac22d603443247f9dafc99166ac2f0df81c",
          "md5": "92c91f608ad7130b95136163b8c8e95a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot1-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot1-dev-shadow.jar",
          "size": 1864297,
          "sha512": "bc0bc4c8ee106a1d54f48013f465b4a2ffb03bf1f89a6ea3e93c445c6caf7eda85db39db8ff542af5f5998c52f993371ad22e7c4b19213f7f1c2bad2934bcd00",
          "sha256": "6ee5162193fe326949cc348114cbdd55639a5701551f811a13d31d97e1f9ec8a",
          "sha1": "6618068852396b6fc90ff7c73eeb69662fc4e491",
          "md5": "dbee93fe43c85941ebc778aac98119fe"
        }
      ]
    }
  ]
}
