{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.15.jar",
          "url": "exposure-1.21.1-neoforge-1.9.15.jar",
          "size": 2189870,
          "sha512": "7c288fac0084086356d6db51b5aa9836f3b701d476af11a6cc5cc3f128ff5425916ef140b54b07976f0039ad07412442faf27ecb8c7bdf9cdf889dbcee1ea617",
          "sha256": "f6bfa2eee3c3d5e3beac3e607cf143d3063d69c65b6d8cffccc259c7400720fc",
          "sha1": "0d04c6df8cb1780512f19fe5ac8c250150f3d8a2",
          "md5": "c5213b2c702266e1c99a52656597ee6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.8-168"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.64"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.15.jar",
          "url": "exposure-1.21.1-neoforge-1.9.15.jar",
          "size": 2189870,
          "sha512": "7c288fac0084086356d6db51b5aa9836f3b701d476af11a6cc5cc3f128ff5425916ef140b54b07976f0039ad07412442faf27ecb8c7bdf9cdf889dbcee1ea617",
          "sha256": "f6bfa2eee3c3d5e3beac3e607cf143d3063d69c65b6d8cffccc259c7400720fc",
          "sha1": "0d04c6df8cb1780512f19fe5ac8c250150f3d8a2",
          "md5": "c5213b2c702266e1c99a52656597ee6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.15-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.15-sources.jar",
          "size": 39302,
          "sha512": "736997c5d5eea7e35230ec32ea44f37ffa75ab1ced5d42a3cd5f22ecaa885aa24327b13d8ffe3eaa5125d7a8a5e71c9e08820f56b9d780b4441ccbcb689d4898",
          "sha256": "eb873c1ae9982ddba1e29e28b4d77b54d678dfe63d269d519470fafdf4fe0605",
          "sha1": "5b54071fdbd109735d338001ad4220aa59488e75",
          "md5": "220e6e0e67d1cf701648234688d56906"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.15-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.15-dev-shadow.jar",
          "size": 1971748,
          "sha512": "efe316cb25712c142247ea3839f4cda847dcd8c326f6ef0efc5242ec326ad1416cbf5f8c6e335026e7a1948105c81cb37f5ad99f90a4f6df0740de31f22debac",
          "sha256": "28c35a3834e9c6581d6db52a8e8fc506424d0ea1ae306d3c3c6eccbdc391728a",
          "sha1": "73a1ae0cd9db1d27e64e447631b1bbfe2bc2ec40",
          "md5": "acda8a73369ceafd44e9dff991cf3bcf"
        }
      ]
    }
  ]
}
