{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.10-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.10-fabric.jar",
          "size": 316329,
          "sha512": "50cedf390da4d2473455d5fff8a9e4d28edb5a0a705e9cd9d1bf37ca5ae333ba81787df89509c3773e0c8921496ba697dbf0fcf813758e3b29854bc592d2ddd0",
          "sha256": "6d43be7e916cde2e94f4bdb5edddd76573b889856b488adb1cec718895758166",
          "sha1": "2dd7b282fc8904c4c1091fb7253affc45f88ee42",
          "md5": "5ce08114ef1144788845d5af5ab33b9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.10-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.10-fabric.jar",
          "size": 316329,
          "sha512": "50cedf390da4d2473455d5fff8a9e4d28edb5a0a705e9cd9d1bf37ca5ae333ba81787df89509c3773e0c8921496ba697dbf0fcf813758e3b29854bc592d2ddd0",
          "sha256": "6d43be7e916cde2e94f4bdb5edddd76573b889856b488adb1cec718895758166",
          "sha1": "2dd7b282fc8904c4c1091fb7253affc45f88ee42",
          "md5": "5ce08114ef1144788845d5af5ab33b9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.10-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.10-sources.jar",
          "size": 82689,
          "sha512": "3eccf55170c4141fc672306ebe045e6affd5e29309a33be4d142bdce39fcf9be13426981ed0c3bfcf85227fd6fcb05879c967622d2fa11676ad2807a5389bdd9",
          "sha256": "216de1f1d26a1d71fada844b49d3b71661c359c78d08852b34f95fb75dac1529",
          "sha1": "3f689f0b1c2fe2b9055bb64ba1621bab9b468039",
          "md5": "583cb9f62e758d197d554273dbd8d022"
        }
      ]
    }
  ]
}
