{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.21.1-1.8.5-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-common-1.21.1-1.8.5-snapshot.jar",
          "size": 1689127,
          "sha512": "e987622812d14f0dac8a9ff66659886eca201516c7a6b8f0ff16bc0827c842050d993e80f584f2a8966aa2a7e8e7b1e91cf047766a90cbfbb3d92feba18e9325",
          "sha256": "421b92de58008d8fa6fc24201f934b571a4d1525b86347763bd46ec3af62dc32",
          "sha1": "8e16edfbac704834a69605096f3936a80fb21ca4",
          "md5": "fa8d477dc9fa0e7201336eca77771b08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-common-1.21.1-1.8.5-snapshot.jar",
          "size": 1689127,
          "sha512": "e987622812d14f0dac8a9ff66659886eca201516c7a6b8f0ff16bc0827c842050d993e80f584f2a8966aa2a7e8e7b1e91cf047766a90cbfbb3d92feba18e9325",
          "sha256": "421b92de58008d8fa6fc24201f934b571a4d1525b86347763bd46ec3af62dc32",
          "sha1": "8e16edfbac704834a69605096f3936a80fb21ca4",
          "md5": "fa8d477dc9fa0e7201336eca77771b08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.21.1-1.8.5-snapshot-sources.jar",
          "url": "exposure-common-1.21.1-1.8.5-snapshot-sources.jar",
          "size": 1144603,
          "sha512": "42238ec12752755ecbc36854ea25beb30f16ea7d52855da7b7e2f658b5a31ef855d2f10824f9d267f24d2a36ce29e7556830974f8d578cde9c818ad9528f4169",
          "sha256": "db1ab142dffa0047cce04c6593f6a1bbad4c238b5cc964e61d6f915d31c3727c",
          "sha1": "afe8002f62b032eb759f579721c9de64356ddaab",
          "md5": "6a87aa7ad8b34b46f299820e27e919fc"
        }
      ]
    }
  ]
}
