{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot7.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot7.jar",
          "size": 2089839,
          "sha512": "9cbfa2067a2d9666269d6fd029dadc739e43d0e1ff36f149f70d9492347f96ae85c795c10dbe5c75edca0d1e7225692749e9f6bbdd96dc741858eb5d5c9d73e2",
          "sha256": "3bef05a8189aeca9795380ac5d6260de934d7c297a4543cb8b93e8733161dd9c",
          "sha1": "834f28116182cb7961a14617ed85fd0e9d5de91e",
          "md5": "69d5b00c597895821f5146d8574f236b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot7.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot7.jar",
          "size": 2089839,
          "sha512": "9cbfa2067a2d9666269d6fd029dadc739e43d0e1ff36f149f70d9492347f96ae85c795c10dbe5c75edca0d1e7225692749e9f6bbdd96dc741858eb5d5c9d73e2",
          "sha256": "3bef05a8189aeca9795380ac5d6260de934d7c297a4543cb8b93e8733161dd9c",
          "sha1": "834f28116182cb7961a14617ed85fd0e9d5de91e",
          "md5": "69d5b00c597895821f5146d8574f236b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot7-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot7-sources.jar",
          "size": 37636,
          "sha512": "1c075df80f8538e6f78ea71d5ef4019faa36adb80387a47a4511ddc75aceb4829fc9d1809c68c226e6b5ccde3b1ac016294cc15969bddcb271b9815f41dfd6b2",
          "sha256": "21e6ffbf3a7b3d6f55a265c18d60431b7120aac346790078e6eb1e575f4dc262",
          "sha1": "8847528298a4381c531b8740565b73535f432317",
          "md5": "fe23959fb052c626b055b774fe5c7d4e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot7-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot7-dev-shadow.jar",
          "size": 1873204,
          "sha512": "0cf7c1aa8b781ae85226941b30270210149fe3b24220d8cb1d24a8bf2f236500e07456320658b843cd8bbc1813bd0b61f823a606d8cd137452d4f265bd92af19",
          "sha256": "12ab36f561b17881903133639f096c25c4d688c09ae11ae76902afe040cd5c8c",
          "sha1": "4572a972f8f09106f9515a9a9513dec46f2b1b29",
          "md5": "44992feab01412015ba07c62edcbe33c"
        }
      ]
    }
  ]
}
