{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.monobank",
    "module": "monobank-1.21.1-fabric",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "monobank-1.21.1-fabric-1.2.0.jar",
          "url": "monobank-1.21.1-fabric-1.2.0.jar",
          "size": 418113,
          "sha512": "87568736aa44631d9e3c423f8ef357a87a1f74455062ac1e79944b6afb895abb92c9e0f6b0d6e01fc4e07220de2b78b80ea25e7316eae7fb341b020a0c34bd10",
          "sha256": "23d7ecc65b9f5fa59b667308c94a22cfc01eab8ef335cb1f38147572e619032f",
          "sha1": "e63665784adcfafde8430355182db264ebcc857c",
          "md5": "1d2ba6f4525a3995eb518bb951154fe0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.github.mortuusars.thief",
          "module": "thief-1.21.1-fabric",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        }
      ],
      "files": [
        {
          "name": "monobank-1.21.1-fabric-1.2.0.jar",
          "url": "monobank-1.21.1-fabric-1.2.0.jar",
          "size": 418113,
          "sha512": "87568736aa44631d9e3c423f8ef357a87a1f74455062ac1e79944b6afb895abb92c9e0f6b0d6e01fc4e07220de2b78b80ea25e7316eae7fb341b020a0c34bd10",
          "sha256": "23d7ecc65b9f5fa59b667308c94a22cfc01eab8ef335cb1f38147572e619032f",
          "sha1": "e63665784adcfafde8430355182db264ebcc857c",
          "md5": "1d2ba6f4525a3995eb518bb951154fe0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "monobank-1.21.1-fabric-1.2.0-sources.jar",
          "url": "monobank-1.21.1-fabric-1.2.0-sources.jar",
          "size": 15477,
          "sha512": "d04105b3479addde3e1710251f234d3d5d287dfbe8e469b9b80ec8d581efd0c755754d342e9e0fd6ac376003b87e42cd327bf2864f5671b1cb2d9f2c505d4aa4",
          "sha256": "7c91bfb0904aa0de44d58cf8a411e29fe52fa19616f8698fab7e7ae95eaba07f",
          "sha1": "a2870bb30aa60a1933624a5e643440b6d51dc2de",
          "md5": "ba84851461665f9c6b2838c3aff4916c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "monobank-1.21.1-fabric-1.2.0-dev-shadow.jar",
          "url": "monobank-1.21.1-fabric-1.2.0-dev-shadow.jar",
          "size": 415308,
          "sha512": "aa1265a73266b5b9d1875515dde411c3e8c26796eb68d7c2f18328bb0ab81ee9d06bfe44d9a00df2acb74e80daa6e3b0a339ebd72b75f727400dc10db339ef2f",
          "sha256": "6bfee8a8dcbdf247c0e741e7c1c21f3f38f4c24ea8f34e346be33eb32c0f1b3a",
          "sha1": "604db4cb29ed32f80a57c1aeb296488ea74e85e2",
          "md5": "100b1759db9e52fb1f262502cf20f3af"
        }
      ]
    }
  ]
}
