{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.17.jar",
          "url": "horseman-1.20.1-common-1.3.17.jar",
          "size": 116541,
          "sha512": "4082402424d3f6513e782d6754039ca84a9889b61830ac86afc235a548fb7994f1bd0d6ce1db1f2b28a811c73094f86f682dc1720150981755f361ad3e2838e8",
          "sha256": "fb2700b28323f35bac681cac8b2833ef267c0471c354e5d91b0e59faeb771f55",
          "sha1": "d4a7f9f77d805a3ba24355a40f5e1245f9b171fe",
          "md5": "470bae5e448540bb4a1dabc32227c7dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.17.jar",
          "url": "horseman-1.20.1-common-1.3.17.jar",
          "size": 116541,
          "sha512": "4082402424d3f6513e782d6754039ca84a9889b61830ac86afc235a548fb7994f1bd0d6ce1db1f2b28a811c73094f86f682dc1720150981755f361ad3e2838e8",
          "sha256": "fb2700b28323f35bac681cac8b2833ef267c0471c354e5d91b0e59faeb771f55",
          "sha1": "d4a7f9f77d805a3ba24355a40f5e1245f9b171fe",
          "md5": "470bae5e448540bb4a1dabc32227c7dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.17-sources.jar",
          "url": "horseman-1.20.1-common-1.3.17-sources.jar",
          "size": 70680,
          "sha512": "96f11e058f3f0509ce25a998721d8c59f92fdc623c2e670d54f0fcca0a31b661c0f2d1c0e7087dfc7d8c8125942c89171082f51f34e7358bd3408aded57f15be",
          "sha256": "49c63f9293449631bcc295d778a1be13b93bc71f4eaa284c44ceb96f768eab02",
          "sha1": "658fef256a398900074e50616b3d0b4b9680a120",
          "md5": "f1383b3f603a07b28b1f8403eb59e460"
        }
      ]
    }
  ]
}
