{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0.jar",
          "url": "horseman-1.21.1-fabric-1.3.0.jar",
          "size": 135916,
          "sha512": "eb6af93443e774a593d58583ee1a9ac4a5a27bcac8e06dbc2f8be561648af0e418e39a97da3c4fe6aacb957e615df2f090f52b4e226399a75e1f8aa242763ed9",
          "sha256": "b5e03563d1e35d6e7075fedff0e66f0924dbc6fd1fdd74bc01e2213947712f60",
          "sha1": "4f7b8200e87c2696c711947ac10d7a6c05fe3a8c",
          "md5": "c4c9525080e5340dcfb251de681ac432"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.9-neoforge"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0.jar",
          "url": "horseman-1.21.1-fabric-1.3.0.jar",
          "size": 135916,
          "sha512": "eb6af93443e774a593d58583ee1a9ac4a5a27bcac8e06dbc2f8be561648af0e418e39a97da3c4fe6aacb957e615df2f090f52b4e226399a75e1f8aa242763ed9",
          "sha256": "b5e03563d1e35d6e7075fedff0e66f0924dbc6fd1fdd74bc01e2213947712f60",
          "sha1": "4f7b8200e87c2696c711947ac10d7a6c05fe3a8c",
          "md5": "c4c9525080e5340dcfb251de681ac432"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.0-sources.jar",
          "size": 13681,
          "sha512": "57bfbb936a71f16a6fa3b29b2abcc9048cfa7a0df8eb0e8db1479254a940d34a37618ff71b588256c607743aa845f195e57e49d1255ef8d0ff2cd3f9a2188529",
          "sha256": "63480857dc6409098e25f005afb4bdd641d540421cbe42b3bed39c11f7a2cb14",
          "sha1": "70bb24f30b9f11a7fdbd766711c63a43062ecd72",
          "md5": "c58ab091725ac4668120b4cd4cedc5ef"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.0-dev-shadow.jar",
          "size": 134453,
          "sha512": "189387907864109de32e206e1ca37c1fd9ae691dc29bb6801b8f5311b3f77ee9f4a29f406ccbe7a28ba5f98ec9d6c07e430a52999a423171b1167d4a2f8558d2",
          "sha256": "f978916e57d92330809af1f0e4d5311a42502958343c2f2043646b5445e66ba3",
          "sha1": "1ade1577ec7a7627f59baf16a933f376d065c9b2",
          "md5": "9d4db1b5049f1416e9da44205fe65d47"
        }
      ]
    }
  ]
}
