{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0.jar",
          "url": "horseman-1.21.1-fabric-1.3.0.jar",
          "size": 135916,
          "sha512": "eb6af93443e774a593d58583ee1a9ac4a5a27bcac8e06dbc2f8be561648af0e418e39a97da3c4fe6aacb957e615df2f090f52b4e226399a75e1f8aa242763ed9",
          "sha256": "b5e03563d1e35d6e7075fedff0e66f0924dbc6fd1fdd74bc01e2213947712f60",
          "sha1": "4f7b8200e87c2696c711947ac10d7a6c05fe3a8c",
          "md5": "c4c9525080e5340dcfb251de681ac432"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.9-neoforge"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0.jar",
          "url": "horseman-1.21.1-fabric-1.3.0.jar",
          "size": 135916,
          "sha512": "eb6af93443e774a593d58583ee1a9ac4a5a27bcac8e06dbc2f8be561648af0e418e39a97da3c4fe6aacb957e615df2f090f52b4e226399a75e1f8aa242763ed9",
          "sha256": "b5e03563d1e35d6e7075fedff0e66f0924dbc6fd1fdd74bc01e2213947712f60",
          "sha1": "4f7b8200e87c2696c711947ac10d7a6c05fe3a8c",
          "md5": "c4c9525080e5340dcfb251de681ac432"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.0-sources.jar",
          "size": 13681,
          "sha512": "d6c622794fe6f2bb03749cd61d8194d691a157fcc67f597fb8f2b1bf41ad54fdbc2af27773a26e75e5ccf5dd1f01431d8636c2f1ba8f43775bfd4049b78e07e7",
          "sha256": "060122672b0d76524e2c2834214c557e98ed22a5499868703a166ae35a3ca535",
          "sha1": "305c72fba92d6688333965e2bbba30dc32759f6b",
          "md5": "9f464bdd3d67f3713af02be1d82a501f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.0-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.0-dev-shadow.jar",
          "size": 134453,
          "sha512": "9df67291ad49bec802264e307929bbbb38970cd4eef9ccb63d5ccb548e94b35de0f2fa598b6c614a6b09b3637492c0d1a444b475c3b4631283593ea69a170338",
          "sha256": "4b206b7d633ccdcf8a87cd4f38eec5872c9cb58e737714ffc07d85cec0162e0b",
          "sha1": "915556f553a4c80083a8ffffbb4312b4ef8aa1f7",
          "md5": "7ae11da3419df9bf2c54f2e3c9d2238b"
        }
      ]
    }
  ]
}
