{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.1-fabric.jar",
          "size": 338301,
          "sha512": "7d63f2fef1267066b2aed3ed3f78e117c13e02c3a71b4a55397cd9284bcb5c5c1a842dd2d31953b74ab0b7a2ba7ff1abbec7cc5a6eabaca51848295cb6cd3038",
          "sha256": "756ecef54afbb8a2449f12cb2343a689f5bd7945efe2a963debf4e6c7d5a6449",
          "sha1": "150907d950a33415450ec99f2eacaaba26e7530c",
          "md5": "e5f4935de6fd13aca3c042d7f5baa888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "probejs-585406",
          "version": {
            "requires": "5227391"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.1-fabric.jar",
          "size": 338301,
          "sha512": "7d63f2fef1267066b2aed3ed3f78e117c13e02c3a71b4a55397cd9284bcb5c5c1a842dd2d31953b74ab0b7a2ba7ff1abbec7cc5a6eabaca51848295cb6cd3038",
          "sha256": "756ecef54afbb8a2449f12cb2343a689f5bd7945efe2a963debf4e6c7d5a6449",
          "sha1": "150907d950a33415450ec99f2eacaaba26e7530c",
          "md5": "e5f4935de6fd13aca3c042d7f5baa888"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.1-sources.jar",
          "url": "thief-1.20.1-fabric-1.2.1-sources.jar",
          "size": 89911,
          "sha512": "616572e8a1c2a105833a1dccbf9bdfeba465d58a8fb242be00b7707ebe9a7bc3af9361c29425494852785a8cf6a2c19e766c3929ac249a46b733ba8cd3dda809",
          "sha256": "8ae2fce79011faed7401aa637d71b115c5e30eeb3ac0cd0a1a0ad6b6da413db2",
          "sha1": "d82616b038ebf151c6a1a923764585760f970588",
          "md5": "68397b66d7f2a29d1f5d78e820bed6fd"
        }
      ]
    }
  ]
}
