{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.21.jar",
          "url": "exposure-1.20.1-forge-1.9.21.jar",
          "size": 2249297,
          "sha512": "66cac5264409cf35edc67c1f06bb0876bae664801fa1bfbcc52a17bbe4541a8f8dba27874ef2f7043b7a456e628c20a7b1c1effa54da1ce238b5530c785c0c7f",
          "sha256": "f8a3c47ee0b234e5e09d1c7eaebe7c9aeace19f278b47f5dc3e49ed0d40fb616",
          "sha1": "39bd780eec2f22b3f9c9324b5e1c1b0c206e64a6",
          "md5": "b9884ff1d80aaaa3d51cb8cdd8c00cd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.21.jar",
          "url": "exposure-1.20.1-forge-1.9.21.jar",
          "size": 2249297,
          "sha512": "66cac5264409cf35edc67c1f06bb0876bae664801fa1bfbcc52a17bbe4541a8f8dba27874ef2f7043b7a456e628c20a7b1c1effa54da1ce238b5530c785c0c7f",
          "sha256": "f8a3c47ee0b234e5e09d1c7eaebe7c9aeace19f278b47f5dc3e49ed0d40fb616",
          "sha1": "39bd780eec2f22b3f9c9324b5e1c1b0c206e64a6",
          "md5": "b9884ff1d80aaaa3d51cb8cdd8c00cd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.21-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.21-sources.jar",
          "size": 52256,
          "sha512": "96eeb6ae25a1c640456476de0a50013e2a12342cbdf0c8ecc7b926f1149ea3e1ae2c6f03338d0b822f7a769f287c221cc2c98eb0686e4f19670dc6fef415f9c7",
          "sha256": "9ef1678c48ca9e389e8ca27518363d2af3eb233febd9c49d7ba057dc6edd16f4",
          "sha1": "9b3e07c3d8bfb141264be6693fdf496e91b28a2e",
          "md5": "2e725cd8014fc66a9d42f4e3668ebc2a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.21-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.21-dev-shadow.jar",
          "size": 2022403,
          "sha512": "7a0d43c2ac2f3f09de9ac161747e949da6aa16c5a38bf8346d1040121f682c3c1d35a944d737fb0812af566d8a682f6f68d90c5a1cd20955f5bdac056676c348",
          "sha256": "87350104b5a0ee0acb6a65db036d306ad206332491bd0a649a1b905f05cf64a9",
          "sha1": "d587690505240ecfe742f30decdadce35eccce48",
          "md5": "c00508c4c25b97e96ef692829366c638"
        }
      ]
    }
  ]
}
