{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.0.2.jar",
          "url": "horseman-common-1.0.2.jar",
          "size": 62735,
          "sha512": "22ebc1ccaa84760908ac9f821af758e4c3d9cd9064e757c0b2c6f60a4b39c8d91510363472ee08b747ec19f32ccd28ac6a891131ab5ecfd3f848411aa878358d",
          "sha256": "57c024a3f3337f1fa88da8e7e23e8d168081fb9bc90ef058f686fb0f110f5ace",
          "sha1": "54ec0947535da5f8ab5ed12a098689463475e213",
          "md5": "fa5a951872d03dea1fa3a30e58d4e716"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.0.2.jar",
          "url": "horseman-common-1.0.2.jar",
          "size": 62735,
          "sha512": "22ebc1ccaa84760908ac9f821af758e4c3d9cd9064e757c0b2c6f60a4b39c8d91510363472ee08b747ec19f32ccd28ac6a891131ab5ecfd3f848411aa878358d",
          "sha256": "57c024a3f3337f1fa88da8e7e23e8d168081fb9bc90ef058f686fb0f110f5ace",
          "sha1": "54ec0947535da5f8ab5ed12a098689463475e213",
          "md5": "fa5a951872d03dea1fa3a30e58d4e716"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.0.2-sources.jar",
          "url": "horseman-common-1.0.2-sources.jar",
          "size": 34094,
          "sha512": "c3dfcce3b3658e56337199c706d5d314c0e51971f1aaeae0b20d0190292b138e6f4eeed6de35764a8f4a5644a35a0a470c0a0aafe1c6799fb83b01460ec9dca7",
          "sha256": "34c7daf22131e6ae57ae8ae0540c56ae4332bd11c84d5f436f0a20a13740079f",
          "sha1": "4b967867ca7933e6f129cfe490672b6e8bc345dd",
          "md5": "d1fa09e06702449bcd0e82300d7d049b"
        }
      ]
    }
  ]
}
