{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-neoforge",
    "version": "1.21.1-1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.1.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.1.jar",
          "size": 149303,
          "sha512": "8b847928e3234829895e45b0f8454de9f3f98dd0dfec15287b06bd7e38ff2874cc20051d95c21a8e08ebaeb3b4640bb2437f07241eea5546187b05c2a8344545",
          "sha256": "5a3b74deb591f2592bb6ef4e650c55935729ef37e9e4af937395096096229939",
          "sha1": "78b947bbfbdde621dd82941b58cf13d31987e543",
          "md5": "47ffe091dbbf858db07aaeb39dae68b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-neoforge",
          "version": {
            "requires": "1.21.1-1.8.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.1.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.1.jar",
          "size": 149303,
          "sha512": "8b847928e3234829895e45b0f8454de9f3f98dd0dfec15287b06bd7e38ff2874cc20051d95c21a8e08ebaeb3b4640bb2437f07241eea5546187b05c2a8344545",
          "sha256": "5a3b74deb591f2592bb6ef4e650c55935729ef37e9e4af937395096096229939",
          "sha1": "78b947bbfbdde621dd82941b58cf13d31987e543",
          "md5": "47ffe091dbbf858db07aaeb39dae68b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.1-sources.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.1-sources.jar",
          "size": 11311,
          "sha512": "06c73e65f77516f61bad37fa30946685f6c605df88ebe6702dff448ec45565e202bf2998316c24e55049d7f12244f61fb93c7d646aee5be4d03cc61883aebdb0",
          "sha256": "710da32e4660463ba47f6bf752e402cd6336a1ffef20c222d3a55edb3c15edc0",
          "sha1": "43c5887804a77b9f1083978678935fe783d8189c",
          "md5": "de7860a77fa1aa87b2a025f0f6fdd6de"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.1-dev-shadow.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.1-dev-shadow.jar",
          "size": 145445,
          "sha512": "d68092e9a96297e1e87307d6a3556cdbe3cc62cf6a06a1bacff11318ff954723d106af5119243715bd5c6c33c47212db063229e61d66a7c106b13c4ec7616da5",
          "sha256": "4c5a7e545472c6987a529a005029bfad1c2356eb908ad59ca77755e13027d467",
          "sha1": "e003d55ea82128a9146859ab34699d82fa467ffb",
          "md5": "5d14fb12b3b5b684641ce4df35b2266a"
        }
      ]
    }
  ]
}
