{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.62.0.219"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.6.jar",
          "url": "scholar-1.20.1-common-1.2.6.jar",
          "size": 650293,
          "sha512": "8f8984bad742ed337e711ba5f5d6214cde8c85ee3efe8b27322ebc61f8328a3d65809faa2b5aaa4ad35e771605a8f2493d180cf0d359057638435ed02142be82",
          "sha256": "860524cc193fc28c5a67bbf13575248214715c92da5d5a961b98717ade980fce",
          "sha1": "3820f9566f9820de246dac150fb81f5d1104b175",
          "md5": "31a39cfd4e433bb2ce74688309d160e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.6.jar",
          "url": "scholar-1.20.1-common-1.2.6.jar",
          "size": 650293,
          "sha512": "8f8984bad742ed337e711ba5f5d6214cde8c85ee3efe8b27322ebc61f8328a3d65809faa2b5aaa4ad35e771605a8f2493d180cf0d359057638435ed02142be82",
          "sha256": "860524cc193fc28c5a67bbf13575248214715c92da5d5a961b98717ade980fce",
          "sha1": "3820f9566f9820de246dac150fb81f5d1104b175",
          "md5": "31a39cfd4e433bb2ce74688309d160e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.6-sources.jar",
          "url": "scholar-1.20.1-common-1.2.6-sources.jar",
          "size": 508540,
          "sha512": "006a7d751748db57d51b671f24f122f1ad5b191660ea9bcde58a5da6043069e36b962531b05bc8ada4f76f0886040d75c8a450a5b21187487d0e81a32f9648c4",
          "sha256": "898b72a42ed331199024a5260ad6b23fd3b60e8bdfcf384af0bb12c1002a888d",
          "sha1": "f75883b1f685644fded3fb6c4d8ccd39c5ddc93e",
          "md5": "3e14f9119cf031f820d1293a6807e30a"
        }
      ]
    }
  ]
}
