{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.1-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.1-forge.jar",
          "size": 332957,
          "sha512": "9fe0043fb5b54aa9475919cf9ad62fa02e13a8b615c6294df5474c6a83f0186d8b323e4df5a567c1ddffe5ee3ec9ae50be460888fdc195a8e497b071fccfd5ac",
          "sha256": "1a31144770447c786be84cba965e67e7620f6ecbc380608d3db123404654bf09",
          "sha1": "f14097860d6975e4dc0a6223de34b10ed4f7e26e",
          "md5": "1441530ae9a6aee9b12c251054f91584"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.1-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.1-forge.jar",
          "size": 332957,
          "sha512": "9fe0043fb5b54aa9475919cf9ad62fa02e13a8b615c6294df5474c6a83f0186d8b323e4df5a567c1ddffe5ee3ec9ae50be460888fdc195a8e497b071fccfd5ac",
          "sha256": "1a31144770447c786be84cba965e67e7620f6ecbc380608d3db123404654bf09",
          "sha1": "f14097860d6975e4dc0a6223de34b10ed4f7e26e",
          "md5": "1441530ae9a6aee9b12c251054f91584"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.1-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.1-sources.jar",
          "size": 89177,
          "sha512": "71aa353112ce90f8e6f23427055e2a47ca592254c028569c7ebda78146184aad9a03d82e83b85537e7c5fb3b6a7372ae54db9d44adfaad4d606f5c303de44139",
          "sha256": "aae1e233480f40b3b77edb82d49276872aabb7eb355402f56e595c8a8d2497e6",
          "sha1": "0b71a0117a5b450f5a01342ad201dbb07aa19cc5",
          "md5": "431455b672bb2d23504b59b5f142ada8"
        }
      ]
    }
  ]
}
