{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.0.0.jar",
          "url": "horseman-common-1.0.0.jar",
          "size": 71188,
          "sha512": "5745385edec4b9a257e3d9d553c76ceaec16df91892982964a8e47fc9916f952a3b2ac2dd53648f6e6546a1ef910e4d5a9ddc19d0bfc34097ba1713877c448ab",
          "sha256": "b5ec98eafb435bfcb111796c64ebd38c79060b6de3f94edcbba4b4e823f03c03",
          "sha1": "c681d3d382b6eb71543dc76dafc9fb094f876073",
          "md5": "24efbf889f23e7b3d231f0b63a1e985e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.0.0.jar",
          "url": "horseman-common-1.0.0.jar",
          "size": 71188,
          "sha512": "5745385edec4b9a257e3d9d553c76ceaec16df91892982964a8e47fc9916f952a3b2ac2dd53648f6e6546a1ef910e4d5a9ddc19d0bfc34097ba1713877c448ab",
          "sha256": "b5ec98eafb435bfcb111796c64ebd38c79060b6de3f94edcbba4b4e823f03c03",
          "sha1": "c681d3d382b6eb71543dc76dafc9fb094f876073",
          "md5": "24efbf889f23e7b3d231f0b63a1e985e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.0.0-sources.jar",
          "url": "horseman-common-1.0.0-sources.jar",
          "size": 40784,
          "sha512": "f365ea1eda797fa94f830736b70ed65ba41f966dac149625928851cae4361adfb515bf72f943258316aa2e80fd6e4afd0b15c0a8bbd2197c471fbad6f76b7846",
          "sha256": "d1983d843bb015066282cd5c0be8f0462fb88621a76fda231f255ff600f7c0af",
          "sha1": "5fdfa42084389288a3aa596a6381a8779e034949",
          "md5": "d9827e2e57618f81735fe7747ff9a291"
        }
      ]
    }
  ]
}
