{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.6.jar",
          "url": "exposure-neoforge-1.21.1-1.8.6.jar",
          "size": 1925378,
          "sha512": "c03b57b373824f3c80799a5d36e5720f91cf388ff58526e5c548ef494712d0b6ff4c1fbde5d784cb44c1bc2e03f8eeec0ed30a41e5e7f163f3cbe42e6babb82c",
          "sha256": "1ebd4b5863d0d62189314487b6b36d3390956aae32a69c03f073980c23f276c4",
          "sha1": "cb33d3b9aa4a6fcf83f02e572d3ebbb455c11ca9",
          "md5": "f3bfd9c75fbb101870ff6e74ba9944ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.0-4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.0-9"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.6.jar",
          "url": "exposure-neoforge-1.21.1-1.8.6.jar",
          "size": 1925378,
          "sha512": "c03b57b373824f3c80799a5d36e5720f91cf388ff58526e5c548ef494712d0b6ff4c1fbde5d784cb44c1bc2e03f8eeec0ed30a41e5e7f163f3cbe42e6babb82c",
          "sha256": "1ebd4b5863d0d62189314487b6b36d3390956aae32a69c03f073980c23f276c4",
          "sha1": "cb33d3b9aa4a6fcf83f02e572d3ebbb455c11ca9",
          "md5": "f3bfd9c75fbb101870ff6e74ba9944ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.6-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.6-sources.jar",
          "size": 36049,
          "sha512": "22ea928475c7416c5efaebacc537cc1dd8c33edc38fc2a544c89b50f854670b7d7ef31bc0a9a0b8cd60a44c79ed5e7d25e194ab464c77484822cc503b18d82a3",
          "sha256": "7f115fb4096d103103a711fc8fe5acb3ef31f7421cb9640a05d713d856252d05",
          "sha1": "52c08636481745806e7e8535720d8248fce488cb",
          "md5": "06ad05323ad98059e79c4050169f48be"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.6-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.6-dev-shadow.jar",
          "size": 1711897,
          "sha512": "34a8e7479c565651a380ad991ef8473bf2dee74e57cf3586f5e9d2081caa196805e37e29480152dd868eb968e8d5a32299478d0152ea8166f298b45c5741b53c",
          "sha256": "87e0b208c14030e9054cf78d479e29224b0ffab807bbb00ba14e7e875be8679e",
          "sha1": "fb1f141dcbdf273a85630cd695fed699463fa5ca",
          "md5": "ed4e8c995c2680778810e3449f1b5108"
        }
      ]
    }
  ]
}
