{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.8.jar",
          "url": "exposure-1.21.1-neoforge-1.9.8.jar",
          "size": 2167556,
          "sha512": "e5128c7b8997c4cb8b75244d48f4d0aedf8c933c9044375cf3edb3993a8db6f4ce05a0c0ff1d526c22ec3fc96de7d5ee005e8c8cade067ab3a563199d9236d36",
          "sha256": "d0c9af55183fc15e66b9a872e4c9a2840233b19186dc77d3dc9da162f10aa8c0",
          "sha1": "0728b6351ab3305ae8d3d8340dd07b438d92f24a",
          "md5": "33874027054c775cad46100a93fc4d5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.8.jar",
          "url": "exposure-1.21.1-neoforge-1.9.8.jar",
          "size": 2167556,
          "sha512": "e5128c7b8997c4cb8b75244d48f4d0aedf8c933c9044375cf3edb3993a8db6f4ce05a0c0ff1d526c22ec3fc96de7d5ee005e8c8cade067ab3a563199d9236d36",
          "sha256": "d0c9af55183fc15e66b9a872e4c9a2840233b19186dc77d3dc9da162f10aa8c0",
          "sha1": "0728b6351ab3305ae8d3d8340dd07b438d92f24a",
          "md5": "33874027054c775cad46100a93fc4d5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.8-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.8-sources.jar",
          "size": 38891,
          "sha512": "76c1eb8c756bf07d8292c4e6eb9d723e0b244fc1e0ed73c374a8ac4d53ee1bac65b5b6381e8b05b7ebf5752539d9781f66b305088674b674a5c9f8825e1b508d",
          "sha256": "61821f18a01a3d23a877942910f73518740b3083dceab627106f8fd53c138069",
          "sha1": "0bd26c2eacbd4171cfa23c26b8fa4cf5f8fee171",
          "md5": "836d8ec0de6758bedac8d4c849749cbd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.8-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.8-dev-shadow.jar",
          "size": 1949638,
          "sha512": "b53595281e356289ab31697884aa68cdba1a3cfe1b5a0dbe01cd608f30a8de6695c50a96b2467804f09bd3a21e1d4f1dff80586f04ab5eaf8abca293ec503825",
          "sha256": "56217f3cf97870bbc5842bdecba1247ff59fcffa3be82b74205a82965804a1d3",
          "sha1": "76a3953de49a3d3f7ff20d1e77505f726437ccaa",
          "md5": "295a5c788ad7be8955857ac359d5b91c"
        }
      ]
    }
  ]
}
