{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.3-fabric.jar",
          "url": "horseman-fabric-1.1.3-fabric.jar",
          "size": 260928,
          "sha512": "72a466c70d35625b0f8ce51839b1d78a7192dad17dbf7c2026d11dc93eea8a87d70a7f00ba9230838622394a0d54d8017eda016c7871a5c6a270efe58446a4ff",
          "sha256": "c834b45c1df8e4d98832f3866656661d03e5bc6a20e310f951be0c923313f73e",
          "sha1": "0056bc92e07ab69d74370c52006cd50ce7273173",
          "md5": "0a07007faf844b6ff062f866b4fb4583"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.3-fabric.jar",
          "url": "horseman-fabric-1.1.3-fabric.jar",
          "size": 260928,
          "sha512": "72a466c70d35625b0f8ce51839b1d78a7192dad17dbf7c2026d11dc93eea8a87d70a7f00ba9230838622394a0d54d8017eda016c7871a5c6a270efe58446a4ff",
          "sha256": "c834b45c1df8e4d98832f3866656661d03e5bc6a20e310f951be0c923313f73e",
          "sha1": "0056bc92e07ab69d74370c52006cd50ce7273173",
          "md5": "0a07007faf844b6ff062f866b4fb4583"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.1.3-sources.jar",
          "url": "horseman-fabric-1.1.3-sources.jar",
          "size": 44127,
          "sha512": "c29d2709bc7e33b269f266f592028d99853ca36562347f91a628f733fd3e02f2865e5e03a1a80e85291485cfeca98e4e608fc4247f74949a400eb3aa68c6b9cc",
          "sha256": "f99926742ba78508400a6c7fe4249e2daf765431997356d7178e76c645cc12a7",
          "sha1": "52c3acdf07a2086f256c79033b247457998c48fa",
          "md5": "001bc54eb7260e2737818e10eb0fe9fd"
        }
      ]
    }
  ]
}
