{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.envelope",
    "module": "envelope-1.21.1-neoforge",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.2-build.353"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.2.jar",
          "url": "envelope-1.21.1-neoforge-0.6.2.jar",
          "size": 1639440,
          "sha512": "c6c076e40ec421eb276b3ef6529d73482dfa2b59fe22871f47acc534ed9c2179b6c0f03d611ab2893701ded271334b61daa83a70c7ecdf57b03efe87e2380ed9",
          "sha256": "5ed3f0797c2c752739071c52bd77e8f7ff18a11224d9679176ab25387ab9d7b9",
          "sha1": "4a651cb23ae3200760d3f2da442749834537a112",
          "md5": "4a1ffddc356fce26668a2e68590ed440"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "foundry.veil",
          "module": "veil-neoforge-1.21.1",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.25.0.322"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "15.10.2+neoforge"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "tschipp.carryon",
          "module": "carryon-neoforge-1.21.1",
          "version": {
            "requires": "2.2.3.3"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.10-280"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.82+mc1.21.1"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "dev.ryanhcode.sable",
          "module": "sable-neoforge-1.21.1",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "dev.simulated_team.simulated",
          "module": "simulated-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.eriksonn.aeronautics",
          "module": "aeronautics-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.ryanhcode.offroad",
          "module": "offroad-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.2.jar",
          "url": "envelope-1.21.1-neoforge-0.6.2.jar",
          "size": 1639440,
          "sha512": "c6c076e40ec421eb276b3ef6529d73482dfa2b59fe22871f47acc534ed9c2179b6c0f03d611ab2893701ded271334b61daa83a70c7ecdf57b03efe87e2380ed9",
          "sha256": "5ed3f0797c2c752739071c52bd77e8f7ff18a11224d9679176ab25387ab9d7b9",
          "sha1": "4a651cb23ae3200760d3f2da442749834537a112",
          "md5": "4a1ffddc356fce26668a2e68590ed440"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.2-sources.jar",
          "url": "envelope-1.21.1-neoforge-0.6.2-sources.jar",
          "size": 33020,
          "sha512": "b3ae90db977e744ba6d9b787b30f969179da662f2460d93a5706812b1e25fa14c083f20ef41e7df160b461ac6afd80d1d4142d9c48fa86304b0451509b2b4c6c",
          "sha256": "c324db37d3823b23f988f08f84d5e45b18d46b3922764d4b76dc2e9248e6a280",
          "sha1": "5657c0a14d2e6538dfd0ff24b1383f738ae2c517",
          "md5": "494ac09fbfc13c5a6692119bd1e1d903"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.6.2-dev-shadow.jar",
          "url": "envelope-1.21.1-neoforge-0.6.2-dev-shadow.jar",
          "size": 1396197,
          "sha512": "8ec9722614b9116513311aaf35274d6c96eb76de5ce2f6a7b2f0c7ce703daacd4e5a0f8789fbc374f25ef7353fbd28f05dce0fa4df42c587b89d941d92bd944f",
          "sha256": "ccbe259367bc51fc7f1c63722ec218dbabada868a52bf1ad3ff78bb13c84a292",
          "sha1": "7596798959f7579a3772f0d27bac69d2ff7e6c25",
          "md5": "f15eadc61459aedec966a7107331466a"
        }
      ]
    }
  ]
}
