{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.envelope",
    "module": "envelope-1.21.1-neoforge",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.5.0.jar",
          "url": "envelope-1.21.1-neoforge-0.5.0.jar",
          "size": 1398018,
          "sha512": "71f5d5c7cb195c63c02c6df06821271c9fbac395b6a6945987d7d20f6df6b2664c1456b70d7901122bb546154e6b1cb9a27d4386ca49787dbf455ad62447e4bc",
          "sha256": "4b25986141a61b9ebaaed57e17178772826f708fbc5b92c639980ac5cbe142da",
          "sha1": "5b1630251e48ef7f7da6437a9b0be9599c2e6c47",
          "md5": "a43c0660bfaffe3454aea3b7d5061d3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "15.10.2+neoforge"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        },
        {
          "group": "tschipp.carryon",
          "module": "carryon-neoforge-1.21.1",
          "version": {
            "requires": "2.2.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.5.0.jar",
          "url": "envelope-1.21.1-neoforge-0.5.0.jar",
          "size": 1398018,
          "sha512": "71f5d5c7cb195c63c02c6df06821271c9fbac395b6a6945987d7d20f6df6b2664c1456b70d7901122bb546154e6b1cb9a27d4386ca49787dbf455ad62447e4bc",
          "sha256": "4b25986141a61b9ebaaed57e17178772826f708fbc5b92c639980ac5cbe142da",
          "sha1": "5b1630251e48ef7f7da6437a9b0be9599c2e6c47",
          "md5": "a43c0660bfaffe3454aea3b7d5061d3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.5.0-sources.jar",
          "url": "envelope-1.21.1-neoforge-0.5.0-sources.jar",
          "size": 25638,
          "sha512": "6962628775139fe78080646deefdd2faac2f49eea2fcb7edbae652d6ceb70d80770eb01983da597f083da05e0043865039420d3b633b68e5163cec8525a4a0a0",
          "sha256": "695e48f1cf76a6d2d6592c7d34cdb63a6a3d75ecdbba684ad2cb66df025f43d5",
          "sha1": "d71a9216006bcd722872cc544da910e8c0d2fcbe",
          "md5": "0f1ee46888003f63af722ce9b57d07e2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.5.0-dev-shadow.jar",
          "url": "envelope-1.21.1-neoforge-0.5.0-dev-shadow.jar",
          "size": 1192084,
          "sha512": "85bfde995ac11117e3c9140c359c846a091b1aa31a71fbeb436e49505cfa54bb072d258dcbd26e2c7604279eb92d93d8a9395af7497965498b79460937904a4e",
          "sha256": "5434f5a42d0bf52920fcbcac0361a6ce93468903d21268208ab3267c72069df8",
          "sha1": "2d25b784a52fb5bc75c594f49cd717a53b9d6ac8",
          "md5": "3747c6320cecdc19a5674a984c6b8def"
        }
      ]
    }
  ]
}
