{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.8.jar",
          "url": "horseman-1.20.1-common-1.3.8.jar",
          "size": 113545,
          "sha512": "eb4575caded186166b4fc570ecab6850f36d5b95b6d75624a7b225e347e2aee3345950a1b6271e3f2283d1e1cbbadb13d46e529b4b578d485d21ec38abade9f8",
          "sha256": "de6cfafad0ed34333d65b9b09326b2d860535055f17abfbdce86fc0036d7b266",
          "sha1": "5a4a8ef288f92f6595b6c542f8e4ca5a18e0539c",
          "md5": "4c60702361bfe942116f4112e5f6f7dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.8.jar",
          "url": "horseman-1.20.1-common-1.3.8.jar",
          "size": 113545,
          "sha512": "eb4575caded186166b4fc570ecab6850f36d5b95b6d75624a7b225e347e2aee3345950a1b6271e3f2283d1e1cbbadb13d46e529b4b578d485d21ec38abade9f8",
          "sha256": "de6cfafad0ed34333d65b9b09326b2d860535055f17abfbdce86fc0036d7b266",
          "sha1": "5a4a8ef288f92f6595b6c542f8e4ca5a18e0539c",
          "md5": "4c60702361bfe942116f4112e5f6f7dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.8-sources.jar",
          "url": "horseman-1.20.1-common-1.3.8-sources.jar",
          "size": 68120,
          "sha512": "51f02d2506cb892b352516dfa519594fdd9450422593fb536d53cea7da0163d9ae2073424781bf6b31ae91e98d51456f9f73b967b6fc05f3e458984c23e6e672",
          "sha256": "64750a19db432b1a50ac036ddc08521262465b79a64898acacb28f4c38fda77c",
          "sha1": "a5c844ea4046ec00731f3317c0c6489a74ed1d0e",
          "md5": "da2b1ad5ec8cc16468e5b7cead9ec175"
        }
      ]
    }
  ]
}
