{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.8.jar",
          "url": "horseman-1.20.1-common-1.3.8.jar",
          "size": 115187,
          "sha512": "733f1bc2a57107eda393c76be503997bfca400ac51d95a5a138af8cf44bd99dc817a4ad4ef8815d07b299e1516aafa739e2acf438da332c8471a9c34a431a26e",
          "sha256": "603f658654d9f68e7b86a67e012168af1101ad51338ed74f6145d3fea1e12b0e",
          "sha1": "432afafcc0e20ac35451904a557676f6cbd5f2f6",
          "md5": "d7cc0daa4089262d97dc25fa39e67529"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.8.jar",
          "url": "horseman-1.20.1-common-1.3.8.jar",
          "size": 115187,
          "sha512": "733f1bc2a57107eda393c76be503997bfca400ac51d95a5a138af8cf44bd99dc817a4ad4ef8815d07b299e1516aafa739e2acf438da332c8471a9c34a431a26e",
          "sha256": "603f658654d9f68e7b86a67e012168af1101ad51338ed74f6145d3fea1e12b0e",
          "sha1": "432afafcc0e20ac35451904a557676f6cbd5f2f6",
          "md5": "d7cc0daa4089262d97dc25fa39e67529"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.8-sources.jar",
          "url": "horseman-1.20.1-common-1.3.8-sources.jar",
          "size": 69721,
          "sha512": "6079c8d7792c4ea67155d9ea90e10a83c47d2278a11a592a82a6cae9a29ccb0f28083ba636f772ca9138016123ef8067f25ab83b8f9c29b6c22112efb7c332cd",
          "sha256": "74d94d1dcfee2c93a47c31ec840e4cc352b0ed0a38bff3672deffe844b547b65",
          "sha1": "5d19b7403206937c99d1ca3262688dc9e5899d8c",
          "md5": "b23a854827b7bca6a80299ffc4c3d2dd"
        }
      ]
    }
  ]
}
