{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.9.1-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.9.1-fabric.jar",
          "size": 681255,
          "sha512": "97535e4fc9e1f2e41f2c435a34508b267cf7af483414b04348aeafcecaac2afec07bbb0bda6284581c01eb171baa37e0d10b859a23acefec795accb0ba9fc1af",
          "sha256": "41e6b9701aca8155c3cd3cd0fd2000d299b14378564eff011e9c38eb6c0cd000",
          "sha1": "c6eb2c47813221e07e669a5171f04aad680b253e",
          "md5": "0487365e3e056610bf14420cc3187c91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.9.1-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.9.1-fabric.jar",
          "size": 681255,
          "sha512": "97535e4fc9e1f2e41f2c435a34508b267cf7af483414b04348aeafcecaac2afec07bbb0bda6284581c01eb171baa37e0d10b859a23acefec795accb0ba9fc1af",
          "sha256": "41e6b9701aca8155c3cd3cd0fd2000d299b14378564eff011e9c38eb6c0cd000",
          "sha1": "c6eb2c47813221e07e669a5171f04aad680b253e",
          "md5": "0487365e3e056610bf14420cc3187c91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.9.1-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.9.1-sources.jar",
          "size": 408155,
          "sha512": "d9c3d39fef46c3aea6fe2bc7629803661878eb17cf5c85b81da36bc5fdb0ca2f771e1c0a9b8990a5ec029ed709c65154cad8977883729c260688df44b7ff9b16",
          "sha256": "37062830fbe60d3083ba4d3a16cd6093f4ee507a2015c695faf40bebda725aa2",
          "sha1": "cc7df4269da135d46093b2cf8c4cac21781a312d",
          "md5": "e77c5da10ce83fd8870f890ab316a77b"
        }
      ]
    }
  ]
}
