{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.5.jar",
          "url": "exposure-common-1.7.5.jar",
          "size": 1266040,
          "sha512": "54dc7e0337717c98485d3789c8e4cd9df216423adf4d7eeaca400bc76656019af3e4d05f4e2654703328f67822519b40a604760cd6ba7afa33f9e7e1d435097e",
          "sha256": "75f35af8ee06676a2fbe097b47992c028d17bb2df55479730fab1010b1849c44",
          "sha1": "cb4fe6ef7fb276dfd2d9bb94fae099abc7848f39",
          "md5": "2f5762911df58fe132f75b990ad523bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.5.jar",
          "url": "exposure-common-1.7.5.jar",
          "size": 1266040,
          "sha512": "54dc7e0337717c98485d3789c8e4cd9df216423adf4d7eeaca400bc76656019af3e4d05f4e2654703328f67822519b40a604760cd6ba7afa33f9e7e1d435097e",
          "sha256": "75f35af8ee06676a2fbe097b47992c028d17bb2df55479730fab1010b1849c44",
          "sha1": "cb4fe6ef7fb276dfd2d9bb94fae099abc7848f39",
          "md5": "2f5762911df58fe132f75b990ad523bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.5-sources.jar",
          "url": "exposure-common-1.7.5-sources.jar",
          "size": 910949,
          "sha512": "d37abf157184ac2f72279e84af1ca63462b9a8f4acfa75ea1c5b0049c6630f045954fd5fc8ae26c1dd4d0c1ba72c918418c2d77ac089cdd847dad30e347ce5ff",
          "sha256": "7356db09795f89513326938aa0c9d7d6d1557493da9d9989f1b813603eef86d0",
          "sha1": "9e5468c3b0dcb72694f2dafb45a32981f5d7b93b",
          "md5": "d413b7725897388254de07a19122a8b0"
        }
      ]
    }
  ]
}
