{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.0.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.0.1-fabric.jar",
          "size": 309415,
          "sha512": "4063df8f49eb8a0cc898507fffd4e949e5456ced1266316a88edb0802bdc48cc40338b511cd17df2899ded1f34c7861c7f87dd2ff5491fe6cbfd670da7e7f4eb",
          "sha256": "1adcb071db9ea906a5fee2898e10f28fa77cc05d364b0aecea46f232bc5bb0be",
          "sha1": "bd238eced9473da77bb13b5e45ee10a60194f2e3",
          "md5": "e9632aae72477c94ddafce8ca74f62e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.0.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.0.1-fabric.jar",
          "size": 309415,
          "sha512": "4063df8f49eb8a0cc898507fffd4e949e5456ced1266316a88edb0802bdc48cc40338b511cd17df2899ded1f34c7861c7f87dd2ff5491fe6cbfd670da7e7f4eb",
          "sha256": "1adcb071db9ea906a5fee2898e10f28fa77cc05d364b0aecea46f232bc5bb0be",
          "sha1": "bd238eced9473da77bb13b5e45ee10a60194f2e3",
          "md5": "e9632aae72477c94ddafce8ca74f62e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.0.1-sources.jar",
          "url": "thief-1.20.1-fabric-1.0.1-sources.jar",
          "size": 72756,
          "sha512": "47503a6d23936212f8ce3c15e8256108ae5f8df78a367c49e4039d46a108c323e50b96e0452f582416181e35fbe6abf2665c905edcdd689e865491bea89120ec",
          "sha256": "c8343856686494cbd326845decafe18836baa479c855c667532e59d0cb28c20b",
          "sha1": "0ffb2e9199ad84f48b1c73f7910f2c5c1db9100d",
          "md5": "4b439925f70cbcf87f018d4caa06d5c7"
        }
      ]
    }
  ]
}
