{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-common",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.1.1.jar",
          "url": "thief-1.20.1-common-1.1.1.jar",
          "size": 117646,
          "sha512": "b5c6f0ddf5e35ff902d2fd447e133da0d26675048b1e45677a3318085c2239ef8443a712b1fa4bfe71f0b05adfd265376fd354ab4907c7e1163b4c8b13545fab",
          "sha256": "8e10911d1cfe610c050e6e38108298df53ba0c2846e89bad1f2382608d193bb5",
          "sha1": "3357edc881fc6f2d613c457181fb59b687649c2f",
          "md5": "9bf6c0458333e8e6b622302c2f76a995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-common-1.1.1.jar",
          "url": "thief-1.20.1-common-1.1.1.jar",
          "size": 117646,
          "sha512": "b5c6f0ddf5e35ff902d2fd447e133da0d26675048b1e45677a3318085c2239ef8443a712b1fa4bfe71f0b05adfd265376fd354ab4907c7e1163b4c8b13545fab",
          "sha256": "8e10911d1cfe610c050e6e38108298df53ba0c2846e89bad1f2382608d193bb5",
          "sha1": "3357edc881fc6f2d613c457181fb59b687649c2f",
          "md5": "9bf6c0458333e8e6b622302c2f76a995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-common-1.1.1-sources.jar",
          "url": "thief-1.20.1-common-1.1.1-sources.jar",
          "size": 66519,
          "sha512": "c496f51ac4ebb21e9446b56526dc7b5251dd9fab0e840b72adeb85fa84fef28abb76a7fc8d14fa79e30bff4e7aa9385512add04e7076a039b99c1a0c56dbff19",
          "sha256": "572d4dd72f1a715615b5efe82281380ac51849557a029ddd0a2dd4c5757a44a5",
          "sha1": "6fc906c694db01a41cc824532cc6284be2ec801b",
          "md5": "fb3856f84ec0adc3fe18bb87c3a876aa"
        }
      ]
    }
  ]
}
