{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.4-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.4-forge.jar",
          "size": 598473,
          "sha512": "eba2256d67b78ff8e7bbfa84901679c43b09736212fa358dcd9caa7a46b179f87f69b3c1d22bbc3250f0a3db6b8b768e848800b9d3eff4b5f017e3e94a17b5f8",
          "sha256": "386e9684485757c2d6e8f53fe6f099d46fafc481e23680beed02f432b6934b62",
          "sha1": "69a500acb10bd0ff33a7e33d44cfbb1161e0ace8",
          "md5": "4cc9063880f10488729fec2e87ab95fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.4-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.4-forge.jar",
          "size": 598473,
          "sha512": "eba2256d67b78ff8e7bbfa84901679c43b09736212fa358dcd9caa7a46b179f87f69b3c1d22bbc3250f0a3db6b8b768e848800b9d3eff4b5f017e3e94a17b5f8",
          "sha256": "386e9684485757c2d6e8f53fe6f099d46fafc481e23680beed02f432b6934b62",
          "sha1": "69a500acb10bd0ff33a7e33d44cfbb1161e0ace8",
          "md5": "4cc9063880f10488729fec2e87ab95fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.4-sources.jar",
          "url": "scholar-1.20.1-forge-1.1.4-sources.jar",
          "size": 316689,
          "sha512": "d013c9bf61ce7ad48f7b77ce1dcc643d5b4ea6e2839f509c490b58a62b3d31f5a58db505fc6628a22bde7322f66293bf8eba0dc257c19a0d426d795da0d057e1",
          "sha256": "993363992b6cab549eba2324d81efd4bb43145acc895779e449a2e4503f0bd8d",
          "sha1": "f9765c6434a515e0eab6a60a50659186048df22a",
          "md5": "1230a35383ae77493e5a1f4192a01984"
        }
      ]
    }
  ]
}
