{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.16.jar",
          "url": "exposure-1.21.1-neoforge-1.9.16.jar",
          "size": 2189912,
          "sha512": "8c72cb320cde5aa13af31329d0c27000e16e451ccedba6b72da26d12ed28f61054414b2f914cc7e78954fe770ba42cdd5d81388421ac3d973cf7196734aaa0fc",
          "sha256": "c4adfe346094cf4ce0008c98bf0d20d7c96b9291b3cd31ff2234495eaca2bb58",
          "sha1": "b933b1d8c38ced7af391a82bc70f5d5c601ff21b",
          "md5": "9a1e2fd4cb76452392509b07e01ce08d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.8-168"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.64"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.16.jar",
          "url": "exposure-1.21.1-neoforge-1.9.16.jar",
          "size": 2189912,
          "sha512": "8c72cb320cde5aa13af31329d0c27000e16e451ccedba6b72da26d12ed28f61054414b2f914cc7e78954fe770ba42cdd5d81388421ac3d973cf7196734aaa0fc",
          "sha256": "c4adfe346094cf4ce0008c98bf0d20d7c96b9291b3cd31ff2234495eaca2bb58",
          "sha1": "b933b1d8c38ced7af391a82bc70f5d5c601ff21b",
          "md5": "9a1e2fd4cb76452392509b07e01ce08d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.16-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.16-sources.jar",
          "size": 39302,
          "sha512": "916c7afaa16868cf406b7b74313877889c44ce3a09ee963319f78c4a165836bd9041bdc16e7fb127cd1e8d30faa5bf70d9a2995bcab45198de31d062ffd54b84",
          "sha256": "bd5f47cedaf185d6ac7b59038919813513fd0df9ffe2c67cbdde05809aca109e",
          "sha1": "dd1fe0d70b33005ce62262e052ef03a1a8b9fb55",
          "md5": "a23d62b461c85e4aa400d3960f9da140"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.16-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.16-dev-shadow.jar",
          "size": 1971794,
          "sha512": "88735e485b9b90f25fcd6abf2a4dd101a6dec4ed990464a4d0b5d0494520411bd4333286f789221c4abb87ede4436ba050c3961f1eebf49dfd9b97ed3f6537cc",
          "sha256": "1a31020d39f3e45f65a4aa202b0d2055b1764e0c4a0e521594ddddb573329b76",
          "sha1": "6783cd4dc4f83531add5c746cd86f3fcdfeb7636",
          "md5": "3c6fa495daadb56d070ac62d815cb875"
        }
      ]
    }
  ]
}
