{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.5-snapshot5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot5.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot5.jar",
          "size": 1917857,
          "sha512": "0f42a70c4d205ab7f1ba70dbfa5720288e056aa4e3e92d694b5b9673fb5adabdaa3bcf56877f9c3e3648cff141e9b904cfdb8fa9a94854f9bd98650de22fd314",
          "sha256": "6f2dad8d8163d6e4b50f6f2664c2c16033cfcf135c1d303b748bf50e9382f9a3",
          "sha1": "b7b7d62e4d15a3c024553b30b672a06fc99b8363",
          "md5": "f64a8c3149a0a941626de3683970fef7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot5.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot5.jar",
          "size": 1917857,
          "sha512": "0f42a70c4d205ab7f1ba70dbfa5720288e056aa4e3e92d694b5b9673fb5adabdaa3bcf56877f9c3e3648cff141e9b904cfdb8fa9a94854f9bd98650de22fd314",
          "sha256": "6f2dad8d8163d6e4b50f6f2664c2c16033cfcf135c1d303b748bf50e9382f9a3",
          "sha1": "b7b7d62e4d15a3c024553b30b672a06fc99b8363",
          "md5": "f64a8c3149a0a941626de3683970fef7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot5-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot5-sources.jar",
          "size": 36413,
          "sha512": "ab597275601fdfa17203f7c732bb61cd76c05d8b7b6f39d587eb42b8761b16e3c0e827045615392a393862b1a207297cd106aa17b9184274acb7c73702386b1e",
          "sha256": "ff42570605f35cff517c953cae7f7d436573be4cfe9e79b6107c8a65564dcfe6",
          "sha1": "8a134e8148220be916e91d47b9a5e2dabb7352fb",
          "md5": "a41353a0deaea1d6f2f5d2e2b3f3dd20"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot5-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot5-dev-shadow.jar",
          "size": 1704543,
          "sha512": "93eea24cf7ad4404038719cc3ca1c50bf96988c83f7f914644d50713e84258f89b328e7100b13f2ed13ba280f58fe7fbd0870cb10551c5ac612a3c7d05f2c299",
          "sha256": "f723ead5f06432e09e60fad0b6ecf25ac6d6314539da7058beab764271196d37",
          "sha1": "55005ad6a4fb7ea2ae550cf3eb01177637f07a02",
          "md5": "ddc765dd02834c423fbb67b49dba2ba3"
        }
      ]
    }
  ]
}
