{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-fabric",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-fabric-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.1.jar",
          "url": "sootychimneys-fabric-1.3.1.jar",
          "size": 165791,
          "sha512": "22808d2208313540c98f274834faed84332c8b96adef533dab6aeddc85ea3ce24c5adc4eaaf16733a529836589bd6d59ba4819643cf703472155e306ec0538b6",
          "sha256": "fb28e15022782c87d4703ccb5bac5c80f5e6f9c3095055d8b506ae36b8d0aa6b",
          "sha1": "977caa0f03736cb7bd80b229ecaed36b804a3433",
          "md5": "e27052d042fc515f672e5f1f7835ae88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.21"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-fabric",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.1.jar",
          "url": "sootychimneys-fabric-1.3.1.jar",
          "size": 165791,
          "sha512": "22808d2208313540c98f274834faed84332c8b96adef533dab6aeddc85ea3ce24c5adc4eaaf16733a529836589bd6d59ba4819643cf703472155e306ec0538b6",
          "sha256": "fb28e15022782c87d4703ccb5bac5c80f5e6f9c3095055d8b506ae36b8d0aa6b",
          "sha1": "977caa0f03736cb7bd80b229ecaed36b804a3433",
          "md5": "e27052d042fc515f672e5f1f7835ae88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.1-sources.jar",
          "url": "sootychimneys-fabric-1.3.1-sources.jar",
          "size": 8671,
          "sha512": "53aa1830718dc59bf6c72d683c7ccb036c544eff0d08d1d053477f5290a7146833df56ec5f22cbf2c7cae9898a03a3c98409fbd1698314a6a6fa4a71b4048112",
          "sha256": "6c3bf5d3159d598cb88571b08d9712ef8992b76feeed8cea1464c2ed7a18bfec",
          "sha1": "0d3b463f8f97dc25cc788a05a59e324de0de70df",
          "md5": "560083bd2744b0fdace9814a460ae546"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-fabric-1.3.1-dev-shadow.jar",
          "url": "sootychimneys-fabric-1.3.1-dev-shadow.jar",
          "size": 162290,
          "sha512": "4c6a9582469979feb7590e8a474934365f62d1623d62c9e0cf60570ac1825ebca53f6a77af7100396f9dbfd6429feba8870a614519fed4c8855ea677cf89812b",
          "sha256": "c0b7b169d23e0e3f28a5fd505691da84344cada7029ca6d1a1ff190ca452ac1f",
          "sha1": "fdaae0f74ed82e232df6aab16f78ae81be29fae5",
          "md5": "653ceef9eb7ee61a458974481b55d3c5"
        }
      ]
    }
  ]
}
