{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.0.jar",
          "url": "horseman-1.21.1-neoforge-1.3.0.jar",
          "size": 317922,
          "sha512": "84594f7ba3a23069c403dc039af8ffc79e1f5142be26c721fb695ba005e9a28026a1c43ac705aa0b14f8dfde6127dcb86ce7d9d639df202422490bde800eeb6a",
          "sha256": "a8d89f97c0a0f6367bc0b80a4323b50ca5a9ddc76a4720b0f31f5a37e634da2a",
          "sha1": "f4f2b6d0415598ec0eac3da780de1d753bfc477e",
          "md5": "7786a527d279a6d68b64c6092d5187f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.0.jar",
          "url": "horseman-1.21.1-neoforge-1.3.0.jar",
          "size": 317922,
          "sha512": "84594f7ba3a23069c403dc039af8ffc79e1f5142be26c721fb695ba005e9a28026a1c43ac705aa0b14f8dfde6127dcb86ce7d9d639df202422490bde800eeb6a",
          "sha256": "a8d89f97c0a0f6367bc0b80a4323b50ca5a9ddc76a4720b0f31f5a37e634da2a",
          "sha1": "f4f2b6d0415598ec0eac3da780de1d753bfc477e",
          "md5": "7786a527d279a6d68b64c6092d5187f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.0-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.0-sources.jar",
          "size": 13732,
          "sha512": "b32c31cc62d47b499ac38ce5c939907be63412fcfe875b43cbd07b72b4f3a2ec8491a256798c8dc6cf85b52d6f0699d45c14bced89c51936bd3b3d4cf7aa944a",
          "sha256": "84884aab695624274ea432f1d81f33b813939da882cf4cb6885d5b85be71ae12",
          "sha1": "fd9eddc9adbd6525afce96ec845adc78b2adae05",
          "md5": "32737765e6594eb8e5a9a56b7fafc8bf"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.0-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.0-dev-shadow.jar",
          "size": 132863,
          "sha512": "080baf3fcfdcaab8efb14b7862b5a18435b90ccf652971e2151b72c870e13f30262953b8b9efa0369ab0851a47d2865e8cc6bc959a44ac1155255cbcfe2f0129",
          "sha256": "169b56b63df293b8971381c7e88e1180eb114ba7b4c9227f7ec7aa76a83725d9",
          "sha1": "946d68f8846462f3ce6f909527a0ab2bf3826cbe",
          "md5": "96ec9e8846d1fd59710cca6a9cfbf47f"
        }
      ]
    }
  ]
}
