{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-fabric",
    "version": "1.21.1-1.1.1-snapshot1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1.jar",
          "size": 159048,
          "sha512": "6dec31f88006dd3c28f73477578e6ca9209c321c5d0f2b5b0069781aa310f57390c44b9e06f33971c3bb51b05272f6a6edd1f01fbadbfd01abb2c14d3a664da8",
          "sha256": "824e609ebbfb885458fb859af8ae49ec0ac80d3b7b799c87023562547b2588e1",
          "sha1": "bef1450686df956975dafd5ace5711a766a2b187",
          "md5": "3ae10a19f7ae2380bf4a55337cbccf19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-fabric",
          "version": {
            "requires": "1.21.1-1.8.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1.jar",
          "size": 159048,
          "sha512": "6dec31f88006dd3c28f73477578e6ca9209c321c5d0f2b5b0069781aa310f57390c44b9e06f33971c3bb51b05272f6a6edd1f01fbadbfd01abb2c14d3a664da8",
          "sha256": "824e609ebbfb885458fb859af8ae49ec0ac80d3b7b799c87023562547b2588e1",
          "sha1": "bef1450686df956975dafd5ace5711a766a2b187",
          "md5": "3ae10a19f7ae2380bf4a55337cbccf19"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1-sources.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1-sources.jar",
          "size": 11493,
          "sha512": "b0f567d6c1a78db4d14199a5dfd09640e3ed819e99bf8bb5c59e0669c6fa21c590002b32da32ab22643528d2e97e91ebee3eba4f33a6f124c2ee644558972dba",
          "sha256": "e64677438470830cf85cc2860789435e4b7519990dd494b82afb8b33d27e17a2",
          "sha1": "8d0ab3ad2b2d2cceff1fd0ca861cf008292c9ba9",
          "md5": "6a52b8755915e076cd9c689d73d358a1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1-dev-shadow.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.1-snapshot1-dev-shadow.jar",
          "size": 145607,
          "sha512": "8eb5130dad8dd287b86169a14ff84863953661a47f4f378db7d459b37a5160f31faadc106ed3b05d917bd27c8a7380a610709e8342e24d4f199b567497228720",
          "sha256": "0d0af492dc6fde32041e711ecbb4c1839d7cb7e62dea415803dfa5fa798e513b",
          "sha1": "317a621e341cfbfd86aa61bb14eafa1e996458d0",
          "md5": "1605e7699e5646f39ea6665c884de833"
        }
      ]
    }
  ]
}
