{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.10-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.10-forge.jar",
          "size": 692466,
          "sha512": "d15bb65dc60a082429824f42ae916707ba5a2b5659ca8cfb3ac8502153f1e78e52a1b99727bb86fab0056dd5a61257c1d59fe4af446545472444f07da43ed844",
          "sha256": "a55a56cb33d04481fc8cbfbffd8266ada8d0c2ad7087aadddaf13cde068fd61f",
          "sha1": "d97976cec1aead54af00b25e41e7de01a4c84b05",
          "md5": "fdae672717e8ccb4199e4be5c07c476f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.10-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.10-forge.jar",
          "size": 692466,
          "sha512": "d15bb65dc60a082429824f42ae916707ba5a2b5659ca8cfb3ac8502153f1e78e52a1b99727bb86fab0056dd5a61257c1d59fe4af446545472444f07da43ed844",
          "sha256": "a55a56cb33d04481fc8cbfbffd8266ada8d0c2ad7087aadddaf13cde068fd61f",
          "sha1": "d97976cec1aead54af00b25e41e7de01a4c84b05",
          "md5": "fdae672717e8ccb4199e4be5c07c476f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.10-sources.jar",
          "url": "scholar-1.20.1-forge-1.1.10-sources.jar",
          "size": 413535,
          "sha512": "6d74a7893d70c2f001cbbee4bed331f64161f8f0182eacdd82d141e4fe0d475982e139dbcda86619b2f2c26a947a1b001f99c8348cdcd7fa6d448e68b78925d3",
          "sha256": "e410e17f552ca292c6908eb9bf2c5964c87711fd1902d4e262f22cc1518dd62c",
          "sha1": "de596c4f1d3ea7d4da25a9b97965bca99d3af1cc",
          "md5": "f56aa2a4ba421da90cd9922d0bad8706"
        }
      ]
    }
  ]
}
