{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.16.jar",
          "url": "exposure-1.20.1-forge-1.9.16.jar",
          "size": 2243634,
          "sha512": "053cec129966e293c0a70e2f6f22b675e28376e0415c6947073f6a10df7bd7018a2be750847bb38a9fad1f1cd2a76d7522e403a36360b87f8988bcd790a811f4",
          "sha256": "c79c6b41e37b8dbb46b588190d09433ccfbd4b0a988a775d12824e2a5e8c534b",
          "sha1": "49e6fb1e81d80214fed8b9cfc90a52ec4b8ce4c6",
          "md5": "d76fa56271ffb1d432e3f668c81b0cc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.16.jar",
          "url": "exposure-1.20.1-forge-1.9.16.jar",
          "size": 2243634,
          "sha512": "053cec129966e293c0a70e2f6f22b675e28376e0415c6947073f6a10df7bd7018a2be750847bb38a9fad1f1cd2a76d7522e403a36360b87f8988bcd790a811f4",
          "sha256": "c79c6b41e37b8dbb46b588190d09433ccfbd4b0a988a775d12824e2a5e8c534b",
          "sha1": "49e6fb1e81d80214fed8b9cfc90a52ec4b8ce4c6",
          "md5": "d76fa56271ffb1d432e3f668c81b0cc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.16-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.16-sources.jar",
          "size": 52584,
          "sha512": "1eaa031f5c392e5ba1b5a5d513a44d0d39f99c2fef40e90b3debc06132fa9178004b70c5d375a30a27300b10c04811334fe230283c890b6ae3e825af24a31cd7",
          "sha256": "2ac8b684f8c334762aaeb7917285bdefb0ad0676ba7fbc12b971a98189366c59",
          "sha1": "8837f9c4c0c36b44671c18b384516221e6c362d4",
          "md5": "0e6bb033026266cf4b5944bf89a23ff0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.16-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.16-dev-shadow.jar",
          "size": 2016778,
          "sha512": "cc78d947ff1c5920e58cde2c8002356077be31d058c8a853101a8bb366da2dd50fdf6dfb6730255f671ddd03ce0fb3da25bd6dd3d300abf8c2ae69f66c40a950",
          "sha256": "52e107bda38eb2da71a09da9faded657920d122bee23cc49aff809f4507c1791",
          "sha1": "1d83aeed6fbe3da203db39330f9bc6432bd4d918",
          "md5": "8d4f37be1358f73a0846d474502d19af"
        }
      ]
    }
  ]
}
