{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-fabric",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.5.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.5.jar",
          "size": 166938,
          "sha512": "f9966fad9ea954025012bc410ab30ae0b2ac3305e03a0cf532b56e57539ed2bad7ad1b4036b1b225bd5fcb0eec56278b304c83f7523fc14f832761a43251d4a7",
          "sha256": "eb86189cc0511decc7c53fac51765bdedf5f33c28138f9927bf3107e07d82140",
          "sha1": "f7ffb5d252f712b2de831d255cf11ef23acbaed9",
          "md5": "34c51bedd4ce83f71216871cf8fc843f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.5.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.5.jar",
          "size": 166938,
          "sha512": "f9966fad9ea954025012bc410ab30ae0b2ac3305e03a0cf532b56e57539ed2bad7ad1b4036b1b225bd5fcb0eec56278b304c83f7523fc14f832761a43251d4a7",
          "sha256": "eb86189cc0511decc7c53fac51765bdedf5f33c28138f9927bf3107e07d82140",
          "sha1": "f7ffb5d252f712b2de831d255cf11ef23acbaed9",
          "md5": "34c51bedd4ce83f71216871cf8fc843f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.5-sources.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.5-sources.jar",
          "size": 8705,
          "sha512": "10d7fe33c7becd462d2a99aee35423413b9c698e45962ede3c90a3a87f37e98ca9c16bde34ac5553dfa8db15edea9399de1d4ed297c401d13080f2eec38e2547",
          "sha256": "cecc893ada73e37b882dc5376ae468c5607c98194a23dae646a19d4321ce5f21",
          "sha1": "c3b5081c82ec5170af5f020378afb058204bb091",
          "md5": "72a1ba0e38b7691ba69e572ecae58b92"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.5-dev-shadow.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.5-dev-shadow.jar",
          "size": 163434,
          "sha512": "d7fc95201b1d48cbea4283c685fb3e0f6d7a6030c6a708176d01eb7917145db6b8b3ef863e99eee64a0885c38aac9b7126ba05439f20f20f91861b9c78b0bb82",
          "sha256": "915aa5f82ae32c8af866c81a57f4611576f706760b7a17d2c50cc40d63764378",
          "sha1": "eafa592479d42c25d59bcbae6474ed9192f64419",
          "md5": "902b19ff9ba96e3bdf4eb9b4f1693001"
        }
      ]
    }
  ]
}
