{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.13.jar",
          "url": "exposure-1.21.1-neoforge-1.9.13.jar",
          "size": 2179861,
          "sha512": "4df1c6a6b52794a64826a247d5ca33cb50f94d83e11b5a20ca90ffc84c85021f522040cf0602231f196d08106069f72507049051a418ff111cad0b24d3e49d7a",
          "sha256": "3e652d57f318b9cbc5ca48921b2b9199223a6a089a48a18f3f7da8708fdf2ea7",
          "sha1": "dbee05b7a892d70acfd3d4c45494a9407bdedcfe",
          "md5": "5a43acb7a014bc6aa02b3a489954b983"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.8-168"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.64"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.13.jar",
          "url": "exposure-1.21.1-neoforge-1.9.13.jar",
          "size": 2179861,
          "sha512": "4df1c6a6b52794a64826a247d5ca33cb50f94d83e11b5a20ca90ffc84c85021f522040cf0602231f196d08106069f72507049051a418ff111cad0b24d3e49d7a",
          "sha256": "3e652d57f318b9cbc5ca48921b2b9199223a6a089a48a18f3f7da8708fdf2ea7",
          "sha1": "dbee05b7a892d70acfd3d4c45494a9407bdedcfe",
          "md5": "5a43acb7a014bc6aa02b3a489954b983"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.13-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.13-sources.jar",
          "size": 39304,
          "sha512": "9ea0c85539570be018739e71048bd852240fa23653ea7118f99803c759c7f926bf69bdd41a9aa41ba94b41a357e937fd6747bfac9e32c5a843c66809a50b7891",
          "sha256": "2a5f30671ee77862100060e05ee6f1024cd00f85f7d760a90ac608655b93ee30",
          "sha1": "b94f9ea93836cf4918253daf2adfbe7f92fc5ed7",
          "md5": "d521aa5e336fe67ca62fd1a8b28159ee"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.13-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.13-dev-shadow.jar",
          "size": 1961877,
          "sha512": "e630cba243dd696606f0484b20761dc21d3fccab4ee5eaf8cdb606d5ae79bf877236bc7703cf359496325d938d1526e281b6d3ab64a2bb43ddee72901a1d5ef2",
          "sha256": "75417a060f2421985527a83714c8e97c318e0c29a4786c28beae2b82c941cee3",
          "sha1": "2c8b8f07a6eb9452042cb6659189acb6aba151c2",
          "md5": "78ecdfe254efd6ecacbfad83713280d9"
        }
      ]
    }
  ]
}
