{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.11-fabric",
    "version": "1.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "scholar-1.21.11-fabric-1.1.13.jar",
          "url": "scholar-1.21.11-fabric-1.1.13.jar",
          "size": 531525,
          "sha512": "02da815a4a967548fb776ed4d7d8aae30d2536654ba4f1fa1087cdb24b943f6215726b4225d0d789ccde31de7bf022ffb9deb2503a353da9cbbe4a3e105f0825",
          "sha256": "d91bd6897aeff57cc7e9ad9a672cd0e24d8f1ab8f0ba823d33ab596a76643c3d",
          "sha1": "e57e69e0ff005d1a4c2959f6a12c9e7d13a0804d",
          "md5": "31995adbad52799a5cb0f5ec8ba50206"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.5+1.21.11"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.11-fabric-1.1.13.jar",
          "url": "scholar-1.21.11-fabric-1.1.13.jar",
          "size": 531525,
          "sha512": "02da815a4a967548fb776ed4d7d8aae30d2536654ba4f1fa1087cdb24b943f6215726b4225d0d789ccde31de7bf022ffb9deb2503a353da9cbbe4a3e105f0825",
          "sha256": "d91bd6897aeff57cc7e9ad9a672cd0e24d8f1ab8f0ba823d33ab596a76643c3d",
          "sha1": "e57e69e0ff005d1a4c2959f6a12c9e7d13a0804d",
          "md5": "31995adbad52799a5cb0f5ec8ba50206"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.11-fabric-1.1.13-sources.jar",
          "url": "scholar-1.21.11-fabric-1.1.13-sources.jar",
          "size": 30235,
          "sha512": "90bd27ce5d6c6bd6ad8b9f756ecd26fd50d4851576b7607d6e65601a1fbf7f716699e1939c7ed9142d2179d66f4342965f3da35f9644993060b88e669ab4d464",
          "sha256": "814637a4c152f0e6e6bba0cd76f8b5c85a2c5a3138d1ebfb7d254d0ab37c64c3",
          "sha1": "f0b37cf78190af6f3deef3c1b4720cc5f191338b",
          "md5": "5fbeba6ca90302a5758328373ba2f9f6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.11-fabric-1.1.13-dev-shadow.jar",
          "url": "scholar-1.21.11-fabric-1.1.13-dev-shadow.jar",
          "size": 524151,
          "sha512": "2b559e1faa48df96c32fcc88451fd558f8845a89201fc5b4cbb3bfcffd21fd70ecf3081e321b49e176aad4d68930488e5668444a9f6020dace46f70aa5eb856e",
          "sha256": "487b7d04e6dc1d67a4d39d4f5671cb2fef52f8c0c16ed5a11609c0f930262579",
          "sha1": "e624a9178988099677717649c107de125daec14e",
          "md5": "4fa9d3a962c741e2994271ce475e29f8"
        }
      ]
    }
  ]
}
