{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "size": 327459,
          "sha512": "0acd0a934aab0bdc5b5c9831a1e821dfe311314d686f3d433eff12e66f3659770e633a1a4be4b8dc3154dcc3e3f63475a78ec658aaf37213cbd9cfa1e030b6da",
          "sha256": "d52425c336897daa8b73f3d9981e121baef48acb43780df96cbaecd2d124cc48",
          "sha1": "2ce1a46711e526fc247375bc8946a12df2d8043c",
          "md5": "fc83fec5480e35b886923b51c065c5b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "size": 327459,
          "sha512": "0acd0a934aab0bdc5b5c9831a1e821dfe311314d686f3d433eff12e66f3659770e633a1a4be4b8dc3154dcc3e3f63475a78ec658aaf37213cbd9cfa1e030b6da",
          "sha256": "d52425c336897daa8b73f3d9981e121baef48acb43780df96cbaecd2d124cc48",
          "sha1": "2ce1a46711e526fc247375bc8946a12df2d8043c",
          "md5": "fc83fec5480e35b886923b51c065c5b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.8-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.8-sources.jar",
          "size": 87234,
          "sha512": "3aa0d39797189519a991a4c45aebf371c3c5092b37708aa53d415f28fb8cf1a36e42100de9479cdb2811e08dd1261643d09cc591dc8c532d94c5a8f8d84e8186",
          "sha256": "1ce14b11df97a1910972ffaffb5ebeb0ababd448655042c11fcb2dc81a71010d",
          "sha1": "290e8c157a142f6e322cd39f6e82d76a2878dd30",
          "md5": "ec7ce1f99886739d6471caa0d06cae0a"
        }
      ]
    }
  ]
}
