{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "size": 329040,
          "sha512": "06683c3dbc0f673a2af17203972cdd91992d6dc2aeb89f638b2d895666de99affaf686e7c455af56de8c5e4f9ace5b44e25d1b2b4b6c7368f2571f1b9913761d",
          "sha256": "b804a7f5e934a5df7c8f68a94f2117e834900c0ceb926f5e25d84ab9e11701b1",
          "sha1": "7f3bce065d6d1e5fa99e1fa048972c8a820c5ae9",
          "md5": "691dfa7174cac14f893b38f5f0f4a126"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.8-forge.jar",
          "size": 329040,
          "sha512": "06683c3dbc0f673a2af17203972cdd91992d6dc2aeb89f638b2d895666de99affaf686e7c455af56de8c5e4f9ace5b44e25d1b2b4b6c7368f2571f1b9913761d",
          "sha256": "b804a7f5e934a5df7c8f68a94f2117e834900c0ceb926f5e25d84ab9e11701b1",
          "sha1": "7f3bce065d6d1e5fa99e1fa048972c8a820c5ae9",
          "md5": "691dfa7174cac14f893b38f5f0f4a126"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.8-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.8-sources.jar",
          "size": 88835,
          "sha512": "644c693d52c03c7f2c33caa5428d8332f4f25dc338344346ab1e2cb2436e279a8ac3d6e3c07f4dc9b971bc782823f7ad006af1e8ab0119c9e6be21a13e8a84e5",
          "sha256": "f622cf34d10046c8e548814e0d9c60f092379109c5ed4c03b25a23a82f4ae383",
          "sha1": "80f53145a963e1e43512855bc6c6036d5f64c20e",
          "md5": "9de5e86fdac516c71f79d331269406e5"
        }
      ]
    }
  ]
}
