{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.14.jar",
          "url": "exposure-1.20.1-forge-1.9.14.jar",
          "size": 2235629,
          "sha512": "8e1c76adf3c87ca783229c942012313d2408b9922c622a84c1ce33b564e9d3837d167bf2357ba4a4d987c401b98e428a67c60c00c582cce4c897fda925dda725",
          "sha256": "85eeca70f3e6e4e11213c2f658effdfc0c3c5cbcbae314a3a3beeef02fb7f194",
          "sha1": "be66037af36af1963a205ffddfd663b7d0b2d77d",
          "md5": "9c6d454bbbef6209c6fcfa6e19984d0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.14.jar",
          "url": "exposure-1.20.1-forge-1.9.14.jar",
          "size": 2235629,
          "sha512": "8e1c76adf3c87ca783229c942012313d2408b9922c622a84c1ce33b564e9d3837d167bf2357ba4a4d987c401b98e428a67c60c00c582cce4c897fda925dda725",
          "sha256": "85eeca70f3e6e4e11213c2f658effdfc0c3c5cbcbae314a3a3beeef02fb7f194",
          "sha1": "be66037af36af1963a205ffddfd663b7d0b2d77d",
          "md5": "9c6d454bbbef6209c6fcfa6e19984d0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.14-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.14-sources.jar",
          "size": 52551,
          "sha512": "185a1218cf8b3b104cf12cdfc75efc809570b9595df3d59314cae5716c49095ac94ab9d15b4b287ea219f4fc86501022e3793533ec531b687f9a9935e53d903c",
          "sha256": "6391b04f85af05f67cc0abc165fc5d40b4be5e5f7b0eb1e0501c8d1ba5a27498",
          "sha1": "6c740988328778d66e52ec8c2109a741cea1ce16",
          "md5": "a161e4fc4b798831b446b28ceddc652f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.14-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.14-dev-shadow.jar",
          "size": 2008922,
          "sha512": "b566e7394b45c79fb5a6e4bfe7c87e35a9be8c2f6dd7b412d050aa5850adce04291078c867894eaf62811f096954c529d7eb85e8732ff979fde892877ba76b89",
          "sha256": "156e26652a8e1dd416c682a2ebbec3595636ed6aa7bd7b453c2ed556d7030fbb",
          "sha1": "44d4803d9820255249f105eafe81fabbeb149631",
          "md5": "449aecf8cff9f0fd5aa8177d05635973"
        }
      ]
    }
  ]
}
