{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.3.jar",
          "url": "exposure-common-1.7.3.jar",
          "size": 1257515,
          "sha512": "f8bbde9b6608cc24e3928cf70ee340119dfbeacba6a49a8e23e31a09ac7a48a34f19f074c21bf519bc77267fdcf1c8860d82c1a047350c723e0e7c26eba788d5",
          "sha256": "10837a18c768aea5450468c1536e5ae1b4519623d54668b0950692a64936dbc9",
          "sha1": "eb5293cc717f7bfd994f288aae218a66a120a57c",
          "md5": "b2615f3f1e0fd3d3ef39acaddab8bd44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.3.jar",
          "url": "exposure-common-1.7.3.jar",
          "size": 1257515,
          "sha512": "f8bbde9b6608cc24e3928cf70ee340119dfbeacba6a49a8e23e31a09ac7a48a34f19f074c21bf519bc77267fdcf1c8860d82c1a047350c723e0e7c26eba788d5",
          "sha256": "10837a18c768aea5450468c1536e5ae1b4519623d54668b0950692a64936dbc9",
          "sha1": "eb5293cc717f7bfd994f288aae218a66a120a57c",
          "md5": "b2615f3f1e0fd3d3ef39acaddab8bd44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.3-sources.jar",
          "url": "exposure-common-1.7.3-sources.jar",
          "size": 902019,
          "sha512": "b81c135b2cf4443025b98f7440fb7f4e41c3ec2b849646432e0b1c79525d7a6d3f0a7761d01f9b4999433f42a20ee94084a6ef87c4ca878dab5cd45a93a020f1",
          "sha256": "8fb135d57592a3d0aba99ac590f7f93bd17b345b4d4fc22f2bf9eec12e021823",
          "sha1": "a4f43d9eef1a7dd56d96f2e76ce608fb3e5783e0",
          "md5": "411084c284ca93676409763461e19506"
        }
      ]
    }
  ]
}
