{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "real-camera-851574",
          "version": {
            "requires": "5328995"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.3.jar",
          "url": "exposure-common-1.7.3.jar",
          "size": 1257444,
          "sha512": "a2ab8be6a0a578863b932a5f05bc3ec19364f08fa3583a592d9a732e8ee88ca0b4bd7f01ffe63793b81b42b85bcb87d76b076bef5d47787801fe25fc76b846cd",
          "sha256": "55109e91e7d9485ebad2c5898487a12ba131261859f825003d195e60e5b6210c",
          "sha1": "d85d269da75f95cd85b1646c74f3f7350d981399",
          "md5": "28520a58b4fb713dae6bca489da83644"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.3.jar",
          "url": "exposure-common-1.7.3.jar",
          "size": 1257444,
          "sha512": "a2ab8be6a0a578863b932a5f05bc3ec19364f08fa3583a592d9a732e8ee88ca0b4bd7f01ffe63793b81b42b85bcb87d76b076bef5d47787801fe25fc76b846cd",
          "sha256": "55109e91e7d9485ebad2c5898487a12ba131261859f825003d195e60e5b6210c",
          "sha1": "d85d269da75f95cd85b1646c74f3f7350d981399",
          "md5": "28520a58b4fb713dae6bca489da83644"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.3-sources.jar",
          "url": "exposure-common-1.7.3-sources.jar",
          "size": 902340,
          "sha512": "c64a9646ec94610888c6ff69e0b2691ad97e7c55aaf74d4ade214c3cad318454e338efe41738fbc2bb9237a3f348f1dd08e721917c65e0929bb30b44dadc77d2",
          "sha256": "d1a4023968892b9f2236bb0078b2e68e927e0de3620c8b091f7d9240d2039c97",
          "sha1": "79b805648c93e90e6afeb5640cbc02a6de06b025",
          "md5": "375a2e9f1860e441254c5d4fa75a0f3a"
        }
      ]
    }
  ]
}
