{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-fabric",
    "version": "1.21.1-1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.0.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.0.jar",
          "size": 158995,
          "sha512": "5cc67ef910ffa8a0ca5198a27eac9206071252e7f6cf3d3a92eb329cc64240e024e685bf7d683b0faf44d8aed573d08b33a1ccd3c4bdd38003b10e266731c69d",
          "sha256": "10288d0688325c559674f75b7736d288ad5d390284839d2b6a90503f325ac334",
          "sha1": "74a043d726c9a48c455550e65e358b22b23953b6",
          "md5": "befcac1c9efdb317c8cee131cee608df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-fabric",
          "version": {
            "requires": "1.21.1-1.8.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.0.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.0.jar",
          "size": 158995,
          "sha512": "5cc67ef910ffa8a0ca5198a27eac9206071252e7f6cf3d3a92eb329cc64240e024e685bf7d683b0faf44d8aed573d08b33a1ccd3c4bdd38003b10e266731c69d",
          "sha256": "10288d0688325c559674f75b7736d288ad5d390284839d2b6a90503f325ac334",
          "sha1": "74a043d726c9a48c455550e65e358b22b23953b6",
          "md5": "befcac1c9efdb317c8cee131cee608df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.0-sources.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.0-sources.jar",
          "size": 11493,
          "sha512": "a9cbe6fc514b750919cb603d3fc83c255cf098e25c7b4c5e13d00b6d4ad2a5291459a891913ecc6efae80d31f1ff1c3ff538b976fd20fe9c23ed0f9c6df72e61",
          "sha256": "0cc4a341ab1bc1b58186b22660926c47e9b3a8ac1d39029ed2bc562df36f6c9d",
          "sha1": "688ebed987f74d463a9507929bea7cb322c5ad85",
          "md5": "9456319ecc336d8646f9dea038341a05"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.0-dev-shadow.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.0-dev-shadow.jar",
          "size": 145557,
          "sha512": "de792b873cd486f9957cb9fd70634f27c912d10cd2b35e3ba682022691568343414fa78f4a7f2adaf139076a1256ab25da184b1a2121881705d897ac6e08e72f",
          "sha256": "977c4bddab879f00032a9500a98b7f6636ae91bddc3f9e4cf24905289cd35b68",
          "sha1": "a9368600a6d2b09b58cea040fd7725eeddeaa677",
          "md5": "1ddb39f91c5e8dbfa30e6cff360e941d"
        }
      ]
    }
  ]
}
