{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.11-neoforge",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge-api",
          "version": {
            "requires": "27.3.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.11-neoforge-1.7.2.jar",
          "url": "horseman-1.21.11-neoforge-1.7.2.jar",
          "size": 468793,
          "sha512": "20e8d053a05eb38aa82f35ba99658c8039e4651e563821c58ce449e2e4c222a0bf4288191b1be1261128074ee1ec69a167a594f5b13ac5c8a0b2a83de589fea7",
          "sha256": "70f7716b2e39c8c9b3ee7d6577d3a55f0dba35bf09ef052d7cd3d1485e7e40e6",
          "sha1": "f9366e538ce5f42dbb30328bd8c563009f4a4249",
          "md5": "2b1eb2a4fc6d09905e87361629a5d86f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge",
          "version": {
            "requires": "27.3.0.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "21.0.1+neoforge"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.11-neoforge-1.7.2.jar",
          "url": "horseman-1.21.11-neoforge-1.7.2.jar",
          "size": 468793,
          "sha512": "20e8d053a05eb38aa82f35ba99658c8039e4651e563821c58ce449e2e4c222a0bf4288191b1be1261128074ee1ec69a167a594f5b13ac5c8a0b2a83de589fea7",
          "sha256": "70f7716b2e39c8c9b3ee7d6577d3a55f0dba35bf09ef052d7cd3d1485e7e40e6",
          "sha1": "f9366e538ce5f42dbb30328bd8c563009f4a4249",
          "md5": "2b1eb2a4fc6d09905e87361629a5d86f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.11-neoforge-1.7.2-sources.jar",
          "url": "horseman-1.21.11-neoforge-1.7.2-sources.jar",
          "size": 12610,
          "sha512": "5a73cb766ccdd6a012e851b519db1b4750e9afc708ac7c3e937a25d95ba4caf8c97f36e852ef5857c43ed8d8cf6df0a35eb81c977aaaf27ca10a2e2445f3b69c",
          "sha256": "9cc42a60e0f06aacef8b1075ab1c6c4ac9a7a6fe451ad0b5a9d0639cf11d72c3",
          "sha1": "6d42823b240e23410bfbe912af6730de34d99ccd",
          "md5": "3ca9c5a815a35230541989c5b242a833"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.11-neoforge-1.7.2-dev-shadow.jar",
          "url": "horseman-1.21.11-neoforge-1.7.2-dev-shadow.jar",
          "size": 281693,
          "sha512": "197fa241a8206cba431285065ebf8991a100ab0b445bada7d743aa10958e957e449a22812925d117121f0d38b3acbb7072777363865c594b6ed5a13c7e90e678",
          "sha256": "9c239ed4f5375a59e1aefaa259c6483c71066bb859ceb8db563056fc92429ebc",
          "sha1": "69e462029c5987f3b93321cb2bd67147eb4701e3",
          "md5": "b5004e223103f995565d96acbeb703f1"
        }
      ]
    }
  ]
}
