{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-neoforge",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge-api",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.1.jar",
          "url": "sootychimneys-neoforge-1.3.1.jar",
          "size": 168692,
          "sha512": "2aedffaf93c299dd248cf78ac00404d682305ab8eabebf33f4fce6dfad788af314f61c3a5a3edb941a6e20fd87e69dbdcd4655b4a59305a64a47e6d23544775e",
          "sha256": "0df8892789658da161580c43c18227b08d8cfe50a29440719419cebd62733f0e",
          "sha1": "a1867aedc60c4ec9957fb166a396c66866d5730c",
          "md5": "d9c26bd0d9126f9e2acced5b8f6d3024"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge",
          "version": {
            "requires": "19.5.2.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.1.jar",
          "url": "sootychimneys-neoforge-1.3.1.jar",
          "size": 168692,
          "sha512": "2aedffaf93c299dd248cf78ac00404d682305ab8eabebf33f4fce6dfad788af314f61c3a5a3edb941a6e20fd87e69dbdcd4655b4a59305a64a47e6d23544775e",
          "sha256": "0df8892789658da161580c43c18227b08d8cfe50a29440719419cebd62733f0e",
          "sha1": "a1867aedc60c4ec9957fb166a396c66866d5730c",
          "md5": "d9c26bd0d9126f9e2acced5b8f6d3024"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.1-sources.jar",
          "url": "sootychimneys-neoforge-1.3.1-sources.jar",
          "size": 9436,
          "sha512": "6db99ff261d642c782400fbc92b1d6eeed8aa7a454c4b87bc5eda07ed229ac73e38d326e4ad1f7eab3a571df4f96146a655d841a2127aa45dddb27ed080fdd5c",
          "sha256": "2cba6a2b8449dd2109df69dad7519e7796849c4982be82126e99a55567f3372b",
          "sha1": "4b5f563086459d884ad1b86601c6c7d2f5c56f7d",
          "md5": "b1289b9c016c06eb0b9ef09695cbcee2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.3.1-dev-shadow.jar",
          "url": "sootychimneys-neoforge-1.3.1-dev-shadow.jar",
          "size": 163813,
          "sha512": "8d48a11d19354017422fafdfb27dfd21ebe05cbd8822b682c783dbaad1333539978c8e87d77b1e907fd4e06f38d9a00d3699124ee3848d645596d6cdff84b7c3",
          "sha256": "8472d852d481ec2b4571a483cda7038bf7634384ae063cb512473dc6fa97c40a",
          "sha1": "ace424d9cf77f39d6359cf9413157da6160ed412",
          "md5": "43dd3c2ef23739203b4764d3b2170ba3"
        }
      ]
    }
  ]
}
