{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.12-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.12-fabric.jar",
          "size": 316339,
          "sha512": "7c93fda0b628453f4e0aaf578457a0feed7df45b466a84f7fa396ee640293238e9afb58a21859bed7b87f865f645d32d95753f78f445c329cd8df9e4a6036113",
          "sha256": "518e88d0d3a28edf9a838eb048e7bba09b05d36e2b21bb91231b2628b83eaadd",
          "sha1": "15f468a124ec9a66ddbcd1415896d454cba019f7",
          "md5": "896f6c4a7820929b8cf831700ce2ca4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.12-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.12-fabric.jar",
          "size": 316339,
          "sha512": "7c93fda0b628453f4e0aaf578457a0feed7df45b466a84f7fa396ee640293238e9afb58a21859bed7b87f865f645d32d95753f78f445c329cd8df9e4a6036113",
          "sha256": "518e88d0d3a28edf9a838eb048e7bba09b05d36e2b21bb91231b2628b83eaadd",
          "sha1": "15f468a124ec9a66ddbcd1415896d454cba019f7",
          "md5": "896f6c4a7820929b8cf831700ce2ca4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.12-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.12-sources.jar",
          "size": 82701,
          "sha512": "01576ac4807208c75e0899471a1368753dcd18e6f310747a91c45d3eb58057f3a0c606c578bb32c96f8a8510fa939b92b5f39663d3b2e2298c6f8b0a719913f5",
          "sha256": "7a79eb281c76d39914a809b54932de6b1adb8d54b2597a5e8087401b1d05bbd6",
          "sha1": "3eca52d050adeb0c794d4eaf24f8e4753160cda4",
          "md5": "4c0491d3902b08ba9a93519a46f06777"
        }
      ]
    }
  ]
}
