{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.0.0-fabric.jar",
          "url": "horseman-fabric-1.0.0-fabric.jar",
          "size": 265834,
          "sha512": "d82d632727bc3121acdc44a3e23c550e7e372a795903dc4fd795da27133fb600c3993c68b17e6efb0c28ebadeac86897f55bcac606bb0e4b38c92383b8758f82",
          "sha256": "4acb9285ef846308d17036fb83d8cb4156c7313821036410c2e3d7001eed5878",
          "sha1": "34c69bb9f16e74397e0ab9cd98f483119fec3e55",
          "md5": "fcebd0d461129b1dc6d7f6b42de67739"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.0.0-fabric.jar",
          "url": "horseman-fabric-1.0.0-fabric.jar",
          "size": 265834,
          "sha512": "d82d632727bc3121acdc44a3e23c550e7e372a795903dc4fd795da27133fb600c3993c68b17e6efb0c28ebadeac86897f55bcac606bb0e4b38c92383b8758f82",
          "sha256": "4acb9285ef846308d17036fb83d8cb4156c7313821036410c2e3d7001eed5878",
          "sha1": "34c69bb9f16e74397e0ab9cd98f483119fec3e55",
          "md5": "fcebd0d461129b1dc6d7f6b42de67739"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.0.0-sources.jar",
          "url": "horseman-fabric-1.0.0-sources.jar",
          "size": 47230,
          "sha512": "e9f7088617eb3593ce125dc688e6e3e823ec6b55f3249b957839bd2fa2540c4cd2955d40af63ca06d25ebb82a92f54384cd2b20e939e5350c23e1539b88d04b7",
          "sha256": "90db3733373c6743e7f8e7569f79f1f5ef070ebe33cfb3de62f42adefdcfe147",
          "sha1": "213be5ab64ad65f06dcfa6fc75029611aeb866ce",
          "md5": "8a31f7b1f5f0bf57f6def76c3e3ca8cd"
        }
      ]
    }
  ]
}
