{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.1-fabric.jar",
          "url": "horseman-fabric-1.1.1-fabric.jar",
          "size": 260775,
          "sha512": "6eeb2efc09ef6f728b22b1566ecf14ded6ab70a73f23b10e465ac2bc576d8ee7e48758c2a91e12b8a4f8a70ed4164c3205d667ffecfbb070caf26150502c69d1",
          "sha256": "f06874c456c5d1f3a609f7f5f86a9da56c66ab42fb120fc36ce784d29f390836",
          "sha1": "591c97c2dc3d13ae131dd57466e228661512d66e",
          "md5": "318714afc09b615f7097b63f76ddadb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.1.1-fabric.jar",
          "url": "horseman-fabric-1.1.1-fabric.jar",
          "size": 260775,
          "sha512": "6eeb2efc09ef6f728b22b1566ecf14ded6ab70a73f23b10e465ac2bc576d8ee7e48758c2a91e12b8a4f8a70ed4164c3205d667ffecfbb070caf26150502c69d1",
          "sha256": "f06874c456c5d1f3a609f7f5f86a9da56c66ab42fb120fc36ce784d29f390836",
          "sha1": "591c97c2dc3d13ae131dd57466e228661512d66e",
          "md5": "318714afc09b615f7097b63f76ddadb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.1.1-sources.jar",
          "url": "horseman-fabric-1.1.1-sources.jar",
          "size": 42778,
          "sha512": "e61fdd9ac0bf9d4fbc4178d4f8e238617fba2fd51a793eb9eec1b66d8db6c7fd9490e4c887ee9d689ea7eea58039961754b4fb0f0e43b29e450137f00a81dd43",
          "sha256": "df97ec9241d5789508a332223258df604afe47899a4d7b7afe04ded646b70915",
          "sha1": "c2c9153ce3e88067e7b189ff101a5b2c93469cf4",
          "md5": "13938a954c45a626e4c9e875e09160af"
        }
      ]
    }
  ]
}
