{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-fabric",
    "version": "1.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.7.jar",
          "url": "exposure-1.21.1-fabric-1.9.7.jar",
          "size": 1956480,
          "sha512": "9d4f21a06e227f1441cd9dd309b5d40fcc8490cc3924271d1db23e71436959218d2981ef7a8007921f794017baf42bff209b97b9433729c1bf1a806a0de6c357",
          "sha256": "ca48e1b77b767c045c641d0b495b295da6a345e3994a5a52ec1763d33d48ab47",
          "sha1": "7dbfeb241c244954cb887b18fb6d47d8f379991d",
          "md5": "f289cc6404df452dddc4f6cc2e3a6a06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.7.jar",
          "url": "exposure-1.21.1-fabric-1.9.7.jar",
          "size": 1956480,
          "sha512": "9d4f21a06e227f1441cd9dd309b5d40fcc8490cc3924271d1db23e71436959218d2981ef7a8007921f794017baf42bff209b97b9433729c1bf1a806a0de6c357",
          "sha256": "ca48e1b77b767c045c641d0b495b295da6a345e3994a5a52ec1763d33d48ab47",
          "sha1": "7dbfeb241c244954cb887b18fb6d47d8f379991d",
          "md5": "f289cc6404df452dddc4f6cc2e3a6a06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.7-sources.jar",
          "url": "exposure-1.21.1-fabric-1.9.7-sources.jar",
          "size": 30905,
          "sha512": "c4d806808cf3ef0593b6a074ead53f6d5cea65769842f19b8544ebfddf55601c3480dae4410120e25aac9fd0a39d34f8f500f851b33285375787306633bd7ec3",
          "sha256": "f3d465ce3c328c817a07082066e0747347c65ff2a46908175c194c7d60cfc9b5",
          "sha1": "e82bad8ece70bcd0d8979cb5c1266eb84a1188c7",
          "md5": "b281da68b18c95f719c3d084928129c4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-fabric-1.9.7-dev-shadow.jar",
          "url": "exposure-1.21.1-fabric-1.9.7-dev-shadow.jar",
          "size": 1937158,
          "sha512": "3bf67dbd8f5604b5e68d12ae31a13eefe514feeeb55f34ae701a375b4c544c9210a927e541ea064243f01e8f69192ecdf3a910fb3db7638e86a4d3889565cf5a",
          "sha256": "43634b008b8cbbb934e8c8f43ae42132ea2d9fd27cf97db91af7911b62d816f5",
          "sha1": "181aa756d6e6eda1604ed9f90a8bc270017cb619",
          "md5": "8b989580682200aebafac475f77bba67"
        }
      ]
    }
  ]
}
