{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-forge",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-forge-1.1.0-forge.jar",
          "url": "horseman-forge-1.1.0-forge.jar",
          "size": 261449,
          "sha512": "0f87924bfaaa1aa55376b23122564186f8987fdfe0cd518edba4669cae7f5a5efc70712c45c1c969995b92bd1ff7d19e5f1ac9c1403db246dff171168e43bd1d",
          "sha256": "4eb5088f886c417bd1efc0d02cd0b7da9365e20115c830c7bded2ec0e56a361a",
          "sha1": "6d4d2bf3f7ad4f04712853b2768c54f0c256e427",
          "md5": "87523a1bd55f656d9c25ec5a41059e4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-forge-1.1.0-forge.jar",
          "url": "horseman-forge-1.1.0-forge.jar",
          "size": 261449,
          "sha512": "0f87924bfaaa1aa55376b23122564186f8987fdfe0cd518edba4669cae7f5a5efc70712c45c1c969995b92bd1ff7d19e5f1ac9c1403db246dff171168e43bd1d",
          "sha256": "4eb5088f886c417bd1efc0d02cd0b7da9365e20115c830c7bded2ec0e56a361a",
          "sha1": "6d4d2bf3f7ad4f04712853b2768c54f0c256e427",
          "md5": "87523a1bd55f656d9c25ec5a41059e4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-forge-1.1.0-sources.jar",
          "url": "horseman-forge-1.1.0-sources.jar",
          "size": 43660,
          "sha512": "474d8b52cdad2aee80f75fecc6313f58ef870f8dfb6ab0f110b1c7aa4375c5b3e7e0c2c1024187cb5f352266243b3db5f37932dc44b9b7d0f90ab3c3880251f8",
          "sha256": "7fd8ad73460238fb8683013a067235b831061efe1bdb723b964f3f5cbbfea7b0",
          "sha1": "a6a98d58e56225a3e18f9fb311d455e17740ca6f",
          "md5": "4462f7d02ed6e8ca750e6fafc9c192eb"
        }
      ]
    }
  ]
}
