{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.14.jar",
          "url": "horseman-1.20.1-common-1.3.14.jar",
          "size": 115017,
          "sha512": "11bc0ad2b5795fe67c580751db65cac7efa479d95fd7135c36eddfba428f50e39adb2dbe9a7d9932cdd04e875b57c2156e460cda5808f6d2a19237fbd83dabe7",
          "sha256": "f1b94056eeac09723d8f2119126afe18100525fc38b1b8da43da6966f41e241e",
          "sha1": "dc1402e8d48f154a26dd7bfc824c74d93f8ca0c7",
          "md5": "9036e8ed60149820c9571c0295e8c721"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.14.jar",
          "url": "horseman-1.20.1-common-1.3.14.jar",
          "size": 115017,
          "sha512": "11bc0ad2b5795fe67c580751db65cac7efa479d95fd7135c36eddfba428f50e39adb2dbe9a7d9932cdd04e875b57c2156e460cda5808f6d2a19237fbd83dabe7",
          "sha256": "f1b94056eeac09723d8f2119126afe18100525fc38b1b8da43da6966f41e241e",
          "sha1": "dc1402e8d48f154a26dd7bfc824c74d93f8ca0c7",
          "md5": "9036e8ed60149820c9571c0295e8c721"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.14-sources.jar",
          "url": "horseman-1.20.1-common-1.3.14-sources.jar",
          "size": 69642,
          "sha512": "72c6e8acea51e472b10d091d61f12b7aefec8fd1d2d44f6bc1af13c577c0bce7c2830708337f6a1c29cda7d5ba6d2a8d8a83f8f7912ec65aefa62aea9b902f72",
          "sha256": "748b89b43428ff0e05c6f54fe98fa7310dccc83bc3a4fbcf0abb394a99e028ed",
          "sha1": "f68c3a658e551dd52afca14f6b4d077e356404a4",
          "md5": "b06fe1495919270fac4f89a02e5956e1"
        }
      ]
    }
  ]
}
