{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.6-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.6-forge.jar",
          "size": 682405,
          "sha512": "04ae6d0deb689daa22f6fede6c171092503673899c0fc1f141c9655cbdf28abebccbd88e80123f77ebe218930f4541e74c299cb9ac572beab3cc63bda2e36cd4",
          "sha256": "a7bfd7014665056cefb43e0c37c936924e91fdd0011fd397c4b06ea0b7f0efda",
          "sha1": "45efd386aa6a0f9bdb907031a366ba4da1a1d668",
          "md5": "8d32742e4e3d0b2a40953871744dcb4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.6-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.6-forge.jar",
          "size": 682405,
          "sha512": "04ae6d0deb689daa22f6fede6c171092503673899c0fc1f141c9655cbdf28abebccbd88e80123f77ebe218930f4541e74c299cb9ac572beab3cc63bda2e36cd4",
          "sha256": "a7bfd7014665056cefb43e0c37c936924e91fdd0011fd397c4b06ea0b7f0efda",
          "sha1": "45efd386aa6a0f9bdb907031a366ba4da1a1d668",
          "md5": "8d32742e4e3d0b2a40953871744dcb4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.6-sources.jar",
          "url": "scholar-1.20.1-forge-1.1.6-sources.jar",
          "size": 405007,
          "sha512": "f2759da19ac996385c95585a2fc7544261e8d65790f4669d3b6ac25fea1d10a0044e58ee952f563ac5850817dc5f4e907b3ebaa0e110816028676c474cce45df",
          "sha256": "1b9321313e7f242a6441bc273d1acf292a580bcd7c13a064fa713ac3ce1be903",
          "sha1": "ced25d17a9cf678c25d09cf5748ea428e12bb802",
          "md5": "65f5d2b3e954ebf9d7d8473d76426be6"
        }
      ]
    }
  ]
}
