{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.6.jar",
          "url": "horseman-1.21.1-common-1.3.6.jar",
          "size": 117139,
          "sha512": "88857cfd82796254ddcb797abd9e8aa28bb60c5aeeed7564ceb46f1024c50f539836f1ef070fe48816a6548c2c59fc99d7a67c42bfc7e0c4862222c39c94474f",
          "sha256": "e5b5db337a0aadaf5426a3f1853fb83d1b4b72df729256a25d4d217a42877e26",
          "sha1": "87f73939fbaea449dca8cf3418956e67bc41543e",
          "md5": "82a8b3726082a1e025e02811f635cf99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.6.jar",
          "url": "horseman-1.21.1-common-1.3.6.jar",
          "size": 117139,
          "sha512": "88857cfd82796254ddcb797abd9e8aa28bb60c5aeeed7564ceb46f1024c50f539836f1ef070fe48816a6548c2c59fc99d7a67c42bfc7e0c4862222c39c94474f",
          "sha256": "e5b5db337a0aadaf5426a3f1853fb83d1b4b72df729256a25d4d217a42877e26",
          "sha1": "87f73939fbaea449dca8cf3418956e67bc41543e",
          "md5": "82a8b3726082a1e025e02811f635cf99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.6-sources.jar",
          "url": "horseman-1.21.1-common-1.3.6-sources.jar",
          "size": 69653,
          "sha512": "4545487808809a10277da9049ebec3f70096e4f21a48fdad5313e4b7f30736517137c3f5db1e03a25cad0f6978fdfea53618e1a1a1de30b2b94cc3cbe87daba1",
          "sha256": "fd58fa8a054a8a513c9ce5b952a6a871822aeb2c49b28a519795c3a181c48df5",
          "sha1": "cde730334622d283d9c1b2bca913ecea0a26369a",
          "md5": "a46a3e0264a9c169939b205826896a6d"
        }
      ]
    }
  ]
}
