{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.10-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.10-forge.jar",
          "size": 329047,
          "sha512": "9743eb3451baac7cd46def415f5a072611807009fb2f45fe7f6a5f58e1e9fffa926e685c02efeaca34bf91e1095be06d4b9847a28ab996370a2dbe9ceeac0e51",
          "sha256": "337493373534c95d3e4a15852d5dad0567479e59db0a550f4b0be82f4f4d4949",
          "sha1": "391c54d717faa67410515ce39cfdaef13721b82a",
          "md5": "d40a2c977959695972533c1a925cc984"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.10-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.10-forge.jar",
          "size": 329047,
          "sha512": "9743eb3451baac7cd46def415f5a072611807009fb2f45fe7f6a5f58e1e9fffa926e685c02efeaca34bf91e1095be06d4b9847a28ab996370a2dbe9ceeac0e51",
          "sha256": "337493373534c95d3e4a15852d5dad0567479e59db0a550f4b0be82f4f4d4949",
          "sha1": "391c54d717faa67410515ce39cfdaef13721b82a",
          "md5": "d40a2c977959695972533c1a925cc984"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.10-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.10-sources.jar",
          "size": 88835,
          "sha512": "cb0daf0547618ce6d0537a8313413e816c52e931be31c37f36858dd7dd288c0030aa9bae949a8ecb5d72eaddbf500c4d681a56d28de68191347b49a8e8b78b75",
          "sha256": "46f01f9d67b850509e8810b34b45058bdcd4eace9e83acc95b33bd6e0993cf80",
          "sha1": "a0771dbb388a9080abc0a9b3c602d5cd9df25872",
          "md5": "bf38cf8b28507ab55f3a7ad9f11b3bfb"
        }
      ]
    }
  ]
}
