{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.10-neoforge",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.10-neoforge-api",
          "version": {
            "requires": "26.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.10-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.10-neoforge-1.3.4.jar",
          "size": 178958,
          "sha512": "dbe51ef5494aa0e7685a68096c2d7536be19c05e515045e2eba000e39d769249474162e7709e34658e8ff59d42ee4d45ea48f34b57453b551a6c4784deaaa338",
          "sha256": "39f5e63900334c17eaff7b3b8a75a805bc2494b5f57775d24f579d0d7348792e",
          "sha1": "df974a8e670f597db02691d2f0ad0a3609b691b3",
          "md5": "07d5e823ae6e8cebfc891d378eccdec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.10-neoforge",
          "version": {
            "requires": "26.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.10-neoforge-1.3.4.jar",
          "url": "sootychimneys-1.21.10-neoforge-1.3.4.jar",
          "size": 178958,
          "sha512": "dbe51ef5494aa0e7685a68096c2d7536be19c05e515045e2eba000e39d769249474162e7709e34658e8ff59d42ee4d45ea48f34b57453b551a6c4784deaaa338",
          "sha256": "39f5e63900334c17eaff7b3b8a75a805bc2494b5f57775d24f579d0d7348792e",
          "sha1": "df974a8e670f597db02691d2f0ad0a3609b691b3",
          "md5": "07d5e823ae6e8cebfc891d378eccdec8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.10-neoforge-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.10-neoforge-1.3.4-sources.jar",
          "size": 13710,
          "sha512": "64b4ff66c8999feb256b63ea03347f47ca536b5001b071f28be9e32eb0ec5601c1901cc24322ee2a15d9f5aa7a9ab2aa48766eac1f253c810a770fb25f40d7b6",
          "sha256": "365b39b48537d83e38a0621d6379c71ee47fc7b6a1daaba0ba87ad507b48335b",
          "sha1": "ff71765dc31abb17cf7b93ef1281c1c6f7e6d22a",
          "md5": "747e555b241da6a98dca41104ab12484"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.10-neoforge-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.10-neoforge-1.3.4-dev-shadow.jar",
          "size": 173731,
          "sha512": "26000da3139aae696e5fc12828cfa8c0b6ef2b78637964cef963bdb7e079af5c66fb224d5027eb6aa4a2a1c7940c8182dd311d18dcad770e7773f878b1be6181",
          "sha256": "393ee5f434f58b788003b3c3aadba35c06ccf93546eda8858540a4a4248971f8",
          "sha1": "6e66372587192786230279359dcdec9704ee6388",
          "md5": "0cc7f2c4bc1602c6e422ec2305b65dbf"
        }
      ]
    }
  ]
}
