{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-26.1.1-fabric",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.4.jar",
          "url": "horseman-26.1.1-fabric-1.7.4.jar",
          "size": 278776,
          "sha512": "a0a6234a662ebd697332ef6817b679c9b8175ffe08b69336f20f36eee72a908c9fac27d03d5a5b412d0cd0e7cda83f58dff6d26a31f99f5b61e233d02b8d4dd3",
          "sha256": "beec9e332f4fce9912ac47e1a7811a4682e31597fd0f7635d8b04b0eeb46b9b1",
          "sha1": "fe75a0a79c16989e36f9d0dbc45bbb69b53476e8",
          "md5": "cd910be33508c266481557a6589e4c84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.4.jar",
          "url": "horseman-26.1.1-fabric-1.7.4.jar",
          "size": 278776,
          "sha512": "a0a6234a662ebd697332ef6817b679c9b8175ffe08b69336f20f36eee72a908c9fac27d03d5a5b412d0cd0e7cda83f58dff6d26a31f99f5b61e233d02b8d4dd3",
          "sha256": "beec9e332f4fce9912ac47e1a7811a4682e31597fd0f7635d8b04b0eeb46b9b1",
          "sha1": "fe75a0a79c16989e36f9d0dbc45bbb69b53476e8",
          "md5": "cd910be33508c266481557a6589e4c84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.4-sources.jar",
          "url": "horseman-26.1.1-fabric-1.7.4-sources.jar",
          "size": 188823,
          "sha512": "1003393922172f6669d1ee7b5a64c4c398a57c96eab494d542b3ba0123b64fe614b1694565638cb680a1dba036d83ec9c85175ca37563f2cc7802f9d6c70017b",
          "sha256": "3d830e219daf2fa05006d090ecf5fd50b59d26ce43046b03a137569856de2d59",
          "sha1": "ba75fb7c21e38f0480d5370006e7426c5ccf0821",
          "md5": "732bb633e10f484adce18f696d60f05b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.4.jar",
          "url": "horseman-26.1.1-fabric-1.7.4.jar",
          "size": 278776,
          "sha512": "a0a6234a662ebd697332ef6817b679c9b8175ffe08b69336f20f36eee72a908c9fac27d03d5a5b412d0cd0e7cda83f58dff6d26a31f99f5b61e233d02b8d4dd3",
          "sha256": "beec9e332f4fce9912ac47e1a7811a4682e31597fd0f7635d8b04b0eeb46b9b1",
          "sha1": "fe75a0a79c16989e36f9d0dbc45bbb69b53476e8",
          "md5": "cd910be33508c266481557a6589e4c84"
        }
      ]
    }
  ]
}
