{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_polaroid",
    "module": "exposure_polaroid-1.20.1-fabric",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-fabric-1.1.3.jar",
          "url": "exposure_polaroid-1.20.1-fabric-1.1.3.jar",
          "size": 153976,
          "sha512": "472c5a35e821e8b36a718a28488ee5f8ff8988ea7b1d977dcd505e182342c6d5d039a2532e7745238ad714c2ef4f2254a8d708559803519213690e3528310038",
          "sha256": "dc68c11a9b53a01106f76f5660c559baeddd2193e6f71b5c6f42965a63f865ac",
          "sha1": "391b143299748b77abd5ec5713393efbff2fb633",
          "md5": "6f1357426043a08245e0ff14e99ea2a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-1.20.1-fabric",
          "version": {
            "requires": "1.9.14"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-fabric-1.1.3.jar",
          "url": "exposure_polaroid-1.20.1-fabric-1.1.3.jar",
          "size": 153976,
          "sha512": "472c5a35e821e8b36a718a28488ee5f8ff8988ea7b1d977dcd505e182342c6d5d039a2532e7745238ad714c2ef4f2254a8d708559803519213690e3528310038",
          "sha256": "dc68c11a9b53a01106f76f5660c559baeddd2193e6f71b5c6f42965a63f865ac",
          "sha1": "391b143299748b77abd5ec5713393efbff2fb633",
          "md5": "6f1357426043a08245e0ff14e99ea2a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-fabric-1.1.3-sources.jar",
          "url": "exposure_polaroid-1.20.1-fabric-1.1.3-sources.jar",
          "size": 6021,
          "sha512": "78dd95835c1536e60d3a98059cbdab40c287a5c3543c6a7614651f90fbf2d909ff52281bc8c6cc4b2f7da2ca88b81e7771ea69573448e13f4fa7b0493443c8a9",
          "sha256": "41cd3be07d485924b6e2501c77323b4bda6e4093205e743829c6a613b8a95142",
          "sha1": "61f031ca070b62ca062d94ff014c9326fa83986e",
          "md5": "4675d4474ede299bf955505860377d50"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.20.1-fabric-1.1.3-dev-shadow.jar",
          "url": "exposure_polaroid-1.20.1-fabric-1.1.3-dev-shadow.jar",
          "size": 150953,
          "sha512": "9906dba0f2cbe5131b3ecfb77c32b349509e7860a17fa7097d65618383b6029f37c371a5520a2c82239c3abe379deb11e48db67f03e2f6a4283800708054045d",
          "sha256": "0ac4efa2cfd1bc449f0b4574333032f10b27983f3ac90739c129c0397039cd9a",
          "sha1": "bc16c2bec51d08fbbe61ed11f38ccd07de45da6b",
          "md5": "8efabf9be1b385f459693c442dfe252e"
        }
      ]
    }
  ]
}
