{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.5.10.jar",
          "url": "horseman-1.21.1-common-1.5.10.jar",
          "size": 241444,
          "sha512": "d2499d61bbf6bbea38f47daf0cc0be5aff9c59ec7f12bab2d2ba1892d38d54824c1332c2321bf0be2bd047d8db4e9975037f682634926caef00834f3d8437e20",
          "sha256": "2ad62bf05c8323db0a93cd7fef3c2478f82c757e11f2c44b54d50075af9c1734",
          "sha1": "e31e9273a96dc341d89c3b628122917de6d7616f",
          "md5": "8fb2f90f64b13cc57342cc21c0646af6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.5.10.jar",
          "url": "horseman-1.21.1-common-1.5.10.jar",
          "size": 241444,
          "sha512": "d2499d61bbf6bbea38f47daf0cc0be5aff9c59ec7f12bab2d2ba1892d38d54824c1332c2321bf0be2bd047d8db4e9975037f682634926caef00834f3d8437e20",
          "sha256": "2ad62bf05c8323db0a93cd7fef3c2478f82c757e11f2c44b54d50075af9c1734",
          "sha1": "e31e9273a96dc341d89c3b628122917de6d7616f",
          "md5": "8fb2f90f64b13cc57342cc21c0646af6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.5.10-sources.jar",
          "url": "horseman-1.21.1-common-1.5.10-sources.jar",
          "size": 158134,
          "sha512": "fd181d8343c3632541ec94d52ef2c9d379baf4c6b3b0ff913aadb16c53ee7ee3b05af5641fba364a0bc677a97e2b4805f63488109c544f274fe3cf8ebd1a48f3",
          "sha256": "79f46cb9dccaaff2c1fdac360bc5195693b6bcc738edc4b365bf7b86a434a747",
          "sha1": "c85e6150a38c6fd5dd3d9c67d42fec15af8570a0",
          "md5": "77cdae971200877884d1d8f1547c2899"
        }
      ]
    }
  ]
}
