{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.5-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.5-fabric.jar",
          "size": 668221,
          "sha512": "4efdf00787d12e60a9ace0db41f1ce276c128e0e7a3691fd7318825e167f404b107ebf23451054fed45528be7e1acaf250e61282816fcbf4021a49e99ecbf574",
          "sha256": "62d09971214113adf160f36a6bfe5de8c4b06133914e780c4e89f9f2f538786f",
          "sha1": "7987058d5dad261d9b49a59cd734e34c554d88bf",
          "md5": "4609dab27f921f38f3ddbff0f548f879"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.5-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.5-fabric.jar",
          "size": 668221,
          "sha512": "4efdf00787d12e60a9ace0db41f1ce276c128e0e7a3691fd7318825e167f404b107ebf23451054fed45528be7e1acaf250e61282816fcbf4021a49e99ecbf574",
          "sha256": "62d09971214113adf160f36a6bfe5de8c4b06133914e780c4e89f9f2f538786f",
          "sha1": "7987058d5dad261d9b49a59cd734e34c554d88bf",
          "md5": "4609dab27f921f38f3ddbff0f548f879"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.5-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.5-sources.jar",
          "size": 396623,
          "sha512": "6f8791474053a6c693b22374119622831e1a8cf2a1fb0f2ffbfe69dc2148401a416e40ce7d85194266cb44650f862c3d819019cc4ece8dada11b86de7d7a3b9f",
          "sha256": "583dc77b475c522086ed2c40be43236a6ef7e094fa81346f121bb3b5ddfc216f",
          "sha1": "ec26590047675246b60edfd133affd65baa8e69d",
          "md5": "6b22f69a9a2cdfd8ca3adb1382d12a57"
        }
      ]
    }
  ]
}
