{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.3.jar",
          "url": "horseman-1.21.1-neoforge-1.3.3.jar",
          "size": 318703,
          "sha512": "232ee6831c3e40e637104284571dccd63afe43b3a707ce2770390ede86efa2254add8bbb934429c1260b63087d1bcf8ec55b2468119e8139e197a34f554130b1",
          "sha256": "7f97ffedbf80307e8566c60a0c4b8acd45fa1f9eef6fadf8797e02f82eaa023b",
          "sha1": "39f45df7e4637b8cbceb6cd73cf0cd90a0a7db9d",
          "md5": "e86ac2509aa6dd4273a6855efadd2c24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "kLyBcoTF"
          }
        },
        {
          "group": "curse.maven",
          "module": "allurement-438003",
          "version": {
            "requires": "6449871"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "neaMfufC"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.3.jar",
          "url": "horseman-1.21.1-neoforge-1.3.3.jar",
          "size": 318703,
          "sha512": "232ee6831c3e40e637104284571dccd63afe43b3a707ce2770390ede86efa2254add8bbb934429c1260b63087d1bcf8ec55b2468119e8139e197a34f554130b1",
          "sha256": "7f97ffedbf80307e8566c60a0c4b8acd45fa1f9eef6fadf8797e02f82eaa023b",
          "sha1": "39f45df7e4637b8cbceb6cd73cf0cd90a0a7db9d",
          "md5": "e86ac2509aa6dd4273a6855efadd2c24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.3-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.3-sources.jar",
          "size": 13733,
          "sha512": "55a7996ea35677a8c9ad7304a556c67b7263339e9e2a795de9cdd9d9ef50267bd79d200cc18b263651dae202ed493e3c4dbf5ddb35c28682a3c47f0b2382d101",
          "sha256": "321f8e291e398b955a7c1fa69c75d64043b6b2626506cfdc8181f210680f3bef",
          "sha1": "ae1477f11616ccda74f7d84371e11270d063ed9f",
          "md5": "0aa52825b5cc6f12f5d9e42e8b36201e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.3-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.3-dev-shadow.jar",
          "size": 133629,
          "sha512": "610c2ecef8937536b65bd2f81c6aebf643df060c502d0c0b8572cdc9ae1ba4fc0e4ea81d30fe2a98efc7c6e39adcad5afe52e8a09c37aa46c37370765a0b8eb8",
          "sha256": "ad2d3388030d353cb8632a86348d72a097fb1835463968887a3636f72166efa4",
          "sha1": "0cadd99ce5ffe4f4cb96595a0b7adfb4aa24ec4b",
          "md5": "f59b0b7602586b553007e26d1b42046f"
        }
      ]
    }
  ]
}
