{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-common",
    "version": "1.21.1-1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.21.1-1.3.2.jar",
          "url": "sootychimneys-common-1.21.1-1.3.2.jar",
          "size": 160432,
          "sha512": "f81c9b017bcc3187737217236ae4928c78a16c722bc9a5ede3d111aae0ea4498dc3953a00d86eef25bfae3dfeba7b86adf73433462e79a1a90234e788e77c17b",
          "sha256": "aabf8d0bd253f672a4381e7d81e72559851630a30ea53b0805e82e24a393a97f",
          "sha1": "bc2d75fb5bd524cfc26a663edb69730abe5f5401",
          "md5": "1be0d7c05ed739caa86a2b58247e9b8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-common-1.21.1-1.3.2.jar",
          "url": "sootychimneys-common-1.21.1-1.3.2.jar",
          "size": 160432,
          "sha512": "f81c9b017bcc3187737217236ae4928c78a16c722bc9a5ede3d111aae0ea4498dc3953a00d86eef25bfae3dfeba7b86adf73433462e79a1a90234e788e77c17b",
          "sha256": "aabf8d0bd253f672a4381e7d81e72559851630a30ea53b0805e82e24a393a97f",
          "sha1": "bc2d75fb5bd524cfc26a663edb69730abe5f5401",
          "md5": "1be0d7c05ed739caa86a2b58247e9b8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-common-1.21.1-1.3.2-sources.jar",
          "url": "sootychimneys-common-1.21.1-1.3.2-sources.jar",
          "size": 116416,
          "sha512": "e89a775f999e89593ffb82d6ef38d1c6985ae3dd179c80fa26ecffb97774031551940c3c3326a7eeb5425be2ffa35eba70eedd445f8757b08ddfe10ee4e4eff5",
          "sha256": "35e9dd8ae5b1f792fbe16f5a301582970925fad42de80fe83b925c04fa879fc3",
          "sha1": "27a8feb89721920a36a7c86f15ba1b55a2cfadbf",
          "md5": "ea5da3a427b5fc338599c9e7649990e3"
        }
      ]
    }
  ]
}
