{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.4.jar",
          "url": "horseman-1.20.1-common-1.3.4.jar",
          "size": 121309,
          "sha512": "371a7b795990f86560f4dd73abb7dc0d8c748a45e243e671f1bcc5f69f187f28245fbab4f15c204f967e5c825d979c9837b139c7f5706b3c88e295b8a119264b",
          "sha256": "4af3f21c2fba388e4aa5e3817cd653522f06b06e8f29b071fec8c7a0beaa5411",
          "sha1": "c0867c7a5902e81317f05f33b57b49086397a7d0",
          "md5": "4350a64f115e4302a634d801e45045eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.4.jar",
          "url": "horseman-1.20.1-common-1.3.4.jar",
          "size": 121309,
          "sha512": "371a7b795990f86560f4dd73abb7dc0d8c748a45e243e671f1bcc5f69f187f28245fbab4f15c204f967e5c825d979c9837b139c7f5706b3c88e295b8a119264b",
          "sha256": "4af3f21c2fba388e4aa5e3817cd653522f06b06e8f29b071fec8c7a0beaa5411",
          "sha1": "c0867c7a5902e81317f05f33b57b49086397a7d0",
          "md5": "4350a64f115e4302a634d801e45045eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.4-sources.jar",
          "url": "horseman-1.20.1-common-1.3.4-sources.jar",
          "size": 71412,
          "sha512": "d9525c4eaa474ae50bde366c8300821f4d0b16ed5f2a36b79e6dea9aa31453e1635b90e254fc2718a6769be8addb14b756ee3072e19555efed123c38e586d4d9",
          "sha256": "af7482299024a6cfa1737822e4f954aa860fb7d4f8ebf1a608121706cea3de0f",
          "sha1": "3d409fd768b131372af1dbc4ef8191bc30b1385a",
          "md5": "44da33131b0c68159318f8cac631cd35"
        }
      ]
    }
  ]
}
