{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-neoforge",
    "version": "1.21.1-1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.21.1-1.3.2.jar",
          "url": "sootychimneys-neoforge-1.21.1-1.3.2.jar",
          "size": 172137,
          "sha512": "547712fa3475ed9c6218d8bdde11dccd77ff2fc53124fe4a2180d1ed173b25ea803c953133799dc1f32d3b24083eb79ef8769ba8c32ca7c9e27ca3e5cc71a64d",
          "sha256": "6cf160f83bad0125b505bca20c43e142fe13ba591edb61c056086535ecd9c1e9",
          "sha1": "77baa0640cb0c5de365f4317c929e109624497b7",
          "md5": "807345092baa8f2a127aa0f8ca1c50a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.0-4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.0-9"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-neoforge-1.21.1-1.3.2.jar",
          "url": "sootychimneys-neoforge-1.21.1-1.3.2.jar",
          "size": 172137,
          "sha512": "547712fa3475ed9c6218d8bdde11dccd77ff2fc53124fe4a2180d1ed173b25ea803c953133799dc1f32d3b24083eb79ef8769ba8c32ca7c9e27ca3e5cc71a64d",
          "sha256": "6cf160f83bad0125b505bca20c43e142fe13ba591edb61c056086535ecd9c1e9",
          "sha1": "77baa0640cb0c5de365f4317c929e109624497b7",
          "md5": "807345092baa8f2a127aa0f8ca1c50a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.21.1-1.3.2-sources.jar",
          "url": "sootychimneys-neoforge-1.21.1-1.3.2-sources.jar",
          "size": 11614,
          "sha512": "70484fa7ceec94c304b3235d894b6ae345c2ef5f938a00f826104bf47b42e15feed1f6aa202155b236f75de609836fb0559af55ae4aa843c4c3c6c748e8084c3",
          "sha256": "fd54407953ebc1dbdd2cf577d31a32143eee5af3af7aa0e04145c0966f2df4a4",
          "sha1": "da3a229751ba875cf110715850125b1c6c5b6915",
          "md5": "a1022f706dff63f93f310447113df76c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-neoforge-1.21.1-1.3.2-dev-shadow.jar",
          "url": "sootychimneys-neoforge-1.21.1-1.3.2-dev-shadow.jar",
          "size": 167183,
          "sha512": "c0fdcad64a1c0ffcb19739966919cd77e15c4a7f11f9c7bc391137314fc96a67ba851eb6cdd7eb371558c83749a89f4b95407879b23353784e8f1bc6741c7690",
          "sha256": "cc103e0827da19aa1a2c58317ff95ab752608e01f71bdb78b21a177d83078c02",
          "sha1": "343e663c829b9143949a8cf545058547fede826e",
          "md5": "01e3e235369bf0570a2d30f5e18c48fe"
        }
      ]
    }
  ]
}
