{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.4-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.4-fabric.jar",
          "size": 321535,
          "sha512": "5e16d8bb28e6a1ef166d5b40b0475ec172b28808690bd97cd37ae76e58d2a16e181763b40f69c1e564da95133ea28b6cb0df78e9f4d43f63bae899d8611fb9e1",
          "sha256": "b1214d71fd79d7d616a127b4b28de91eaeee65309fc7ec076de3be760149251c",
          "sha1": "66d76cb5e799679665104a55278a9ad7670c44e1",
          "md5": "9e109b417f0c429412600fc98b8150b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.4-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.4-fabric.jar",
          "size": 321535,
          "sha512": "5e16d8bb28e6a1ef166d5b40b0475ec172b28808690bd97cd37ae76e58d2a16e181763b40f69c1e564da95133ea28b6cb0df78e9f4d43f63bae899d8611fb9e1",
          "sha256": "b1214d71fd79d7d616a127b4b28de91eaeee65309fc7ec076de3be760149251c",
          "sha1": "66d76cb5e799679665104a55278a9ad7670c44e1",
          "md5": "9e109b417f0c429412600fc98b8150b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.4-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.4-sources.jar",
          "size": 84037,
          "sha512": "8160ad3d93beda477da08f21c0b74394b96d1c9a91e5a8a36c5531ca04b0967c458aabcff813e8fbfedc06534fa8959ffeee85b1ea9c5002fd3aa22bcc805e9e",
          "sha256": "d8fa300c8c20b51708c754f86b6dc090780d8c679cdc3085fe285922683a7e44",
          "sha1": "b2325e4e6360d0f988a271f03d51f410f4453f1c",
          "md5": "23e327b447463f745b6489646a3f84c9"
        }
      ]
    }
  ]
}
