{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.6-fabric.jar",
          "url": "exposure-fabric-1.7.6-fabric.jar",
          "size": 1298794,
          "sha512": "3383885123e3bd60e2de31585735a6773d1d7afe178e908c49732fff0b6608f68b5db2eb7807ab2097ccebf5fa9c6170f1a773584597d3ec1e3296e43dfeb86d",
          "sha256": "91e10c747225844ff07a653c1fde7fd29dff8e8ab970ce9316971ceea2220b2f",
          "sha1": "7e7831f8546b4529c4d4a43dcc2b718c95f92d4b",
          "md5": "6fbe2b3f7ff6eeb4319723cb74abb967"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.6-fabric.jar",
          "url": "exposure-fabric-1.7.6-fabric.jar",
          "size": 1298794,
          "sha512": "3383885123e3bd60e2de31585735a6773d1d7afe178e908c49732fff0b6608f68b5db2eb7807ab2097ccebf5fa9c6170f1a773584597d3ec1e3296e43dfeb86d",
          "sha256": "91e10c747225844ff07a653c1fde7fd29dff8e8ab970ce9316971ceea2220b2f",
          "sha1": "7e7831f8546b4529c4d4a43dcc2b718c95f92d4b",
          "md5": "6fbe2b3f7ff6eeb4319723cb74abb967"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.6-sources.jar",
          "url": "exposure-fabric-1.7.6-sources.jar",
          "size": 943994,
          "sha512": "f9004211390bf3c0d79b11eb72a2f1394114e7ca7f888fe22ab972204b6df1bbcc4d6ac9979185ed91d977d3e51010189eca40e6f70285a05368ee0af743a8bc",
          "sha256": "234d74b28d158b484695d2e8c178461f3e28931d979790b9186e2971df5a4352",
          "sha1": "7fb42ce38f94e111012c175dfdf8d77dde2b83b3",
          "md5": "88144b518887da7e8578dafa90210cac"
        }
      ]
    }
  ]
}
