{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot11.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot11.jar",
          "size": 2111892,
          "sha512": "985559a880e72b1b2593aa44cb7492b1543607bc8718d1868942386826c9aba297ec0de456be110afc58cbd8ba6c95df2bfc1c495068c41a4cee4aedc8c0193e",
          "sha256": "80b2514603bba865d83d203afff50548d40fc07dde21cf2a7c4ff580bb7aa81d",
          "sha1": "ce015ab944bd6aa0d8917502f2c8677ac5f637a6",
          "md5": "04bf8a07a196482aa9c7d14b05adc147"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot11.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot11.jar",
          "size": 2111892,
          "sha512": "985559a880e72b1b2593aa44cb7492b1543607bc8718d1868942386826c9aba297ec0de456be110afc58cbd8ba6c95df2bfc1c495068c41a4cee4aedc8c0193e",
          "sha256": "80b2514603bba865d83d203afff50548d40fc07dde21cf2a7c4ff580bb7aa81d",
          "sha1": "ce015ab944bd6aa0d8917502f2c8677ac5f637a6",
          "md5": "04bf8a07a196482aa9c7d14b05adc147"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot11-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot11-sources.jar",
          "size": 37636,
          "sha512": "96f7e68a61bcbe3bb048fdfcdd458231f99da4ea82a4a30b7bd7a06fd5bd88c4a1dd6f2074680867095ee6b50aaff9abd903ba190b9d84e575052516dccef778",
          "sha256": "65bb83ff885a7da24d15fe5818777308eec17fad6c9808447cc012f1ac7507a0",
          "sha1": "6a00ca381bd7ebbe62901889729be989ab91d9b9",
          "md5": "1d0998e93c62059c8a8fc973bde807f2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot11-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot11-dev-shadow.jar",
          "size": 1894764,
          "sha512": "70ac32977d46cc208003ced46a514798d4bf7719657d060c7e8fe888e91518a7f29aa6c9d8e37c5560368480d160982d5eb49415d67bcd5fff4213d70b6460e8",
          "sha256": "43b36a73c8bd05c809d5d6e3764676774590e4c06647bd147f3fa0835a5aae0d",
          "sha1": "10772d32bad22e4ff70afc5608a1a5f591131e09",
          "md5": "e6a59780d1f3786f924eef4e512b9193"
        }
      ]
    }
  ]
}
