{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot2.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot2.jar",
          "size": 2081533,
          "sha512": "7f4e3cc65f61f2190192f23b5b449905eca61b2a21619951d18df6c0ac348dd318511cad5c09816d19e4826b409c9e96f4b6170951b737c3cb44518d08872903",
          "sha256": "b232448e5e82c792f0a13dd8b018c394a83abc04e9a28dbba7c2494a6a5a560f",
          "sha1": "055cf96a112c69cb33a16f08e8de96b917e4c853",
          "md5": "0abb6a3fe16a39350a1391f2001e3712"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot2.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot2.jar",
          "size": 2081533,
          "sha512": "7f4e3cc65f61f2190192f23b5b449905eca61b2a21619951d18df6c0ac348dd318511cad5c09816d19e4826b409c9e96f4b6170951b737c3cb44518d08872903",
          "sha256": "b232448e5e82c792f0a13dd8b018c394a83abc04e9a28dbba7c2494a6a5a560f",
          "sha1": "055cf96a112c69cb33a16f08e8de96b917e4c853",
          "md5": "0abb6a3fe16a39350a1391f2001e3712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot2-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot2-sources.jar",
          "size": 37636,
          "sha512": "5120d49e23a4851c369d176624edb3d0486554d7d3e05365e5d56adbc03b13da21faceb11bd814c6e9d9450bee5633f37c60ba8a8856101b3db8ef14638ae198",
          "sha256": "2fd9921a2b473efd80a84be87feba865ef64e240a54aa8cd45ee52e189492d47",
          "sha1": "a2a85e59fb793ce7e11a97e971a417d9bfa1f348",
          "md5": "8dd6bc3660a45822e1ae007b08b6cbb4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot2-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot2-dev-shadow.jar",
          "size": 1865115,
          "sha512": "f30b956bf10567c271aed0b1675a50d511b249e11890579414c5afb8c8af6084f42ecda0eb4e25c644f492ea99a427de6f35e0c000fe7847dee2f943971b42fa",
          "sha256": "6476fd8d44fd2c0477612fbcdfcfb2af236c0783b4ce9fc9b00df86c9d1771b7",
          "sha1": "e9d0569dad7a730c9c6420b4377732730387d426",
          "md5": "b9f3fbd71f1a18fd0981b8b1d66c06ef"
        }
      ]
    }
  ]
}
