{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.6-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.6-fabric.jar",
          "size": 670395,
          "sha512": "18714cd7316c2125aebaf93dddb38065d073b2ed18c7c9f254769c9fdf0e059ab64e52a154c0ab5b46616256097ac3a0c4b43bae10b75d1e744a5078e9c6986d",
          "sha256": "c5c0ad23b4adce1562b2b0cbe24f13a81b04975245447c619bdf169e05ef4edc",
          "sha1": "06e79690c78677f1ce89cb5baccd7ca006bb039d",
          "md5": "4e9caf168a76f92dc0633ceacf705771"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.6-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.6-fabric.jar",
          "size": 670395,
          "sha512": "18714cd7316c2125aebaf93dddb38065d073b2ed18c7c9f254769c9fdf0e059ab64e52a154c0ab5b46616256097ac3a0c4b43bae10b75d1e744a5078e9c6986d",
          "sha256": "c5c0ad23b4adce1562b2b0cbe24f13a81b04975245447c619bdf169e05ef4edc",
          "sha1": "06e79690c78677f1ce89cb5baccd7ca006bb039d",
          "md5": "4e9caf168a76f92dc0633ceacf705771"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.6-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.6-sources.jar",
          "size": 398953,
          "sha512": "e69aebc642d2b2e6362eb9ab43a17e3ae8fe43617318e2d432d415f63949ce50190124404ff56aea384002a79e6345d8f9d777343cc8d551af2b3d776d5ac920",
          "sha256": "6b35e65570580bb39685a71955d0b2279b9017efcad629d9a36f52d1acea09f7",
          "sha1": "8d1270c8094f1dfd269bddfdc940e01e4142dd52",
          "md5": "f8b9b5404035f28ff11bd28c86758834"
        }
      ]
    }
  ]
}
