{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.5.jar",
          "url": "horseman-1.21.1-fabric-1.3.5.jar",
          "size": 138823,
          "sha512": "8791e78268e004c7d7fc06cc2d16b2c33374cc12b0c3d8da3e134cafe5ea992296f498eab658811c3edd98da4b51b15f4f52a55b3e4076f999a5e54107b65581",
          "sha256": "7d1f05d7c311a7dd6e7bd38bba072569d34ac3768238c67e07eeca5cfc674fe4",
          "sha1": "0f57b0f743bf3466e833f26efcfeb935517c8b9e",
          "md5": "72061bb3eb5415dcefb561f32866ed3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.5.jar",
          "url": "horseman-1.21.1-fabric-1.3.5.jar",
          "size": 138823,
          "sha512": "8791e78268e004c7d7fc06cc2d16b2c33374cc12b0c3d8da3e134cafe5ea992296f498eab658811c3edd98da4b51b15f4f52a55b3e4076f999a5e54107b65581",
          "sha256": "7d1f05d7c311a7dd6e7bd38bba072569d34ac3768238c67e07eeca5cfc674fe4",
          "sha1": "0f57b0f743bf3466e833f26efcfeb935517c8b9e",
          "md5": "72061bb3eb5415dcefb561f32866ed3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.5-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.5-sources.jar",
          "size": 14731,
          "sha512": "cc1be9c4e07f99e78f4bb0d7a5bd6b18fa32375ee8460f0ebab16dd9ba9c622bcaedc4b812f79ca406812a2acdfe928c0dfe6340449235e71e82adf808278ced",
          "sha256": "eea321652cc585ecd702e19c417be904eb1511541d7e941250ed53187cd9d3b4",
          "sha1": "5ced112bf7142cb0e1257519334928123c0d629a",
          "md5": "699606410bb684266c96ad2b6ce4a078"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.5-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.5-dev-shadow.jar",
          "size": 137418,
          "sha512": "8b9bca131cda786815cd283829cbcb9b9abb22231784c5dd5e283338f468d1ac900750ffc7fd5172b6509e057eb55b571925c200cfb07726321731e2dcf9ffb3",
          "sha256": "43273d70a1cc1d094f4165aadce247704df647980f4fd916b0296da3eff0b1be",
          "sha1": "2930944a3b083759c435ff8601c6828c482041f8",
          "md5": "c051dcf6b02dfd0be7de8f7f777cec62"
        }
      ]
    }
  ]
}
