{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.12.jar",
          "url": "horseman-1.20.1-common-1.3.12.jar",
          "size": 115198,
          "sha512": "d1ca0bf74031ab0341274a5060a7ca0a697523d64d9c451b56e42eac434fc02e882dd3ff0b0379c26972b3e528ddd51b5e0826a6ffa85c3ecc9aa40524674cbb",
          "sha256": "f5d7c24f7706f8f42ac7015b687eb933cfac206af85feb5db6e61452691e5c1d",
          "sha1": "c79e579831cfb3122d48f5be39197901a7def94d",
          "md5": "f49c28f96345b31de20bb104feedee97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.12.jar",
          "url": "horseman-1.20.1-common-1.3.12.jar",
          "size": 115198,
          "sha512": "d1ca0bf74031ab0341274a5060a7ca0a697523d64d9c451b56e42eac434fc02e882dd3ff0b0379c26972b3e528ddd51b5e0826a6ffa85c3ecc9aa40524674cbb",
          "sha256": "f5d7c24f7706f8f42ac7015b687eb933cfac206af85feb5db6e61452691e5c1d",
          "sha1": "c79e579831cfb3122d48f5be39197901a7def94d",
          "md5": "f49c28f96345b31de20bb104feedee97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.12-sources.jar",
          "url": "horseman-1.20.1-common-1.3.12-sources.jar",
          "size": 69733,
          "sha512": "f09b22f692833c653dae504601d4d78d71b87a0e16a9dd95c2d4c9f887d8308a83140fa2d8c8183f7bc6d566eb7158b45ec46479f1736146fed2c9c4fb662da6",
          "sha256": "4ec0666907b025de7515c9e3043e496e7889987c844f4ab4d08e4fed7052366c",
          "sha1": "16a2a9cb39e5ae10c6e56cd4dabe620b70073c79",
          "md5": "4d0f5177b7cc67bab846e7ec79ebd0ef"
        }
      ]
    }
  ]
}
