{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-26.1.1-common",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-common-api",
          "version": {
            "requires": "29.3.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.2.jar",
          "url": "horseman-26.1.1-common-1.7.2.jar",
          "size": 255549,
          "sha512": "5ebeb46a80fe77520ce1233340ec48c1ef1511242ede61896c5e64504e689cd4f2e4d043b2c2e0662c9bc0631d8203ad05603fcf101b0bfe041437093b080dbc",
          "sha256": "21e7e7803b05099a42586f12c1935359081e269d4a12329835f542e25b90cc42",
          "sha1": "8f973d16b5785c1b30392d09142e7211c7d63392",
          "md5": "5cab86695c481b4f0dbb2ee3d3230c48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.2.jar",
          "url": "horseman-26.1.1-common-1.7.2.jar",
          "size": 255549,
          "sha512": "5ebeb46a80fe77520ce1233340ec48c1ef1511242ede61896c5e64504e689cd4f2e4d043b2c2e0662c9bc0631d8203ad05603fcf101b0bfe041437093b080dbc",
          "sha256": "21e7e7803b05099a42586f12c1935359081e269d4a12329835f542e25b90cc42",
          "sha1": "8f973d16b5785c1b30392d09142e7211c7d63392",
          "md5": "5cab86695c481b4f0dbb2ee3d3230c48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.2-sources.jar",
          "url": "horseman-26.1.1-common-1.7.2-sources.jar",
          "size": 177504,
          "sha512": "9d91bdd673bd273eb6e19465c3aeaf1137b2bc72ecc728a1fd561625fe031bd4008c44d339bf64091d175e566b820ef955d6da598e5276c11890ecf1aa0e1156",
          "sha256": "cdf83f09b7980224704c9666a89e27011222d2cc8270684e1e4976585de96e80",
          "sha1": "520d47b3ba835ebe63c382dbfd39262f4322b8e6",
          "md5": "3ea2097b60318ef813963776ca59e58f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.2.jar",
          "url": "horseman-26.1.1-common-1.7.2.jar",
          "size": 255549,
          "sha512": "5ebeb46a80fe77520ce1233340ec48c1ef1511242ede61896c5e64504e689cd4f2e4d043b2c2e0662c9bc0631d8203ad05603fcf101b0bfe041437093b080dbc",
          "sha256": "21e7e7803b05099a42586f12c1935359081e269d4a12329835f542e25b90cc42",
          "sha1": "8f973d16b5785c1b30392d09142e7211c7d63392",
          "md5": "5cab86695c481b4f0dbb2ee3d3230c48"
        }
      ]
    }
  ]
}
