{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.1.jar",
          "url": "horseman-1.20.1-common-1.3.1.jar",
          "size": 119582,
          "sha512": "d304dc416b85dc5a458bce6479ed472086256f294d3a4b2fc6fceb3b9beee80c8f797edea9cba925856fba7171d7350778ce0ccea7ab722e513b823747c76767",
          "sha256": "31787a11916c5e51f3f245689bdfa2d43f269bf39fd6b688a918478f6e6effe8",
          "sha1": "6b737fda021acf0ad92f0cf702a702259f98b4aa",
          "md5": "1941c2fd4391e5c560526e7a5561ebd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.1.jar",
          "url": "horseman-1.20.1-common-1.3.1.jar",
          "size": 119582,
          "sha512": "d304dc416b85dc5a458bce6479ed472086256f294d3a4b2fc6fceb3b9beee80c8f797edea9cba925856fba7171d7350778ce0ccea7ab722e513b823747c76767",
          "sha256": "31787a11916c5e51f3f245689bdfa2d43f269bf39fd6b688a918478f6e6effe8",
          "sha1": "6b737fda021acf0ad92f0cf702a702259f98b4aa",
          "md5": "1941c2fd4391e5c560526e7a5561ebd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.1-sources.jar",
          "url": "horseman-1.20.1-common-1.3.1-sources.jar",
          "size": 70210,
          "sha512": "673a4b2c2ca4b9e11f4e360c8e0d5ee11daa5f34fa587fb265e3c08ff0b9fbf431b466ed40195d398e9da35c6d350706af490907bcfe1a067422d78a6bf30e21",
          "sha256": "9df5dfab78b8ee04155f39b2dccf3b30de14ae62a1b600df9b72970f4ba8df47",
          "sha1": "91d639cef232265ad572887d04c9e89941a80f4a",
          "md5": "c1f57d9b7ffeed4ccdfc30c34bcba5ef"
        }
      ]
    }
  ]
}
