{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.11.jar",
          "url": "exposure-1.21.1-neoforge-1.9.11.jar",
          "size": 2179406,
          "sha512": "ee07ae723e05dfa756ff375c88d8d71cd44f3fb854d37766507ab4b84d83a3fc5dd41929ce3c613a512a319be33bf28a256f8bd26dd021697f209e0c42c89f10",
          "sha256": "35339f608762d0c886d2cb9a21f6eb8ca9d56ff9a9701cc4bf9c6f8000bba20e",
          "sha1": "41b14add4442c0e155e2755d4bcfdfd644a39b55",
          "md5": "4f3dc8a2f8b31744fa881c9fd209d7d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.11.jar",
          "url": "exposure-1.21.1-neoforge-1.9.11.jar",
          "size": 2179406,
          "sha512": "ee07ae723e05dfa756ff375c88d8d71cd44f3fb854d37766507ab4b84d83a3fc5dd41929ce3c613a512a319be33bf28a256f8bd26dd021697f209e0c42c89f10",
          "sha256": "35339f608762d0c886d2cb9a21f6eb8ca9d56ff9a9701cc4bf9c6f8000bba20e",
          "sha1": "41b14add4442c0e155e2755d4bcfdfd644a39b55",
          "md5": "4f3dc8a2f8b31744fa881c9fd209d7d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.11-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.11-sources.jar",
          "size": 39287,
          "sha512": "4ac91977c4a38e1245d7bdbd695f2474a648fe195f961b32707840db3ad4688dfae97c443de6c852c9cae8c7626c1d25ccd09ff781946a96a8f79eebe8f0fa02",
          "sha256": "a23c84f7e7480c6d09a74a5c933ae5eca6347d66bc3a6767042ad266e3a7e704",
          "sha1": "016ea43d9d84dcacebbd55f24f6b39f3e3778845",
          "md5": "bdcbed8b8816846da7226668260abdf7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.11-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.11-dev-shadow.jar",
          "size": 1961424,
          "sha512": "12d559744bd87b4fb4fb1624cae904a9dc54ae849b5c6770c0bc1f5be356bd5cd22e71ca2c856ac1b1f5629dda2896b3fcd58fc68a678bc2d171757b746989b4",
          "sha256": "3a3a4df829cc3fd22f6534bc63b2ff5fabcc129c36253cdc3596d471a118d190",
          "sha1": "eaecaea57d8caf7826be9152fa44ea8f0dd306ea",
          "md5": "3cfe8fe7164d45f33179960fa6f3662e"
        }
      ]
    }
  ]
}
