{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot5.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot5.jar",
          "size": 2088662,
          "sha512": "831c429d5488154eea15b9a3cb46b3d0378783b5e309bf367ee205d5337401b4e1e2f1dda5d6050e241bbed1c0eea5a7aaaf56ba3fc3f8e01c5496540b0b0732",
          "sha256": "886728b3c2d4c956d28aa35fae61fda882cfff7b30a4f13a8ad4869527e5da32",
          "sha1": "9c23b63900d5c682aa88d30bda7912b3cc30a783",
          "md5": "4ce014fc251fda562501545b0e6cc073"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot5.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot5.jar",
          "size": 2088662,
          "sha512": "831c429d5488154eea15b9a3cb46b3d0378783b5e309bf367ee205d5337401b4e1e2f1dda5d6050e241bbed1c0eea5a7aaaf56ba3fc3f8e01c5496540b0b0732",
          "sha256": "886728b3c2d4c956d28aa35fae61fda882cfff7b30a4f13a8ad4869527e5da32",
          "sha1": "9c23b63900d5c682aa88d30bda7912b3cc30a783",
          "md5": "4ce014fc251fda562501545b0e6cc073"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot5-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot5-sources.jar",
          "size": 37636,
          "sha512": "7fb90e78c314ab1fd7288ac84fcfa8aa91ab9c6b6d32eca9d9f4fcd0de066e801c9067bacb78ca033d5976e7d6d9398ec5deb9cbd06b01fa71e75f76d392286e",
          "sha256": "da30df1ae8fe56645284d177700e263ad5a1282cab9d8d1d6105d68c279d209e",
          "sha1": "f5437023b5454cd80a77c392a696578624fb043f",
          "md5": "10512c5c9b6c9759e94adf860daba723"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot5-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot5-dev-shadow.jar",
          "size": 1872029,
          "sha512": "439e908dfa4edbbd9608a6e3f1e94b4b9bcd0703127be27af8d29571da241f13202055fb5a762d04f198e8d6a5995e17e31038f087c1e1baede6e13564ef5cc9",
          "sha256": "0a6828342d3d082c6511aa39b45e6d820b491ab0b93fbb8139ba0936a78cdbd3",
          "sha1": "8f85877e573e55c0967411897a16ffd3c641516c",
          "md5": "40ec864b65c0e87b1ef4b127a2bb6f75"
        }
      ]
    }
  ]
}
