{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.5-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "size": 1903149,
          "sha512": "5c2772247ea4e5238973918d9375988759f4e3829e8318843166f355a3caec857720f6510964a51f8fd6c745167b9b2dd4c20d1d099438a64f44c9eb3e0041ee",
          "sha256": "ccf26f7cbf58b9e04aa35ca03cefdfbddccd206a5370ca7b021e673efd68d3b5",
          "sha1": "19d5fd607c6ec914aab26a57136e06b740a2efb3",
          "md5": "4919967f7349bba4cf601fadc68fbf6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "size": 1903149,
          "sha512": "5c2772247ea4e5238973918d9375988759f4e3829e8318843166f355a3caec857720f6510964a51f8fd6c745167b9b2dd4c20d1d099438a64f44c9eb3e0041ee",
          "sha256": "ccf26f7cbf58b9e04aa35ca03cefdfbddccd206a5370ca7b021e673efd68d3b5",
          "sha1": "19d5fd607c6ec914aab26a57136e06b740a2efb3",
          "md5": "4919967f7349bba4cf601fadc68fbf6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot-sources.jar",
          "size": 38702,
          "sha512": "edd987a8831d69361acc2deebb0b030c15a94b67145a037b75b8eefbf0ebd7cc68a22e56e491bc6af9655d15aaa89c15cc3dbdf7b38e43be842c5e7acfcc7c92",
          "sha256": "33df9513395b1d8a3d8773e668c72aceceec4327a0631fc6b3946116933e5e54",
          "sha1": "375d2e230a259f255d8339646768df5b0fe301e9",
          "md5": "e22945b0a5c03b67fd7879958660f13b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot-dev-shadow.jar",
          "size": 1689981,
          "sha512": "10a6a9835f5f09cf26180fa715bcfe1430fc9ba7ca47d8ee524e93ce1bc0593760f5b7b168637d9eaf409e85772656b086cff5a24e6f9f7ed278f83b65904a42",
          "sha256": "af0d9cdc1e750d8c5e3c12741b83db76d38109acfa5d20d235a6416978f3f781",
          "sha1": "02ab12ac5ceab3c15968554a0307b2e9acc6b3af",
          "md5": "65d70394d734ba5db2a06df378e7c11e"
        }
      ]
    }
  ]
}
