{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.5-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "size": 1903149,
          "sha512": "be8ee0dce7ce455d2584e9bc0e62ad389c0df703b535b36926c490f70a772660e0addcb61d170c5cce6035d897d4b2589bac9c2477b76ecd81d778d41c098c73",
          "sha256": "961d3835d45e5edfeeb86436629c6260136f070bf1a1f0e09135429f76167596",
          "sha1": "8b7f7994f386bbfbea5a8c507e3cafda871fd377",
          "md5": "a40a232e4dc4e6dc45d4b9624105e974"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot.jar",
          "size": 1903149,
          "sha512": "be8ee0dce7ce455d2584e9bc0e62ad389c0df703b535b36926c490f70a772660e0addcb61d170c5cce6035d897d4b2589bac9c2477b76ecd81d778d41c098c73",
          "sha256": "961d3835d45e5edfeeb86436629c6260136f070bf1a1f0e09135429f76167596",
          "sha1": "8b7f7994f386bbfbea5a8c507e3cafda871fd377",
          "md5": "a40a232e4dc4e6dc45d4b9624105e974"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot-sources.jar",
          "size": 38702,
          "sha512": "e3f2acf9f2eba114c64a8264d1302b1a8c721631c68755c12ed6632d8399481b29637b1db737fd87c36dd735f327f3cd5b851411ea05b88ba6d72740f791f0f0",
          "sha256": "cb3aa0ce20ffbeaccb96ef823adf15a4ba8a1477c078df928d379d47c088f362",
          "sha1": "b8fd1361bb3e5d4def059a70966e70bf880240d9",
          "md5": "7252d3a1e151caadcf5aa1ce89865624"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot-dev-shadow.jar",
          "size": 1689984,
          "sha512": "a2c0ec8ed1e088069f74c49175137f4932566aaaab4a5c44d4e4fca77d06b83fb9384cec4e67323918c241d2de31dfb76a3cdacd4cfdc5b419153cccdb6a40df",
          "sha256": "4a3397f3da94f61c10f2df7e9fe52359467aed6bb9765188bce1c1c16b30340a",
          "sha1": "63489874f72b4bd34e1d5286bb040f23409a311b",
          "md5": "8ba754f0f80536c5bca093faffe990b3"
        }
      ]
    }
  ]
}
