{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.1.jar",
          "url": "horseman-common-1.1.1.jar",
          "size": 65691,
          "sha512": "456c3e51db6858a590d3be5d318562a5f505043d30ea655b7233e456389dac391e380a2301807b68b59c9f3052b7e012f85e14f9b4db7396747733e462482daf",
          "sha256": "1125e38c981f4bae86a110c898c4e094ee3890150168619f7a440c3e63b1089c",
          "sha1": "93e85eb48e5439f1f260cf7cf42fc3db9fd68ead",
          "md5": "0d2efeb964e404414cc9bc3fd9fde192"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.1.jar",
          "url": "horseman-common-1.1.1.jar",
          "size": 65691,
          "sha512": "456c3e51db6858a590d3be5d318562a5f505043d30ea655b7233e456389dac391e380a2301807b68b59c9f3052b7e012f85e14f9b4db7396747733e462482daf",
          "sha256": "1125e38c981f4bae86a110c898c4e094ee3890150168619f7a440c3e63b1089c",
          "sha1": "93e85eb48e5439f1f260cf7cf42fc3db9fd68ead",
          "md5": "0d2efeb964e404414cc9bc3fd9fde192"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.1.1-sources.jar",
          "url": "horseman-common-1.1.1-sources.jar",
          "size": 36376,
          "sha512": "05ee700512148b2edaacf91e22ca8712265522470e3900034ceb556ab8e8f18bdf9fef9e369cf19614fa13cd7761874905d6bd37ac4d2b489b03985c7e173fe3",
          "sha256": "da0b0bb703fdfd375bb06b89877b3dfaef375c9850836178b2a7c6f826f6d669",
          "sha1": "cc314830b223ce63be85802cbeef9ae51c4d24b9",
          "md5": "7e3229d815a3489b9ca6cff453aa754c"
        }
      ]
    }
  ]
}
