{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.7.jar",
          "url": "horseman-1.21.1-fabric-1.3.7.jar",
          "size": 139000,
          "sha512": "55547c74c8a81836eed94ec7b5805243bfd2ca919909a4d64659a57957896e80da9d8268b63d7f29da0637342a13d613148dcd7eb2b8886b2394a70f03f805c0",
          "sha256": "0b4aa6202d29515678f05fe673f1e65fb689ba9faca58b10341ea1399f0dc184",
          "sha1": "46a6f1af095299d90850e8428b6559a45dc1bcef",
          "md5": "6f1f59227b8573e7da6fb1f0ec76f898"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.7.jar",
          "url": "horseman-1.21.1-fabric-1.3.7.jar",
          "size": 139000,
          "sha512": "55547c74c8a81836eed94ec7b5805243bfd2ca919909a4d64659a57957896e80da9d8268b63d7f29da0637342a13d613148dcd7eb2b8886b2394a70f03f805c0",
          "sha256": "0b4aa6202d29515678f05fe673f1e65fb689ba9faca58b10341ea1399f0dc184",
          "sha1": "46a6f1af095299d90850e8428b6559a45dc1bcef",
          "md5": "6f1f59227b8573e7da6fb1f0ec76f898"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.7-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.7-sources.jar",
          "size": 14731,
          "sha512": "4fde4843509050eab4feca121993044faf296b33965ca13b0c970a5be97837a097063ebc630762be73a8f4422502435deea919e7a66af0467c0b52ff5af80dbc",
          "sha256": "09dc5014193f4727347af1ed0401193ad4c8d6c8a8e0e5ccdd920f59ee88f41a",
          "sha1": "8dbdd9ea0f30896a728be064d193e532023bf965",
          "md5": "6746d7e76139105c714c61f03ee77da0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.7-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.7-dev-shadow.jar",
          "size": 137619,
          "sha512": "1aefccd5e83c4b0f0e06ed6ba26a66875bb57ec0ba0c062e5942718c2847cfa278f15e1cd04a29c7d0ec50151d27597af97e6b7d2075d37fb57f620e88ee2fc2",
          "sha256": "b8cbf0bafbb2506c1c29b57a3bb2f1c1432c015923609f42e49370296c3760e6",
          "sha1": "ce0a12f8ad08670e8c6bbbd1c3f48c1f3cfb7b73",
          "md5": "666c0d9f69d7317fa6bec305916ff204"
        }
      ]
    }
  ]
}
