{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.5.1.jar",
          "url": "scholar-1.20.1-common-1.2.5.1.jar",
          "size": 650294,
          "sha512": "5e463bb089c0b424da17cb204b8d5494f2c6538fba632d348a3a71c850b76a9e899e2947b201a3989949f133c09ccc2d3ce39158be27ee74796ca87f693b6dc6",
          "sha256": "8a11fae79e4d5ef83ba1c69f4b2e2615806f7c7653c13d93e840175550f303c9",
          "sha1": "1507507a98089aed4498574881f88cbe9fee5d02",
          "md5": "6a3afc1ac0629fc81b7af23e029a191a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.5.1.jar",
          "url": "scholar-1.20.1-common-1.2.5.1.jar",
          "size": 650294,
          "sha512": "5e463bb089c0b424da17cb204b8d5494f2c6538fba632d348a3a71c850b76a9e899e2947b201a3989949f133c09ccc2d3ce39158be27ee74796ca87f693b6dc6",
          "sha256": "8a11fae79e4d5ef83ba1c69f4b2e2615806f7c7653c13d93e840175550f303c9",
          "sha1": "1507507a98089aed4498574881f88cbe9fee5d02",
          "md5": "6a3afc1ac0629fc81b7af23e029a191a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.5.1-sources.jar",
          "url": "scholar-1.20.1-common-1.2.5.1-sources.jar",
          "size": 508540,
          "sha512": "744a753f67e4cb7e188a42e1e91dbf09e1f7c9e9de52870d4e002c1ca4b94b63c4ad71b7720e45462865a590e9f47fb56e9b6bc31fdbc840af56b0e035e12e3e",
          "sha256": "d7664eb9a220beaa47b3ab79009390eff4d15b42b7b441a5143f2c5842ae6261",
          "sha1": "a9f3dcd219c2cbb2f6014460509c9df64613c5f1",
          "md5": "c9911fe7ba01230af234047c3c0b6a4e"
        }
      ]
    }
  ]
}
