{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.5-snapshot1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot1.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot1.jar",
          "size": 1910025,
          "sha512": "8ea44e9ca10e2025bc5aeee522c549cd67a10e52c4f8ccf7296560da649ddae61c34f274f0af0ee1c83681cb609c93546fddb2a7076391ee361327c632772c40",
          "sha256": "64035e536e68dc5364f79d0955b6bf64bfe755c0fa1c4370ae4da53205d6cf1a",
          "sha1": "94bc628bc4dc83dc7170825de5fd1e0acc1ff2a5",
          "md5": "5a078c7e3d986c682a5e10f75fad4e5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot1.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot1.jar",
          "size": 1910025,
          "sha512": "8ea44e9ca10e2025bc5aeee522c549cd67a10e52c4f8ccf7296560da649ddae61c34f274f0af0ee1c83681cb609c93546fddb2a7076391ee361327c632772c40",
          "sha256": "64035e536e68dc5364f79d0955b6bf64bfe755c0fa1c4370ae4da53205d6cf1a",
          "sha1": "94bc628bc4dc83dc7170825de5fd1e0acc1ff2a5",
          "md5": "5a078c7e3d986c682a5e10f75fad4e5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot1-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot1-sources.jar",
          "size": 38702,
          "sha512": "4be1780cdecc61a13b4536ebe9e9140090f2e485c6193d4579e87b0586bff4b0ddb4ec97e9e08b4ffd442f372ad6f873f8c69fae85f7d8e45e6694cd10214709",
          "sha256": "2a21d2d92ad175896d7fbbe7d707aeac71c61ba13aae1124f568d4b23c740ed3",
          "sha1": "a3976d1880cea83df9cbd168cbba5f5649c3591d",
          "md5": "6109de285c917ecf85557f3eb97663e6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot1-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot1-dev-shadow.jar",
          "size": 1696844,
          "sha512": "a25cb417fd637f77ce5cf0c3d0a0af3b0f5a3f6aec321067e4107b713982ddb740cc497b5885bbd7468191494e81f1c58ca33638a1e84450b853dc857469d1b1",
          "sha256": "a92d837c903dfcfdf5d425152e1acd7aa21bbc32033eaffac289e44ca0893988",
          "sha1": "124f7fd860e20bceda89ef0863a3aeddc66c5d78",
          "md5": "5b752f25c2895eecb912c40a60742912"
        }
      ]
    }
  ]
}
