{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.envelope",
    "module": "envelope-1.21.1-common",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.25.0.322"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-common-0.6.1.jar",
          "url": "envelope-1.21.1-common-0.6.1.jar",
          "size": 1379054,
          "sha512": "58564c487e85bd48b20c9b799d0545dedfa3dd709bea267817a3f6316dd8b445705a8f7bfd00da8605acdb0816be95c60fdafc07f67b7a010929af6f695d32bf",
          "sha256": "f3ffaf04787a36298bd02aac672030acec3f67ee22d8f494bfda5ef1d9ec8f0f",
          "sha1": "56df4e650a926dde16f669248ed6537057a737fa",
          "md5": "f96f92d385ffbf55dbd4f2ccd7166de9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-common-0.6.1.jar",
          "url": "envelope-1.21.1-common-0.6.1.jar",
          "size": 1379054,
          "sha512": "58564c487e85bd48b20c9b799d0545dedfa3dd709bea267817a3f6316dd8b445705a8f7bfd00da8605acdb0816be95c60fdafc07f67b7a010929af6f695d32bf",
          "sha256": "f3ffaf04787a36298bd02aac672030acec3f67ee22d8f494bfda5ef1d9ec8f0f",
          "sha1": "56df4e650a926dde16f669248ed6537057a737fa",
          "md5": "f96f92d385ffbf55dbd4f2ccd7166de9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-common-0.6.1-sources.jar",
          "url": "envelope-1.21.1-common-0.6.1-sources.jar",
          "size": 832698,
          "sha512": "2e7b71208b8e832f58c0011aba3e19be0f51bf8e2d63114e1ed84f7c6fa03c013385913195fc7bd9ced4b5e94340623e32045913975a5ba9494b829ccaecb192",
          "sha256": "550592f2a9fb3afa7abbf392a9db568c9ffc8ba2afa3f6a1744b4422e1d918fe",
          "sha1": "eb6205ef4de9632bdbbe574326b1133718f70992",
          "md5": "8fe2171327429a3dfe0759aa14d67bf6"
        }
      ]
    }
  ]
}
