{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.4.jar",
          "url": "exposure-common-1.7.4.jar",
          "size": 1257522,
          "sha512": "c3a0d9b8ee8fe53d4abd6886ebd78e11dda37d767d9737e800204c016c4f9f74ebaca6fc4da8d259330b7c254fb11b21ebf7873e2f4e59c84944e4e5b26de0b9",
          "sha256": "04b8eb63ee76124dbe0b8a60a008b5ec71b28a2642b2a3cc3ede71af02cb6c65",
          "sha1": "a3ffefc36126d63c05c054ddf329f6cf08224b3d",
          "md5": "8e2ef52bf67b69c5e6369eb436f625af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.4.jar",
          "url": "exposure-common-1.7.4.jar",
          "size": 1257522,
          "sha512": "c3a0d9b8ee8fe53d4abd6886ebd78e11dda37d767d9737e800204c016c4f9f74ebaca6fc4da8d259330b7c254fb11b21ebf7873e2f4e59c84944e4e5b26de0b9",
          "sha256": "04b8eb63ee76124dbe0b8a60a008b5ec71b28a2642b2a3cc3ede71af02cb6c65",
          "sha1": "a3ffefc36126d63c05c054ddf329f6cf08224b3d",
          "md5": "8e2ef52bf67b69c5e6369eb436f625af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.4-sources.jar",
          "url": "exposure-common-1.7.4-sources.jar",
          "size": 902026,
          "sha512": "2739d22e1e3e5bb0acf2d0a6276d4cd8509c0f0f2aa811bb69663bb0b7cf1d0c5eb6be774c26588203521f91e6a056dc1984af958fcf8fe1213fdf2d0258c6f8",
          "sha256": "937edc5703fa81e803f79839d254cbc411c469cf52cd1aa9e69931a56ca88d68",
          "sha1": "695ef3ab7cf5b6145f042eb38295fbb728a008c4",
          "md5": "a8473114d04135a15b70bb5cdcd0da40"
        }
      ]
    }
  ]
}
