{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-26.2-fabric",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-26.2-fabric-1.3.5.jar",
          "url": "sootychimneys-26.2-fabric-1.3.5.jar",
          "size": 175758,
          "sha512": "4c4468cabb33601c62b2a05d384fcac9db9fba25762503a2562520e574dea98157f7fdbb34dd87d553fe99efbe22be45212abad242363a8aaa283a7124e6ae6e",
          "sha256": "023a23eb36154cef1500f09f3f0bb019917528222965cedc3fbd4b934a460a4f",
          "sha1": "4a39cbb2ae82a66ce0b5603be4d30bf9ba5c3d43",
          "md5": "607480c1081e8a8b1615a30d3b128e0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-26.2-fabric-1.3.5.jar",
          "url": "sootychimneys-26.2-fabric-1.3.5.jar",
          "size": 175758,
          "sha512": "4c4468cabb33601c62b2a05d384fcac9db9fba25762503a2562520e574dea98157f7fdbb34dd87d553fe99efbe22be45212abad242363a8aaa283a7124e6ae6e",
          "sha256": "023a23eb36154cef1500f09f3f0bb019917528222965cedc3fbd4b934a460a4f",
          "sha1": "4a39cbb2ae82a66ce0b5603be4d30bf9ba5c3d43",
          "md5": "607480c1081e8a8b1615a30d3b128e0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-26.2-fabric-1.3.5-sources.jar",
          "url": "sootychimneys-26.2-fabric-1.3.5-sources.jar",
          "size": 115694,
          "sha512": "55a0315bc38af24622e926e4fd84bb24aa07ead7e76b95510ec83e4fe3648d14b93b486ca22f42185e89771712603a590ae77fa2fbbee0df1e12af2bd7755778",
          "sha256": "2b043e0ea4ab720e0acb25169b1c1e59536af861fe3e378367576338ba5316a8",
          "sha1": "29883b823c1ee6ee3e478353160ac44f83748556",
          "md5": "87d1bdf210a57ac26d8b1c629b942816"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-26.2-fabric-1.3.5.jar",
          "url": "sootychimneys-26.2-fabric-1.3.5.jar",
          "size": 175758,
          "sha512": "4c4468cabb33601c62b2a05d384fcac9db9fba25762503a2562520e574dea98157f7fdbb34dd87d553fe99efbe22be45212abad242363a8aaa283a7124e6ae6e",
          "sha256": "023a23eb36154cef1500f09f3f0bb019917528222965cedc3fbd4b934a460a4f",
          "sha1": "4a39cbb2ae82a66ce0b5603be4d30bf9ba5c3d43",
          "md5": "607480c1081e8a8b1615a30d3b128e0a"
        }
      ]
    }
  ]
}
