{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.mortaar",
    "module": "mortaar-1.21.1-fabric",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.6.jar",
          "url": "mortaar-1.21.1-fabric-1.5.6.jar",
          "size": 167226,
          "sha512": "3ea7abe0c5816dcbe831070e0cc6de2aba83fc88e8f7b372320d6c699445cbf88fba814749b3aed4cc195524581e946d8ef6dfcd0f4abd7746ae99b89b253dbc",
          "sha256": "8aca5d574be79f650f76a0f88eaf07de456765f7ff7d305eef0ad9b18463dfdb",
          "sha1": "1fb0465c9592f846f77be9891922913358aa79ea",
          "md5": "8dfa0fe93355e3fb6608e913ef747164"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.6.jar",
          "url": "mortaar-1.21.1-fabric-1.5.6.jar",
          "size": 167226,
          "sha512": "3ea7abe0c5816dcbe831070e0cc6de2aba83fc88e8f7b372320d6c699445cbf88fba814749b3aed4cc195524581e946d8ef6dfcd0f4abd7746ae99b89b253dbc",
          "sha256": "8aca5d574be79f650f76a0f88eaf07de456765f7ff7d305eef0ad9b18463dfdb",
          "sha1": "1fb0465c9592f846f77be9891922913358aa79ea",
          "md5": "8dfa0fe93355e3fb6608e913ef747164"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.6-sources.jar",
          "url": "mortaar-1.21.1-fabric-1.5.6-sources.jar",
          "size": 8061,
          "sha512": "44c897410b151ca31f4cac0f6e39b6187bc60ac537f77030245d5b3cdf0c2c9aea2e511fc586360cbe8c5868e56ffee640aeecdbabfb6c9449a165851ebb5a86",
          "sha256": "a5bce663080904ad517a18f385644f4f494a0d8a56be7677e7d4a1ca77d4ddf2",
          "sha1": "696997baa7648837569c2f1ac66d8a112ff5a4ba",
          "md5": "2478eaf00e7c2861f3b331f0789afa83"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-fabric-1.5.6-dev-shadow.jar",
          "url": "mortaar-1.21.1-fabric-1.5.6-dev-shadow.jar",
          "size": 164379,
          "sha512": "3d4bc4a101f7126747c2b2fc13df979ea46c5c72b57269840dd117a516d4570ef41968b9bda05914e4001a66ee09ece330de12b21955f5fec61e0d0161b55904",
          "sha256": "e03217eeb0349a665578c3117321e8ed6f87b8ff3ba7ed048f0c718aec7c8e35",
          "sha1": "94f518ca7d8368ff866af36ba4d702e83ecd0297",
          "md5": "5e441e73e6ff5e2a7e5b079afe228d06"
        }
      ]
    }
  ]
}
