{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-neoforge",
    "version": "1.21.1-1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.2.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.2.jar",
          "size": 149304,
          "sha512": "06b7a9f4c2debc683952f16f01f4e06744c56947b14baa3a62836f8c2c84431b429e2a4bb511cb10a2d665038fa41cc5cbb34bcc08d0d20d5e3c5c231ee23407",
          "sha256": "cceee4b4acc19b6e3fb95b009e3cc920f796ea81b2c6b47f3b1e97cb4a70ef50",
          "sha1": "835ead49af2dd38e89ed7a1efa55f29715d4c231",
          "md5": "b7b027eed9e5c6320d8cd78030015604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-neoforge",
          "version": {
            "requires": "1.21.1-1.8.4"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.2.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.2.jar",
          "size": 149304,
          "sha512": "06b7a9f4c2debc683952f16f01f4e06744c56947b14baa3a62836f8c2c84431b429e2a4bb511cb10a2d665038fa41cc5cbb34bcc08d0d20d5e3c5c231ee23407",
          "sha256": "cceee4b4acc19b6e3fb95b009e3cc920f796ea81b2c6b47f3b1e97cb4a70ef50",
          "sha1": "835ead49af2dd38e89ed7a1efa55f29715d4c231",
          "md5": "b7b027eed9e5c6320d8cd78030015604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.2-sources.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.2-sources.jar",
          "size": 11363,
          "sha512": "cb1e1935c8115405ec6488e70ce46400d1307ca396bb3c8aee5f2b66aa0d7f218cb50dc9729642fd2f3454bb30795352d565ace1e1d4e58eea9dbf6ad198711f",
          "sha256": "dd6df1019bd343b8093717f6c92e98e26a701943178a36ae56bbade413541153",
          "sha1": "8b13af85569d607c2d156cfb2615fffcb1188c38",
          "md5": "25d2c9403915a65d6bc2400619accbd5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-neoforge-1.21.1-1.1.2-dev-shadow.jar",
          "url": "exposure_catalog-neoforge-1.21.1-1.1.2-dev-shadow.jar",
          "size": 145446,
          "sha512": "f9a5116dee06f6bfee1674e03528177f44f16605d11a57ff2e39188695ebbbe0f68d8a86c9e238e0f3f1928a73e781df9e7650703833701449c41fcd0dc24057",
          "sha256": "5b737a0225cd6bff2e833a216a8ec1edf8e99c8b66335a7a18ca74a4925462a8",
          "sha1": "0f7f27d7458d30270d0f8cad054c6774b80e8184",
          "md5": "a50cc27fd4e6bd9cde3fec6a5b4142e8"
        }
      ]
    }
  ]
}
