{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.1-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.1-forge.jar",
          "size": 848428,
          "sha512": "4010607f09e0b82338a20da6d3dd359d0de6d03e8e67329d8d94ee06b73088e2d7cfa3a34dedbb1ed966b3203495ecd94b84bf500860641d0aa59d906ee8debb",
          "sha256": "90d169331e04dca5afbcb5733fcca13122e67d7eba1c6bafd041ee9731d1cfee",
          "sha1": "f5a9d73e3fa5e2ef18ebd9dac54312eb21eed043",
          "md5": "b5007eaf06b59efe150a4b0b39bf8a23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.1-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.1-forge.jar",
          "size": 848428,
          "sha512": "4010607f09e0b82338a20da6d3dd359d0de6d03e8e67329d8d94ee06b73088e2d7cfa3a34dedbb1ed966b3203495ecd94b84bf500860641d0aa59d906ee8debb",
          "sha256": "90d169331e04dca5afbcb5733fcca13122e67d7eba1c6bafd041ee9731d1cfee",
          "sha1": "f5a9d73e3fa5e2ef18ebd9dac54312eb21eed043",
          "md5": "b5007eaf06b59efe150a4b0b39bf8a23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.1-sources.jar",
          "url": "scholar-1.20.1-forge-1.2.1-sources.jar",
          "size": 523233,
          "sha512": "be70298e17fecb3d33cad367597c00a82d7dc1cf0b4393134c370945b6bbe88d18d4194854abc2705bf102b3122eab1b38f5982847695f6c304aa7a8de1052c1",
          "sha256": "d4fecf1c0f115f6468c7467cea57770826dae510f571e1a177773f7b30cbce7a",
          "sha1": "0d51a3ea2924a34ee7bc0b29467dff81879693fd",
          "md5": "9e089e7e39b76ab9c8484844dda3a5c8"
        }
      ]
    }
  ]
}
