{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-forge",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.7.3-forge.jar",
          "url": "exposure-forge-1.7.3-forge.jar",
          "size": 1304439,
          "sha512": "1b1fa0fc16a8315f997bad5710ec543c7f3b78c82bd0b290bcbf289d2ca24c58fe4f85107fa8dd1ae65c84250c7b64839f1932736a03ba96ad8b08cfc8130d10",
          "sha256": "ca505e0679b0d9af544cfe7003b569e25d605d564d137af406a842ddb4bd8091",
          "sha1": "479d13e952e08436c4dc27f42108f44bcbd249a2",
          "md5": "9972818bd24f3d0d2824f9b0b4ce7c9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.7.3-forge.jar",
          "url": "exposure-forge-1.7.3-forge.jar",
          "size": 1304439,
          "sha512": "1b1fa0fc16a8315f997bad5710ec543c7f3b78c82bd0b290bcbf289d2ca24c58fe4f85107fa8dd1ae65c84250c7b64839f1932736a03ba96ad8b08cfc8130d10",
          "sha256": "ca505e0679b0d9af544cfe7003b569e25d605d564d137af406a842ddb4bd8091",
          "sha1": "479d13e952e08436c4dc27f42108f44bcbd249a2",
          "md5": "9972818bd24f3d0d2824f9b0b4ce7c9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-forge-1.7.3-sources.jar",
          "url": "exposure-forge-1.7.3-sources.jar",
          "size": 942358,
          "sha512": "ed88733ce1dbab4dd495afd0e009443a11595e6c2ebfe7467df0205e037871f31f1c08b2e0765a6734b5574f98c08b8313115739cb7714e997c6c877f90f0a75",
          "sha256": "7950b40dc69e4527b7c0dc1639cfe75341f53e37cd1e14581cc26631d72b4259",
          "sha1": "b37d22ef8756f15a05cdec40e8dc0bb1b04a31ba",
          "md5": "4f98d78c7771b3920068500502de7f79"
        }
      ]
    }
  ]
}
