{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-26.1.2-common",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.2-common-api",
          "version": {
            "requires": "29.6.2.31"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.4.jar",
          "url": "scholar-26.1.2-common-1.2.4.jar",
          "size": 718799,
          "sha512": "28169e7315f82398eb8988f0e47bbacc8350a4352e9ef0cf2c8901ead2c3597c317b73bccc187ae224d7efc84883c2e0669d7c65093fc751c7020f3794c25d28",
          "sha256": "5b3af7797176ffbb958bfb69ce160b6a4c0320b00900b575c392663590f78483",
          "sha1": "f050f722b74eb60e9328b62f323775a07bb0b653",
          "md5": "a911c5412c49afc1d85ea67e28e89da4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.4.jar",
          "url": "scholar-26.1.2-common-1.2.4.jar",
          "size": 718799,
          "sha512": "28169e7315f82398eb8988f0e47bbacc8350a4352e9ef0cf2c8901ead2c3597c317b73bccc187ae224d7efc84883c2e0669d7c65093fc751c7020f3794c25d28",
          "sha256": "5b3af7797176ffbb958bfb69ce160b6a4c0320b00900b575c392663590f78483",
          "sha1": "f050f722b74eb60e9328b62f323775a07bb0b653",
          "md5": "a911c5412c49afc1d85ea67e28e89da4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.4-sources.jar",
          "url": "scholar-26.1.2-common-1.2.4-sources.jar",
          "size": 559475,
          "sha512": "eebf9ae2768f771422b295396e36431e5643e826f45deac6ca6d25d2dd97a4643cecbea6257afbc0def1192592ebcecdc7d9d42a913ee2d6f9798fde8766f4a1",
          "sha256": "c7665c6d32bd58083c23d97bcefb14e4eeccfdf88ac92bc3c201ad62151fb8b8",
          "sha1": "3650007386c4ed787b9ca3aa1e40905b513bd2be",
          "md5": "b740948c9320e2871812b0d44a02433e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.4.jar",
          "url": "scholar-26.1.2-common-1.2.4.jar",
          "size": 718799,
          "sha512": "28169e7315f82398eb8988f0e47bbacc8350a4352e9ef0cf2c8901ead2c3597c317b73bccc187ae224d7efc84883c2e0669d7c65093fc751c7020f3794c25d28",
          "sha256": "5b3af7797176ffbb958bfb69ce160b6a4c0320b00900b575c392663590f78483",
          "sha1": "f050f722b74eb60e9328b62f323775a07bb0b653",
          "md5": "a911c5412c49afc1d85ea67e28e89da4"
        }
      ]
    }
  ]
}
