{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.5.1-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.5.1-fabric.jar",
          "size": 668661,
          "sha512": "67ef80f876f2a12a275ac5544a6b6b5f4c435ad8206c0cf200d3314b7bdf6b59c496c4d76e8838acdfa3b1565b167fa0835b4f5d7384872c071cdff975afb07b",
          "sha256": "81d059d52bd23c409af79fb8c76acf4d9ef44b91d550346383d4e537479aea36",
          "sha1": "bddff667fe04a383bcf66dc4bd795bff32d34851",
          "md5": "7b9f046acbd66255d34507f49690a247"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.5.1-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.5.1-fabric.jar",
          "size": 668661,
          "sha512": "67ef80f876f2a12a275ac5544a6b6b5f4c435ad8206c0cf200d3314b7bdf6b59c496c4d76e8838acdfa3b1565b167fa0835b4f5d7384872c071cdff975afb07b",
          "sha256": "81d059d52bd23c409af79fb8c76acf4d9ef44b91d550346383d4e537479aea36",
          "sha1": "bddff667fe04a383bcf66dc4bd795bff32d34851",
          "md5": "7b9f046acbd66255d34507f49690a247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.5.1-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.5.1-sources.jar",
          "size": 396962,
          "sha512": "ec0b0a050c8299e33f97fb2160f06fea61d5c4516532583f3e1e619a442b33345d37a79f6938c39d36a01e79207bc726d16e3bef9c9d15ba869b3bae3d70f4cd",
          "sha256": "09628d18efc6508c7640dff260b4df33c50cda73aa1c6aee95a6362f70daf5c4",
          "sha1": "b8d2fe05e423fde91f9b055ef5bbf00f18beb7a7",
          "md5": "3eae6f03485a25034b759b900436ecca"
        }
      ]
    }
  ]
}
