{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.10.jar",
          "url": "exposure-1.21.1-neoforge-1.8.10.jar",
          "size": 1926427,
          "sha512": "8bd9c1ccf66fb95d6d58c48e3ef7af2f3ec8bffc12a7aa3efb12e64781d5a191751adde3a5f0777b58b7dbe869f982fbb5179ec631bb1c81be74c89579afeb08",
          "sha256": "acd3d38daf0c7f6c20fb45acda8b3df0fb537d487cff22adbeca0f7a5b82d15f",
          "sha1": "6fedd83c2e07eaf72145b7584615f4a6811c0fd8",
          "md5": "8121ceda6bf28cf909b3733eab55b239"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.10.jar",
          "url": "exposure-1.21.1-neoforge-1.8.10.jar",
          "size": 1926427,
          "sha512": "8bd9c1ccf66fb95d6d58c48e3ef7af2f3ec8bffc12a7aa3efb12e64781d5a191751adde3a5f0777b58b7dbe869f982fbb5179ec631bb1c81be74c89579afeb08",
          "sha256": "acd3d38daf0c7f6c20fb45acda8b3df0fb537d487cff22adbeca0f7a5b82d15f",
          "sha1": "6fedd83c2e07eaf72145b7584615f4a6811c0fd8",
          "md5": "8121ceda6bf28cf909b3733eab55b239"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.10-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.8.10-sources.jar",
          "size": 36117,
          "sha512": "9deee4fdd99e48cd446b44841cb513bb3b7d2eb12328a58b942dc3a24b7248e98f36124731169c7510ff69bb59b90363a6de6a28bdaf8f1cdd33e6cfba015f17",
          "sha256": "bc0dd0962da189c9c4d34291f0e3b59ced1bea044bfe9cd54913206fff189340",
          "sha1": "57a0997099eb5d30168578a429a92f3f906325ba",
          "md5": "befbd4a505a2ec4ac8ca6748a2055703"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.10-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.8.10-dev-shadow.jar",
          "size": 1712923,
          "sha512": "028fe22bd96aed3eeba7f8ac1e98008a0ff3fc9d84956cf73bf9eae5abcda859f418616fddfcfd002178b0365e47330be88e6bd42409a6b90aaababf021f6222",
          "sha256": "563f977c53a4e861b2f2971a3bcfef96b2158a9455cdb4062c43d88e715f9273",
          "sha1": "6a3caaaa232300b0859b68ab68f395f2be5efaf5",
          "md5": "bd854653ca8b65e08ab79cc808e76073"
        }
      ]
    }
  ]
}
