{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.11-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.11-fabric.jar",
          "size": 316339,
          "sha512": "44221da5baa15898ba653ca6c67000fd3cfda16dfa88adfdeacce4d047782510c57433c8179a497f616aaa99c4539a59d53ff907f63fb50d1381b7b95058e26b",
          "sha256": "3233c6ed3853e078c4d986b20b194877fb60a837bea0f7a77195890bfa621f79",
          "sha1": "dbbfc140d8225dc97620ec78a0ccbf4f6a367714",
          "md5": "23f5e461ef15f7a1a13ffbfceae47d4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.11-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.11-fabric.jar",
          "size": 316339,
          "sha512": "44221da5baa15898ba653ca6c67000fd3cfda16dfa88adfdeacce4d047782510c57433c8179a497f616aaa99c4539a59d53ff907f63fb50d1381b7b95058e26b",
          "sha256": "3233c6ed3853e078c4d986b20b194877fb60a837bea0f7a77195890bfa621f79",
          "sha1": "dbbfc140d8225dc97620ec78a0ccbf4f6a367714",
          "md5": "23f5e461ef15f7a1a13ffbfceae47d4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.11-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.11-sources.jar",
          "size": 82701,
          "sha512": "4e3f79596a4747547a4f1b83569febbd2baafd264b255db877ebd61d9ad4005021efb5b6f481d4a78f9d15fbf91aafec2e0677f27acb31b28ba2f7a9be638881",
          "sha256": "5f3745ee2a22a5318ede8768d9677bcbddc3ae29e3696ebc7b73018f0083157f",
          "sha1": "69c84d4191e83950c34e1e8a46de04e777e88495",
          "md5": "75e9c78d77f76fedebaf800392c0bf49"
        }
      ]
    }
  ]
}
