{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.1-neoforge",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.1.3.jar",
          "url": "scholar-1.21.1-neoforge-1.1.3.jar",
          "size": 495483,
          "sha512": "87704275b6878eebe8f2dab03169bbc6102a433acfc2c7fde8408ab134e5c7c13bdc1fa2bbc492f0c67fad3c0a50c4f19ef22bc2db4a238180cd200817a3d0cd",
          "sha256": "12b5aabfad98c51ce972ce0bbb513a9fa5f589373b7080df63b24d695d346740",
          "sha1": "13a2586ecdb10f41653571a34482e959702d53fd",
          "md5": "244c04a0cf04540063f509ebfec72273"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.1.3.jar",
          "url": "scholar-1.21.1-neoforge-1.1.3.jar",
          "size": 495483,
          "sha512": "87704275b6878eebe8f2dab03169bbc6102a433acfc2c7fde8408ab134e5c7c13bdc1fa2bbc492f0c67fad3c0a50c4f19ef22bc2db4a238180cd200817a3d0cd",
          "sha256": "12b5aabfad98c51ce972ce0bbb513a9fa5f589373b7080df63b24d695d346740",
          "sha1": "13a2586ecdb10f41653571a34482e959702d53fd",
          "md5": "244c04a0cf04540063f509ebfec72273"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.1.3-sources.jar",
          "url": "scholar-1.21.1-neoforge-1.1.3-sources.jar",
          "size": 29307,
          "sha512": "9b4c8858a10dd4de1b4be14f0225faf1fdb25eadd451251ed2609e106fd7bc0e2ef7c1bfbd14cc8df4cfded91dc603f2255d85780dd837c7abfbde66ef43a8c9",
          "sha256": "1a78c0edccc70f36586bda5c7b61f7c192276eb4e6a83bb93156eb568a9c1e90",
          "sha1": "4dd63f3643dd2bc2b58f22e42dcb21c2a2e267c0",
          "md5": "ce0f8b921c9fc243ccf2c3a25157ccbb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.1-neoforge-1.1.3-dev-shadow.jar",
          "url": "scholar-1.21.1-neoforge-1.1.3-dev-shadow.jar",
          "size": 307854,
          "sha512": "f6be6ccb221f8fc5b149433d2d527f400f7985d2935977e20136a16364f1dbea61d87cb76355817912a2472b276ecd24f547847d19482aedb64fa1622f8c40d6",
          "sha256": "ea7cb4ef17d8b1f7dfef93af773254c18d4a659cba9196e811688cbc8ad88118",
          "sha1": "8e091741d929b00131b84acab0b3df969a7907f5",
          "md5": "31e3e3959588a6e4c2a3182098b1cc28"
        }
      ]
    }
  ]
}
