{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.9.jar",
          "url": "exposure-neoforge-1.21.1-1.8.9.jar",
          "size": 1925989,
          "sha512": "2a3ce59582037058cd5cb979f9c6d270e2f55a61203879b16003344fd56d65c4b2caffccfd832b505ef4431ae838e6277aa85c2692c2f09bd8b8a32f80d02538",
          "sha256": "0cf575fa4360f9e03d6e7a1b18f61422d8f59fc749e2517ceeaec3fb4b878417",
          "sha1": "e84b3c4844500717c769b9a162130be64535ab09",
          "md5": "787c34e85f036798efbe05c88fa38fe2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.9.jar",
          "url": "exposure-neoforge-1.21.1-1.8.9.jar",
          "size": 1925989,
          "sha512": "2a3ce59582037058cd5cb979f9c6d270e2f55a61203879b16003344fd56d65c4b2caffccfd832b505ef4431ae838e6277aa85c2692c2f09bd8b8a32f80d02538",
          "sha256": "0cf575fa4360f9e03d6e7a1b18f61422d8f59fc749e2517ceeaec3fb4b878417",
          "sha1": "e84b3c4844500717c769b9a162130be64535ab09",
          "md5": "787c34e85f036798efbe05c88fa38fe2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.9-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.9-sources.jar",
          "size": 36117,
          "sha512": "7ae838c047c18a8aa8129f4d301e9008898bbe495252707d30d8c75b8ae743cd55bd2d2bcca1db03c2c6fa07353a3b91ade707e98b16a603b66b5cb1e1cfc2d9",
          "sha256": "df8f3ea097b6f06ba3e00ac83dc8af084ffcb98f07213460d85f768e6d558876",
          "sha1": "99e38d71069dda23f4581f7c1a395aab8cdcae6d",
          "md5": "b83244423ed728128e7cfecd20940319"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.9-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.9-dev-shadow.jar",
          "size": 1712519,
          "sha512": "390a6fc07ea6735d44b3bd4daca9b90addb5beb4806dec50e21b0dd17f187840476b50ce285982dc5224dbf38f344a576551e0d4e77c255331b9692ebf30f75b",
          "sha256": "4414902ac229e270e8b20abce84e1b48363bc1db27953c2802cc5e39d032f12d",
          "sha1": "76694c1257a2825def0e5d7770770897cea570cc",
          "md5": "8d75ba252eac56780e7659062ed5158c"
        }
      ]
    }
  ]
}
