{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.2.jar",
          "url": "scholar-1.20.1-common-1.2.2.jar",
          "size": 650116,
          "sha512": "131fdecef06ce3c3d710c72d9784da72ee17228637b409f20805955ff1a251fe6cd6abc6e77d211674b14783b28dcccddd1a69a9fbe3ca67b8a7bf89962bdadd",
          "sha256": "4482b81e5ba3df0e7cf7cc68e024f89788f80698277c0936751f54837f486016",
          "sha1": "dd65df1dce15c4b3cc5df438fba30e83bb01ac0c",
          "md5": "5613fdb82372b9a6636db10896fa3f22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.2.jar",
          "url": "scholar-1.20.1-common-1.2.2.jar",
          "size": 650116,
          "sha512": "131fdecef06ce3c3d710c72d9784da72ee17228637b409f20805955ff1a251fe6cd6abc6e77d211674b14783b28dcccddd1a69a9fbe3ca67b8a7bf89962bdadd",
          "sha256": "4482b81e5ba3df0e7cf7cc68e024f89788f80698277c0936751f54837f486016",
          "sha1": "dd65df1dce15c4b3cc5df438fba30e83bb01ac0c",
          "md5": "5613fdb82372b9a6636db10896fa3f22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.2-sources.jar",
          "url": "scholar-1.20.1-common-1.2.2-sources.jar",
          "size": 508489,
          "sha512": "1ea698544cb1c62777bc42d30287d2fc3b0fe99d1e95a8dc7ca7d6834f1e16f96ce653602fc9f0398e65a7d974fa9332a5f36d9e31f07786563d5d0622ec6952",
          "sha256": "670dde2eadc70814f42dc99c5805ccd39f3cd0530998c1e612c8302d6ffad461",
          "sha1": "140c948857bac3243a0f47f551cda58fccdec1fb",
          "md5": "552b971a4674e81d6301733b1e699f84"
        }
      ]
    }
  ]
}
