{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.1.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.1.1-fabric.jar",
          "size": 315520,
          "sha512": "bb6a35c8d4bfd85fcf974288b151699be5d2033dbccf23b9c948fdee3c5e54b2903557d6de0aadec29d498fd287db2913b4ffdeda18f886fa4c0dfb7ec931297",
          "sha256": "12f8fd8e718bf37c2a6ab58dbde46fb3f698ed08dd246a50a97a9b4d802461a6",
          "sha1": "50fa3357fbea168c8cd7002ee5776745d6bcafc5",
          "md5": "4d70f006380e13bd827080eeb0912021"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.1.1-fabric.jar",
          "url": "thief-1.20.1-fabric-1.1.1-fabric.jar",
          "size": 315520,
          "sha512": "bb6a35c8d4bfd85fcf974288b151699be5d2033dbccf23b9c948fdee3c5e54b2903557d6de0aadec29d498fd287db2913b4ffdeda18f886fa4c0dfb7ec931297",
          "sha256": "12f8fd8e718bf37c2a6ab58dbde46fb3f698ed08dd246a50a97a9b4d802461a6",
          "sha1": "50fa3357fbea168c8cd7002ee5776745d6bcafc5",
          "md5": "4d70f006380e13bd827080eeb0912021"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.1.1-sources.jar",
          "url": "thief-1.20.1-fabric-1.1.1-sources.jar",
          "size": 76394,
          "sha512": "b4f38dcc85c071dc698b6fc3eb2f0d35ee9e1c20864b745bd91f383588f471a1ef9ef70e7977cf34f6cdcb9d15cbf0f659fb3e971826709fdc9257592367b308",
          "sha256": "f4c5f53de7a6ab59d49035314ff42eef15a0d70f0521c1b91a6503fa4af7ba86",
          "sha1": "e042b52d8d3362c37db729ff13334415e795fe13",
          "md5": "5bb1bc17a45ee7d09b16900b842bc52c"
        }
      ]
    }
  ]
}
