{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-neoforge",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.6.jar",
          "url": "horseman-1.21.1-neoforge-1.3.6.jar",
          "size": 319059,
          "sha512": "cfb7b7e2e9dc42c7ff9791e19ae276f41341c6aa3d51a01a32828baca74844bb0d953889ae6ad0c2b64b2eaa4ea020f7ca0a0534c24b3022f15d20bf933b3515",
          "sha256": "5716f5af4f3ba3b4e1490036eafa58ae3246e2e4914ec5ac89270d659173dfeb",
          "sha1": "b0895d7bbe54e2d0023c4dc134c9361f94f3d75f",
          "md5": "5ddf52509aa0dadf0be48585f81055e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.6.jar",
          "url": "horseman-1.21.1-neoforge-1.3.6.jar",
          "size": 319059,
          "sha512": "cfb7b7e2e9dc42c7ff9791e19ae276f41341c6aa3d51a01a32828baca74844bb0d953889ae6ad0c2b64b2eaa4ea020f7ca0a0534c24b3022f15d20bf933b3515",
          "sha256": "5716f5af4f3ba3b4e1490036eafa58ae3246e2e4914ec5ac89270d659173dfeb",
          "sha1": "b0895d7bbe54e2d0023c4dc134c9361f94f3d75f",
          "md5": "5ddf52509aa0dadf0be48585f81055e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.6-sources.jar",
          "url": "horseman-1.21.1-neoforge-1.3.6-sources.jar",
          "size": 13830,
          "sha512": "0f5a79e0b93f1568a504d1f28eeed0097356f2978bd7b0bb5d0eeca823c2af0a41f02a294b7701ee23ff9984c13d53b422e672ab09998ef31904b0d2f190460f",
          "sha256": "f363ccd1c91828db37298fda14920c207791567acc0c4caf87d62b716f3bbf5e",
          "sha1": "292f86894e239b59d9e2565542097a9bdebd6059",
          "md5": "43612dc49fa534c1d6e90d7304e07366"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-neoforge-1.3.6-dev-shadow.jar",
          "url": "horseman-1.21.1-neoforge-1.3.6-dev-shadow.jar",
          "size": 133981,
          "sha512": "e24901f48344403d159c80919db34ac147df0b8a8b61f325f8c1da445c4ce59e89896640e66a5d235809af5499c92359e9d9afec35b4ee63c76512639a2cfc1c",
          "sha256": "9a11d1d33ddbbdd1fd8e2183b170555c389768af97b09402dd3255ab5a07dc95",
          "sha1": "7813dc7bb2963b70418779343ef3fecf3479dbef",
          "md5": "47515c90dcfc6b7d711ce8aeeed3f955"
        }
      ]
    }
  ]
}
