{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-common",
    "version": "1.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-common-1.8.11.jar",
          "url": "exposure-1.21.1-common-1.8.11.jar",
          "size": 1713978,
          "sha512": "00dadd10941d7c7475bf04307da09b0cd79924f3466adfa83fcd9746fac83e993040ab6770dd058e53438e08e141ed8c4316ce222b0e3465b948927a0ca9c2ab",
          "sha256": "53f8baa1bf2bf1bbfb9f14589ad40717a9f319b941e91ac62b785a3712367498",
          "sha1": "fb985e611b75d22a5b45ce5eaaa764c1d454095f",
          "md5": "0a983d502b7c69045de47ca9d7886538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-common-1.8.11.jar",
          "url": "exposure-1.21.1-common-1.8.11.jar",
          "size": 1713978,
          "sha512": "00dadd10941d7c7475bf04307da09b0cd79924f3466adfa83fcd9746fac83e993040ab6770dd058e53438e08e141ed8c4316ce222b0e3465b948927a0ca9c2ab",
          "sha256": "53f8baa1bf2bf1bbfb9f14589ad40717a9f319b941e91ac62b785a3712367498",
          "sha1": "fb985e611b75d22a5b45ce5eaaa764c1d454095f",
          "md5": "0a983d502b7c69045de47ca9d7886538"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-common-1.8.11-sources.jar",
          "url": "exposure-1.21.1-common-1.8.11-sources.jar",
          "size": 1158266,
          "sha512": "6f11e2f426f0acc38aad6a96f2e026c72cf7abefdae44fbcf593f315b51014c9c0b7ccfac32ffc099022f24bff273dfe5f64cc03f3f81422a5f04362580c7173",
          "sha256": "f43c5bbd2a0dbe16425e2a20cf00069a97d60e0d07d3deafbe9aed5a494765b3",
          "sha1": "eddae266c5a63a5bf9b75ed161702f452b34618a",
          "md5": "0c9dedd252c19aff3fc1e1b8177a30ff"
        }
      ]
    }
  ]
}
