{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.10.jar",
          "url": "scholar-1.20.1-common-1.1.10.jar",
          "size": 477586,
          "sha512": "b6eb47542aa24293f722aaca96d97710dfe18caf3b2fc785223b6a45ef3750bd84e6e3bf6cb7c13d77d9de2e36e217cefd0fc2f2770168df70445affc395b8ed",
          "sha256": "42f95565d62e5cfd65cd2bf7d9cf7defa7ac6844aff495c0bd093fc4b9df2cb3",
          "sha1": "1253f0d139f02594a2bb4924f6d077f5ffc9ee3e",
          "md5": "621d5e25f10d292ddd491a2f2db0889e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.10.jar",
          "url": "scholar-1.20.1-common-1.1.10.jar",
          "size": 477586,
          "sha512": "b6eb47542aa24293f722aaca96d97710dfe18caf3b2fc785223b6a45ef3750bd84e6e3bf6cb7c13d77d9de2e36e217cefd0fc2f2770168df70445affc395b8ed",
          "sha256": "42f95565d62e5cfd65cd2bf7d9cf7defa7ac6844aff495c0bd093fc4b9df2cb3",
          "sha1": "1253f0d139f02594a2bb4924f6d077f5ffc9ee3e",
          "md5": "621d5e25f10d292ddd491a2f2db0889e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.10-sources.jar",
          "url": "scholar-1.20.1-common-1.1.10-sources.jar",
          "size": 380614,
          "sha512": "4e3c104ec5de668137e0fa7abbf4717c561f940224f53ab5212e27c6d4883aa4c1f4f4796f86ff57267f4dee21a00487d53a83db4e7ead281c4e96e2e9837f49",
          "sha256": "b099ebf3454c929b98e40e12b3a147f2ef42fe37e43c9a2e0b80c4367e657262",
          "sha1": "8b5fc4923da4c1906323d0f8a7449b2c256caa89",
          "md5": "3e1f21aa84246025d308a8cfae910d16"
        }
      ]
    }
  ]
}
