{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.7-fabric.jar",
          "url": "exposure-fabric-1.7.7-fabric.jar",
          "size": 1308074,
          "sha512": "2eaba1a8917890ea3110c24915cfa87fc4f1a668d1b118362861138e7eab92975f97a33a6094ab244a28d4f0cfd6d277d052fc2eba5d70f051bfc86878a09243",
          "sha256": "2436ab698e34f46bddb1c75d80cb5e33461e5669d4b49ea9035f1b305f3366a3",
          "sha1": "e93869a83cfb342bde300c40c2d5a95054d92197",
          "md5": "490a6b540b28606f20af6e9b18dbc15b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.7-fabric.jar",
          "url": "exposure-fabric-1.7.7-fabric.jar",
          "size": 1308074,
          "sha512": "2eaba1a8917890ea3110c24915cfa87fc4f1a668d1b118362861138e7eab92975f97a33a6094ab244a28d4f0cfd6d277d052fc2eba5d70f051bfc86878a09243",
          "sha256": "2436ab698e34f46bddb1c75d80cb5e33461e5669d4b49ea9035f1b305f3366a3",
          "sha1": "e93869a83cfb342bde300c40c2d5a95054d92197",
          "md5": "490a6b540b28606f20af6e9b18dbc15b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.7-sources.jar",
          "url": "exposure-fabric-1.7.7-sources.jar",
          "size": 953273,
          "sha512": "00add938c0bc5fe510a4f998a6db77d279d00ba95d7f8076161170e83e0f0f2d908e719cba0fac67b6abc43be0d469b2b647a63e547488d74af5b9df5b643927",
          "sha256": "bac029089c12d8e8079e2084a4b8befef35c15733f6c44e964a320ee05f4ffa6",
          "sha1": "f9dd8b0b151d51db6f95485b19ed601d842095cf",
          "md5": "b26c72ad49863fc925a89f0aff8e2186"
        }
      ]
    }
  ]
}
