{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-26.1.1-fabric",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.3.jar",
          "url": "horseman-26.1.1-fabric-1.7.3.jar",
          "size": 278773,
          "sha512": "ec362dbe364dff16f2ad9c0c967d3b28f883c1880b830af526ac5a934094501548d1ec95525fdfdf3407edded1a2c2b7cb00bf3e0d62caa6dde04733c536469b",
          "sha256": "534d2a0f7a91a69d616589733aa93b3178c47fe1b55cf2997ed87df1c25d6cb9",
          "sha1": "ef2e6e3101082868af7e61d18958968d56abe680",
          "md5": "26e76d11ce661bf65fa7e5ab00a3b994"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.3.jar",
          "url": "horseman-26.1.1-fabric-1.7.3.jar",
          "size": 278773,
          "sha512": "ec362dbe364dff16f2ad9c0c967d3b28f883c1880b830af526ac5a934094501548d1ec95525fdfdf3407edded1a2c2b7cb00bf3e0d62caa6dde04733c536469b",
          "sha256": "534d2a0f7a91a69d616589733aa93b3178c47fe1b55cf2997ed87df1c25d6cb9",
          "sha1": "ef2e6e3101082868af7e61d18958968d56abe680",
          "md5": "26e76d11ce661bf65fa7e5ab00a3b994"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.3-sources.jar",
          "url": "horseman-26.1.1-fabric-1.7.3-sources.jar",
          "size": 188794,
          "sha512": "9fc55da6d828f50e9932b41a04eab65e3d0ecd6284cfe156a3d97ac287fd1116ae5121c8c7fc5dfbc00a2bc19a856b8d9b072a7a8b49a2743b6841e90a05c8e3",
          "sha256": "cbadd544f8740944dfa67946b0653753ab12029870dee3bb74484efc68f18bda",
          "sha1": "a217262f5ddc94bd701d77e89543cacfd1eacee3",
          "md5": "4dfcedad56946f1fe1985b2aa6bd17ab"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.3.jar",
          "url": "horseman-26.1.1-fabric-1.7.3.jar",
          "size": 278773,
          "sha512": "ec362dbe364dff16f2ad9c0c967d3b28f883c1880b830af526ac5a934094501548d1ec95525fdfdf3407edded1a2c2b7cb00bf3e0d62caa6dde04733c536469b",
          "sha256": "534d2a0f7a91a69d616589733aa93b3178c47fe1b55cf2997ed87df1c25d6cb9",
          "sha1": "ef2e6e3101082868af7e61d18958968d56abe680",
          "md5": "26e76d11ce661bf65fa7e5ab00a3b994"
        }
      ]
    }
  ]
}
