{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.3.jar",
          "url": "horseman-1.21.1-common-1.3.3.jar",
          "size": 117035,
          "sha512": "2eca5f424be80544a08e3b896de6dc90f61be0b16336caae072da3856e00460287cda18fe73b87aecde49dba65690684c88cd424ad7bfe0d9bc7b11a54b41fc4",
          "sha256": "108ade3f57fa692850477ccfd173cc87925c651c73869b6887bba6d247b11deb",
          "sha1": "b77bf9aabfd4de2e7678fb8c6caeb0d6c40cd6d7",
          "md5": "9bb4abb60954d9e5637853ef0a0f1189"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.3.jar",
          "url": "horseman-1.21.1-common-1.3.3.jar",
          "size": 117035,
          "sha512": "2eca5f424be80544a08e3b896de6dc90f61be0b16336caae072da3856e00460287cda18fe73b87aecde49dba65690684c88cd424ad7bfe0d9bc7b11a54b41fc4",
          "sha256": "108ade3f57fa692850477ccfd173cc87925c651c73869b6887bba6d247b11deb",
          "sha1": "b77bf9aabfd4de2e7678fb8c6caeb0d6c40cd6d7",
          "md5": "9bb4abb60954d9e5637853ef0a0f1189"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.3-sources.jar",
          "url": "horseman-1.21.1-common-1.3.3-sources.jar",
          "size": 69607,
          "sha512": "682c11752eee18a88c43d697a5860e072a6ab1cd63553b3dddad21cde9bb05416daeb8540869f94741aedf422e04d217dcc10b19d95f2a3dd3df6ffd2101d04c",
          "sha256": "152d02348649fe9ad3c6ff8cd2f1aeb4c8a40bc81d8dc1da2e81c35157076558",
          "sha1": "c4b72f0ed06c421aa38debc890c03a9869f1594d",
          "md5": "33b7dc854d782c9cc7f806fa92a66cd5"
        }
      ]
    }
  ]
}
