{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.19.jar",
          "url": "exposure-1.20.1-forge-1.9.19.jar",
          "size": 2243909,
          "sha512": "7ff49e66791d21030f67a56bc1ccb37cc8c60a0e1d374ee2a80d4bda810bd051cfb3d0bee81137783218e9ac89dc0973255c43288d48bdc476f81c6436205dfe",
          "sha256": "ae3b918e1877462006503b3169691c6259e3b31566a0f5cc047d55338b170744",
          "sha1": "b3dd7b69905a349b280f66ad0a82c2bb89423d99",
          "md5": "4d2927cf4d4c424afce4897c0ce9a98a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.19.jar",
          "url": "exposure-1.20.1-forge-1.9.19.jar",
          "size": 2243909,
          "sha512": "7ff49e66791d21030f67a56bc1ccb37cc8c60a0e1d374ee2a80d4bda810bd051cfb3d0bee81137783218e9ac89dc0973255c43288d48bdc476f81c6436205dfe",
          "sha256": "ae3b918e1877462006503b3169691c6259e3b31566a0f5cc047d55338b170744",
          "sha1": "b3dd7b69905a349b280f66ad0a82c2bb89423d99",
          "md5": "4d2927cf4d4c424afce4897c0ce9a98a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.19-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.19-sources.jar",
          "size": 52286,
          "sha512": "3dccaa3f20899a7007eda995f7d9700b040a3eaa63566a6f786ce5f81aa17d13e2274730f68b19cee9dc4a698b1d6f4c32f24690a4177c8a43079720db0095e1",
          "sha256": "0046cb2ddec90808827a775024638db7db4d96c0885c83f51e8ff999b21e6003",
          "sha1": "c83e7f30b14e06da7b7f721c1f9dc5a370cc2c25",
          "md5": "8b0655470d41855bb1cd3289ea8e688b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.19-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.19-dev-shadow.jar",
          "size": 2017052,
          "sha512": "32133fba7cb14016b5193be3c669ed832fb735b88ef8956dd5d82f2f322ac39916c5090ba12b3256461129c898fbd612a7bbd68e64e4e8abb0e8f2309f640d84",
          "sha256": "6f1e86e2513315a207f43217d2d401998e69fcf18bdaefcf5ba9c6838b19d099",
          "sha1": "f68ec30aebd738b5796d555291e81484afffcef1",
          "md5": "b5ed197e3253cca18c42750fa81d0bbf"
        }
      ]
    }
  ]
}
