{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.4-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.4-snapshot.jar",
          "url": "exposure-neoforge-1.21.1-1.8.4-snapshot.jar",
          "size": 1903605,
          "sha512": "31e29cebfde28e52c38478d130147f6f855ad8c2564c386a4c6ee0b553f3418680a41ba85868acbd564fb47bd964a6ddf1d451f56cf31d00f37acd5d0d5765a4",
          "sha256": "961c9bd466eb87a4d8206fcd2f81c5d04f4c6f7b2c854440c53e6b2d720e96a0",
          "sha1": "096c10d23b39262be550798326b16f23efb25e11",
          "md5": "b9d11ad88e259d98e84830859402e9bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.4-snapshot.jar",
          "url": "exposure-neoforge-1.21.1-1.8.4-snapshot.jar",
          "size": 1903605,
          "sha512": "31e29cebfde28e52c38478d130147f6f855ad8c2564c386a4c6ee0b553f3418680a41ba85868acbd564fb47bd964a6ddf1d451f56cf31d00f37acd5d0d5765a4",
          "sha256": "961c9bd466eb87a4d8206fcd2f81c5d04f4c6f7b2c854440c53e6b2d720e96a0",
          "sha1": "096c10d23b39262be550798326b16f23efb25e11",
          "md5": "b9d11ad88e259d98e84830859402e9bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.4-snapshot-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.4-snapshot-sources.jar",
          "size": 38699,
          "sha512": "6bdd365bc690f9ac404e4914107f437ed7cc7ed42c91b9584fbf269da3f2293ee772e653d7d69675f9ca5039ace1102480f79f4af9fc9793c0c63a9176c7bae4",
          "sha256": "07e0cc578e7684f9893881d1882d3f2efc232e66b9a3beee730ddba65bac314e",
          "sha1": "0d6ef2d9cfc7f2d10e992da58c36ce1434c92f7f",
          "md5": "45ceeefef49c969f42ef918cdbbf4a51"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.4-snapshot-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.4-snapshot-dev-shadow.jar",
          "size": 1690391,
          "sha512": "4401d47057c66efd4ec50b61d3657a4441e059091011500441d33a600d3217ba5fa961bfe13bcda0357a002d7cb45f3a75b76f8aefe7c104b015925cb76adfcd",
          "sha256": "f64c38701b813b6421241a3e4f482267ac490126c757d4a227ff2c5be31311fa",
          "sha1": "9bd8f5f1df5c4a12e49f0001eb8d41fc53622327",
          "md5": "8125d447ae2e2115dd35b8cd469c22be"
        }
      ]
    }
  ]
}
