{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-common",
    "version": "1.9.0-snapshot6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-common-1.9.0-snapshot6.jar",
          "url": "exposure-1.21.1-common-1.9.0-snapshot6.jar",
          "size": 1876519,
          "sha512": "17ebb54987467e7b7afedcdc9db4f8a1de8f3be10890b9ffc5794943b4829e0e108096c98ecfaa63976da00abcb99b965139a6a98013b50e48e8c96819d263f2",
          "sha256": "bcc2eeb3c7d361c8b83ca6b136288a36e0639b876b2d4ccc2a22f030af25f878",
          "sha1": "5daecbd6dafe55d43bcb92e427cff01237a671ee",
          "md5": "c8bfeabfd5030725bbd38f73c3ea7620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-common-1.9.0-snapshot6.jar",
          "url": "exposure-1.21.1-common-1.9.0-snapshot6.jar",
          "size": 1876519,
          "sha512": "17ebb54987467e7b7afedcdc9db4f8a1de8f3be10890b9ffc5794943b4829e0e108096c98ecfaa63976da00abcb99b965139a6a98013b50e48e8c96819d263f2",
          "sha256": "bcc2eeb3c7d361c8b83ca6b136288a36e0639b876b2d4ccc2a22f030af25f878",
          "sha1": "5daecbd6dafe55d43bcb92e427cff01237a671ee",
          "md5": "c8bfeabfd5030725bbd38f73c3ea7620"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-common-1.9.0-snapshot6-sources.jar",
          "url": "exposure-1.21.1-common-1.9.0-snapshot6-sources.jar",
          "size": 1259230,
          "sha512": "2a85d46ce251601f26b4d8dc17e0f5b33c14d5eb544e9ff73c266df286a5e052706cab60c4d5664b286f77cde2489a191f0ba56ae42dd690d2f7ba31637bdb3e",
          "sha256": "816fbe3aeb89f2f069ef7057303be57d4103dca1f6d8bc66495c45ccfd1c84cc",
          "sha1": "4b02f3f818f4a32846bf0d13ee758d73aef9a0e9",
          "md5": "7d89e55edc15e4c6b0825f1aa2da4f71"
        }
      ]
    }
  ]
}
