{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.0-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.0-fabric.jar",
          "size": 318189,
          "sha512": "8798e33830d7a9c2cc0ee3096716fa42c46f3ed067587c842373aad7eb9fd463eb1b4159e60fbfb434248066b9bc4f3c030b9ec89c48e9c8fee5e026f5ff0e22",
          "sha256": "6a69bf6555f99d2e186c160d9bde4e9b66d1364d1ae13b4fd48371e4e8b1c670",
          "sha1": "fb27c2f5d9e2eb1b0e9255d9f6c4c493431d0765",
          "md5": "f8d3a95a46bf97dd33b8064db6b07eb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.0-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.0-fabric.jar",
          "size": 318189,
          "sha512": "8798e33830d7a9c2cc0ee3096716fa42c46f3ed067587c842373aad7eb9fd463eb1b4159e60fbfb434248066b9bc4f3c030b9ec89c48e9c8fee5e026f5ff0e22",
          "sha256": "6a69bf6555f99d2e186c160d9bde4e9b66d1364d1ae13b4fd48371e4e8b1c670",
          "sha1": "fb27c2f5d9e2eb1b0e9255d9f6c4c493431d0765",
          "md5": "f8d3a95a46bf97dd33b8064db6b07eb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.0-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.0-sources.jar",
          "size": 81977,
          "sha512": "78b9a3eecde9c2c184c6aac8eb856bc6b63526a8ad003663120711cb20b99ad998c1d64fa20e04275a141a710b454fac4da90b2e2646fab091e32e60a3495633",
          "sha256": "176229b2ed03481429ccd7d151904ed459db266cc1209a4fcff6e45cf15123d7",
          "sha1": "a7e7bc524da8e097520b6d0df29a585e6eaa6342",
          "md5": "8070ee11980f667d085bd6e4072bf6b8"
        }
      ]
    }
  ]
}
