{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.2.jar",
          "url": "horseman-common-1.1.2.jar",
          "size": 65706,
          "sha512": "bf1d7557d27ae9e8c0d5047e98732617cb110cab4b9801f6fdc58529beb96b77278e266b601162f9bc59ca30d65d229ee5b1167f99e9c5d69ef12c26c60785a7",
          "sha256": "377d65f955bfe01ad01eb06fe9240f8589df0af15798bd5701fecb496792e593",
          "sha1": "b3e5159e515d3edc685ea746d2bb0140acd60e40",
          "md5": "2c77b5edf2d0e719f92c9fc24f048d65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.2.jar",
          "url": "horseman-common-1.1.2.jar",
          "size": 65706,
          "sha512": "bf1d7557d27ae9e8c0d5047e98732617cb110cab4b9801f6fdc58529beb96b77278e266b601162f9bc59ca30d65d229ee5b1167f99e9c5d69ef12c26c60785a7",
          "sha256": "377d65f955bfe01ad01eb06fe9240f8589df0af15798bd5701fecb496792e593",
          "sha1": "b3e5159e515d3edc685ea746d2bb0140acd60e40",
          "md5": "2c77b5edf2d0e719f92c9fc24f048d65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.1.2-sources.jar",
          "url": "horseman-common-1.1.2-sources.jar",
          "size": 36349,
          "sha512": "5394e470f819305d1e7dfc31f36518344425a41b8361cba9371baa572bda174cdd032f48c538132100a525619e376309e3363eebac55a11852a5011ddd21689a",
          "sha256": "6968fc24927475f1c32a0eb7748631fc177f4f3203de6950c2844d8d0a2e8fde",
          "sha1": "6c61fc4c5b8821341ac9133fa2e8351d504a9f1b",
          "md5": "e0cf22d9b1cb734452b973e47c06496d"
        }
      ]
    }
  ]
}
