{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot4.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot4.jar",
          "size": 2081984,
          "sha512": "6f052527f1978e129a6721e1b1035af6ecba8a687e508c312ff99ce04dad70e9336a2b7ea8f78b3bd8adc7078329874a663877d0c4a111cc5e9075899289440b",
          "sha256": "8f16e57cff7d74a8148b856b460e57fe0042bad238d0038589ca193890ee0106",
          "sha1": "cd96bc8965233ee964430fdf7498545603821662",
          "md5": "342a7056dc167e520e52463fe6073313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot4.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot4.jar",
          "size": 2081984,
          "sha512": "6f052527f1978e129a6721e1b1035af6ecba8a687e508c312ff99ce04dad70e9336a2b7ea8f78b3bd8adc7078329874a663877d0c4a111cc5e9075899289440b",
          "sha256": "8f16e57cff7d74a8148b856b460e57fe0042bad238d0038589ca193890ee0106",
          "sha1": "cd96bc8965233ee964430fdf7498545603821662",
          "md5": "342a7056dc167e520e52463fe6073313"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot4-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot4-sources.jar",
          "size": 37636,
          "sha512": "c06f034cf62bc357d0517a2d729869e7b81652f716c86d7433fa31d9dfbd4865f71ab64237244df15b4a2a9b1f413bd970eb66f59b87abb604915aed7d1ffc68",
          "sha256": "85fbd4039247bd75f0f2f901092a906adeff94b4800b3a9c9f466107a0ef98ab",
          "sha1": "4943e033bb16b1adab673b27e165642d5115b592",
          "md5": "a4499280f164b45a7da3478b28b04447"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot4-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot4-dev-shadow.jar",
          "size": 1865563,
          "sha512": "8f82cd18ba7712770cf2fd76cac4944b42be58addccaff123efc4732d5c2fea7347b2c35f57961491541c9adfa104a23d45a7b6e4c9182667f43f9271761189a",
          "sha256": "dd4172960db8c1594e9fdeeb60a8775bd3c555477ece52da07eb85261535b9c0",
          "sha1": "297f3ba5d24d18dd3526cb5d685770edfcb4b1f6",
          "md5": "7caaab3dcc8548630264796848dde121"
        }
      ]
    }
  ]
}
