{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.3-fabric.jar",
          "url": "exposure-fabric-1.7.3-fabric.jar",
          "size": 1286384,
          "sha512": "aac0a6ae4bd3ec2936a9e56171d6c70a341a5bc7831c915d8b48a5042b5bd55ece71d603008a16dfa8552013131246ba70df5c6325c95e48b9af448fe7f29f71",
          "sha256": "1e3f5fad1c57c99032c31ec4e02f93050ebbdbe7f9731ff89de4baa909d5b52a",
          "sha1": "d61c69d39f6db8b5dd5d438ae336e4720d4b2444",
          "md5": "9e549b46e23ce84363e86f0c0a5b1966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.3-fabric.jar",
          "url": "exposure-fabric-1.7.3-fabric.jar",
          "size": 1286384,
          "sha512": "aac0a6ae4bd3ec2936a9e56171d6c70a341a5bc7831c915d8b48a5042b5bd55ece71d603008a16dfa8552013131246ba70df5c6325c95e48b9af448fe7f29f71",
          "sha256": "1e3f5fad1c57c99032c31ec4e02f93050ebbdbe7f9731ff89de4baa909d5b52a",
          "sha1": "d61c69d39f6db8b5dd5d438ae336e4720d4b2444",
          "md5": "9e549b46e23ce84363e86f0c0a5b1966"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.3-sources.jar",
          "url": "exposure-fabric-1.7.3-sources.jar",
          "size": 932653,
          "sha512": "3b8e47baea7c215714e9dd977f73f4e8bab844267e5f84f434356a7fe7c143711cc224ec5b1856d051114b12b92eb05ea78afb1fc804bb7d69abb3a95e5fc5e5",
          "sha256": "4b4cad5a1d5ed606cfeacbcf105ea0d978bc4100f68843c6f8faf3e3855fb50f",
          "sha1": "a077c133286f21f6f36a10ef23088e6bd3ca3fad",
          "md5": "b00dd2f388ffd11b0535e3645c3ca63b"
        }
      ]
    }
  ]
}
