{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.3-fabric.jar",
          "url": "exposure-fabric-1.7.3-fabric.jar",
          "size": 1286412,
          "sha512": "bb7dc27733e04213c2d2e5c88fc57079f99f74800c4ee60618b41d2bb54d364eec946a0af66e23760237078565d0a8d2adc4410174e54a47f67ef69a641e28c2",
          "sha256": "41c2c9f815eb766d8c612c40914579a93ca33f56d187aacc64ed0807745a03d7",
          "sha1": "931c3c7c657f8bfc60df1ed4494fc7a5a5319fcb",
          "md5": "8c461ecfa6a317e06d95eb4e3502b067"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.3-fabric.jar",
          "url": "exposure-fabric-1.7.3-fabric.jar",
          "size": 1286412,
          "sha512": "bb7dc27733e04213c2d2e5c88fc57079f99f74800c4ee60618b41d2bb54d364eec946a0af66e23760237078565d0a8d2adc4410174e54a47f67ef69a641e28c2",
          "sha256": "41c2c9f815eb766d8c612c40914579a93ca33f56d187aacc64ed0807745a03d7",
          "sha1": "931c3c7c657f8bfc60df1ed4494fc7a5a5319fcb",
          "md5": "8c461ecfa6a317e06d95eb4e3502b067"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.3-sources.jar",
          "url": "exposure-fabric-1.7.3-sources.jar",
          "size": 932655,
          "sha512": "6f06b9638e71b8e53eb6088714ab59f5d1e9d2d33b2d07c2865b2f1318639bcbde2651201ce36bf3e907fef26f5033fa04673c3e94e6dcac219b35ff5ecdf408",
          "sha256": "fdce819e91cc590060d24641b9729c442062bc955ebc138f06827a01bbe4318a",
          "sha1": "1d5a5f12585b2dfdb27d3c3dfaa6b97d1ae9d62a",
          "md5": "dbf1aeb05cbfd45c96ed3d39a362b8e4"
        }
      ]
    }
  ]
}
