{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.3-fabric.jar",
          "url": "exposure-fabric-1.7.3-fabric.jar",
          "size": 1286383,
          "sha512": "ca9253d2681fef5800277bdc18cf770589471537ee7588052069d3a83334d631ae2e41535442ffec02b18fcc22ac04fa28b54530a210fe746d59379f3becc5bc",
          "sha256": "08106db724ff94cacd24df15fab77886a53485383cc3a4bdc2442db92ef9953d",
          "sha1": "d5ab9b1bc50eecb510bce6ba54690325c9ef93a1",
          "md5": "31579d4c29cff2c3863be9961afad3d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.3-fabric.jar",
          "url": "exposure-fabric-1.7.3-fabric.jar",
          "size": 1286383,
          "sha512": "ca9253d2681fef5800277bdc18cf770589471537ee7588052069d3a83334d631ae2e41535442ffec02b18fcc22ac04fa28b54530a210fe746d59379f3becc5bc",
          "sha256": "08106db724ff94cacd24df15fab77886a53485383cc3a4bdc2442db92ef9953d",
          "sha1": "d5ab9b1bc50eecb510bce6ba54690325c9ef93a1",
          "md5": "31579d4c29cff2c3863be9961afad3d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.3-sources.jar",
          "url": "exposure-fabric-1.7.3-sources.jar",
          "size": 932652,
          "sha512": "6e319f43b0e8866ffd427136a2567634e901e892bdc0f57763fa9b3158f6867177c3213745dcf6e68e7fe26b2ae9099b451ed4546bb2c7d50783138bf53162b8",
          "sha256": "da870d3918f9abebe96f1741e80e9cc101ebd8032997a6a8b9e261dc8452fd57",
          "sha1": "5edd3df31a43d0b5587bdeac282f6caac2991765",
          "md5": "f11ddb1547d47ec7e5a05129b1995e9c"
        }
      ]
    }
  ]
}
