{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-neoforge",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.3.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.3.jar",
          "size": 175513,
          "sha512": "072e89de046ea21b0d189c0ff348a9bd6e61229bfcdf98d16efad9c5e72c88d7f61c9617ef6d5de212d24c5cc2ed493890d17482802302bc8e5c7d32168448af",
          "sha256": "31ce578443c84bd1bf1f5748f9eeac7cd1c35e242932de8959dfb8aaff6224f3",
          "sha1": "e3439125c1e10d08dd7a53152f21cc5028dda102",
          "md5": "7b96114f65a556b854aec2ff337bba07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.3-47"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.45"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.3.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.3.jar",
          "size": 175513,
          "sha512": "072e89de046ea21b0d189c0ff348a9bd6e61229bfcdf98d16efad9c5e72c88d7f61c9617ef6d5de212d24c5cc2ed493890d17482802302bc8e5c7d32168448af",
          "sha256": "31ce578443c84bd1bf1f5748f9eeac7cd1c35e242932de8959dfb8aaff6224f3",
          "sha1": "e3439125c1e10d08dd7a53152f21cc5028dda102",
          "md5": "7b96114f65a556b854aec2ff337bba07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.3-sources.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.3-sources.jar",
          "size": 13231,
          "sha512": "0c760bbe4fbb3dcb86b3101b462b3815a6e555cf649fa59d51d852ae45fb502013aa2e25f036e02cbc35f0770452f0e02ffb51dac22b5c325a2c7f268ffe0eec",
          "sha256": "f13afe3917f40276e8153da5f95bc10e3aa7f9a2cd93ee88b6ea7a17d4637c51",
          "sha1": "4aead0f7adc245f0dc04e1e70fa6dc74c5be12ff",
          "md5": "9a9ae67a1055fdc30db3997b18a33e29"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-neoforge-1.3.3-dev-shadow.jar",
          "url": "sootychimneys-1.21.1-neoforge-1.3.3-dev-shadow.jar",
          "size": 170536,
          "sha512": "869cea7c596de6d13f458f370c6418e7e55ca77846e1f81373e99f3fc1bd630e6abdfeed00532b7604cf3cd7bbf6429721edabb484f65bf8d0f98937bf78e228",
          "sha256": "0cf28e5b08c1b52a389cd0cdd9d1cde16bb498146f3e4eace17cf27e1e329666",
          "sha1": "e6b63cb09a29cdabe5ade9b6628ebae2819fa291",
          "md5": "45eb0eb4f01d5a8c523e292e1588dcd2"
        }
      ]
    }
  ]
}
