{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.5.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.5.2.1.jar",
          "url": "horseman-1.21.1-common-1.5.2.1.jar",
          "size": 228976,
          "sha512": "f82f0ce0585d2de10423e0f02f22d993bad62d5b58828853a308ca09c974851b05770d845a6fcc08552ef30335aaf4433e4b93a88d7431c405579783e8f6a628",
          "sha256": "986da4b8e8c61abb0eed5346b0b2b5060a1b2bb6c78a990b47cfb34df5f46625",
          "sha1": "b583e36cac3024a7956b21ab7037f34f574fba70",
          "md5": "736eeb641d4f29f0cb81e98f07924c06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.5.2.1.jar",
          "url": "horseman-1.21.1-common-1.5.2.1.jar",
          "size": 228976,
          "sha512": "f82f0ce0585d2de10423e0f02f22d993bad62d5b58828853a308ca09c974851b05770d845a6fcc08552ef30335aaf4433e4b93a88d7431c405579783e8f6a628",
          "sha256": "986da4b8e8c61abb0eed5346b0b2b5060a1b2bb6c78a990b47cfb34df5f46625",
          "sha1": "b583e36cac3024a7956b21ab7037f34f574fba70",
          "md5": "736eeb641d4f29f0cb81e98f07924c06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.5.2.1-sources.jar",
          "url": "horseman-1.21.1-common-1.5.2.1-sources.jar",
          "size": 148112,
          "sha512": "08df1340fd29f289a129f212240ca0b9bfab3d8083bd4ebb91893e64066d041a68ac449970f0b15599ae00a5ad6d3de14042195eaa59b475738e8b0ce63a4409",
          "sha256": "a079eceaa16ad23009e775a6a3b3f1a8ae8b53ef90476c7140f3caae27e5d916",
          "sha1": "594cdab2314501770be7b9159a8a6d39f95912d3",
          "md5": "876cc77a96c4552937ccdef38b5217f9"
        }
      ]
    }
  ]
}
