{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot3.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot3.jar",
          "size": 2081977,
          "sha512": "c4ce827538292169acc596d4900051759ba77aa4eda06d4e57e4f0077543ff6f995cb59ea79a9465a5a43e3cc1bd95750dc0b2f3fcc9cc33d403cf1c571fb323",
          "sha256": "700e7fa6803293934eea4568dee9395d927f9b252aa1713776b8cedfac2a2d52",
          "sha1": "054b342e229f1ef7a1af2c9e18a608dfa5527e7c",
          "md5": "6e60617c387322f78e29c2f3aa3076f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot3.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot3.jar",
          "size": 2081977,
          "sha512": "c4ce827538292169acc596d4900051759ba77aa4eda06d4e57e4f0077543ff6f995cb59ea79a9465a5a43e3cc1bd95750dc0b2f3fcc9cc33d403cf1c571fb323",
          "sha256": "700e7fa6803293934eea4568dee9395d927f9b252aa1713776b8cedfac2a2d52",
          "sha1": "054b342e229f1ef7a1af2c9e18a608dfa5527e7c",
          "md5": "6e60617c387322f78e29c2f3aa3076f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot3-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot3-sources.jar",
          "size": 37636,
          "sha512": "8f1997f10e5a9510f4bdad570db1efea812939891dc66803e2d94d6b89b8647c9e779dc99741848182e9157a60062946c00bac065dcc64a2d747c87385014390",
          "sha256": "73d2f6ee6f0212e66cfcfb8772920a0df5d933d2fae7e7fadfd3ebc87d78b19d",
          "sha1": "b796bc2600af1e8f73c6c8372cc7ef94792ddb1e",
          "md5": "f8f231a6a7df2088e7d775b9f044419e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot3-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot3-dev-shadow.jar",
          "size": 1865548,
          "sha512": "043939fb07c499ff0e0efafb26a9e227efbdea537edcc93da18b9ed71a6b881c085a4ff89a1bbe87caedbd68ed6dd6e5efae64de9364805fe4aeac668f9c814c",
          "sha256": "0af9ce7b01a1eb6976b54a5fe94191e8033e80419f0c3aeedfd08d9a5d9cb086",
          "sha1": "c25a5fa3f99d72b62d74d6f8343cc06d0998e0a8",
          "md5": "eb5a0aefa20986e5424a202959915139"
        }
      ]
    }
  ]
}
