{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.7.jar",
          "url": "exposure-1.21.1-neoforge-1.9.7.jar",
          "size": 2167090,
          "sha512": "03ef0dc21045ec7f3fbc264de58faa014f0e04052e7ef46c3828f0c106486d8477294ee5d415c4ed87e2b2a827c1650d22db4ac8f0864f97841289a8c20ef364",
          "sha256": "242cd022144355df338eff5318b2fe34d8260955f5b3f799640677cb4b5cf079",
          "sha1": "9aa69ee08626bb35297d5272847124681a7118ea",
          "md5": "4b8bf26f872ef5b61b22978c6e95c307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.7.jar",
          "url": "exposure-1.21.1-neoforge-1.9.7.jar",
          "size": 2167090,
          "sha512": "03ef0dc21045ec7f3fbc264de58faa014f0e04052e7ef46c3828f0c106486d8477294ee5d415c4ed87e2b2a827c1650d22db4ac8f0864f97841289a8c20ef364",
          "sha256": "242cd022144355df338eff5318b2fe34d8260955f5b3f799640677cb4b5cf079",
          "sha1": "9aa69ee08626bb35297d5272847124681a7118ea",
          "md5": "4b8bf26f872ef5b61b22978c6e95c307"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.7-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.7-sources.jar",
          "size": 38891,
          "sha512": "4cb679c2751fa6a5eb3e88893135baa330e9381f4da4a2587c77882a85579d52b78210c287a19d2d555c659bab265bcb1deca8e8669e8428c3314280321eef49",
          "sha256": "575e220e0eb3cf5e602f3846deb343eeea8b01f92fd6a1e8507e9ac25b0402f2",
          "sha1": "75345e33c899d17c1f0272133c4bcc7042f004fc",
          "md5": "fdaaa190c2b5c13a881eecdc9c29d443"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.7-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.7-dev-shadow.jar",
          "size": 1949174,
          "sha512": "05b75b165e00354d3331d0f19de441e628740fc28a4c59dc8804aa9817d72d155436ae2cd200f098ceea83d5715b2baaf5d58c1165b8ba6acb576117784420f7",
          "sha256": "049501ceb2eba2c1b8422260736b347702d164eb3ca237a3b8c55b917edf28ec",
          "sha1": "accf119e24e467858b9f65bf7ce917efee1d7497",
          "md5": "07b805b68007365f3d9b9ed0b34d751b"
        }
      ]
    }
  ]
}
