{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10.jar",
          "url": "horseman-1.21.1-fabric-1.3.10.jar",
          "size": 139555,
          "sha512": "be0f8e032932727a787fabdb96864ef085673afb33621572355d734cb4489f3b5ed85f5e5a29d70f0c9c56a777a9e9eaf15d186af4ad0b266f20471e23420557",
          "sha256": "1be40d0472bce3a7f9357b79e429f6ae922b5fedf2af80f4d8e8c86bcca85b39",
          "sha1": "82c6ba7ab66132bcd1d09c39de0400febe29b9c4",
          "md5": "8be34b0c85f7d85b6d7cb54446a949d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10.jar",
          "url": "horseman-1.21.1-fabric-1.3.10.jar",
          "size": 139555,
          "sha512": "be0f8e032932727a787fabdb96864ef085673afb33621572355d734cb4489f3b5ed85f5e5a29d70f0c9c56a777a9e9eaf15d186af4ad0b266f20471e23420557",
          "sha256": "1be40d0472bce3a7f9357b79e429f6ae922b5fedf2af80f4d8e8c86bcca85b39",
          "sha1": "82c6ba7ab66132bcd1d09c39de0400febe29b9c4",
          "md5": "8be34b0c85f7d85b6d7cb54446a949d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.10-sources.jar",
          "size": 17899,
          "sha512": "6a8f75b2ed2fced6c785ff34b781f556127e703ecf78ee8da4c35d3bf428550d18f499346f896355d5042c43eede11747359e0cd4a19fc8a40df25cb7267f4e4",
          "sha256": "faf44a325c499fd8597842c7671df581e7960c7cbe4c02d80edc3c8d9caeb5ec",
          "sha1": "2154a0c42ff5040b8de7bad76d1c8a5899ea7c90",
          "md5": "ae43ddc86d5e284377ff394f922ad5cb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.10-dev-shadow.jar",
          "size": 138083,
          "sha512": "b7b1aff3068e61689df1e12a6bffbe59308fb02b53d1213cec4a15a740a6d14aa1263e4bb91fefbe2b0e7aee6e0322f6e1271005ac40917e107fec4c2928c41e",
          "sha256": "f921a2e97d6c8d1f978dc3e8246cbb8110633be31ac576bc4ce0d597f79456f2",
          "sha1": "05cdf4b30117144e598fd522cd7290fb8ef2cfc8",
          "md5": "e855ad386087aec47b35a9aab53c6c44"
        }
      ]
    }
  ]
}
