{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10.jar",
          "url": "horseman-1.21.1-fabric-1.3.10.jar",
          "size": 197975,
          "sha512": "52fed1350b6d0cf359af2da11cef8794db07fc7dac04e322b34a16d734b52476268c050af777e369649f7ee7e238cb859ebcc8011a578889d49895460d311f66",
          "sha256": "5a813b5ab524a68f22ad81dc07c2dc8792eb1cf87f83690fc7a4d58f2be2c789",
          "sha1": "84e0554ad4be04912b7b66a79cf0e4b48ddd758b",
          "md5": "902ff510e2d0fb4c0c97e4bf6d586ac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10.jar",
          "url": "horseman-1.21.1-fabric-1.3.10.jar",
          "size": 197975,
          "sha512": "52fed1350b6d0cf359af2da11cef8794db07fc7dac04e322b34a16d734b52476268c050af777e369649f7ee7e238cb859ebcc8011a578889d49895460d311f66",
          "sha256": "5a813b5ab524a68f22ad81dc07c2dc8792eb1cf87f83690fc7a4d58f2be2c789",
          "sha1": "84e0554ad4be04912b7b66a79cf0e4b48ddd758b",
          "md5": "902ff510e2d0fb4c0c97e4bf6d586ac5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.10-sources.jar",
          "size": 18374,
          "sha512": "d1f2b0f36154beb6dee31b1f5b52ae08035fe6a7122a549b963498c180ff37b17fb00aee43a2d09470c2d9d43e0c76ee3d19867c91a2c8f3a18d6e14412fef62",
          "sha256": "4153496982e7da9fef0d527d291a43c4d2f630abcc269130ef89d777b94ae628",
          "sha1": "accb596b97fbf92d5a48e3e5293cf1ba5b5247e5",
          "md5": "40a7d84b4f200ccbbde53c1d1b62d31b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.10-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.10-dev-shadow.jar",
          "size": 196136,
          "sha512": "458c0183d71da37c9755f1ba662807fca60df18120bee6f8269d474cb6111ee55486682f3747c1ef005e02ecca6c4a9a9dd854a2600516ee583ab6af6d4906fd",
          "sha256": "f244963d765fb402d40cae90df29c8782558102971b01739e62b15fefee2f405",
          "sha1": "50e1248201cecb218470d1804c5ac7caa4a0ae04",
          "md5": "3ff3758c281a086d9c479c6579d9e7bb"
        }
      ]
    }
  ]
}
