{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.6-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.6-forge.jar",
          "size": 335092,
          "sha512": "ed88232d007e2667a3ae554dbbb5917fa4b5c12b9c443c30ac1f8237f8f70498881542d04589942fb9a656d4def86561667d8806658c7538fd9e2ecb7bc502ce",
          "sha256": "62d8757c63b2ac4dde3d87e34208b553db877d40fa0fea8623cd65cc71115c54",
          "sha1": "c76c1ba5b5a716db601469b2292287d3dfa5cdf0",
          "md5": "916b521fa3a8f25b9ab1ad74a9c0a141"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.6-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.6-forge.jar",
          "size": 335092,
          "sha512": "ed88232d007e2667a3ae554dbbb5917fa4b5c12b9c443c30ac1f8237f8f70498881542d04589942fb9a656d4def86561667d8806658c7538fd9e2ecb7bc502ce",
          "sha256": "62d8757c63b2ac4dde3d87e34208b553db877d40fa0fea8623cd65cc71115c54",
          "sha1": "c76c1ba5b5a716db601469b2292287d3dfa5cdf0",
          "md5": "916b521fa3a8f25b9ab1ad74a9c0a141"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.6-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.6-sources.jar",
          "size": 90590,
          "sha512": "68af64c6120cbeac1ef07479a3fdc5bbe6cdd1bc2529913dd926e5a3cf909a91f37186c60329cda436cc7b9ebb4a9c921b557ff3daf8d23c70c9bca5d4c97f40",
          "sha256": "9a7d7a6f1277751a5116bc9e5d52792bcbb257cf81e1b3c93abcc0f8feccb6ec",
          "sha1": "c3e5e2ee098602531e53499e9185521aa1c3f0e4",
          "md5": "3649ca92d4491d2763b6b3fec8eb3f83"
        }
      ]
    }
  ]
}
