{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-common",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-common-1.9.2.jar",
          "url": "exposure-1.21.1-common-1.9.2.jar",
          "size": 1901700,
          "sha512": "ae965c23240007c73db3e54cd1a93f94f61115a807dfc3b82601bdfc36c941d498bc67131080c2e80fb1f46591eebec7a8fdfbe77e43f225d67ece4cb6897fc1",
          "sha256": "d58d3ef580d449b8d713a436bc21303f11693cc730cc1dd1fb53f89dfdb560c6",
          "sha1": "2534ce49d8874ebd7d50c0399223f8f41c0135f6",
          "md5": "827e689affe261dca75c05f066f47cd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-common-1.9.2.jar",
          "url": "exposure-1.21.1-common-1.9.2.jar",
          "size": 1901700,
          "sha512": "ae965c23240007c73db3e54cd1a93f94f61115a807dfc3b82601bdfc36c941d498bc67131080c2e80fb1f46591eebec7a8fdfbe77e43f225d67ece4cb6897fc1",
          "sha256": "d58d3ef580d449b8d713a436bc21303f11693cc730cc1dd1fb53f89dfdb560c6",
          "sha1": "2534ce49d8874ebd7d50c0399223f8f41c0135f6",
          "md5": "827e689affe261dca75c05f066f47cd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-common-1.9.2-sources.jar",
          "url": "exposure-1.21.1-common-1.9.2-sources.jar",
          "size": 1275533,
          "sha512": "2840db51ef22905962d3bb3d7910a98a2d49f6b6827ea7600be9849964d2a5bcae7f52e90ccec022f40d240ca9adebbfd314f51bfdfec811a30be5adfb747f69",
          "sha256": "44067061afd9764bfdbc0fda67fca6de1a727703a7934c411983ee17480eb20f",
          "sha1": "9572f50fae6ce157d323d21bcdbc1e9212209016",
          "md5": "ee68071b07a86aaac480c189e6ce9bf3"
        }
      ]
    }
  ]
}
