{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.mortaar",
    "module": "mortaar-1.21.1-common",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-common-1.5.3.jar",
          "url": "mortaar-1.21.1-common-1.5.3.jar",
          "size": 140791,
          "sha512": "baeb43423f1c0bdb0eefa46fa7e1aae5da7892150d1fb90ea8d41b0abc24114f839994ea40cce55948b9990ee58654c2b84c092a254cca79b2410726e37770da",
          "sha256": "aea7d8829fecf3a21cba0ab74fb2c155faa4e7b208a5d69019e464aa3df55c63",
          "sha1": "de0c0fdd532b9633462fe1f4ab86f602e937ab7e",
          "md5": "0d62f0f4a23b7437376b60f7bf8b63fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "mortaar-1.21.1-common-1.5.3.jar",
          "url": "mortaar-1.21.1-common-1.5.3.jar",
          "size": 140791,
          "sha512": "baeb43423f1c0bdb0eefa46fa7e1aae5da7892150d1fb90ea8d41b0abc24114f839994ea40cce55948b9990ee58654c2b84c092a254cca79b2410726e37770da",
          "sha256": "aea7d8829fecf3a21cba0ab74fb2c155faa4e7b208a5d69019e464aa3df55c63",
          "sha1": "de0c0fdd532b9633462fe1f4ab86f602e937ab7e",
          "md5": "0d62f0f4a23b7437376b60f7bf8b63fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mortaar-1.21.1-common-1.5.3-sources.jar",
          "url": "mortaar-1.21.1-common-1.5.3-sources.jar",
          "size": 64622,
          "sha512": "0c7c469eec2ffa5a9fff74dac4f09760a6068fc615aa429756af6bb84ab77de39374197cf60526ee44516bb407e63ef1ab67b9fc63b8e6bc76380086023ef270",
          "sha256": "a1b202a30233d760a01589ca77b0ad83710cd6673aced7a1f8788016d7cf41f0",
          "sha1": "98720c796589c60fd6fe4fc977716f51035c8c41",
          "md5": "ea1efadc0244f74b78cdc2bd4461ebd3"
        }
      ]
    }
  ]
}
