{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.2.jar",
          "url": "horseman-1.21.1-common-1.3.2.jar",
          "size": 115810,
          "sha512": "93b9384a778441e7443821b3446f70d5545825558e3acfbf778a97b2c320a4d7c29c44c6ef8a8e2a823465a3154c76d0f3628e80edff18c9ce005d411f8e298d",
          "sha256": "7d5f30a5bc20a193920d2ae23fcd603048b4dfd7e0aaff3117bbc6fee139f6a6",
          "sha1": "8af2ec42b4275b0ab5356d1cd901f69707d9baf2",
          "md5": "499d4850ac2d9cc458ad57fddee1faf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.2.jar",
          "url": "horseman-1.21.1-common-1.3.2.jar",
          "size": 115810,
          "sha512": "93b9384a778441e7443821b3446f70d5545825558e3acfbf778a97b2c320a4d7c29c44c6ef8a8e2a823465a3154c76d0f3628e80edff18c9ce005d411f8e298d",
          "sha256": "7d5f30a5bc20a193920d2ae23fcd603048b4dfd7e0aaff3117bbc6fee139f6a6",
          "sha1": "8af2ec42b4275b0ab5356d1cd901f69707d9baf2",
          "md5": "499d4850ac2d9cc458ad57fddee1faf7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.2-sources.jar",
          "url": "horseman-1.21.1-common-1.3.2-sources.jar",
          "size": 68710,
          "sha512": "82f99e2c58b8f317065dbd1d3b21ec41f020fd6cf29a9df14f62e3e6c722b439bb47d55251479a262b9123e8a2a0cd09bc0b1dd78f105bd40c8e2f46a31a8364",
          "sha256": "ab87ce6a603b3fe32eecbeb24eda9670b5962e671e39c527315516f802bedb01",
          "sha1": "f4f6c127536518bf1d937a9890d8dbb92a072aeb",
          "md5": "7a1e4957588821d0a5d2c4781adeb36c"
        }
      ]
    }
  ]
}
