{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.4.jar",
          "url": "sootychimneys-1.21.1-common-1.3.4.jar",
          "size": 161272,
          "sha512": "43eab9381952c757461b7f59355b6a411059c88d8cb8a37b0619db49e4e0e62c61100eede56b329cef65a2d65f8df93801bb4f472075c5154166801820fceaca",
          "sha256": "70888bfc417ee006e18135ac587d155fd21002f374818819a29c49f8d807124d",
          "sha1": "da701f6b63f65e6af448723f29b93da033dc578f",
          "md5": "01c62f64a89075d9d263c88580da8773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.4.jar",
          "url": "sootychimneys-1.21.1-common-1.3.4.jar",
          "size": 161272,
          "sha512": "43eab9381952c757461b7f59355b6a411059c88d8cb8a37b0619db49e4e0e62c61100eede56b329cef65a2d65f8df93801bb4f472075c5154166801820fceaca",
          "sha256": "70888bfc417ee006e18135ac587d155fd21002f374818819a29c49f8d807124d",
          "sha1": "da701f6b63f65e6af448723f29b93da033dc578f",
          "md5": "01c62f64a89075d9d263c88580da8773"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.1-common-1.3.4-sources.jar",
          "size": 117246,
          "sha512": "ad8e3bb996cfcebaaca8245f6b42cf5d39f606ef5642ffd066f356c06b1c65eeead2a0e72758668d3a90b540b7d98838f217327d2983a194c467a461db29f262",
          "sha256": "0881ac588e775cbbd063ef76af1876ed622d18e82daaec4ec7d25e2ee963c4d9",
          "sha1": "f3086140f8cfd3a4f635ac0b40a302b1e1a84fa2",
          "md5": "6a37f5b9eb988e5e5468818cdf0bf18e"
        }
      ]
    }
  ]
}
