{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.15-fabric.jar",
          "url": "exposure-fabric-1.7.15-fabric.jar",
          "size": 1342701,
          "sha512": "fe3a3d767e31f891f2bc787a2e1e522378f12b3199679a214afb89fd0f3159f5bdeb182f0bc4aaad3d324ed884db9f5ab9554b2255f0224e9957da1a7a13f287",
          "sha256": "7ab4934f1bf5ef5656e14a7622d72270157ba793ade3046f1f32f7135ac38335",
          "sha1": "3cd1b954b2d4784a3925626b262f0fae9cf7f958",
          "md5": "1e60e3075580aabd9e7f3e448700819c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.20.1-0.5.13-fabric"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.15-fabric.jar",
          "url": "exposure-fabric-1.7.15-fabric.jar",
          "size": 1342701,
          "sha512": "fe3a3d767e31f891f2bc787a2e1e522378f12b3199679a214afb89fd0f3159f5bdeb182f0bc4aaad3d324ed884db9f5ab9554b2255f0224e9957da1a7a13f287",
          "sha256": "7ab4934f1bf5ef5656e14a7622d72270157ba793ade3046f1f32f7135ac38335",
          "sha1": "3cd1b954b2d4784a3925626b262f0fae9cf7f958",
          "md5": "1e60e3075580aabd9e7f3e448700819c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.15-sources.jar",
          "url": "exposure-fabric-1.7.15-sources.jar",
          "size": 979825,
          "sha512": "414fe452e861c1da3856a609a727931f5618f3cd574de675d7fe6bc981ed032f5b975fa4bb6b0535e2900f2eaf8ed3443eef4ab6e86ccd053fa31823e8225c8b",
          "sha256": "30e16372e64ff7547f65c1c1ce37b5a8876b972b1d37b0aefb1d922c489609d5",
          "sha1": "d992eb566e8fb15667e1853c09ec223cd054fc25",
          "md5": "020e5afab5115d72e375c5d70fd1cf39"
        }
      ]
    }
  ]
}
