{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.0-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.0-fabric.jar",
          "size": 461002,
          "sha512": "725aa20050dabd9110197ee9251f5de22a1d6a22de8a4e9df8d91b9ca4a57cdfbba0460c0c0678f6e2dcaf1fe9a577330098957a0a051b6a82923f56b4a82a7a",
          "sha256": "c06116d582a0da41e4625b04c1c91eb4704c582113382d49a972b14f180f19b1",
          "sha1": "26dfa6cce8a60c15626ec2e6b5637a018a75bc17",
          "md5": "0b74e672a652d3c6bbddc963c305af83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.25"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.0-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.0-fabric.jar",
          "size": 461002,
          "sha512": "725aa20050dabd9110197ee9251f5de22a1d6a22de8a4e9df8d91b9ca4a57cdfbba0460c0c0678f6e2dcaf1fe9a577330098957a0a051b6a82923f56b4a82a7a",
          "sha256": "c06116d582a0da41e4625b04c1c91eb4704c582113382d49a972b14f180f19b1",
          "sha1": "26dfa6cce8a60c15626ec2e6b5637a018a75bc17",
          "md5": "0b74e672a652d3c6bbddc963c305af83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.0-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.0-sources.jar",
          "size": 185221,
          "sha512": "cd199b3c27ef346b7072aef0257ab81ae52ed49618b6c2e661ccf5b077d8c3df7bf1ac64fb2717f5bf4e968d281049cffe7ae3ea9409c5ca0b3c890389a21035",
          "sha256": "c76723ea6c43619592c865bca6d641edc562d034108560c65a16aa7e1035b34d",
          "sha1": "f3d6442bd412c43674a009ffcf53857e05c8d02d",
          "md5": "5f40dadaac55070c1f00527b5d1075f7"
        }
      ]
    }
  ]
}
