{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.1.0-fabric.jar",
          "url": "thief-1.20.1-fabric-1.1.0-fabric.jar",
          "size": 311583,
          "sha512": "305a34476b22986a3d7df4e077da99bf00eee30cdbdd450b589dbf76a5f308d63a84728ce2081aafc5e85f65cc52390659971af826c5b79637484dce75ea03bc",
          "sha256": "584058728733ebb775e49e56d36c72307b1cc46dfa7d8bb9c36bcbbd7fffb8b3",
          "sha1": "1502cbece8f235c8b08518f21195a99e4ef98202",
          "md5": "7047d6f9ce40036723a92db1fe0f24b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.1.0-fabric.jar",
          "url": "thief-1.20.1-fabric-1.1.0-fabric.jar",
          "size": 311583,
          "sha512": "305a34476b22986a3d7df4e077da99bf00eee30cdbdd450b589dbf76a5f308d63a84728ce2081aafc5e85f65cc52390659971af826c5b79637484dce75ea03bc",
          "sha256": "584058728733ebb775e49e56d36c72307b1cc46dfa7d8bb9c36bcbbd7fffb8b3",
          "sha1": "1502cbece8f235c8b08518f21195a99e4ef98202",
          "md5": "7047d6f9ce40036723a92db1fe0f24b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.1.0-sources.jar",
          "url": "thief-1.20.1-fabric-1.1.0-sources.jar",
          "size": 74486,
          "sha512": "bc779db3deff5276743df2a70623bcf24315eab0861bd9092c59b1607cddddad15dcadc1e9ac8f30296c47b4057dc730eec6fe757cc9f8e054eb12a60853bb32",
          "sha256": "103dba7c924c0bcf4337bc9c8dd4299af5ef30926f41d3c69d7d062b3d1351be",
          "sha1": "9891cb15f60316f4185b8b4a597889a28a95f18b",
          "md5": "decc6064adc57a38d0ea6ddb093dad3b"
        }
      ]
    }
  ]
}
