{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.7.jar",
          "url": "exposure-neoforge-1.21.1-1.8.7.jar",
          "size": 1925512,
          "sha512": "9cbc945ccedea049a7bd7e2fb6fda7a8b19db2f859f7d03a6986ee70e20d0ace8736ab1183dbccf38e4ec57886dd0324ba6be9ca1421230335908527b29ab23c",
          "sha256": "e230e7fc6b4e7e2fe5805bede9490c3c7cbae1946a0f6859e173856a61b4e4fc",
          "sha1": "81464ebf3e6cc47606d024ecdf22bdebc18fe3b3",
          "md5": "fcb5da47d41c379ffe1b3415686dd2ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.7.jar",
          "url": "exposure-neoforge-1.21.1-1.8.7.jar",
          "size": 1925512,
          "sha512": "9cbc945ccedea049a7bd7e2fb6fda7a8b19db2f859f7d03a6986ee70e20d0ace8736ab1183dbccf38e4ec57886dd0324ba6be9ca1421230335908527b29ab23c",
          "sha256": "e230e7fc6b4e7e2fe5805bede9490c3c7cbae1946a0f6859e173856a61b4e4fc",
          "sha1": "81464ebf3e6cc47606d024ecdf22bdebc18fe3b3",
          "md5": "fcb5da47d41c379ffe1b3415686dd2ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.7-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.7-sources.jar",
          "size": 36117,
          "sha512": "e0916c34967bac33bc0b2a2ef1a2bf41f7654fe815995f331ef2921dd470abe4240727c21668e3a08da9febcd433509fb5f7a612aac6833e4b6c3b06afb918ad",
          "sha256": "c4d4c3447e46ba8ebd87ba02cee0d9255a3e1331e1904cf8efe3ae09ac929b1f",
          "sha1": "05cfb12df424de417398fc9874266e56fd1ce8e0",
          "md5": "a8a969938a3e0c153a6f71800567361a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.7-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.7-dev-shadow.jar",
          "size": 1712031,
          "sha512": "7a81b7b0f3edce4aee74937d8739f55754ebeee6f3256c7732f553f6cc8469cce20182d50e2ab1145565eb06e8cd44584bcc527f9c17952d9707bc60bbd3b95b",
          "sha256": "0b487f5b8183b2a357eea5cce9f446b00536d4debd0c092d195ba5564e5954eb",
          "sha1": "fbb7201dbff371c1a76ab9c59d7418b7caac8b9d",
          "md5": "d3d77145318e7c22084597972e3a3ef7"
        }
      ]
    }
  ]
}
