{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-neoforge",
    "version": "1.21.1-1.8.5-snapshot6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot6.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot6.jar",
          "size": 1923583,
          "sha512": "5ffd1ccef12bafb4af9e19b6000eeee676ad7ad7564ea49d3b1f5a180a23744e75ed35df69bc6376b6cb68a195de941a3d85c1d6e6e065900d1707c0f21763d0",
          "sha256": "109b4d999b9e2592d3225a5674ed99163b3174045b3ba511f5d98d968d5b230f",
          "sha1": "51412fc23445a8b990f82efd8ad5a3c275de7be7",
          "md5": "d424cf09993ea5b6a946f96044b135f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot6.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot6.jar",
          "size": 1923583,
          "sha512": "5ffd1ccef12bafb4af9e19b6000eeee676ad7ad7564ea49d3b1f5a180a23744e75ed35df69bc6376b6cb68a195de941a3d85c1d6e6e065900d1707c0f21763d0",
          "sha256": "109b4d999b9e2592d3225a5674ed99163b3174045b3ba511f5d98d968d5b230f",
          "sha1": "51412fc23445a8b990f82efd8ad5a3c275de7be7",
          "md5": "d424cf09993ea5b6a946f96044b135f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot6-sources.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot6-sources.jar",
          "size": 36413,
          "sha512": "75b6e6771ac5d54598b4522e6c89f589ab6b989d053cdf9b8765140fa32f142b12ad82fe08eef5dfaee6ddfcf8aafec738c26d474335b8fae214c5d44732221d",
          "sha256": "fa61b7a2359fdf63041c66cfb3af28d98ba5f13aeed1e511fc3bbfbf28c81fc0",
          "sha1": "e33abd81fd5c553f0e9263c2f753468f0d75dbaa",
          "md5": "17079b6eff70f02ab2ab1d3b0eecf002"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-neoforge-1.21.1-1.8.5-snapshot6-dev-shadow.jar",
          "url": "exposure-neoforge-1.21.1-1.8.5-snapshot6-dev-shadow.jar",
          "size": 1710177,
          "sha512": "0bdc9370a5ec7d490fad26c4b0bb762cea00f21208cbfad753949edffef4308089176aff3ad84c8cac7613206e78aadd2bbb4f6223755780fce2e47b4528ec0e",
          "sha256": "7c286004c4ef44c27febdfb49a73188e862dc68c62c5057caf5d89bec66916a3",
          "sha1": "34a878d40a8073de8d383bf3a66cc385ff5203ec",
          "md5": "61f8562a387d40c1cae56ded3f5f73b1"
        }
      ]
    }
  ]
}
