{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-26.1.2-fabric",
    "version": "1.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.2-fabric-1.2.5.jar",
          "url": "thief-26.1.2-fabric-1.2.5.jar",
          "size": 157002,
          "sha512": "5be1f3272b2eb84e786b24d7e2f3b940701d5963fef3b4146ef5ed7f732e6ad1869064c7f9f60cd372daedff0c96f0abd90785b130177a10ed77a22953917495",
          "sha256": "91a1c4c5f4023b8b6ae3a96fe2338fdb01d77c55eb9acba20aaa0c6bef643d2c",
          "sha1": "1a2e74a227251acbf6ceac668dbc1c0e2f2005e6",
          "md5": "b0122f73dd8d53b228920f1d299b3a86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.2-fabric-1.2.5.jar",
          "url": "thief-26.1.2-fabric-1.2.5.jar",
          "size": 157002,
          "sha512": "5be1f3272b2eb84e786b24d7e2f3b940701d5963fef3b4146ef5ed7f732e6ad1869064c7f9f60cd372daedff0c96f0abd90785b130177a10ed77a22953917495",
          "sha256": "91a1c4c5f4023b8b6ae3a96fe2338fdb01d77c55eb9acba20aaa0c6bef643d2c",
          "sha1": "1a2e74a227251acbf6ceac668dbc1c0e2f2005e6",
          "md5": "b0122f73dd8d53b228920f1d299b3a86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.2-fabric-1.2.5-sources.jar",
          "url": "thief-26.1.2-fabric-1.2.5-sources.jar",
          "size": 85068,
          "sha512": "d1afbf00811fb7003c5d454487482a6e48ac4a411ec3f967e902befc642b0030473b3858cf0c36891909a525024c44944650335abc074a1955a6783513e4d3d5",
          "sha256": "621bc2212914c1a9bc8ea670d28dafb47e3ead403009e8cc36ff4a1c7b3bc991",
          "sha1": "cfff050f7a49d9bfc6306bfbbb43d7395dd31b8b",
          "md5": "28aa099aebdc05a6a05122ff62a4da7f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.2-fabric-1.2.5.jar",
          "url": "thief-26.1.2-fabric-1.2.5.jar",
          "size": 157002,
          "sha512": "5be1f3272b2eb84e786b24d7e2f3b940701d5963fef3b4146ef5ed7f732e6ad1869064c7f9f60cd372daedff0c96f0abd90785b130177a10ed77a22953917495",
          "sha256": "91a1c4c5f4023b8b6ae3a96fe2338fdb01d77c55eb9acba20aaa0c6bef643d2c",
          "sha1": "1a2e74a227251acbf6ceac668dbc1c0e2f2005e6",
          "md5": "b0122f73dd8d53b228920f1d299b3a86"
        }
      ]
    }
  ]
}
