{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.11.jar",
          "url": "exposure-1.21.1-neoforge-1.8.11.jar",
          "size": 1926502,
          "sha512": "dd14630a72d1bc9bcb9a7611871aa76a56c78ed758408f520407312eac03abfdd2747fb6ec3c9b9114e3d21e4a62f9cf73d8560b1a92e7cdaa64b627fb78c35c",
          "sha256": "8f94452b73c5bfa7c89836e37b33a37bc6cd0b18550f2503ae3009fd3bbd4381",
          "sha1": "2d4865716d5dfd9933841798ce9e7ba194a8109c",
          "md5": "11cf1cec348df9714ac5b8244a972c37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.11.jar",
          "url": "exposure-1.21.1-neoforge-1.8.11.jar",
          "size": 1926502,
          "sha512": "dd14630a72d1bc9bcb9a7611871aa76a56c78ed758408f520407312eac03abfdd2747fb6ec3c9b9114e3d21e4a62f9cf73d8560b1a92e7cdaa64b627fb78c35c",
          "sha256": "8f94452b73c5bfa7c89836e37b33a37bc6cd0b18550f2503ae3009fd3bbd4381",
          "sha1": "2d4865716d5dfd9933841798ce9e7ba194a8109c",
          "md5": "11cf1cec348df9714ac5b8244a972c37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.11-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.8.11-sources.jar",
          "size": 36118,
          "sha512": "94263dfec014830cf37f43d463963ecebdf614dfbf1806923fdab00cbbefb9c1c786541dd19b9d6a20f01067976ac2f49649dec472fdbd79dd5363dbfd133285",
          "sha256": "ec77fed380c62faa14839bd67f7feec38b9755aa9aa370f8cc6039279a5cb3ae",
          "sha1": "7fc9f9201fa14007e4ce50cc3555a92e54c1a319",
          "md5": "4ee24ced308499e6e62aec1b9a72603c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.8.11-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.8.11-dev-shadow.jar",
          "size": 1713003,
          "sha512": "6f41fcc1c7ddbcd63811c54a6ff36a8bdf237bb7cc16183417400aaf9420d576bb032ddc8f26124eb3161d182eb6b4599c396b45d8210a8deb566b7596ad6a8a",
          "sha256": "e7e54ddad578338e38b4b1b9f347f1c1e74e390cacd510cc1b3be26f33b1c4f4",
          "sha1": "64f5049a9e3bb45068c8421cbb7d5692cf2488e3",
          "md5": "5092b8d62ecb84fb2eb629b0e4bf9f1c"
        }
      ]
    }
  ]
}
