{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-fabric",
    "version": "1.21.1-1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.2.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.2.jar",
          "size": 160867,
          "sha512": "6fb985954d0b412cc6197dc909554c9f840f0495ffbdd50790a04770a475de4072c1aa9f524491a49ad60d6123fda36743ea5da3e367e27f4ef54e075014bd12",
          "sha256": "a510309cfe3e57001a78cafff20c23c37de7c83794539234ae23e2d49c80f9ca",
          "sha1": "e8ae8afc39125c933bd1327508a5ac821b8a5c4f",
          "md5": "e857533c9068e4b040aee0e476054356"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-fabric",
          "version": {
            "requires": "1.21.1-1.8.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.2.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.2.jar",
          "size": 160867,
          "sha512": "6fb985954d0b412cc6197dc909554c9f840f0495ffbdd50790a04770a475de4072c1aa9f524491a49ad60d6123fda36743ea5da3e367e27f4ef54e075014bd12",
          "sha256": "a510309cfe3e57001a78cafff20c23c37de7c83794539234ae23e2d49c80f9ca",
          "sha1": "e8ae8afc39125c933bd1327508a5ac821b8a5c4f",
          "md5": "e857533c9068e4b040aee0e476054356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.2-sources.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.2-sources.jar",
          "size": 11531,
          "sha512": "6776c07b0965491883fed0d033cf1f5e5ae5718795ca7bb2afc51422d6e2e12e446ee1de4643ddb3013172f53801b8e59245c894d4a394ec21fd4d553f4d2346",
          "sha256": "7af31fecbb9a43d39589c3dd68a6a390ea8bae44be943b3e28c8ba97a2240dde",
          "sha1": "5af2d153e4428889456157990595119c00445837",
          "md5": "bfd023e1369458bec508757bf5448d8a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.21.1-1.1.2-dev-shadow.jar",
          "url": "exposure_catalog-fabric-1.21.1-1.1.2-dev-shadow.jar",
          "size": 147401,
          "sha512": "eece7c900ab412234aac2f3df8e2b4e69deb5dd5e5da9092b5c29bb6cee438607c1b9c8879d018d0112f9984336731b0d172ef5d28bd44483b9de4ccc4adad81",
          "sha256": "312981313847d310d0d9c4d5a203afc6549bb4956003a5aadcc557297919a4e0",
          "sha1": "c4bc9075e03e67eedd5acbaa84e199d19b21e5b5",
          "md5": "33607acc1fb48e717cb0466df36e3fe9"
        }
      ]
    }
  ]
}
