{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.9.jar",
          "url": "exposure-common-1.7.9.jar",
          "size": 1282458,
          "sha512": "a03e83955afb1ba5dfca8a5c52eaaa52ce3c21d117a1cb24890dbc9d737044e521644672ab766399f96c523819807a4d5724cfb9dab80b1d95a6a5a0f3f0c543",
          "sha256": "66511b712f5c117d18d3a85409085f0bbd588b290aa0c87b323a2d063078177c",
          "sha1": "3cb146f85c073270acc2ec70aaa4d9364ce269ed",
          "md5": "a19b5a68494acb1a2fd691490563ed2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.9.jar",
          "url": "exposure-common-1.7.9.jar",
          "size": 1282458,
          "sha512": "a03e83955afb1ba5dfca8a5c52eaaa52ce3c21d117a1cb24890dbc9d737044e521644672ab766399f96c523819807a4d5724cfb9dab80b1d95a6a5a0f3f0c543",
          "sha256": "66511b712f5c117d18d3a85409085f0bbd588b290aa0c87b323a2d063078177c",
          "sha1": "3cb146f85c073270acc2ec70aaa4d9364ce269ed",
          "md5": "a19b5a68494acb1a2fd691490563ed2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.9-sources.jar",
          "url": "exposure-common-1.7.9-sources.jar",
          "size": 924907,
          "sha512": "b20bff6ccd54fb9b7b75e41d2e52e96c72a7f602f8a293509c604221d87fbf86b861e7e8032517103e18f70bb317159f4f0907d36bc0c3686e642f2882cd7176",
          "sha256": "b968a3b0bda2b51eb310f637b7f9d9f9d3223c5364d48d45518a649cc6781399",
          "sha1": "256f4e189b8f7caa975c41708235fd2e45829941",
          "md5": "1a7b801d7ec48492c137465da876f867"
        }
      ]
    }
  ]
}
