{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.2.jar",
          "url": "scholar-1.20.1-common-1.1.2.jar",
          "size": 264464,
          "sha512": "ce7cb7af71ba6656437ffc89a670be6a26c443047559dd951de1804696b560f28b36f5e135fc47f8304afff562e4e7c21d78c6a2af8a471ffde0f630958038b8",
          "sha256": "b4ee6ec720d7254fd5ef1d0e2fd523e3fd488757a11f66149d9dc679a90b746e",
          "sha1": "278581c3ba3cfe4e1ab6399a3e11680c8677cc7f",
          "md5": "dfacb0f8f05544ad0fad5221ca17419a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.25"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.2.jar",
          "url": "scholar-1.20.1-common-1.1.2.jar",
          "size": 264464,
          "sha512": "ce7cb7af71ba6656437ffc89a670be6a26c443047559dd951de1804696b560f28b36f5e135fc47f8304afff562e4e7c21d78c6a2af8a471ffde0f630958038b8",
          "sha256": "b4ee6ec720d7254fd5ef1d0e2fd523e3fd488757a11f66149d9dc679a90b746e",
          "sha1": "278581c3ba3cfe4e1ab6399a3e11680c8677cc7f",
          "md5": "dfacb0f8f05544ad0fad5221ca17419a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.2-sources.jar",
          "url": "scholar-1.20.1-common-1.1.2-sources.jar",
          "size": 170552,
          "sha512": "cc3857622a886c43fae3747da7f90240c587ea678a0f3046d9ed7adce95ee9671bf936a35600ccf9773a11ace1ac4f2cc59a18bb3602d1be2de7d0284599036e",
          "sha256": "61b05598285af6dfb0e68766c22ad3a7452dfa720b1d40381c2f6e4c44814786",
          "sha1": "8b51b6536013a445322df914d21a777c5a0865d8",
          "md5": "24ecc3a0a5e81c0553d29b357ed5a914"
        }
      ]
    }
  ]
}
