{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.8-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.8.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.8-common-api",
          "version": {
            "requires": "24.2.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.8-common-1.3.4.jar",
          "url": "sootychimneys-1.21.8-common-1.3.4.jar",
          "size": 164615,
          "sha512": "6a962585e8d68ea47f68076882f0b9aec55c1b4a63f3871c205e8e7e34009f8af70df97413055cbda27d50ffcd76c6982cf96357d11d3fe285946cfd236fe7b7",
          "sha256": "b7cd28598b11f4a6554507642f4c455b8a220d876a08d25620abb3512444a61a",
          "sha1": "cd7f2f24b91cd15e954d39b28dd84b5b73570f15",
          "md5": "069fcf130a3c1dc8fa7a7819ceda67ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.8-common-1.3.4.jar",
          "url": "sootychimneys-1.21.8-common-1.3.4.jar",
          "size": 164615,
          "sha512": "6a962585e8d68ea47f68076882f0b9aec55c1b4a63f3871c205e8e7e34009f8af70df97413055cbda27d50ffcd76c6982cf96357d11d3fe285946cfd236fe7b7",
          "sha256": "b7cd28598b11f4a6554507642f4c455b8a220d876a08d25620abb3512444a61a",
          "sha1": "cd7f2f24b91cd15e954d39b28dd84b5b73570f15",
          "md5": "069fcf130a3c1dc8fa7a7819ceda67ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.8-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.8-common-1.3.4-sources.jar",
          "size": 106934,
          "sha512": "e6e36ce732e4b74760c7f8240b10306073d3076496f89c3d10621bcdaaa2b3e85815bf8dbf7d3e2e60e16160d3dd0df0b8e81fece3a3c9638248e02cd4e6efd7",
          "sha256": "b8ce9f68477b3e68c2168149b2af1d1687485906cfeee8abef6447ad69bd9464",
          "sha1": "376c09eaec406c3b944d34dc84c0f5d248d265e1",
          "md5": "c10d1f8c2e02b013e95d485ed7ddcda1"
        }
      ]
    }
  ]
}
