{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.11.jar",
          "url": "horseman-1.20.1-common-1.3.11.jar",
          "size": 115199,
          "sha512": "ca52675d757699492449bb8d7b38a70339437c2f8381dc938c5d1c54319835d0f809fa65c3ecb2f09694207f8a204aec4bbf81be689056cd80e7a1fd05c81627",
          "sha256": "b4fa75f1b7d308500fac8102ac63f210c56cbf3c0a9c057227e720d25d33e5ae",
          "sha1": "6a35d38f34ca107b8f57fc6055c7cbad0fc96772",
          "md5": "e7a940bbfe49bfe654c931f10995d0a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.11.jar",
          "url": "horseman-1.20.1-common-1.3.11.jar",
          "size": 115199,
          "sha512": "ca52675d757699492449bb8d7b38a70339437c2f8381dc938c5d1c54319835d0f809fa65c3ecb2f09694207f8a204aec4bbf81be689056cd80e7a1fd05c81627",
          "sha256": "b4fa75f1b7d308500fac8102ac63f210c56cbf3c0a9c057227e720d25d33e5ae",
          "sha1": "6a35d38f34ca107b8f57fc6055c7cbad0fc96772",
          "md5": "e7a940bbfe49bfe654c931f10995d0a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.11-sources.jar",
          "url": "horseman-1.20.1-common-1.3.11-sources.jar",
          "size": 69733,
          "sha512": "e143e84f1ecefd4eca0d2858dce90608ec6832c04cd5d20cb878603947afacf44c96442305e30e6cb4bf85a9d0d2fc21d272c5047b33bfd93b43f7043f716024",
          "sha256": "9da12cbc854241302bb883496718ae6654d2c3483dd4a3f3a9a564a0c640b3a0",
          "sha1": "83a79d939adf599a65bd9a0b770fca23adad1627",
          "md5": "c1bc7b1ddd839889d787692e5394720a"
        }
      ]
    }
  ]
}
