{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.62.0.219"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.62.0.219"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.8-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.2.8-fabric.jar",
          "size": 835107,
          "sha512": "3fec535c7ab4731e4f4aae53f76ff1d5452e8fdbcff5c3ce90c25faa73623c7a7cb492b6f5229913fc4f3e9ed6c75ef39f94c25561fa04f881c92c2460e0bb83",
          "sha256": "d4e1cd20bf984958260436e2c543fe9257a4789d8b41f3c2fd89b226de66d409",
          "sha1": "08b211b199fb0bcd4972dca8267399a42babe0f4",
          "md5": "a51151602ebee0d0e1495ecb9c35e70f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.62.0.219"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.8-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.2.8-fabric.jar",
          "size": 835107,
          "sha512": "3fec535c7ab4731e4f4aae53f76ff1d5452e8fdbcff5c3ce90c25faa73623c7a7cb492b6f5229913fc4f3e9ed6c75ef39f94c25561fa04f881c92c2460e0bb83",
          "sha256": "d4e1cd20bf984958260436e2c543fe9257a4789d8b41f3c2fd89b226de66d409",
          "sha1": "08b211b199fb0bcd4972dca8267399a42babe0f4",
          "md5": "a51151602ebee0d0e1495ecb9c35e70f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.8-sources.jar",
          "url": "scholar-1.20.1-fabric-1.2.8-sources.jar",
          "size": 517382,
          "sha512": "0326d77556d147e63bb6a1ee93726250361a4f09dde7ca8f7b9ca7bee1e72245e7da26100fa74e83930603c14b0cf81fe77ce7c61f68faba1487fd49e41aa588",
          "sha256": "bbef07e9f52a46dd026eca3ff389155669e8be0beff82f98ba286679b6f8a161",
          "sha1": "2f97f15d80c9aad663d1967d77b0ec04ecaddee0",
          "md5": "4c9f0f62f504dcd06dd13cc86232ce48"
        }
      ]
    }
  ]
}
