{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "size": 315609,
          "sha512": "7ce8df610568acdce4f207e7255fc68547aa872cbe618d9e6f595713a209570e0e95124ba9bf4f3c74f94576e7a5c0ed43c48faae62a79006b45ce79663962d6",
          "sha256": "e766089b57a4278a54a2d2e539f06728430d79fe08b4287c01d50e3741668ad6",
          "sha1": "4c357364bd1099e8e1763039f09115cec2303a24",
          "md5": "7f87ac7386c4061f1fb7b4c240821929"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "size": 315609,
          "sha512": "7ce8df610568acdce4f207e7255fc68547aa872cbe618d9e6f595713a209570e0e95124ba9bf4f3c74f94576e7a5c0ed43c48faae62a79006b45ce79663962d6",
          "sha256": "e766089b57a4278a54a2d2e539f06728430d79fe08b4287c01d50e3741668ad6",
          "sha1": "4c357364bd1099e8e1763039f09115cec2303a24",
          "md5": "7f87ac7386c4061f1fb7b4c240821929"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.8-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.8-sources.jar",
          "size": 82346,
          "sha512": "5ab2d8b726bb0563680c5c121936714983c6d37e54b5b54853365bed923eb40284dbd9f8c0ae9f63b7f358b066220dcdb3dd4696390d0ddb8b30a75726a3d71f",
          "sha256": "aa3959ffd3f0e5f0fa822511d0cbe5d3245441bba9a0f888c316f033b0303ac7",
          "sha1": "55a8940fd8a94ebd3cc5ec4a3829df836a6f7a65",
          "md5": "5da6b440f398c762cb2970a8ebe8955b"
        }
      ]
    }
  ]
}
