{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "size": 314041,
          "sha512": "b1089cdaf3fa2547d69d1d2981ef824784a28da016bb899bc05320fc19d331d22df80278b561593d1e952fce1ca5c1dc02f51d4aa4d66b09632bbc7a87b1801e",
          "sha256": "4837302872bbbed4278a641546feaaa6311ed6f362d08bc54154145d31268583",
          "sha1": "8ffd5315bfb93d0e9484d5357a578c3367f54076",
          "md5": "ce87690a3adb28f76100529cdfe56343"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.8-fabric.jar",
          "size": 314041,
          "sha512": "b1089cdaf3fa2547d69d1d2981ef824784a28da016bb899bc05320fc19d331d22df80278b561593d1e952fce1ca5c1dc02f51d4aa4d66b09632bbc7a87b1801e",
          "sha256": "4837302872bbbed4278a641546feaaa6311ed6f362d08bc54154145d31268583",
          "sha1": "8ffd5315bfb93d0e9484d5357a578c3367f54076",
          "md5": "ce87690a3adb28f76100529cdfe56343"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.8-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.8-sources.jar",
          "size": 80745,
          "sha512": "40bedf2264801b2ae2fb4a111ccf871954657db878bee975ac9fba2efd66c3bd1450cf992486a3db0988a00367638053b6b508355bb62f8de9d371ee50e4ec40",
          "sha256": "588dbe8864d9bd99a933efaec9298621e19f03725a512fb29bb2e8ba27fdec46",
          "sha1": "ebc1942ab7c9e302bf8ba19ee769dbef36d97c45",
          "md5": "6a651a191883afdcdfa379a644edb233"
        }
      ]
    }
  ]
}
