{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-forge",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-forge-1.1.3-forge.jar",
          "url": "horseman-forge-1.1.3-forge.jar",
          "size": 263693,
          "sha512": "66daad42f5a87ec3f02ab4ebf37d1c44cc4d8312064aab6c2e020103dc3c23e985d653e5bb0347d10b05704afeb0ed75bb2e7e7d46bd36a056e962d3b57f4d08",
          "sha256": "74235f29cc6a7123021a1508d7030efa008ff6dc3f8d37fe255d3f95416272a2",
          "sha1": "01f9397ad3661fb2650d3d21bd1513028e951a6a",
          "md5": "0d97f062cf3846df0e397b0dc3d29ad1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-forge-1.1.3-forge.jar",
          "url": "horseman-forge-1.1.3-forge.jar",
          "size": 263693,
          "sha512": "66daad42f5a87ec3f02ab4ebf37d1c44cc4d8312064aab6c2e020103dc3c23e985d653e5bb0347d10b05704afeb0ed75bb2e7e7d46bd36a056e962d3b57f4d08",
          "sha256": "74235f29cc6a7123021a1508d7030efa008ff6dc3f8d37fe255d3f95416272a2",
          "sha1": "01f9397ad3661fb2650d3d21bd1513028e951a6a",
          "md5": "0d97f062cf3846df0e397b0dc3d29ad1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-forge-1.1.3-sources.jar",
          "url": "horseman-forge-1.1.3-sources.jar",
          "size": 44838,
          "sha512": "bb9083783cb56c36462b45c97414801b0784f31cb88e8eccb28183ec6d266ee849e7e7a6633dd3b4183187b3eb195b746b67feccb66e7ab4cc01eff591e3f6a0",
          "sha256": "8230ef9d962b61f3b8999fa7937d9b651e6d39b2b43d521c3d638ac72b5e0c66",
          "sha1": "d9332d90172582b0f1ebb4e69c63f8c67fed3783",
          "md5": "b26a498d6c85d9141539ef8a41533f67"
        }
      ]
    }
  ]
}
