{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-26.1.2-common",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.2-common-api",
          "version": {
            "requires": "29.6.2.31"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.0.jar",
          "url": "scholar-26.1.2-common-1.2.0.jar",
          "size": 712951,
          "sha512": "3471663ab8aba8247e120151a0cca3333f0fcc7e7ac6cb95c6e99071f908bc4f12020fc935496e85cc3e0775c78bb466fbf53fdb1085a523874069d820dc4fd1",
          "sha256": "a8cec663498d31c93b2489b173d7005df02b4754b628f938deb4988d403e9168",
          "sha1": "aba7c1f41c85886a28fae5793a48b2ee3f1f0213",
          "md5": "b0629b0061a6def2be9c1c2a2b3c7062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.0.jar",
          "url": "scholar-26.1.2-common-1.2.0.jar",
          "size": 712951,
          "sha512": "3471663ab8aba8247e120151a0cca3333f0fcc7e7ac6cb95c6e99071f908bc4f12020fc935496e85cc3e0775c78bb466fbf53fdb1085a523874069d820dc4fd1",
          "sha256": "a8cec663498d31c93b2489b173d7005df02b4754b628f938deb4988d403e9168",
          "sha1": "aba7c1f41c85886a28fae5793a48b2ee3f1f0213",
          "md5": "b0629b0061a6def2be9c1c2a2b3c7062"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.0-sources.jar",
          "url": "scholar-26.1.2-common-1.2.0-sources.jar",
          "size": 555022,
          "sha512": "a0c70dc87fa85730b7eee15ad8d7c7d34cdbb6cf958c9deabe22e18ae4c993809b6452c2ffbaf2c92252c1b6f428fef718670b30edc9ec4a216c08a5fcb11951",
          "sha256": "83922a44ce08396aa22498981327b58d25579db9d29c3a894ccecb882ddac181",
          "sha1": "fb1c9cc2d2069a9c9db96333a80143344b0bf1cc",
          "md5": "7e4de01f7a60cb6ee2d7b051928a728d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-common-1.2.0.jar",
          "url": "scholar-26.1.2-common-1.2.0.jar",
          "size": 712951,
          "sha512": "3471663ab8aba8247e120151a0cca3333f0fcc7e7ac6cb95c6e99071f908bc4f12020fc935496e85cc3e0775c78bb466fbf53fdb1085a523874069d820dc4fd1",
          "sha256": "a8cec663498d31c93b2489b173d7005df02b4754b628f938deb4988d403e9168",
          "sha1": "aba7c1f41c85886a28fae5793a48b2ee3f1f0213",
          "md5": "b0629b0061a6def2be9c1c2a2b3c7062"
        }
      ]
    }
  ]
}
