{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.5.1-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.5.1-forge.jar",
          "size": 849896,
          "sha512": "b40d338f99ba760fe180e2e35cc477b84c695503f5cb9b9e226db419e4c37383eeb833649ef7ad13711710cd10545273f40c8d9c6ff3e78814600608bc3dafa1",
          "sha256": "4442f7afe1bbbb2b3eb06b9dc2860e296f1f8c24f3bfb3e1255df6304da5452d",
          "sha1": "925b42ce059db92ce33c3b8c205924dac996c5fd",
          "md5": "8388850796a2578e3ed6dbe571963b2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.5.1-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.5.1-forge.jar",
          "size": 849896,
          "sha512": "b40d338f99ba760fe180e2e35cc477b84c695503f5cb9b9e226db419e4c37383eeb833649ef7ad13711710cd10545273f40c8d9c6ff3e78814600608bc3dafa1",
          "sha256": "4442f7afe1bbbb2b3eb06b9dc2860e296f1f8c24f3bfb3e1255df6304da5452d",
          "sha1": "925b42ce059db92ce33c3b8c205924dac996c5fd",
          "md5": "8388850796a2578e3ed6dbe571963b2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.5.1-sources.jar",
          "url": "scholar-1.20.1-forge-1.2.5.1-sources.jar",
          "size": 523647,
          "sha512": "b8d34876c8165c8953b8eaac29f08579a5b77ebdb99652044bb2e5723b75a7c488f0ddce2daab48cb2ab387436a7e8e750785b7a860cfad4349766628e6cc7a2",
          "sha256": "ea117a330676e5f966260e66553b9c2eeb3ccf2f628a8f501db6c13bf5535b64",
          "sha1": "6a6f29a7d6df584a6bb9c3d67cad43b5c566295d",
          "md5": "01a46aeadcf93a0b301899940abe03f8"
        }
      ]
    }
  ]
}
