{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_polaroid",
    "module": "exposure_polaroid-1.21.1-fabric",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.0.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.0.jar",
          "size": 176791,
          "sha512": "aa5c92f0439efd76657adbdd4cfe53bfa0798023f88ca97ff02e13a0fece8d97af666843bc059e4914bc782a31686bc970bcc2152e95a475223019fa45d2a053",
          "sha256": "0d0a520667c7985da947e51db993624a5ea5003e79b3542fded162a543e0a258",
          "sha1": "288e038e80ce4e9420853cd1006e6dd90e689a41",
          "md5": "228744f0a0c42851fb47bc27423f314d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-1.21.1-fabric",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "io.github.mortuusars.exposure_catalog",
          "module": "exposure_catalog-fabric",
          "version": {
            "requires": "1.21.1-1.1.1-snapshot1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.0.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.0.jar",
          "size": 176791,
          "sha512": "aa5c92f0439efd76657adbdd4cfe53bfa0798023f88ca97ff02e13a0fece8d97af666843bc059e4914bc782a31686bc970bcc2152e95a475223019fa45d2a053",
          "sha256": "0d0a520667c7985da947e51db993624a5ea5003e79b3542fded162a543e0a258",
          "sha1": "288e038e80ce4e9420853cd1006e6dd90e689a41",
          "md5": "228744f0a0c42851fb47bc27423f314d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.0-sources.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.0-sources.jar",
          "size": 10487,
          "sha512": "9031cd81bc78e8afaf2c390d0df47d695f4e08f47ce77c50f2b45b59afe5e443e8780eab122e01bb2cde4ca26cd965f6d96f4acd3b315801c7bd0fea7ba7ae1f",
          "sha256": "b03b7486481e29aad844c511839071a5de83118813de5fefa308b704efc85bce",
          "sha1": "438a85a458e61c4e1eaedf2e6a5e68b9cf680252",
          "md5": "a5b0fd96bcddcd47b040017595f18def"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.0-dev-shadow.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.0-dev-shadow.jar",
          "size": 174003,
          "sha512": "bc01093f1d2b7787e9a5174d5d1fafd37ccf1b313d7585195a36379512b48848b373f618a233b727cc54e932e2f72c06203bce71136d60666211a1371d41c2b6",
          "sha256": "9c0006f1e62b5b729268d07d163f1b66f6665152d542b183e3bdbd33fca348e6",
          "sha1": "232d8fd89a54a200dd299db1daad68d4769c076a",
          "md5": "9549f72b5d39f447bc515771c30153c4"
        }
      ]
    }
  ]
}
