{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-fabric",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.4.jar",
          "size": 166875,
          "sha512": "16fa5735dfc91db1a7a1775f27c8ef32e24fd8c2f54b20199db42783943ce84e8c7d52078cf5dbf0d74e66613f1b273c8d9f010b0ae6ff69f9c8dec49596d5de",
          "sha256": "e165121f19ecfb7cfa20f48476fcb26560103266cd5923a4ab1df8c219222944",
          "sha1": "78d6b52728e26dbb066cedee7c09bda9d558a1de",
          "md5": "748e80d87742b6891405dc6d9bf02423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.4.jar",
          "size": 166875,
          "sha512": "16fa5735dfc91db1a7a1775f27c8ef32e24fd8c2f54b20199db42783943ce84e8c7d52078cf5dbf0d74e66613f1b273c8d9f010b0ae6ff69f9c8dec49596d5de",
          "sha256": "e165121f19ecfb7cfa20f48476fcb26560103266cd5923a4ab1df8c219222944",
          "sha1": "78d6b52728e26dbb066cedee7c09bda9d558a1de",
          "md5": "748e80d87742b6891405dc6d9bf02423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.4-sources.jar",
          "size": 8697,
          "sha512": "0edea31d9d98d390e14a4d203c8565a837a0d36d06b84ff818663e546ee05784fd11c8dc74fbf401e18628406eaafecb0f5850bbc858ab8de2e402729f7775c7",
          "sha256": "79b4e40de3c61a3d2c5861550c25500edfed79b87ec3c384f1f51d1e218e51b5",
          "sha1": "f6327906ef561a49780b90cdb6fd894b9c75963b",
          "md5": "98095d6c770a28355b4499d4c340d328"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-fabric-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.1-fabric-1.3.4-dev-shadow.jar",
          "size": 163372,
          "sha512": "b1b61b749de5ec2a47f8324fba41e7f1fe205f95334c1faf5c648f5ec79f282b3a943e7a707678fb6df152c1ecdbffa6c61b02edc5aaccf25323a7fbf628d492",
          "sha256": "e8d11a71b9376e0c5aff68f01d6bca431263e3a56358468a9a26afcca12b2db9",
          "sha1": "3f06a6ac61ca6866ec23779feb996c0e8131e43e",
          "md5": "9853597b4bf1a14ec2048797f21afc38"
        }
      ]
    }
  ]
}
