{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-1.20.1-fabric",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.2-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.2-fabric.jar",
          "size": 338339,
          "sha512": "500e17a8012c9a2e14f69920745c02f2338d0386c40ca96c94461e172c5d4083fa24228b0b1beae06c2f6a0f049582b885d0b6e3ce97e05ac296fab68f1a1926",
          "sha256": "06caa96240207f924229133f336c33231361397d1f9ac9b76886a65497a56555",
          "sha1": "dd5ca0320f1525036438e06db58baf08512ee0f1",
          "md5": "9b982bdd17ee69a892186d6938588f19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "probejs-585406",
          "version": {
            "requires": "5227391"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.2-fabric.jar",
          "url": "thief-1.20.1-fabric-1.2.2-fabric.jar",
          "size": 338339,
          "sha512": "500e17a8012c9a2e14f69920745c02f2338d0386c40ca96c94461e172c5d4083fa24228b0b1beae06c2f6a0f049582b885d0b6e3ce97e05ac296fab68f1a1926",
          "sha256": "06caa96240207f924229133f336c33231361397d1f9ac9b76886a65497a56555",
          "sha1": "dd5ca0320f1525036438e06db58baf08512ee0f1",
          "md5": "9b982bdd17ee69a892186d6938588f19"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-1.20.1-fabric-1.2.2-sources.jar",
          "url": "thief-1.20.1-fabric-1.2.2-sources.jar",
          "size": 89950,
          "sha512": "2014db9eac6e052571e60310841dc05cb2ad4081177714b7dbf229e3553a6e382df632292a594cf4763db810eff381ff70b71803fd2afb6759c8fe502c6aa002",
          "sha256": "f687f591914e55e19685c56465c51cef2139b3204c49ecb54f329ac7e499bbda",
          "sha1": "348172cd70e21300adbccb4e793b94daee8c0a85",
          "md5": "3abde3aa5980e85d0c0a35706aecf120"
        }
      ]
    }
  ]
}
