{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-common",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.4.jar",
          "url": "horseman-common-1.1.4.jar",
          "size": 67647,
          "sha512": "a008aea811166f7ec62811df0f4caad13e74e3c4c5613cb36020e3087b9e5773c7596690a0ce9a9f479bbdea1b5531cd9ae7e26d2637e3e0262fd04de4dbe954",
          "sha256": "e12d8f84ca10603042b713867f6dc96ef54ff884c89965dc7b8f3268b501b38a",
          "sha1": "6857682b2b8e0f97a23bea58dda605618c57ce42",
          "md5": "e86407d371bc8cf4dd4d4affafcac874"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-common-1.1.4.jar",
          "url": "horseman-common-1.1.4.jar",
          "size": 67647,
          "sha512": "a008aea811166f7ec62811df0f4caad13e74e3c4c5613cb36020e3087b9e5773c7596690a0ce9a9f479bbdea1b5531cd9ae7e26d2637e3e0262fd04de4dbe954",
          "sha256": "e12d8f84ca10603042b713867f6dc96ef54ff884c89965dc7b8f3268b501b38a",
          "sha1": "6857682b2b8e0f97a23bea58dda605618c57ce42",
          "md5": "e86407d371bc8cf4dd4d4affafcac874"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-common-1.1.4-sources.jar",
          "url": "horseman-common-1.1.4-sources.jar",
          "size": 37408,
          "sha512": "06d12a0189e5d3713ba106a032dafe4c8761bcb4d77449fbe7ca46d536f7f57951f68b01bb568a2fab0f28b97993c42b75f08fbc3d0be2574aea586645a78790",
          "sha256": "14a2c4422b69b095e16659d3c879e0fec8abe76c98778a5134512018caddfcf5",
          "sha1": "3ed098ea4083781e7a07bdd1f1989045bd9c9cd7",
          "md5": "203554ea6036d3ebb3e1e40862ad3c98"
        }
      ]
    }
  ]
}
