{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.0-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.0-forge.jar",
          "size": 848426,
          "sha512": "d0dcda772d7014cf5d9be79db98ae9aae510bc9a0508c2fc7e01c13f1f1b1e62adaa6dab991ba870803410c392d375dd1f152444351f553f4a2ff30ee178ac18",
          "sha256": "72fee95e962dcc78911e2214e09e65678086936f689057782f581c3db24e6079",
          "sha1": "75f6b7b1e12ccfd50e285280348329ad2c7fb8e6",
          "md5": "3a72b1e0a90cceacf5b00eda373a25cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.0-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.0-forge.jar",
          "size": 848426,
          "sha512": "d0dcda772d7014cf5d9be79db98ae9aae510bc9a0508c2fc7e01c13f1f1b1e62adaa6dab991ba870803410c392d375dd1f152444351f553f4a2ff30ee178ac18",
          "sha256": "72fee95e962dcc78911e2214e09e65678086936f689057782f581c3db24e6079",
          "sha1": "75f6b7b1e12ccfd50e285280348329ad2c7fb8e6",
          "md5": "3a72b1e0a90cceacf5b00eda373a25cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.0-sources.jar",
          "url": "scholar-1.20.1-forge-1.2.0-sources.jar",
          "size": 523230,
          "sha512": "58b976e6b58dfa706e05a46ea2e3571d984ddbde2af20f5af2e99bbe9fbbda3f7c2277114d2fefbf834fcd837cd5ed06b21acffcedfcc2fb87973c5905caaf06",
          "sha256": "8d6e6e1bb1268bfa2e3699cfbe12c6fbc2f0f6379697412570ffca691f6793b7",
          "sha1": "3fc4eafebc100b463a0f1724de24767e47ac70cf",
          "md5": "bf5865bdfa1cb8a7a544c6aefcb86895"
        }
      ]
    }
  ]
}
