{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.11-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.11.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-common-api",
          "version": {
            "requires": "27.4.0.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.11-common-1.3.4.jar",
          "url": "sootychimneys-1.21.11-common-1.3.4.jar",
          "size": 165015,
          "sha512": "f4e47ba7cec051bd1b6c87d050eaf2864b483595bef74db8ef41ffcc5e3d63f2b337f09626b1ebf6d847f96925447c1d2ab8f95cbdf8603db5a8f2903d8bcf6e",
          "sha256": "3db9e95ae77bbb3ef7a152c158257ba71d700753e771365f3c49bfebe7b771de",
          "sha1": "ddd3475bf5b8afc8742a56802cfaf11c735962fe",
          "md5": "8b4b93e88354e61545ae53e35ccafda7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.11.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.11-common-1.3.4.jar",
          "url": "sootychimneys-1.21.11-common-1.3.4.jar",
          "size": 165015,
          "sha512": "f4e47ba7cec051bd1b6c87d050eaf2864b483595bef74db8ef41ffcc5e3d63f2b337f09626b1ebf6d847f96925447c1d2ab8f95cbdf8603db5a8f2903d8bcf6e",
          "sha256": "3db9e95ae77bbb3ef7a152c158257ba71d700753e771365f3c49bfebe7b771de",
          "sha1": "ddd3475bf5b8afc8742a56802cfaf11c735962fe",
          "md5": "8b4b93e88354e61545ae53e35ccafda7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.11-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.11-common-1.3.4-sources.jar",
          "size": 106953,
          "sha512": "7a9e8c8212cda991a8494bf029d019f63221c5b8e737dc395f3d70ef163c13c9b3e37464406525aa4aa7031ff21ec5974943cdeebc8268b62e255509ef32e195",
          "sha256": "0568f32e83207c46a7748588d9733a843b0e1045ee6c4c3598a053fd972b2ab4",
          "sha1": "b6b337b7f4ecfb91360fe5379cce36356637fa08",
          "md5": "d384b6977e37e33d5890ccc8f10f7c19"
        }
      ]
    }
  ]
}
