{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_catalog",
    "module": "exposure_catalog-fabric",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.0.3-fabric.jar",
          "url": "exposure_catalog-fabric-1.0.3-fabric.jar",
          "size": 155544,
          "sha512": "85850e97a6f942c188f58b0b91bc81c92201304612e290dac7d63a59e2199e722a78c846128ebb64b60af0b0f95f23b70d2c270d2beacfb3467d10103059c781",
          "sha256": "448dd884a4fc4b49cbe78e3859ce7dc6f75f5d8a5c7165379f2bd935f47fe3aa",
          "sha1": "ba2cb9164947806f4e2cfc63c5de85ab7c233944",
          "md5": "d450c3981200750e3ce7df61861e0ed4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-fabric",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_catalog-fabric-1.0.3-fabric.jar",
          "url": "exposure_catalog-fabric-1.0.3-fabric.jar",
          "size": 155544,
          "sha512": "85850e97a6f942c188f58b0b91bc81c92201304612e290dac7d63a59e2199e722a78c846128ebb64b60af0b0f95f23b70d2c270d2beacfb3467d10103059c781",
          "sha256": "448dd884a4fc4b49cbe78e3859ce7dc6f75f5d8a5c7165379f2bd935f47fe3aa",
          "sha1": "ba2cb9164947806f4e2cfc63c5de85ab7c233944",
          "md5": "d450c3981200750e3ce7df61861e0ed4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_catalog-fabric-1.0.3-sources.jar",
          "url": "exposure_catalog-fabric-1.0.3-sources.jar",
          "size": 73413,
          "sha512": "7cf57f22022e73a38b630238658994e34905f4f75dc9b45d5fa33909848a2fb0e2e2a69d7f118f0bf4b71d61584839a57b36a6e96f2cd81c6bc30d7d152c996b",
          "sha256": "f33ca72d56da3a5771ad5ebfd3f3d6892932d3f522165f392ef9f67b1a8408cb",
          "sha1": "3ebd5247c392b1b3716136b52963f7713e3fd687",
          "md5": "aa41886a2b0972a5034470224c33183d"
        }
      ]
    }
  ]
}
