{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.20.1-forge",
    "version": "1.9.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6855440"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.15.jar",
          "url": "exposure-1.20.1-forge-1.9.15.jar",
          "size": 2237051,
          "sha512": "c651cbf953236660ec9f4fb9ea6c2b7a2ef2bd15a5035826983b3db8cba696920540c47aa7cc4756c2db79abef3229c59b72466488305a33b7860c9d0157cdea",
          "sha256": "2d14291210dafcb271a7029897400d6dba2b985a7a4540f90eb00d8fff52d182",
          "sha1": "d8648914f2b253639478325ecda2e82931e64b47",
          "md5": "00cecc8bbd318aa65daaf17e7d746e74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "5681725"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.15.jar",
          "url": "exposure-1.20.1-forge-1.9.15.jar",
          "size": 2237051,
          "sha512": "c651cbf953236660ec9f4fb9ea6c2b7a2ef2bd15a5035826983b3db8cba696920540c47aa7cc4756c2db79abef3229c59b72466488305a33b7860c9d0157cdea",
          "sha256": "2d14291210dafcb271a7029897400d6dba2b985a7a4540f90eb00d8fff52d182",
          "sha1": "d8648914f2b253639478325ecda2e82931e64b47",
          "md5": "00cecc8bbd318aa65daaf17e7d746e74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.15-sources.jar",
          "url": "exposure-1.20.1-forge-1.9.15-sources.jar",
          "size": 52551,
          "sha512": "90ba8204d9f23c2052ee7774345a5e7b471eb78c5ee89933b0b87bbef274163e3d7e88330a9cad5ccf6b158b6fc7b8883db507a06d2f04ef3b7929f45576e8f4",
          "sha256": "427e1b37467ff9110307df6283adf992fc7ceb7331d9dd64b91d245bce4f089c",
          "sha1": "9a133a55014428098a70560ad9f9bc684eb1193c",
          "md5": "c175f9d9ce4b2d4f4997e25d078cfa88"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.20.1-forge-1.9.15-dev-shadow.jar",
          "url": "exposure-1.20.1-forge-1.9.15-dev-shadow.jar",
          "size": 2010302,
          "sha512": "54509c1b012a9145d8a45f2463dc6260a198be600611214128bb2bea6e6aa21aaad6c343d999412bc9c04d34a10dc8d30ff9e8bd1fb48a9b7e9ad822eee2f86e",
          "sha256": "a5e7450077e304c37f7d40ec667386f0d5c623b4ed0d096ea1b8f234b13285ac",
          "sha1": "e2845233c9110240c7564d9be31cf9a5ff8a3236",
          "md5": "f69d002d7dadb0617909ff312a70efab"
        }
      ]
    }
  ]
}
