{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.20.1-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.20.1-common-1.3.4.jar",
          "url": "sootychimneys-1.20.1-common-1.3.4.jar",
          "size": 164265,
          "sha512": "65389e7ddbde31eeb6538f5c311aa975adb09df1426447a29a81d7845ccf854703f748d2a476a4ea8f1f9e1a25e7320b7a2c4ccb225ba56a2f35a1e48f6a26e8",
          "sha256": "23c9c81fde15b3f965b6f0e87866f8f803e54f9fe63dfa3a3b0a5c0772f9ed34",
          "sha1": "26108b427ba7c1a9fc582eed0a2c83e173e5c682",
          "md5": "c6b94151c0707f459ea440c546e6e437"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.20.1-common-1.3.4.jar",
          "url": "sootychimneys-1.20.1-common-1.3.4.jar",
          "size": 164265,
          "sha512": "65389e7ddbde31eeb6538f5c311aa975adb09df1426447a29a81d7845ccf854703f748d2a476a4ea8f1f9e1a25e7320b7a2c4ccb225ba56a2f35a1e48f6a26e8",
          "sha256": "23c9c81fde15b3f965b6f0e87866f8f803e54f9fe63dfa3a3b0a5c0772f9ed34",
          "sha1": "26108b427ba7c1a9fc582eed0a2c83e173e5c682",
          "md5": "c6b94151c0707f459ea440c546e6e437"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.20.1-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.20.1-common-1.3.4-sources.jar",
          "size": 119661,
          "sha512": "05374c3662afc3d946f7f16e44d38ccfb0831fda089dcbe946b386fc1cd538f8a470ab9d35f0ca3ccae0571ddcaa84a3c553a1ce847ecceee40d2e3b14469a60",
          "sha256": "e1f5d9f6b3822d97143b624ae4aa63538ad9f51fc3afaec4a849839367ab5b58",
          "sha1": "9d4e4fe47997fa1770d1f68e38463cf6cb105fe5",
          "md5": "4134611f22b41f35224c1f7dfd4955c6"
        }
      ]
    }
  ]
}
