{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.9-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.9-forge.jar",
          "size": 692365,
          "sha512": "08ed6ef563eb66b0444ebb432e69e04462e8d1be00368f505b1fc11c22ec65a54f61e7e11a36c1791a18df7c14b2d6b670b5e1cbf9c8c99aa7ab435afe671aca",
          "sha256": "687e66b8f6d79e973da2781020384afcab6fb4b869eac20f8acac86a44aec7dd",
          "sha1": "7ff0ac67e8872fdf9d2e5ddbd5f2b144706cb1ff",
          "md5": "80d36c35caeb0087f3f4e0175ce9f94c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.9-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.9-forge.jar",
          "size": 692365,
          "sha512": "08ed6ef563eb66b0444ebb432e69e04462e8d1be00368f505b1fc11c22ec65a54f61e7e11a36c1791a18df7c14b2d6b670b5e1cbf9c8c99aa7ab435afe671aca",
          "sha256": "687e66b8f6d79e973da2781020384afcab6fb4b869eac20f8acac86a44aec7dd",
          "sha1": "7ff0ac67e8872fdf9d2e5ddbd5f2b144706cb1ff",
          "md5": "80d36c35caeb0087f3f4e0175ce9f94c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.9-sources.jar",
          "url": "scholar-1.20.1-forge-1.1.9-sources.jar",
          "size": 413014,
          "sha512": "c9b45f284dc897aceb634a3a09be669a7b6e647542c9f644daa03bc7722fbd8c15542df4b90b6c32898b64669bcb6cda3a95d9190f375dbcd552bd33b5c5bd5f",
          "sha256": "d88a68595cdbbaea64af4fc1719c05a5460b1f5b0bd7a40deb2c79357e77a204",
          "sha1": "0bf1ec27278a9d80d2e9d8eb3cd20dc14da5e41b",
          "md5": "260e349e7ef20f2b1b871f2afa5c807a"
        }
      ]
    }
  ]
}
