{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.10-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.10.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.10-common-api",
          "version": {
            "requires": "26.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.10-common-1.3.4.jar",
          "url": "sootychimneys-1.21.10-common-1.3.4.jar",
          "size": 164598,
          "sha512": "fada35f157f66c3684318d154d3f47604b7b5a4d186b78573197791a6cfc7202d48ef5de066e20e556e08d477503dd8f94e462986f99591a218df2058c967413",
          "sha256": "15e57e54cfefbdf6136e264e8e92d6531b8d9a34038a42058d6c1f2d00489f96",
          "sha1": "b9bcb604a23ebdb2e05eb82359f076e3fa1ec431",
          "md5": "44d42e84850bc2667238b0a4cb3b8267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.10.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.10-common-1.3.4.jar",
          "url": "sootychimneys-1.21.10-common-1.3.4.jar",
          "size": 164598,
          "sha512": "fada35f157f66c3684318d154d3f47604b7b5a4d186b78573197791a6cfc7202d48ef5de066e20e556e08d477503dd8f94e462986f99591a218df2058c967413",
          "sha256": "15e57e54cfefbdf6136e264e8e92d6531b8d9a34038a42058d6c1f2d00489f96",
          "sha1": "b9bcb604a23ebdb2e05eb82359f076e3fa1ec431",
          "md5": "44d42e84850bc2667238b0a4cb3b8267"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.10-common-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.10-common-1.3.4-sources.jar",
          "size": 106925,
          "sha512": "808f178999b46309d80d8f5744ed191161757c9b065d9f8db7b6949120e70532225b3855f26e1e35c7d9731a7549054cc40969917d4d11ede4e5903db41b5bfb",
          "sha256": "cf3280da9c6965245bb2b06c006224f44a942074b85713ec44593683df585308",
          "sha1": "e467eaa654645e193db6463eb3c13adb3538ec76",
          "md5": "e860ed1762e74f4a94b4b89365501a81"
        }
      ]
    }
  ]
}
