{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.monobank",
    "module": "monobank-1.21.1-neoforge",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "monobank-1.21.1-neoforge-1.2.0.jar",
          "url": "monobank-1.21.1-neoforge-1.2.0.jar",
          "size": 602658,
          "sha512": "0905432ea360b75788fbb01e49a7d1d4b3ac19ff084223edc6d5efd52aa1e7f8636b522fc6c131c5a845415c1f78cae89aabd1827a5081db94a312492b2c3596",
          "sha256": "231864ec8d74a649b402635cf6746db704f7cb0df24d21221cc7689739ee385e",
          "sha1": "7f9bd2fe772c5536cb2d44a7357caa96a605c51f",
          "md5": "cd5e3afb546affddfa8cf2e10a6738c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.4-53"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.46"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "io.github.mortuusars.thief",
          "module": "thief-1.21.1-neoforge",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "monobank-1.21.1-neoforge-1.2.0.jar",
          "url": "monobank-1.21.1-neoforge-1.2.0.jar",
          "size": 602658,
          "sha512": "0905432ea360b75788fbb01e49a7d1d4b3ac19ff084223edc6d5efd52aa1e7f8636b522fc6c131c5a845415c1f78cae89aabd1827a5081db94a312492b2c3596",
          "sha256": "231864ec8d74a649b402635cf6746db704f7cb0df24d21221cc7689739ee385e",
          "sha1": "7f9bd2fe772c5536cb2d44a7357caa96a605c51f",
          "md5": "cd5e3afb546affddfa8cf2e10a6738c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "monobank-1.21.1-neoforge-1.2.0-sources.jar",
          "url": "monobank-1.21.1-neoforge-1.2.0-sources.jar",
          "size": 16592,
          "sha512": "12ae38f54eeb451bec729995297afc0e2e4fb08740a4f35353e0779ee269ae17ff15d21483b539b862753fc21f527099b4033455ebd40cecedbee17c1d6246d9",
          "sha256": "36a35e46c21bfced607468aeeeb8c0ea64a7e7a0e33c4d892f3431115e71d29b",
          "sha1": "5ce9564923ddba27cdbc77c7926df5e39bcdb2f5",
          "md5": "62fa2c8545f039efcdf2b7e4a679923a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "monobank-1.21.1-neoforge-1.2.0-dev-shadow.jar",
          "url": "monobank-1.21.1-neoforge-1.2.0-dev-shadow.jar",
          "size": 415141,
          "sha512": "8024438891d9acbed676f22fd2f409d797d33b4bfab3f5e6dc4eacdb583e747a84e993cf9479e73962cf1e9c5217eee3fffb4170b3799bdeaac7bf3339fa13ec",
          "sha256": "816272f2eff80dd2a3fe0f8b7fef3cc6f85fa5f9ca9acb882687b9d371cf267b",
          "sha1": "3aa6be8991bd28844ffb011ec4f81cfafd73a597",
          "md5": "13d93726e073bebe6c224d8829712205"
        }
      ]
    }
  ]
}
