{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.0-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.0-forge.jar",
          "size": 327550,
          "sha512": "993470a02f9b8c1cab507d49f1f402b038b6b44be38206f2fedb1c5c6b47d9c4043ed78aea400555775ed26902479030c52f58104e5c2755dc287100626cd859",
          "sha256": "ca36ac92ab6697fc0a49299848b371eb1fa0b4e7185952f8fb7264e8b44c57a2",
          "sha1": "51eef329447cf20ebca30739b81d795aaa701cf2",
          "md5": "9b19435a2c85f97c26823e0fbb91b403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.0-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.0-forge.jar",
          "size": 327550,
          "sha512": "993470a02f9b8c1cab507d49f1f402b038b6b44be38206f2fedb1c5c6b47d9c4043ed78aea400555775ed26902479030c52f58104e5c2755dc287100626cd859",
          "sha256": "ca36ac92ab6697fc0a49299848b371eb1fa0b4e7185952f8fb7264e8b44c57a2",
          "sha1": "51eef329447cf20ebca30739b81d795aaa701cf2",
          "md5": "9b19435a2c85f97c26823e0fbb91b403"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.0-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.0-sources.jar",
          "size": 85323,
          "sha512": "e140cf5c0aa0e1b91b5395f10d117d63b98e493a34d2c5bf2e343b3dfc1b7a2466ae7f76be2360d3d61e38c9ca76054870b30a1c09c190a6459f9d86476074d8",
          "sha256": "e8670896ee066c2c534f326d217dd809382a508b3b2052a74f0f8da90da9db91",
          "sha1": "c1de47cffcb7b56dd2f91f73ab3ff06a4f7719d5",
          "md5": "d7bb53d6a8f003e8dcc32b113f031d02"
        }
      ]
    }
  ]
}
