{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.0.jar",
          "url": "horseman-1.21.1-common-1.3.0.jar",
          "size": 116524,
          "sha512": "6d84140b9eb8482acb09778efc2d8342ddd74d283ef54182ed43b035f051d0d56e0b8101255d9c31755987025244abfce64172d695e10196795599abbebd051a",
          "sha256": "4f307792c2c54697ff19f11f809689c5e13e834e3cd3c7e5c10654d38c718e02",
          "sha1": "06de1ea0918ef06393a12ac90f02ac8f316dc09c",
          "md5": "2bdb7070d83b14ae3e306c34ff7e86e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.0.jar",
          "url": "horseman-1.21.1-common-1.3.0.jar",
          "size": 116524,
          "sha512": "6d84140b9eb8482acb09778efc2d8342ddd74d283ef54182ed43b035f051d0d56e0b8101255d9c31755987025244abfce64172d695e10196795599abbebd051a",
          "sha256": "4f307792c2c54697ff19f11f809689c5e13e834e3cd3c7e5c10654d38c718e02",
          "sha1": "06de1ea0918ef06393a12ac90f02ac8f316dc09c",
          "md5": "2bdb7070d83b14ae3e306c34ff7e86e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.0-sources.jar",
          "url": "horseman-1.21.1-common-1.3.0-sources.jar",
          "size": 69070,
          "sha512": "235fd694fa6d12d5286a6f2e670ac138508c6cf02b89723ff75ba004434a0134e8e6e39ac56d84c220b97126bcd70cb6a8f679cfeab889f3d2ad01fe445ad828",
          "sha256": "866b9b1f5c5c3d499524ad9d148a6f59f27cf91f270c230556990ca359efe1e3",
          "sha1": "ad763e2dbef19970be54a65fa0fb3ed465ed80c2",
          "md5": "9a874ba6b86a54edc2e35fa6f66486e8"
        }
      ]
    }
  ]
}
