{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.0.jar",
          "url": "horseman-1.21.1-common-1.3.0.jar",
          "size": 116524,
          "sha512": "625a11c527bbbf5660342929d3885d2bad0a7154af4b6ddedf5b1988095669aac1fec57b386ba8e8bf5e4747e2e7fe4d4e8814f40b25f04bf4d61ae207b4c0ad",
          "sha256": "13d458cf6bebd64b232b19241d63db3d1a1ca17bbd63d26ae6ec033cc3f50587",
          "sha1": "a4f1407a4d57b8c8d9e9c6ec90361ad885025122",
          "md5": "a144bf9882c4f3ac2e513d8269ee5887"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.0.jar",
          "url": "horseman-1.21.1-common-1.3.0.jar",
          "size": 116524,
          "sha512": "625a11c527bbbf5660342929d3885d2bad0a7154af4b6ddedf5b1988095669aac1fec57b386ba8e8bf5e4747e2e7fe4d4e8814f40b25f04bf4d61ae207b4c0ad",
          "sha256": "13d458cf6bebd64b232b19241d63db3d1a1ca17bbd63d26ae6ec033cc3f50587",
          "sha1": "a4f1407a4d57b8c8d9e9c6ec90361ad885025122",
          "md5": "a144bf9882c4f3ac2e513d8269ee5887"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.0-sources.jar",
          "url": "horseman-1.21.1-common-1.3.0-sources.jar",
          "size": 69070,
          "sha512": "2db3a25fd808e0a7dd98717309adf77319fcd09fbf67177ac1550101483a674b1f37f75cd564af600ecf59011532a5acd541e951a037becd417b13afa0c77d10",
          "sha256": "6289fd30b42a14d8e0f018c69ce59ee5f8c543bdcb8b67bbb6323424ac29776a",
          "sha1": "12b3cc82376af55b2654a30df9c53c2c578265e8",
          "md5": "240be02c8d6f811db5afa4f654ad6c65"
        }
      ]
    }
  ]
}
