{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot10.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot10.jar",
          "size": 2111894,
          "sha512": "6c96018794b249c1c594ad0715ae6dc9a65bd7b24a64f6e97c4d48efb2c8d1356add665775c15dc69619fd7134609d61a6d32d55afc28824e9c2c20630144062",
          "sha256": "7ec2edca99deb62e52c16008ae4174ee17008669dfe81499e06cf00fb486ce3b",
          "sha1": "c820aef70ae6e6d392115e389f8f9b26523bd133",
          "md5": "492d2584a4380b0de46a01d4e90da9bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot10.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot10.jar",
          "size": 2111894,
          "sha512": "6c96018794b249c1c594ad0715ae6dc9a65bd7b24a64f6e97c4d48efb2c8d1356add665775c15dc69619fd7134609d61a6d32d55afc28824e9c2c20630144062",
          "sha256": "7ec2edca99deb62e52c16008ae4174ee17008669dfe81499e06cf00fb486ce3b",
          "sha1": "c820aef70ae6e6d392115e389f8f9b26523bd133",
          "md5": "492d2584a4380b0de46a01d4e90da9bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot10-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot10-sources.jar",
          "size": 37636,
          "sha512": "e09be21c997b19dd98f27607df030d3c41d37339df30abd64e31054e8e2c3e335af84d7c0e2129d5c28090a09db0059d409079f5c537506ee8e4f14d21c90824",
          "sha256": "71735d0e1ecad78ad55c1a3ad454ac33e0dc3a874b47d6877483df44721f9ff4",
          "sha1": "c4a7ee7f3b99811f5414affd91427d99426974b6",
          "md5": "f3bc3df3763aef24d958a8563a44fa56"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot10-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot10-dev-shadow.jar",
          "size": 1894759,
          "sha512": "9212552209acbc0eee63a21b99b2a16272d8c7b782ff45e4e2079a7be90a6fc2f88cd1a47fa98548d0b11be3baeec6b413f0356614a5a00c5176a54a051259e7",
          "sha256": "2ff293f21a54bf7c56dd3916263f3e7b49f27e07fcd3362897f1dfb42854b895",
          "sha1": "6b2b41f94bf16f00a5585031fa0884a03de90865",
          "md5": "fb8a542f9945052531917beb549c2f9d"
        }
      ]
    }
  ]
}
