{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.5.jar",
          "url": "scholar-1.20.1-common-1.2.5.jar",
          "size": 650268,
          "sha512": "224bf052ed48e21354a8f2e6554659210886cedfc92bc751ad4a3c3c2f512147c308fd805b9105d4841bda8cca9aa3385fc3c8fbb94b542986f0306fb70e6ec1",
          "sha256": "b55bc1b2b6bc5aac693723f2bf66ae6edd3f816eaa38d4de5ddc6b038264983d",
          "sha1": "c86d0ac373b251b28e36cd3be357b27398269d6d",
          "md5": "689042138205bc9c0c785329f9b6ffd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.5.jar",
          "url": "scholar-1.20.1-common-1.2.5.jar",
          "size": 650268,
          "sha512": "224bf052ed48e21354a8f2e6554659210886cedfc92bc751ad4a3c3c2f512147c308fd805b9105d4841bda8cca9aa3385fc3c8fbb94b542986f0306fb70e6ec1",
          "sha256": "b55bc1b2b6bc5aac693723f2bf66ae6edd3f816eaa38d4de5ddc6b038264983d",
          "sha1": "c86d0ac373b251b28e36cd3be357b27398269d6d",
          "md5": "689042138205bc9c0c785329f9b6ffd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.2.5-sources.jar",
          "url": "scholar-1.20.1-common-1.2.5-sources.jar",
          "size": 508537,
          "sha512": "6285c96c6f132203aa49e1a722bed79d274f12c3445feb2c8fa952b40cc668aba67902eccc5071d407d75fe6bebff396c9c9f7693f9a3085aaacc8afe509febe",
          "sha256": "a412f60e1501eda4aa2eff6ce31d0ea6d3805b0ce9613cc1e6b8834cb48a7c29",
          "sha1": "de89b119b3b695cb106baaeff6e8e4ca13ed70db",
          "md5": "584f4336d9d1bb4a3fdf2a6eead117b0"
        }
      ]
    }
  ]
}
