{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.0.jar",
          "url": "horseman-1.20.1-common-1.3.0.jar",
          "size": 119869,
          "sha512": "7ff8a34773ba3824924b4f7be65b7b011451a219bfb4b14771e87483efacede91140fbaafcdcbf269e809fa3daf3a9a0f31edd5fe8add96ad5b9ccf203a5f876",
          "sha256": "5116b644aa1188513451265d57c37eb0ee1ca96c0947d751c70efebf21655d0b",
          "sha1": "4e86f0acac84c5054fdedff8f4ef29d9bb53fffa",
          "md5": "3a256d05a60bd516501c5ce0a9e0f764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.0.jar",
          "url": "horseman-1.20.1-common-1.3.0.jar",
          "size": 119869,
          "sha512": "7ff8a34773ba3824924b4f7be65b7b011451a219bfb4b14771e87483efacede91140fbaafcdcbf269e809fa3daf3a9a0f31edd5fe8add96ad5b9ccf203a5f876",
          "sha256": "5116b644aa1188513451265d57c37eb0ee1ca96c0947d751c70efebf21655d0b",
          "sha1": "4e86f0acac84c5054fdedff8f4ef29d9bb53fffa",
          "md5": "3a256d05a60bd516501c5ce0a9e0f764"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-common-1.3.0-sources.jar",
          "url": "horseman-1.20.1-common-1.3.0-sources.jar",
          "size": 70296,
          "sha512": "609fa736f911420f8f9b2505cd5797335ba8fe3610fa9e8e883066529d1bc50479e6e795a5627d4f3c8bb2483caf2ebabb1446bb3969a4b0a3edddc71e75c962",
          "sha256": "671475d263de91d91a54e58fbc11ab78c4d8bb01ca03c909cd68d13f6fd808f9",
          "sha1": "bd26e374a2ea22f63582984ab63b7a7e5766e0c5",
          "md5": "31e3192553f12996d0009fd71e002baa"
        }
      ]
    }
  ]
}
