{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.16.jar",
          "url": "exposure-common-1.7.16.jar",
          "size": 1314241,
          "sha512": "2b83ee6b8b9ad416776813edd31c3fd3ab54334bcc097a960876201f5ee9774c61e8ea28e671fa18f88792561c8f15e01fa9e6b9bdd56bc81b1d89a493fdaafa",
          "sha256": "088faec6ee93254d8eab90c24ea02217034344a40ed444f048f135d805d0e11c",
          "sha1": "fc222c30abab591f30760f6323d13911617f08d0",
          "md5": "e1db1761ada7e0639c70d2d7d35a037a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.16.jar",
          "url": "exposure-common-1.7.16.jar",
          "size": 1314241,
          "sha512": "2b83ee6b8b9ad416776813edd31c3fd3ab54334bcc097a960876201f5ee9774c61e8ea28e671fa18f88792561c8f15e01fa9e6b9bdd56bc81b1d89a493fdaafa",
          "sha256": "088faec6ee93254d8eab90c24ea02217034344a40ed444f048f135d805d0e11c",
          "sha1": "fc222c30abab591f30760f6323d13911617f08d0",
          "md5": "e1db1761ada7e0639c70d2d7d35a037a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.16-sources.jar",
          "url": "exposure-common-1.7.16-sources.jar",
          "size": 949573,
          "sha512": "c362e8f199353c9a3c764539c1d9551620f8990aac262d2fa2130362aff2a32a4b3212ad60f35e73ac6023b46d5bca0904aa9e6074a92c141c0a8f92afb893b4",
          "sha256": "e7dbf37c5d303a4f953780eb41abb9c8d9bbbc86c2d53f7c23383d85ae2ff425",
          "sha1": "4a5266dfccaabe5b886424be7d18e9595bd99948",
          "md5": "4d211502b49ed613a6e776456eff75aa"
        }
      ]
    }
  ]
}
