{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.0-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.0-forge.jar",
          "size": 467003,
          "sha512": "88d23949401d02c6772562c7a32642063cde43ab01468e9181cba4987cb2a7dd51cbe01a8fd2f5611157608d2fbeb4baabae9eb7faaf973ccc2015cb7de5154e",
          "sha256": "dda60fd393d00149b02c3e85d666aa0495bb8d1139b2f0bccbf456af9ae16412",
          "sha1": "6b31a6eaff6b5ce509c08d3c9e4e9acd3698b81a",
          "md5": "213de58db538e68263c31e00532b3bc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.0-forge.jar",
          "url": "scholar-1.20.1-forge-1.1.0-forge.jar",
          "size": 467003,
          "sha512": "88d23949401d02c6772562c7a32642063cde43ab01468e9181cba4987cb2a7dd51cbe01a8fd2f5611157608d2fbeb4baabae9eb7faaf973ccc2015cb7de5154e",
          "sha256": "dda60fd393d00149b02c3e85d666aa0495bb8d1139b2f0bccbf456af9ae16412",
          "sha1": "6b31a6eaff6b5ce509c08d3c9e4e9acd3698b81a",
          "md5": "213de58db538e68263c31e00532b3bc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.1.0-sources.jar",
          "url": "scholar-1.20.1-forge-1.1.0-sources.jar",
          "size": 187138,
          "sha512": "abce021e870f57da5318db871ad8914f237492b99dc82094ce0688c3e572bdd51cfd6442e29612185aa3e2adc89418a9af00edf2e1388846810e15419435db9d",
          "sha256": "9436c00ed325d0c16dec55a8999d80fa139387d58c58cd173e5d899b3f70a267",
          "sha1": "ce8977ad5ab38f20cbaf5d58c88be0868ce3ee09",
          "md5": "1164965ceadcb41183078029b8aa2efc"
        }
      ]
    }
  ]
}
