{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-26.1.1-common",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-common-api",
          "version": {
            "requires": "29.3.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.4.jar",
          "url": "horseman-26.1.1-common-1.7.4.jar",
          "size": 255552,
          "sha512": "6a5c7dee9aa6febd208001bc005501bdde87ff90a325c6f79ed4cecd6360b7f36335a75bbff56671e8fce3fe5e52a28ed54e72c1155d4c2c00b0c98204f088f4",
          "sha256": "a95bfa4d1a005f961611b9a9ca8d12354c6be23e3391be765eab4661845feaaf",
          "sha1": "14d32e3108af16036525de15cd8773a9526859d2",
          "md5": "a4095009a3309afd58d114432e10fc32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.4.jar",
          "url": "horseman-26.1.1-common-1.7.4.jar",
          "size": 255552,
          "sha512": "6a5c7dee9aa6febd208001bc005501bdde87ff90a325c6f79ed4cecd6360b7f36335a75bbff56671e8fce3fe5e52a28ed54e72c1155d4c2c00b0c98204f088f4",
          "sha256": "a95bfa4d1a005f961611b9a9ca8d12354c6be23e3391be765eab4661845feaaf",
          "sha1": "14d32e3108af16036525de15cd8773a9526859d2",
          "md5": "a4095009a3309afd58d114432e10fc32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.4-sources.jar",
          "url": "horseman-26.1.1-common-1.7.4-sources.jar",
          "size": 177507,
          "sha512": "6d638f0539a62ee6bf1f359c30b2b59c37e6c0d72ccfb4c42129886aa01bfa64fdb91f20d6ccae57e9780f484a96754c88e9249c3b79590befec695ccb96d744",
          "sha256": "dfbbef4f15246d4dbd749bc253688be97d0e3ac7dfb6ec3b1ae9877ff504c160",
          "sha1": "9d1e65a0985d64c083a82915faca3d5ecd048f40",
          "md5": "b031a353db30e3ace63e6448dc730537"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-common-1.7.4.jar",
          "url": "horseman-26.1.1-common-1.7.4.jar",
          "size": 255552,
          "sha512": "6a5c7dee9aa6febd208001bc005501bdde87ff90a325c6f79ed4cecd6360b7f36335a75bbff56671e8fce3fe5e52a28ed54e72c1155d4c2c00b0c98204f088f4",
          "sha256": "a95bfa4d1a005f961611b9a9ca8d12354c6be23e3391be765eab4661845feaaf",
          "sha1": "14d32e3108af16036525de15cd8773a9526859d2",
          "md5": "a4095009a3309afd58d114432e10fc32"
        }
      ]
    }
  ]
}
