{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.0-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.2.0-fabric.jar",
          "size": 834037,
          "sha512": "4469d25e6c0670798ed0191bad2e3e4d478fe58494e73e51b5b8ad0a0c4cf36789227d441bcb961d4abfb73778f5d3d3cba9d750f047ad5e5d5a01f722365c0f",
          "sha256": "335321d7b2c576db294a69859e2801c896d3840b17c9400649bf6738060182ad",
          "sha1": "839fecbcafaae06b16835a01ef07f737505a5559",
          "md5": "54639d9e6bc7e8883b8f99fcbf47cd92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.0-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.2.0-fabric.jar",
          "size": 834037,
          "sha512": "4469d25e6c0670798ed0191bad2e3e4d478fe58494e73e51b5b8ad0a0c4cf36789227d441bcb961d4abfb73778f5d3d3cba9d750f047ad5e5d5a01f722365c0f",
          "sha256": "335321d7b2c576db294a69859e2801c896d3840b17c9400649bf6738060182ad",
          "sha1": "839fecbcafaae06b16835a01ef07f737505a5559",
          "md5": "54639d9e6bc7e8883b8f99fcbf47cd92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.2.0-sources.jar",
          "url": "scholar-1.20.1-fabric-1.2.0-sources.jar",
          "size": 516952,
          "sha512": "f9cf387fa9fecdcfe24ee935b9676b2475809a33f804216c83974db396d211b657a7b160e2ea66038b4120a080ee4926cd7f24c29b0dd069c963aa2fc8d44835",
          "sha256": "212bdc3e54f628eb8d99630ee6bacbd120f98bb3b2c0ddaedd42215bb74222c0",
          "sha1": "bdf213908eb6c85d25102c9fe89f883b803cf8a9",
          "md5": "c7c6355c8e0d5b3fc51b8634895bb064"
        }
      ]
    }
  ]
}
