{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.0-snapshot9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot9.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot9.jar",
          "size": 2093479,
          "sha512": "0c758c2407bc33302c2d0f9c1f6bc9be639203bde76b876e28e393de5fbce49bdb1af5e1d873dafec7ffa7b852f1db60f1cea4a9f34c718b967747c201ed57c3",
          "sha256": "064ab937a4cbd23896b7589740ae34d13c6134a5ae4f2b343d5b9fe63122e562",
          "sha1": "9d5b5b8eecabdab62da67bfe37bf1d48f4be9977",
          "md5": "c1d90169c1f98bb503ab59a8969e12b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot9.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot9.jar",
          "size": 2093479,
          "sha512": "0c758c2407bc33302c2d0f9c1f6bc9be639203bde76b876e28e393de5fbce49bdb1af5e1d873dafec7ffa7b852f1db60f1cea4a9f34c718b967747c201ed57c3",
          "sha256": "064ab937a4cbd23896b7589740ae34d13c6134a5ae4f2b343d5b9fe63122e562",
          "sha1": "9d5b5b8eecabdab62da67bfe37bf1d48f4be9977",
          "md5": "c1d90169c1f98bb503ab59a8969e12b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot9-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot9-sources.jar",
          "size": 37636,
          "sha512": "85cfb126bc5f6d90b6228e238edff43ed1aef65464328f3f0aa7bdea5ea3b4a84bcea3f806608453268494ba3c916010c0d52ef07414e0735360716087961cba",
          "sha256": "bbe8b2ddf8bf35a0c95520621e38b626f360df84f75f2f623b63a632957faceb",
          "sha1": "9ff6411abe8c27a075c31cb260676336b9df6440",
          "md5": "a7ddae989e1f2832a50fcc3a11346903"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.0-snapshot9-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.0-snapshot9-dev-shadow.jar",
          "size": 1876760,
          "sha512": "b1c828562658ab17c2564354974cea26fa7acef738fd963013c9d443592f2386093e0b1899bcac6ad1d012a70f2f1c99ce14b05ad6914cda70966e5428efdea1",
          "sha256": "41de95d4635fe981a288c347c775e2e3e40d55975fa3b32be80c879718404609",
          "sha1": "2f3ad2d2b68b926ab9934cf997eb9a9743366a4e",
          "md5": "f8cbbd1aaf8e37caba2d39ed3fcde415"
        }
      ]
    }
  ]
}
