{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-forge",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.3-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.3-forge.jar",
          "size": 334825,
          "sha512": "662392b5237690b138b085629df1c890feb3a76003ac78932b24008da67ee89dec7520dbe881ea2e8d077b61dd7d3c975acee46eacf79e942c7811e081c26d7c",
          "sha256": "892b3022e2409ab0ac21eab7c7216a2f020e49f4a578819390cd85fd36162850",
          "sha1": "57b450a207d7ba4f3319c3a065430de733b412f8",
          "md5": "092e37a2f194c49715992e0bda63cc14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.3-forge.jar",
          "url": "horseman-1.20.1-forge-1.3.3-forge.jar",
          "size": 334825,
          "sha512": "662392b5237690b138b085629df1c890feb3a76003ac78932b24008da67ee89dec7520dbe881ea2e8d077b61dd7d3c975acee46eacf79e942c7811e081c26d7c",
          "sha256": "892b3022e2409ab0ac21eab7c7216a2f020e49f4a578819390cd85fd36162850",
          "sha1": "57b450a207d7ba4f3319c3a065430de733b412f8",
          "md5": "092e37a2f194c49715992e0bda63cc14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-forge-1.3.3-sources.jar",
          "url": "horseman-1.20.1-forge-1.3.3-sources.jar",
          "size": 90452,
          "sha512": "ee6b55ee2bb7c34e234675bcdf058b840847dff1a32c59c769098d0c273ab48be1d3ac57debd70b8d620b7507d22f5467d7b0311a9af74c14d59c8c1bac64dae",
          "sha256": "bac61fca9832021e80454431206586a7100e536d2fde3df544090270d7dc7fbc",
          "sha1": "e7ab39cdbde7069ba18e49047c76b4a8ad9b3586",
          "md5": "3a2117f05f568ad278f463a9e975a0bf"
        }
      ]
    }
  ]
}
