{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.20.1-forge",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.20.1-forge-1.3.4.jar",
          "url": "sootychimneys-1.20.1-forge-1.3.4.jar",
          "size": 363887,
          "sha512": "ac1406eec837d3de0893db78ea51964d12ec535f4f6c7819ebf30281aa2ef861df5085ef9496398e2f8783c9cd180eb01a750897ac060e3e66c34aba0c8f4ef4",
          "sha256": "4ce146a1caa9049c59a79dbc77f05de597d341d259f198f41b502186631edf68",
          "sha1": "2243c7cd658953be02ae2e08fe14f2709705b75e",
          "md5": "63a4c7bf6d8b45978ac333dd00246c8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.112"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.20.1-forge-1.3.4.jar",
          "url": "sootychimneys-1.20.1-forge-1.3.4.jar",
          "size": 363887,
          "sha512": "ac1406eec837d3de0893db78ea51964d12ec535f4f6c7819ebf30281aa2ef861df5085ef9496398e2f8783c9cd180eb01a750897ac060e3e66c34aba0c8f4ef4",
          "sha256": "4ce146a1caa9049c59a79dbc77f05de597d341d259f198f41b502186631edf68",
          "sha1": "2243c7cd658953be02ae2e08fe14f2709705b75e",
          "md5": "63a4c7bf6d8b45978ac333dd00246c8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.20.1-forge-1.3.4-sources.jar",
          "url": "sootychimneys-1.20.1-forge-1.3.4-sources.jar",
          "size": 14488,
          "sha512": "8414ba7b7c9138292325c0bc5ebf6830fef1539563676824da12a723a1a4c640ac1ec2fae74e52efdc2a29370890b4f5bf8b2765ede9fc514df1f08b6f01c635",
          "sha256": "a10cc6cadda2cc43f41920b0291026cc6f45a9fa2efe10e6339be50d439b05aa",
          "sha1": "47e89027ec7e4b22eb2b6454158bfb88cdea0113",
          "md5": "50ee131ae9fbee48ada5c1ce27d2e6f0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.20.1-forge-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.20.1-forge-1.3.4-dev-shadow.jar",
          "size": 175013,
          "sha512": "26caa5d103c3d6812edc2adec2d62a8905bdb4a463e81591940ee5eb9168f792b1e36a4897a6f7564f6c82c9d548649292739f8f20dd6c3e4aba50846e3310f2",
          "sha256": "5d2277eec4455bf70e9b6a597fd7091b2567e23e927fb36d98eb15a7de07b6de",
          "sha1": "f9ffcdfb47e1caa4f5f926a74890be8e85062b01",
          "md5": "fde4d4d33a450ad87552986ece23a52f"
        }
      ]
    }
  ]
}
