{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-26.1.1-fabric",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.2.jar",
          "url": "horseman-26.1.1-fabric-1.7.2.jar",
          "size": 278771,
          "sha512": "58ba0b1fdd6f301fa017ce9fdbc5f814aa772b82059ab00c0d80ea85b7cda7688376b99201988670a876782dd685d2e95dae8d849218bb8332d45f12bf920395",
          "sha256": "1a91844b21e1428dceb738cadffd2edfc0becbb97741403309e4406c20308232",
          "sha1": "f42ba42d194babcd0d852943cce1aa62be76ef25",
          "md5": "5a5fb25afa0ea049d1528ea1a35aed31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.2.jar",
          "url": "horseman-26.1.1-fabric-1.7.2.jar",
          "size": 278771,
          "sha512": "58ba0b1fdd6f301fa017ce9fdbc5f814aa772b82059ab00c0d80ea85b7cda7688376b99201988670a876782dd685d2e95dae8d849218bb8332d45f12bf920395",
          "sha256": "1a91844b21e1428dceb738cadffd2edfc0becbb97741403309e4406c20308232",
          "sha1": "f42ba42d194babcd0d852943cce1aa62be76ef25",
          "md5": "5a5fb25afa0ea049d1528ea1a35aed31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.2-sources.jar",
          "url": "horseman-26.1.1-fabric-1.7.2-sources.jar",
          "size": 188791,
          "sha512": "b363095806863b85d9c105b5bdeee14210a46d348f18f4d1bc625a7e706ba57757128e5eab48c9836b6c04bbe1715a6908c54ccf690e59b2f90e3b52c8f2e896",
          "sha256": "5f371f841a11bb86c3e703648b95714eb4b3d517a4d81f49c3ab455a8d6c39e3",
          "sha1": "1f260093ba0297ec204fb9ee9a75fa3468afb85a",
          "md5": "55d1f438eb7c77b24cf8366b133780ef"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-26.1.1-fabric-1.7.2.jar",
          "url": "horseman-26.1.1-fabric-1.7.2.jar",
          "size": 278771,
          "sha512": "58ba0b1fdd6f301fa017ce9fdbc5f814aa772b82059ab00c0d80ea85b7cda7688376b99201988670a876782dd685d2e95dae8d849218bb8332d45f12bf920395",
          "sha256": "1a91844b21e1428dceb738cadffd2edfc0becbb97741403309e4406c20308232",
          "sha1": "f42ba42d194babcd0d852943cce1aa62be76ef25",
          "md5": "5a5fb25afa0ea049d1528ea1a35aed31"
        }
      ]
    }
  ]
}
