{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.11-fabric",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.11-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.11-fabric-1.3.4.jar",
          "size": 170257,
          "sha512": "15899697947d3733902d34f230a85e6b8ca4a51fe76570c0af42f52916bb49199cb88af5208cee706ae7c7a8f2aa04d5621c3d45439ef208b238c6de0f5f31ce",
          "sha256": "3e4e697a4176f5929d08d254bde110a75beef2f9033e3fea28abeb57f08360b2",
          "sha1": "581f752d94dc8cf160bbd01fba4b5934ba2e9420",
          "md5": "1f90781e331a2262743e269da15e5fb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.5+1.21.11"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.11-fabric-1.3.4.jar",
          "url": "sootychimneys-1.21.11-fabric-1.3.4.jar",
          "size": 170257,
          "sha512": "15899697947d3733902d34f230a85e6b8ca4a51fe76570c0af42f52916bb49199cb88af5208cee706ae7c7a8f2aa04d5621c3d45439ef208b238c6de0f5f31ce",
          "sha256": "3e4e697a4176f5929d08d254bde110a75beef2f9033e3fea28abeb57f08360b2",
          "sha1": "581f752d94dc8cf160bbd01fba4b5934ba2e9420",
          "md5": "1f90781e331a2262743e269da15e5fb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.11-fabric-1.3.4-sources.jar",
          "url": "sootychimneys-1.21.11-fabric-1.3.4-sources.jar",
          "size": 7433,
          "sha512": "a6690ab5e7c963046aa54fb8522013cb6f1c0fc269a667a448da7ea1896cac02726227912a450fd3535c6dc2434475c78eeb5713dbd8c8e5c92f76f5256342ff",
          "sha256": "60ab4cf3864aa71dfb5dc34facfd11842708a464968d1ca2216fc11c08c5b32f",
          "sha1": "f3907985fda7bf6e381af85d618ff26e34868ed6",
          "md5": "556880215b54dc045317231f92d4e306"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.11-fabric-1.3.4-dev-shadow.jar",
          "url": "sootychimneys-1.21.11-fabric-1.3.4-dev-shadow.jar",
          "size": 166562,
          "sha512": "96e8214d215c801a55cd0307aa64215dd17f718ac37f61d172f880a58dab0451141cfb397af541cfcc94c64fbecd4ca341a8d30398a153797669444713dedd9a",
          "sha256": "e691c0c6c9b09cbe4b0ed0100ede29e13fbb5d5715fe26067c6d2b1c68c56797",
          "sha1": "feb65a154317072701a8f0b53ee74535d418ec93",
          "md5": "ee03f899f0565dc6d9e8b1734deeb5f9"
        }
      ]
    }
  ]
}
