{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.13-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.13-fabric.jar",
          "size": 316339,
          "sha512": "e52af4ea9404318c8fd8951a25026c4fd25b8514aa9a77ab52295eea9387ac2257bfb6b81a5b436f8b59b888e5c680352296ec767fa9b664dde41c8727d8d9b6",
          "sha256": "53ab4bd001e22b6fcc6a207ef9c5635279d6b6062b78c50575c6d1def949fd4a",
          "sha1": "546c777a1eb1474a9b9c04d53ac5aa8954b358df",
          "md5": "5bb80521ea5346f0fb5d323180b4a3f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.13-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.13-fabric.jar",
          "size": 316339,
          "sha512": "e52af4ea9404318c8fd8951a25026c4fd25b8514aa9a77ab52295eea9387ac2257bfb6b81a5b436f8b59b888e5c680352296ec767fa9b664dde41c8727d8d9b6",
          "sha256": "53ab4bd001e22b6fcc6a207ef9c5635279d6b6062b78c50575c6d1def949fd4a",
          "sha1": "546c777a1eb1474a9b9c04d53ac5aa8954b358df",
          "md5": "5bb80521ea5346f0fb5d323180b4a3f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.13-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.13-sources.jar",
          "size": 82701,
          "sha512": "1fd43a4b04314d13848f41cec619b412a53446e4aef593a4993186fd6ea0faa7451984d19f803db39490d44f125c788fab4599e5a32e7b8726a9e9746b3f8b92",
          "sha256": "551fb898fc83e05344d9fb35bce593276242ace6003dea9f06b819ee154cdd03",
          "sha1": "bd44b7fafe7bb7b9282c0118337c0f409cc8adb2",
          "md5": "d84fd3aae8174121ec6e0a3130e8ac46"
        }
      ]
    }
  ]
}
