{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.sootychimneys",
    "module": "sootychimneys-1.21.1-common",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.5.jar",
          "url": "sootychimneys-1.21.1-common-1.3.5.jar",
          "size": 161333,
          "sha512": "ebacaacd992d338936de5bd1eaeb933c9bc160bb75dbc5f5191b94adf38fad40d6c7f94e2320fa9614e6b23dd52d69a58999188d8f4537a583a4dc36d8926501",
          "sha256": "e4c3e2ff0dbb714cffc6b4106821c1f79d312898fa3a76fba310e2bf9c981b8d",
          "sha1": "66fcccbb94033e7155062eade6afcfc6bde7b936",
          "md5": "3930e042e41f44e2824240a238bbd772"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.5.jar",
          "url": "sootychimneys-1.21.1-common-1.3.5.jar",
          "size": 161333,
          "sha512": "ebacaacd992d338936de5bd1eaeb933c9bc160bb75dbc5f5191b94adf38fad40d6c7f94e2320fa9614e6b23dd52d69a58999188d8f4537a583a4dc36d8926501",
          "sha256": "e4c3e2ff0dbb714cffc6b4106821c1f79d312898fa3a76fba310e2bf9c981b8d",
          "sha1": "66fcccbb94033e7155062eade6afcfc6bde7b936",
          "md5": "3930e042e41f44e2824240a238bbd772"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sootychimneys-1.21.1-common-1.3.5-sources.jar",
          "url": "sootychimneys-1.21.1-common-1.3.5-sources.jar",
          "size": 117298,
          "sha512": "45417b25a0a4efbc6a43e3f9e538559fdd21620204f57436a6be16711cab0e12a793592098b6c02da7f67dfa78c6966e7d7149e6d9d9e7a6a5297e7d570b2689",
          "sha256": "412281808573ae049b0091c42c85ed99e69eceb9bfa008ee403502402cbff399",
          "sha1": "2dbede7547bc6b02c040e65076a906cf909f4039",
          "md5": "fab68707e05f3e47f8f5058e7518ae8c"
        }
      ]
    }
  ]
}
