{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.0.jar",
          "url": "scholar-1.20.1-common-1.1.0.jar",
          "size": 252116,
          "sha512": "14f574d05be1c433ba8e77ccf904c5fb829f90d8921e9074e4a99be86de972496dd14e1456bd4c36495e867c668736a1084121f186414b8ed733f69a348065de",
          "sha256": "4b2cee780d7cc5e22a88c873968cb6ab6116ffdfc8615d40feea60f9705a1b45",
          "sha1": "66196c00f52a771ceada351b5454f8c68d84dec7",
          "md5": "46d4e8926cb96f006907d0c05f35a6e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.25"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.0.jar",
          "url": "scholar-1.20.1-common-1.1.0.jar",
          "size": 252116,
          "sha512": "14f574d05be1c433ba8e77ccf904c5fb829f90d8921e9074e4a99be86de972496dd14e1456bd4c36495e867c668736a1084121f186414b8ed733f69a348065de",
          "sha256": "4b2cee780d7cc5e22a88c873968cb6ab6116ffdfc8615d40feea60f9705a1b45",
          "sha1": "66196c00f52a771ceada351b5454f8c68d84dec7",
          "md5": "46d4e8926cb96f006907d0c05f35a6e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.0-sources.jar",
          "url": "scholar-1.20.1-common-1.1.0-sources.jar",
          "size": 158848,
          "sha512": "1fa6b339c37031a850af97cdb9ec8e33e525338f06a8e3a1abf00a4049f0c071dca5012d67c405651be633d423ae8b4a82a4b0d52986a259bbdabf265ca35278",
          "sha256": "208841cd0ce2b8aa0dcebf2667111897eec804c92c0040910f954f4e4968ccef",
          "sha1": "3fb4b39a631a004ffc788ed69c6d95995d987561",
          "md5": "9c41ecb70c92a6ab30fee8c471fde415"
        }
      ]
    }
  ]
}
