{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.8-fabric.jar",
          "url": "exposure-fabric-1.7.8-fabric.jar",
          "size": 1310205,
          "sha512": "f1e81daeb462502688f7c0ebe5558853835318ab765b3f781c541b4bdf50148878e820c454b2680b736545fb9d0d17110f4b1e5187feb22d45be677174ed6e5b",
          "sha256": "3b1edd965e98a9e280f122f120ccfa1f74856423a3251f3ba6542e5cdf33826a",
          "sha1": "ec67015cd51c6e6335280b2dac25e2f6332b586a",
          "md5": "73885734cdc42a42deb9c3d8d5cf9bdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.8-fabric.jar",
          "url": "exposure-fabric-1.7.8-fabric.jar",
          "size": 1310205,
          "sha512": "f1e81daeb462502688f7c0ebe5558853835318ab765b3f781c541b4bdf50148878e820c454b2680b736545fb9d0d17110f4b1e5187feb22d45be677174ed6e5b",
          "sha256": "3b1edd965e98a9e280f122f120ccfa1f74856423a3251f3ba6542e5cdf33826a",
          "sha1": "ec67015cd51c6e6335280b2dac25e2f6332b586a",
          "md5": "73885734cdc42a42deb9c3d8d5cf9bdd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.8-sources.jar",
          "url": "exposure-fabric-1.7.8-sources.jar",
          "size": 954126,
          "sha512": "ed2f88d610ce046232f253e4513528c2cc3ba2edd37e226d7e7f81ae75e6f9a33105f67d324a35fb0fff981fb709efa28ac6df1b3c550f1ea52234a82e3d7cd7",
          "sha256": "2215d0a502f67848c5374be100eb882f15817fb2ebdf3ff5ff3186deb2c461e2",
          "sha1": "e8fc828fc7340a7c7db86a62d191541db623098e",
          "md5": "a3f8539e4abc03579d216c29e708c25b"
        }
      ]
    }
  ]
}
