{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-forge",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.2-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.2-forge.jar",
          "size": 849730,
          "sha512": "c8a70e7bb3fe814715e2307eb07a87f27a08364951c25f085c496d4520feceefa4dce7561298fedbd20ca92904fcefa1bc0f649ffbf46c94532766392cca6e69",
          "sha256": "63272ae8faff523d2dd885634c6abd1f8368235b69df9a6db590aac93dafd3e4",
          "sha1": "33c49424b27db253547b567a2aa1d94c7e7089ea",
          "md5": "f07ad7a305636d4abc166f0d60f96405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "blueprint",
          "version": {
            "requires": "z4m8zvm5"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "woodworks",
          "version": {
            "requires": "236Amnif"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "embeddium",
          "version": {
            "requires": "0.3.31+mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.2-forge.jar",
          "url": "scholar-1.20.1-forge-1.2.2-forge.jar",
          "size": 849730,
          "sha512": "c8a70e7bb3fe814715e2307eb07a87f27a08364951c25f085c496d4520feceefa4dce7561298fedbd20ca92904fcefa1bc0f649ffbf46c94532766392cca6e69",
          "sha256": "63272ae8faff523d2dd885634c6abd1f8368235b69df9a6db590aac93dafd3e4",
          "sha1": "33c49424b27db253547b567a2aa1d94c7e7089ea",
          "md5": "f07ad7a305636d4abc166f0d60f96405"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-forge-1.2.2-sources.jar",
          "url": "scholar-1.20.1-forge-1.2.2-sources.jar",
          "size": 523589,
          "sha512": "1cbecb81dd711763bfea2488c966333f3dc32b27610dab8cf2d17fc1642bbe96b1e21f12df5a8fdfd183e81c1b5f056cc93f110b5d9b67c70f9d2452f6068726",
          "sha256": "1edd87c9d973d9b11c84329b7b621ce5be40750682e28758a3730f9f0e17fba1",
          "sha1": "577affb7ae89aebbe4b8d289609dfec55e3e4a49",
          "md5": "34decb1487b7294ff4f89676a4891165"
        }
      ]
    }
  ]
}
