{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.6-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.6-fabric.jar",
          "size": 321653,
          "sha512": "809c97d2a38e825eae5d3c6e7b970a32a979d1e34f06a27347e2c646895f1e5cb35239ed17d2480f96903f28f8acd9942c4e7d52057c00af8fc4a892fea70b78",
          "sha256": "06e9979a1faf5bf989a4c24467eb73b32aa636afa55b42b5af3f98992e7ead10",
          "sha1": "65c54d925b67d864c96bcf0ab4fe9db615bd95eb",
          "md5": "863eaa1bb0bd63398f5741b5aa94efc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.6-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.6-fabric.jar",
          "size": 321653,
          "sha512": "809c97d2a38e825eae5d3c6e7b970a32a979d1e34f06a27347e2c646895f1e5cb35239ed17d2480f96903f28f8acd9942c4e7d52057c00af8fc4a892fea70b78",
          "sha256": "06e9979a1faf5bf989a4c24467eb73b32aa636afa55b42b5af3f98992e7ead10",
          "sha1": "65c54d925b67d864c96bcf0ab4fe9db615bd95eb",
          "md5": "863eaa1bb0bd63398f5741b5aa94efc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.6-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.6-sources.jar",
          "size": 84082,
          "sha512": "7da0530d885dabbf06e89cc41769fc3dd38ecb9fa8f1a30067436847877d61de087a695297f36ab99ad949b62bfe76a9cb3b94e888ac748e15a5e4aeab54c4c7",
          "sha256": "4d2adf97b24c9bf385bbf7f711c333107b7d95d0e102807cb6b74a0357479033",
          "sha1": "1eb84ae1b95bc328db933d5ba2d795b6175dced1",
          "md5": "ab560c8f11cddd94ad2f97bf5c8d729e"
        }
      ]
    }
  ]
}
