{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.6.jar",
          "url": "horseman-1.21.1-fabric-1.3.6.jar",
          "size": 138915,
          "sha512": "160a5c35fc3274722568afba23606374ac18ac7915ea8054563521b43f58c13b3929e6c14e984dc5ac76ad84046fe82f6900bccb746a3d509b8abe3427c925c3",
          "sha256": "d9599fdffc936391844457055bc77a5995823b4508f7d6d35d728cb9bde71184",
          "sha1": "cc85493a4a217c7490165eebabd305f0d32befa7",
          "md5": "0b2768b25ab6abecee9ba424dfd6c22d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.6.jar",
          "url": "horseman-1.21.1-fabric-1.3.6.jar",
          "size": 138915,
          "sha512": "160a5c35fc3274722568afba23606374ac18ac7915ea8054563521b43f58c13b3929e6c14e984dc5ac76ad84046fe82f6900bccb746a3d509b8abe3427c925c3",
          "sha256": "d9599fdffc936391844457055bc77a5995823b4508f7d6d35d728cb9bde71184",
          "sha1": "cc85493a4a217c7490165eebabd305f0d32befa7",
          "md5": "0b2768b25ab6abecee9ba424dfd6c22d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.6-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.6-sources.jar",
          "size": 14731,
          "sha512": "769712a0a301d739fc1a6e824dd142d13450f86f5611614633abc360d5f6931c273d0fa5aeef580be8b6602357eec40979147c00f8eb427f89913ef1be67dada",
          "sha256": "7807ce6bb3486cc7a51ea3e9d707ca55c840e68a928158e93c0d7a4561e36dfb",
          "sha1": "8b799ef8a558b25f53a59d0131fde9e7cef67269",
          "md5": "3906f7d5abd3943ae18dfe8191dd7564"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.6-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.6-dev-shadow.jar",
          "size": 137537,
          "sha512": "4dbc025df506144744ef7e8553530a63a19b7b56d48eb5974f4cb242d0453888b1093498f5eaee0f0d798f08c59f026a27588959fee71d3bb6bfd744d5c10a46",
          "sha256": "d27cd2e7f7c7a046b16709d16da42112fb5ca357dcc677a0beb8dc3544a6c8f4",
          "sha1": "ecab62758b1d01eac8c2275a4333052dde84ddd8",
          "md5": "9394c75a610630f5625970ed3a2e8152"
        }
      ]
    }
  ]
}
