{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-fabric",
    "version": "1.7.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.11-fabric.jar",
          "url": "exposure-fabric-1.7.11-fabric.jar",
          "size": 1315739,
          "sha512": "bb29bc0f8662f390780fd3ac933c7d5c783a144db4eb6f63831fb69c5654b3e13ab26fdedf6c765fc7607b4d9a3e9055a79b60ba15f0fa1151f32b557b397e54",
          "sha256": "1c6615f649108a40f7055a104eed5e2d4da2e2ac55a21d84376737e13a109def",
          "sha1": "e87d9166d210efe22187b357c2e20bc34ebff9c5",
          "md5": "fbe1648d0ee275c0deadd4a66ccf0561"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.20.1-0.5.13-fabric"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.11-fabric.jar",
          "url": "exposure-fabric-1.7.11-fabric.jar",
          "size": 1315739,
          "sha512": "bb29bc0f8662f390780fd3ac933c7d5c783a144db4eb6f63831fb69c5654b3e13ab26fdedf6c765fc7607b4d9a3e9055a79b60ba15f0fa1151f32b557b397e54",
          "sha256": "1c6615f649108a40f7055a104eed5e2d4da2e2ac55a21d84376737e13a109def",
          "sha1": "e87d9166d210efe22187b357c2e20bc34ebff9c5",
          "md5": "fbe1648d0ee275c0deadd4a66ccf0561"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.11-sources.jar",
          "url": "exposure-fabric-1.7.11-sources.jar",
          "size": 959846,
          "sha512": "9418a2de8390c8d231d0747373be0af5db3036f546018f089e5e97e1c73863865dc16f0c1fe5d628b703949c4cba730a80c1aff5269e1805823b42d4ffeb6f43",
          "sha256": "15cdbde00f529c20b34dc9a688d245e2b421a42f7dc4ef6ad5cb9427ad9655e4",
          "sha1": "28f038ed683bd5a070b9b2e91b325558f2c29055",
          "md5": "3a832ae72b8cbe795dd8e8ed936c94b9"
        }
      ]
    }
  ]
}
