{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.9.jar",
          "url": "horseman-1.21.1-fabric-1.3.9.jar",
          "size": 139480,
          "sha512": "5ff4ac8fa615032aac677413d0dce0ec89e06682e00418eff410ead05b3920383e57750ccdbbc62d2d62c1266bdf75d1518688c4a95697fc162f1c0ec68c2ace",
          "sha256": "eb20143aba04b05814381af05cc418a95e81370a91112664f35511e66cfdecf2",
          "sha1": "7ca36f3bf6683c88734a65e0eb854be3c2e4147a",
          "md5": "50c4e1c7649781b46dee2d1ba5b02190"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.9.jar",
          "url": "horseman-1.21.1-fabric-1.3.9.jar",
          "size": 139480,
          "sha512": "5ff4ac8fa615032aac677413d0dce0ec89e06682e00418eff410ead05b3920383e57750ccdbbc62d2d62c1266bdf75d1518688c4a95697fc162f1c0ec68c2ace",
          "sha256": "eb20143aba04b05814381af05cc418a95e81370a91112664f35511e66cfdecf2",
          "sha1": "7ca36f3bf6683c88734a65e0eb854be3c2e4147a",
          "md5": "50c4e1c7649781b46dee2d1ba5b02190"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.9-sources.jar",
          "url": "horseman-1.21.1-fabric-1.3.9-sources.jar",
          "size": 17899,
          "sha512": "ac7043604c607e2408844cac2c740abc92ce0ca9d76521c0dca5b3e8b09dec248edb5139c1fbb771d81d6bd0de44d806ba53570c21bf6c6b5776b32300658ba7",
          "sha256": "bca9db391c3fd12b6b9efc3ac9c514c31b8b1c3806db7ba69378c11cb9000416",
          "sha1": "2c9ebbc2c540d7b667e4f612c9ef9bb3d1e2d673",
          "md5": "4250693a0b954f42d156d166ecbed901"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.3.9-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.3.9-dev-shadow.jar",
          "size": 138101,
          "sha512": "5b5ed67a4a62aab5bcd4379852dcb5682039b00dd0af471753162f547609f903a0491e3702a0ca9640d8db908e926a5bac388822bcd5c4b608c14197b3c61510",
          "sha256": "0838ce0123e310f6bf71273a550401187d6d336b2e872cf854755003748b850b",
          "sha1": "08508af276e28615829b2efcff37eb2ed15b23cd",
          "md5": "1c511beac39bf347edc1382f075439c5"
        }
      ]
    }
  ]
}
