{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.21.11-neoforge",
    "version": "1.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge-api",
          "version": {
            "requires": "27.4.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.11-neoforge-1.1.16.jar",
          "url": "scholar-1.21.11-neoforge-1.1.16.jar",
          "size": 719147,
          "sha512": "86a38215a5f5cb9ae956c3a39fa21123e4e6c8577864022d8421d0473a79c43d66c1b2e60c1addae2e4fbb46a3d089d3243ae17cca9016ce0a62d0f60d0351e5",
          "sha256": "52f5c6cdba29764fe527be594ac81680c40d3af9a6db43c10c78deef1eb4dcb9",
          "sha1": "527e52aa5155be4684e8d221eb5cd1d5dfddef8d",
          "md5": "3562100f27135f4a6329d4918fd6504b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge",
          "version": {
            "requires": "27.4.0.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "scholar-1.21.11-neoforge-1.1.16.jar",
          "url": "scholar-1.21.11-neoforge-1.1.16.jar",
          "size": 719147,
          "sha512": "86a38215a5f5cb9ae956c3a39fa21123e4e6c8577864022d8421d0473a79c43d66c1b2e60c1addae2e4fbb46a3d089d3243ae17cca9016ce0a62d0f60d0351e5",
          "sha256": "52f5c6cdba29764fe527be594ac81680c40d3af9a6db43c10c78deef1eb4dcb9",
          "sha1": "527e52aa5155be4684e8d221eb5cd1d5dfddef8d",
          "md5": "3562100f27135f4a6329d4918fd6504b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.11-neoforge-1.1.16-sources.jar",
          "url": "scholar-1.21.11-neoforge-1.1.16-sources.jar",
          "size": 31845,
          "sha512": "14df65ea6f68e8bca2be2395be6d95b2173404846fb45944810dc5947ac7d435320ea73fc3eef600a7a9bffa3d6f0a26d64cd26f298a71d4e17d58a28182fdbf",
          "sha256": "1223f83d479658d55cd1ff4ea3c71335f3f22aa1314091a672e6168e97a674a3",
          "sha1": "c556c2a0cf60b745394d14cee3773a5f2f8c1338",
          "md5": "5e62fb7ce2700e5ac5d08e394518c4d6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.21.11-neoforge-1.1.16-dev-shadow.jar",
          "url": "scholar-1.21.11-neoforge-1.1.16-dev-shadow.jar",
          "size": 527365,
          "sha512": "22fd4cd384fa3b1fcf090f31f8c51c9038f98d05fb3258321344287fb99f6e8480a6aecf5b393247eff1b79feebf7ecda300a61bb28cec15cf3180b134c776e1",
          "sha256": "90c62b864714c1393cf11830dd8006d30442c6c5d7fe1e9fe6f56ac575ddeb18",
          "sha1": "0b4f51312061a3c1284826365b7c7e3add902c67",
          "md5": "488475dd3848a0ed3f1f54ea58d7b82b"
        }
      ]
    }
  ]
}
