{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.20.1-fabric",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.2-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.2-fabric.jar",
          "size": 318259,
          "sha512": "e1d70306a2f763970bb097981a86b11e9b67840fa2c7ce38dd58adb836ebf382d48c044d3828c0107787b3c27d1c1ee81e8fbed3f387c83172495918efff9ef6",
          "sha256": "4ac84a0d18f3a84ee26010f59325f80bdfb70d7163774b639eec4b3f5e79a389",
          "sha1": "e011c0cc81456383d871fe335e89e13d81fe2fb7",
          "md5": "d5b9a3f28b6959eba7f5dfda6d39cab2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "horseshoes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.2-fabric.jar",
          "url": "horseman-1.20.1-fabric-1.3.2-fabric.jar",
          "size": 318259,
          "sha512": "e1d70306a2f763970bb097981a86b11e9b67840fa2c7ce38dd58adb836ebf382d48c044d3828c0107787b3c27d1c1ee81e8fbed3f387c83172495918efff9ef6",
          "sha256": "4ac84a0d18f3a84ee26010f59325f80bdfb70d7163774b639eec4b3f5e79a389",
          "sha1": "e011c0cc81456383d871fe335e89e13d81fe2fb7",
          "md5": "d5b9a3f28b6959eba7f5dfda6d39cab2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.20.1-fabric-1.3.2-sources.jar",
          "url": "horseman-1.20.1-fabric-1.3.2-sources.jar",
          "size": 81980,
          "sha512": "2e58e92c259341442217b09176fb04361a8221187bff7042a139d853c0136cba42436bbee66fdaf852564d2b1103e42fcc61c2254d36869f5cd27ef83360fffe",
          "sha256": "cef5a24189c2782904949208d6a08cbf330a4c6d026b8b83516e78e6f3c7c361",
          "sha1": "e768cb0bdac72ab758a22270c7b2fa094fbbfd21",
          "md5": "55a20e59ea9138f7ff14f6172e280723"
        }
      ]
    }
  ]
}
