{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure_polaroid",
    "module": "exposure_polaroid-1.21.1-fabric",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.3.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.3.jar",
          "size": 179186,
          "sha512": "c0b359bb5f4a2ea738de95a57b08c61bb3ea71e3af16fda631a47e89076bfe1f68df0c21cc1e2ed68df90f4ea12a27ee736ea704899815b073dd092bc1d79a24",
          "sha256": "891c40567bb567f42911ad2c690d6ab3913bb68443cd6beba6d8113ae6018492",
          "sha1": "6e931cec46f9bd4359a1ebf88798a22efc72baec",
          "md5": "aa665531c8aa208a52880bb9eb29bb0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.github.mortuusars.exposure",
          "module": "exposure-1.21.1-fabric",
          "version": {
            "requires": "1.9.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "io.github.mortuusars.exposure_catalog",
          "module": "exposure_catalog-fabric",
          "version": {
            "requires": "1.21.1-1.1.1-snapshot1"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.3.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.3.jar",
          "size": 179186,
          "sha512": "c0b359bb5f4a2ea738de95a57b08c61bb3ea71e3af16fda631a47e89076bfe1f68df0c21cc1e2ed68df90f4ea12a27ee736ea704899815b073dd092bc1d79a24",
          "sha256": "891c40567bb567f42911ad2c690d6ab3913bb68443cd6beba6d8113ae6018492",
          "sha1": "6e931cec46f9bd4359a1ebf88798a22efc72baec",
          "md5": "aa665531c8aa208a52880bb9eb29bb0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.3-sources.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.3-sources.jar",
          "size": 10518,
          "sha512": "8887bf5b8551019b37e962a3c2eaa8499ef41182d4b6a0f13345e9f03e0c07f0f20b340e6c6dfb4568030bfa35e45d8ba7011ca1ccbddf69b23978bfe773563a",
          "sha256": "9cb6c12f61dc9d5fab9e1cb1dc913e91a64db37f7accfd56438809fde6af4930",
          "sha1": "44485493db49bd453e6ef874d89db4d3546f8490",
          "md5": "fba008f00b128862a5da9090231c2ea3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure_polaroid-1.21.1-fabric-1.1.3-dev-shadow.jar",
          "url": "exposure_polaroid-1.21.1-fabric-1.1.3-dev-shadow.jar",
          "size": 176365,
          "sha512": "af1660715eeee4ebfb034b88e80c32af230020883dd16ea4edd4745aea01ea61d3beb68ceaec696df6b1fab9594c94d29dfce214f72235e64c049d943863d3c8",
          "sha256": "13260914a07240d140be1d51721fdfca5c8eac453646f95b988637db5ccb9aa7",
          "sha1": "80d8ee0eef1e2d0a8683d4bf82cf00cdf4875d16",
          "md5": "8e192d0403dc0f9a5f583e95e855e552"
        }
      ]
    }
  ]
}
