{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.17.jar",
          "url": "exposure-1.21.1-neoforge-1.9.17.jar",
          "size": 2190343,
          "sha512": "0ad5c7fa4368dc08f4e5a43cadfe9dea951e51734fe689524657f5439a06289f48eac78ae3f5d7ec031d75ad28c1ccca7623c0834e0686c5ebb83dcc26648178",
          "sha256": "892b9600b3a664e1c1721611b99dd1799d05048303cf025ee89c470e062874b8",
          "sha1": "7f979d58add6b477ae299b6de0dab7b25cb8e74a",
          "md5": "ac6ae8c9a657c5b05f0d7b6cfe338c55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.8-168"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.64"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "essentialsmod",
          "version": {
            "requires": "y6XzoYMQ"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "crossroads",
          "version": {
            "requires": "EgSYNn26"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.17.jar",
          "url": "exposure-1.21.1-neoforge-1.9.17.jar",
          "size": 2190343,
          "sha512": "0ad5c7fa4368dc08f4e5a43cadfe9dea951e51734fe689524657f5439a06289f48eac78ae3f5d7ec031d75ad28c1ccca7623c0834e0686c5ebb83dcc26648178",
          "sha256": "892b9600b3a664e1c1721611b99dd1799d05048303cf025ee89c470e062874b8",
          "sha1": "7f979d58add6b477ae299b6de0dab7b25cb8e74a",
          "md5": "ac6ae8c9a657c5b05f0d7b6cfe338c55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.17-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.17-sources.jar",
          "size": 39298,
          "sha512": "ea1070d7bf8f62fcac5ec0b7d2e1ed9f83210b6c08ab0b2f70be5773331781eb173a3044960569daeab9c92b4e9bf990b43007b26d7acccfb8e14f77c9b893ec",
          "sha256": "f9b972a43c69ddb5d266b608143d2e8f6d044846cc9f4f37ea93265883a1e477",
          "sha1": "c7563c939d2f0617af06bf3d59faa2c9dfbd03de",
          "md5": "7d753a256ff1aca7640102b0386bb384"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.17-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.17-dev-shadow.jar",
          "size": 1972231,
          "sha512": "e86346ef72a20a8f22ff6948c232d80effccc9179814cd21123d7b44668b2db9522a352ed07b92f571f5475933408102fc19bf8edd76d1c37a6facba2eaf8b1c",
          "sha256": "16b50ca1faa8ca8aa6b17d48007f8670afa5dcf821738f0c011b025e3671df00",
          "sha1": "2e112d9bf52d888b8829cf26c474d6daf741674c",
          "md5": "6e48ce72db4fe6f31d0a8db3b1ef884d"
        }
      ]
    }
  ]
}
