{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.10.jar",
          "url": "horseman-1.21.1-common-1.3.10.jar",
          "size": 117868,
          "sha512": "725016e14f14155828b9adcf7aa59c2e9285e7609288b07bb8bc252f5cb8782bb93b787061ecb334b048c7d10dc8a8444d4e5e3b242a20997f56ce0bb282384e",
          "sha256": "ac1706233e2a61f9d81d1397e4dc78649611353d4db074c12e59764e8e2b28a2",
          "sha1": "22d3a97c4ff6e784d209181ee828fa73374ff440",
          "md5": "2505937118caea213204b3b1b12c1b74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.10.jar",
          "url": "horseman-1.21.1-common-1.3.10.jar",
          "size": 117868,
          "sha512": "725016e14f14155828b9adcf7aa59c2e9285e7609288b07bb8bc252f5cb8782bb93b787061ecb334b048c7d10dc8a8444d4e5e3b242a20997f56ce0bb282384e",
          "sha256": "ac1706233e2a61f9d81d1397e4dc78649611353d4db074c12e59764e8e2b28a2",
          "sha1": "22d3a97c4ff6e784d209181ee828fa73374ff440",
          "md5": "2505937118caea213204b3b1b12c1b74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.10-sources.jar",
          "url": "horseman-1.21.1-common-1.3.10-sources.jar",
          "size": 70070,
          "sha512": "3a986aea9a07f6b133f34c79ef0d73c639207249d0b31071d847e0f0d1938dfbe4111ae4faebd18e1177e43af1ca8bd734eb22ba79c0ec4c61384152bd68e1cf",
          "sha256": "997161f59b86f966eeb4da3610691aab34336a78f7f95665d9e072988d52c980",
          "sha1": "1948ca638d78def81339d5c78769347894252c03",
          "md5": "a764be1f5ea05d68e91655c8888d3476"
        }
      ]
    }
  ]
}
