{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-common",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.10.jar",
          "url": "horseman-1.21.1-common-1.3.10.jar",
          "size": 176145,
          "sha512": "6e918dd14cd8b436100183da3088c30728895283799889e44b3f8743a6c9e1bfe899d59481fb43b84691e1dbcae0cbd7e1fe9d70ce84dcc66ff76d8e7afa6d26",
          "sha256": "51d16fb0d55a4628a29dac899c25a47cdef71d61a6d418888af75dca5382a77a",
          "sha1": "c6846529461b43796b13fdf30a52e39ba3f1d3e4",
          "md5": "4ee8338b6394fdbe6bc19007d48e136f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.10.jar",
          "url": "horseman-1.21.1-common-1.3.10.jar",
          "size": 176145,
          "sha512": "6e918dd14cd8b436100183da3088c30728895283799889e44b3f8743a6c9e1bfe899d59481fb43b84691e1dbcae0cbd7e1fe9d70ce84dcc66ff76d8e7afa6d26",
          "sha256": "51d16fb0d55a4628a29dac899c25a47cdef71d61a6d418888af75dca5382a77a",
          "sha1": "c6846529461b43796b13fdf30a52e39ba3f1d3e4",
          "md5": "4ee8338b6394fdbe6bc19007d48e136f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-common-1.3.10-sources.jar",
          "url": "horseman-1.21.1-common-1.3.10-sources.jar",
          "size": 101288,
          "sha512": "a1c38d8380be72cd9da590ff3fac2fbb37b37d1602d63ff684174c71497b759f440c8e4ee691a4b932ff42cf0af7e9e3a5ead09c597cbe083e291759566d650a",
          "sha256": "fe8634c5e4aa8743c01fd6f6b5d31ea465a358d884156cd3ce759156aecc9b0d",
          "sha1": "dc6b4bfa0e539e35814ef17849ffb27fa04429c6",
          "md5": "f9345967d839ff94755d04961502ef26"
        }
      ]
    }
  ]
}
