{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.1.jar",
          "url": "scholar-1.20.1-common-1.1.1.jar",
          "size": 263064,
          "sha512": "61d56cbf3c0d682a39ea1432340f85cd9239d3baa546056e01d1b4faefd22f63d9dbbeb8cb0282258030689fba7f758962ede9ea2fd71af7a5b3543eb5b039c4",
          "sha256": "02a5cb3af316b3d33884135e2393e8263b4c99e918b3895af27ef726f017156f",
          "sha1": "093f10f511b2ba81f8e1c350509e8f6a83d31cf4",
          "md5": "e7cbef4693453e736811334c940d3ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.25"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.1.jar",
          "url": "scholar-1.20.1-common-1.1.1.jar",
          "size": 263064,
          "sha512": "61d56cbf3c0d682a39ea1432340f85cd9239d3baa546056e01d1b4faefd22f63d9dbbeb8cb0282258030689fba7f758962ede9ea2fd71af7a5b3543eb5b039c4",
          "sha256": "02a5cb3af316b3d33884135e2393e8263b4c99e918b3895af27ef726f017156f",
          "sha1": "093f10f511b2ba81f8e1c350509e8f6a83d31cf4",
          "md5": "e7cbef4693453e736811334c940d3ff8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.1-sources.jar",
          "url": "scholar-1.20.1-common-1.1.1-sources.jar",
          "size": 169258,
          "sha512": "68dce6635369b028bb9ff4d08935ecd4dbe5017ee161b945c8978f174efec0cbb86e2cbdb16812f4b926f299c32a163a151636dd2ae206bdd47030f0fefad6c0",
          "sha256": "081c7ca30334edec2a0427b44a04f3e3786332ce8348a4e256ad667cd4682164",
          "sha1": "803c22579c631828056dd3f8bbcabf1fc415993b",
          "md5": "9650ccd6999e4b1d796eef9816b7135b"
        }
      ]
    }
  ]
}
