{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-26.1.2-fabric",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.2.jar",
          "url": "scholar-26.1.2-fabric-1.2.2.jar",
          "size": 737607,
          "sha512": "9bbcdcf63e32b0a50b5a6b1835317814981302355be71f11f3d33330974c6a03cb2a575f83db898a4d958dc6af0ab35c9d15952a3cc4f67030d140c5dbccbd77",
          "sha256": "cd1ad29710d5ca500616a0421734141114d421cd0704a1fc39c1b427ddf6c01f",
          "sha1": "d91814242687739ef0a1e0405c57abb719716386",
          "md5": "be200b3a39c7fa7d9108bdda138118d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.144.3+26.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.2.jar",
          "url": "scholar-26.1.2-fabric-1.2.2.jar",
          "size": 737607,
          "sha512": "9bbcdcf63e32b0a50b5a6b1835317814981302355be71f11f3d33330974c6a03cb2a575f83db898a4d958dc6af0ab35c9d15952a3cc4f67030d140c5dbccbd77",
          "sha256": "cd1ad29710d5ca500616a0421734141114d421cd0704a1fc39c1b427ddf6c01f",
          "sha1": "d91814242687739ef0a1e0405c57abb719716386",
          "md5": "be200b3a39c7fa7d9108bdda138118d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.2-sources.jar",
          "url": "scholar-26.1.2-fabric-1.2.2-sources.jar",
          "size": 565621,
          "sha512": "4bdc0fc06eba77fa8862eb09208259749b116c027276424f15cdf336ab77e571c14c3c939c5fe08665c2b04c1162a925b94d47843b71c747a3b90436df837d4b",
          "sha256": "4ef8f8b13419314cb3f41e00ab670be2289f7b05424edaf091fcca4d6013e8c5",
          "sha1": "06a353208f61368293691d0223dd4adff10e69fa",
          "md5": "5b1dc274a0c2dd97a2f20f224b4c7830"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-fabric-1.2.2.jar",
          "url": "scholar-26.1.2-fabric-1.2.2.jar",
          "size": 737607,
          "sha512": "9bbcdcf63e32b0a50b5a6b1835317814981302355be71f11f3d33330974c6a03cb2a575f83db898a4d958dc6af0ab35c9d15952a3cc4f67030d140c5dbccbd77",
          "sha256": "cd1ad29710d5ca500616a0421734141114d421cd0704a1fc39c1b427ddf6c01f",
          "sha1": "d91814242687739ef0a1e0405c57abb719716386",
          "md5": "be200b3a39c7fa7d9108bdda138118d5"
        }
      ]
    }
  ]
}
