{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.6.jar",
          "url": "scholar-1.20.1-common-1.1.6.jar",
          "size": 464741,
          "sha512": "e5037bd35fa90191354962d11660d4831f56a7c6a76c2b028de4e493a6549c583c3c9f7181af68d3c916a85bd4384ce0cf81749b86e30eb98dbff5deeb2a9f36",
          "sha256": "120d2eff4e0988d261e5399753f4bf813ef2cf0b167c9aa4d561c26733e48198",
          "sha1": "188e5c4fefc581bc308fdb5dd15b9cfe6818356b",
          "md5": "bf0a2762b7f0e4975c81f489c9405ae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.6.jar",
          "url": "scholar-1.20.1-common-1.1.6.jar",
          "size": 464741,
          "sha512": "e5037bd35fa90191354962d11660d4831f56a7c6a76c2b028de4e493a6549c583c3c9f7181af68d3c916a85bd4384ce0cf81749b86e30eb98dbff5deeb2a9f36",
          "sha256": "120d2eff4e0988d261e5399753f4bf813ef2cf0b167c9aa4d561c26733e48198",
          "sha1": "188e5c4fefc581bc308fdb5dd15b9cfe6818356b",
          "md5": "bf0a2762b7f0e4975c81f489c9405ae9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.6-sources.jar",
          "url": "scholar-1.20.1-common-1.1.6-sources.jar",
          "size": 370673,
          "sha512": "f1978934fde06165f64fe486051d5b660ff85920b577042aae90c6207254b27349347cf25a09b5d8d0d43f79ec9ea12543df661e6e8d8c5e487f919cb58e62e8",
          "sha256": "3cd5cb5f0e1247fcf18954bebe9fafb0ac4da06453b701342645998557294d21",
          "sha1": "4f100058ff56e3714cdf7c4ae42aec78ca00924b",
          "md5": "7d88390a65c7a2a57809229a7cacf4df"
        }
      ]
    }
  ]
}
