{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-1.21.1-neoforge",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino",
          "version": {
            "requires": "2101.2.6-build.66"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.1-build.181"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.4.jar",
          "url": "exposure-1.21.1-neoforge-1.9.4.jar",
          "size": 2161107,
          "sha512": "e2b9b4393f40f421009ef97d7e909f5528ec7ca793a98bcbe5fa39318f8a7f8fe7f3e942278ce5af8606f10fc0401c22d81d710f1b567a661e4f4a9589c1d7c7",
          "sha256": "131046bb6ab66ef997114c4d89e2a56c51a09564ee8ae3122b9af67ddbe91cd8",
          "sha1": "0b9fa667851a2c4675a6f283659d22726dd922db",
          "md5": "a0e01bb77bb1da46ab616a68170f9cc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.1-15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "yeetusexperimentus-635427",
          "version": {
            "requires": "5444189"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "embeddium-908741",
          "version": {
            "requires": "6118392"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.4.jar",
          "url": "exposure-1.21.1-neoforge-1.9.4.jar",
          "size": 2161107,
          "sha512": "e2b9b4393f40f421009ef97d7e909f5528ec7ca793a98bcbe5fa39318f8a7f8fe7f3e942278ce5af8606f10fc0401c22d81d710f1b567a661e4f4a9589c1d7c7",
          "sha256": "131046bb6ab66ef997114c4d89e2a56c51a09564ee8ae3122b9af67ddbe91cd8",
          "sha1": "0b9fa667851a2c4675a6f283659d22726dd922db",
          "md5": "a0e01bb77bb1da46ab616a68170f9cc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.4-sources.jar",
          "url": "exposure-1.21.1-neoforge-1.9.4-sources.jar",
          "size": 38898,
          "sha512": "bd714542ee8dcdc0918b6a6e47272920fc2d7060229aaba4258a694b58331aeca3f74b30f0edf997611cf5eab74694cbbe778c5643dda4a1010888a77e3651ea",
          "sha256": "7e0ea768e5e7ba5f2990e0a279c88b6e3fac7d47f5072672cbfde3aae50e00d2",
          "sha1": "bafcba802ddbac9fa0a34097a5882c614aa8ee85",
          "md5": "0d72c71badf2e9748e364deb6e111ff1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.21.1-neoforge-1.9.4-dev-shadow.jar",
          "url": "exposure-1.21.1-neoforge-1.9.4-dev-shadow.jar",
          "size": 1943327,
          "sha512": "3a7f2ed89c6f89940a35c615fb11e770a9c05a4c859b517b8974fabcbde4841d510c1710348cc6c617fa720b9e6acf53efe59c3e71eb8bdf9436e5bea1dd90ab",
          "sha256": "6f2f1ce68f52b400c6cb01fbddf594b87a0c872d58619fbae88936af4fa99ba9",
          "sha1": "4ac1e7d0c35fa7235888dde4496601800f871c77",
          "md5": "8b53fa8ed6b21deb8810f80ec7cf7fdf"
        }
      ]
    }
  ]
}
