{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.exposure",
    "module": "exposure-common",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.8.jar",
          "url": "exposure-common-1.7.8.jar",
          "size": 1281424,
          "sha512": "48348033223e19dcb576c5a91149213a3e5276b63872fce2f57909fd61600bcf72df4e806cc56924f847cafce85c385680d301c9923377ca05c59d1e1df32d56",
          "sha256": "afc6c529773f3b9192e2519adb9e9214bb253baa2ff3a5a456833264d5ce77ba",
          "sha1": "fe2520c65f6a62f9363f834faa80cf2ccf76f12e",
          "md5": "73ec113e4b0a601011b01d96e5de7ea5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-common-1.7.8.jar",
          "url": "exposure-common-1.7.8.jar",
          "size": 1281424,
          "sha512": "48348033223e19dcb576c5a91149213a3e5276b63872fce2f57909fd61600bcf72df4e806cc56924f847cafce85c385680d301c9923377ca05c59d1e1df32d56",
          "sha256": "afc6c529773f3b9192e2519adb9e9214bb253baa2ff3a5a456833264d5ce77ba",
          "sha1": "fe2520c65f6a62f9363f834faa80cf2ccf76f12e",
          "md5": "73ec113e4b0a601011b01d96e5de7ea5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-common-1.7.8-sources.jar",
          "url": "exposure-common-1.7.8-sources.jar",
          "size": 923796,
          "sha512": "506edef635bf1d078b021a02bd6920d76388c2d69669302d388fe2c3b33c735026fab068656bd1ada1cce21d718716e2fe4cef19b8815a304ad2f8f7064adcf4",
          "sha256": "804bf81bd366a817f618399d163a623c0dd058836715721507cd207606dc9913",
          "sha1": "92a69d500c9157b58161df37edc1cc994efda7aa",
          "md5": "d78479fff1b3e42fe6ab189faca5e59d"
        }
      ]
    }
  ]
}
