{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-fabric",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.0.1-fabric.jar",
          "url": "horseman-fabric-1.0.1-fabric.jar",
          "size": 257903,
          "sha512": "e529ea0311289f9461f8d3ede08c14038da305fbd68337906b0115093f42d846eceadb0567bfbbcb163f0e746e0b50fccf5947207379216b4ae9db283ed3bc38",
          "sha256": "20e27c0974d0d466eaeb051e952317817e568c3444697b1cfb3e2a1854a903d4",
          "sha1": "344dddfc43a904ecd6d29392906d1104adaa47d3",
          "md5": "04ead436fb9d2fbb0b031d851f094198"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-fabric-1.0.1-fabric.jar",
          "url": "horseman-fabric-1.0.1-fabric.jar",
          "size": 257903,
          "sha512": "e529ea0311289f9461f8d3ede08c14038da305fbd68337906b0115093f42d846eceadb0567bfbbcb163f0e746e0b50fccf5947207379216b4ae9db283ed3bc38",
          "sha256": "20e27c0974d0d466eaeb051e952317817e568c3444697b1cfb3e2a1854a903d4",
          "sha1": "344dddfc43a904ecd6d29392906d1104adaa47d3",
          "md5": "04ead436fb9d2fbb0b031d851f094198"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-fabric-1.0.1-sources.jar",
          "url": "horseman-fabric-1.0.1-sources.jar",
          "size": 40519,
          "sha512": "98e09ee7f936a198b96fa365a88401d5d781625681508603cf34585e2636c207c705f9045eea162a727bec00ddb583e110e4656f85ea39020103275a26ea9bd5",
          "sha256": "c2747252f2265dff8edf6ac3052b0e7fba1ee3ccd4805b04f856d10fd3ffdd8a",
          "sha1": "d69d14d80219b60362c7594a5ba995b747abad03",
          "md5": "57ae47a7bed7572ff37c6d9d354efff3"
        }
      ]
    }
  ]
}
