{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-fabric",
    "version": "1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.9-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.9-fabric.jar",
          "size": 681054,
          "sha512": "a8271c598ca8f628b58c1a96fc24a3ecf53e7c95ca8932bdff3728033c83b9df112e26be0ccc827b4800d0fd002d6459771fc19a31792e6356b77a700b7c44e5",
          "sha256": "41a66a06d22ffe6ef4ac2d614aa5b9de4c6be4d7ac58ec7a6a5781a064319abf",
          "sha1": "bdd345dfa380aed42a98c81c53612e7104a6e1ac",
          "md5": "cc2aedc763d8440ec93abab4a736d583"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "more-chiseled-bookshelf-variants",
          "version": {
            "requires": "rb2kjXS0"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.9-fabric.jar",
          "url": "scholar-1.20.1-fabric-1.1.9-fabric.jar",
          "size": 681054,
          "sha512": "a8271c598ca8f628b58c1a96fc24a3ecf53e7c95ca8932bdff3728033c83b9df112e26be0ccc827b4800d0fd002d6459771fc19a31792e6356b77a700b7c44e5",
          "sha256": "41a66a06d22ffe6ef4ac2d614aa5b9de4c6be4d7ac58ec7a6a5781a064319abf",
          "sha1": "bdd345dfa380aed42a98c81c53612e7104a6e1ac",
          "md5": "cc2aedc763d8440ec93abab4a736d583"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-fabric-1.1.9-sources.jar",
          "url": "scholar-1.20.1-fabric-1.1.9-sources.jar",
          "size": 408122,
          "sha512": "e2a5aafb011b8a1984427f5c5815b5934d10ba14d30425435b9477691954805edd4e03467fc43286cf23a37c37b60ab55c71b9039a568ac264b3bb3025def3a8",
          "sha256": "d9a4a13d96c83bab6b0ba457e0f35fdb310b3e10cecf5fdf80303f4594508566",
          "sha1": "21d478023a922543e1e150b926c41dcb60b1e221",
          "md5": "b762e056dd4f07d4bf7afc1bdd3850a5"
        }
      ]
    }
  ]
}
