{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-26.1.2-neoforge",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "scholar-26.1.2-neoforge-1.2.4.jar",
          "url": "scholar-26.1.2-neoforge-1.2.4.jar",
          "size": 742123,
          "sha512": "244f4c4db6a8006629ac149ad24c0614d10f1fd0a26e1acce5d3941599d15ebc2fc5ffa3b7fca7b6c16bdadf5778e6171b9ca5def5033da32755d50850771750",
          "sha256": "a18e7e97796fc68780c6d9c43c26d9e23341decf5f986c3330997a996628e27a",
          "sha1": "7684d99da880252080908585249dfb82d34b868d",
          "md5": "cca6380e0552ed68a0253480ff90876e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-neoforge-1.2.4.jar",
          "url": "scholar-26.1.2-neoforge-1.2.4.jar",
          "size": 742123,
          "sha512": "244f4c4db6a8006629ac149ad24c0614d10f1fd0a26e1acce5d3941599d15ebc2fc5ffa3b7fca7b6c16bdadf5778e6171b9ca5def5033da32755d50850771750",
          "sha256": "a18e7e97796fc68780c6d9c43c26d9e23341decf5f986c3330997a996628e27a",
          "sha1": "7684d99da880252080908585249dfb82d34b868d",
          "md5": "cca6380e0552ed68a0253480ff90876e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-neoforge-1.2.4-sources.jar",
          "url": "scholar-26.1.2-neoforge-1.2.4-sources.jar",
          "size": 570507,
          "sha512": "ffc5bfc2dd1cffd9a1e9619f8168e8011a2b2798017996cb6878dc471fd4fd116722ea8096a0d67ac5e53915b2728aa48f7cc8d6476719155fcd51bddc72f644",
          "sha256": "b5c89c4d13bf0b26d07f686a55934503ef2f4bbbc3204f506f69be4d9e5665f1",
          "sha1": "50370695abf3b56d392bc43c892e5e0c4fa99d06",
          "md5": "571b56fd75f29b98b87b33f8ce88d601"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-26.1.2-neoforge-1.2.4.jar",
          "url": "scholar-26.1.2-neoforge-1.2.4.jar",
          "size": 742123,
          "sha512": "244f4c4db6a8006629ac149ad24c0614d10f1fd0a26e1acce5d3941599d15ebc2fc5ffa3b7fca7b6c16bdadf5778e6171b9ca5def5033da32755d50850771750",
          "sha256": "a18e7e97796fc68780c6d9c43c26d9e23341decf5f986c3330997a996628e27a",
          "sha1": "7684d99da880252080908585249dfb82d34b868d",
          "md5": "cca6380e0552ed68a0253480ff90876e"
        }
      ]
    }
  ]
}
