{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.thief",
    "module": "thief-26.1.1-common",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-common-api",
          "version": {
            "requires": "29.3.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.1-common-1.2.3.jar",
          "url": "thief-26.1.1-common-1.2.3.jar",
          "size": 126806,
          "sha512": "caa17fe500d1604ff6ff6c072b4bf421304c0017d67162c69b71b44f45fe3449470cdc02248885075c6bcbf25efbd59dcc426a84cd889f78d932246917bd364f",
          "sha256": "994769e8cdeb9094d9bb177284f112c327e182aad3f43fc042f5cff8405eb0de",
          "sha1": "dfa747296a3c1092188cabda27c45c1fbc5812f6",
          "md5": "7388701cde7146de613017993aa6f1d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "thief-26.1.1-common-1.2.3.jar",
          "url": "thief-26.1.1-common-1.2.3.jar",
          "size": 126806,
          "sha512": "caa17fe500d1604ff6ff6c072b4bf421304c0017d67162c69b71b44f45fe3449470cdc02248885075c6bcbf25efbd59dcc426a84cd889f78d932246917bd364f",
          "sha256": "994769e8cdeb9094d9bb177284f112c327e182aad3f43fc042f5cff8405eb0de",
          "sha1": "dfa747296a3c1092188cabda27c45c1fbc5812f6",
          "md5": "7388701cde7146de613017993aa6f1d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.1-common-1.2.3-sources.jar",
          "url": "thief-26.1.1-common-1.2.3-sources.jar",
          "size": 69779,
          "sha512": "a504be2803d24b2adc4d25ce9539a2f71d85efd85ba132d01888de5846743a669d666eeaf4b931d8204d667da081271930cf6d5b7e8d99f80d97fe1fcbea8fbc",
          "sha256": "34e60c100f1dedb02ea1a8c1b5021a2e63dff9df981a05fe01650d5c7a3d407b",
          "sha1": "ebc0f347c534652c353a782d3e93022480a3b820",
          "md5": "b3893cee053671d0d93e9bdd9146a5cc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thief-26.1.1-common-1.2.3.jar",
          "url": "thief-26.1.1-common-1.2.3.jar",
          "size": 126806,
          "sha512": "caa17fe500d1604ff6ff6c072b4bf421304c0017d67162c69b71b44f45fe3449470cdc02248885075c6bcbf25efbd59dcc426a84cd889f78d932246917bd364f",
          "sha256": "994769e8cdeb9094d9bb177284f112c327e182aad3f43fc042f5cff8405eb0de",
          "sha1": "dfa747296a3c1092188cabda27c45c1fbc5812f6",
          "md5": "7388701cde7146de613017993aa6f1d1"
        }
      ]
    }
  ]
}
