{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.scholar",
    "module": "scholar-1.20.1-common",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.4.jar",
          "url": "scholar-1.20.1-common-1.1.4.jar",
          "size": 378810,
          "sha512": "083d6ad357b30a1b7cde96f6f50d2778f0033a8aa445e6474979a55b7edb64aed43fe19889ee485618703ab4a57dcc8b902328f6cf7ad4eab2a7ff09dda8d0b5",
          "sha256": "40999d3697934637b99fd30535fe1152f4d2ff00f43333e9a0761940287c548b",
          "sha1": "420ad8e0b599cecceb703e7f3808f277e91901e4",
          "md5": "197321985be239d782c9fe5a88955dbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.4.jar",
          "url": "scholar-1.20.1-common-1.1.4.jar",
          "size": 378810,
          "sha512": "083d6ad357b30a1b7cde96f6f50d2778f0033a8aa445e6474979a55b7edb64aed43fe19889ee485618703ab4a57dcc8b902328f6cf7ad4eab2a7ff09dda8d0b5",
          "sha256": "40999d3697934637b99fd30535fe1152f4d2ff00f43333e9a0761940287c548b",
          "sha1": "420ad8e0b599cecceb703e7f3808f277e91901e4",
          "md5": "197321985be239d782c9fe5a88955dbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "scholar-1.20.1-common-1.1.4-sources.jar",
          "url": "scholar-1.20.1-common-1.1.4-sources.jar",
          "size": 283901,
          "sha512": "c3e68e88c54268f8e35e89d2f537e2b417cef62aa5e7a1294ffa7b442f02370f729f929db21b669de3f5dde16dd0329da111f52f6880d855cd8742fc255a03a0",
          "sha256": "729c5f9c9af733e2c5f67541838f437be2b6c66fa2241140ddb176b6dd96a230",
          "sha1": "38e2196f347ea2d06839f8e15ad2969b44cf2f36",
          "md5": "0ba6c580b14ca0ce9483146df2962826"
        }
      ]
    }
  ]
}
