{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.horseman",
    "module": "horseman-1.21.1-fabric",
    "version": "1.4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6155158"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.19.0.220"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.3.1.jar",
          "url": "horseman-1.21.1-fabric-1.4.3.1.jar",
          "size": 205622,
          "sha512": "40c93fb237d692eb6381f4b176c80e09a432f7c17d2bcfc401f2d892236dc487660ac2f00d2b01f768c6a0e517aefbd51f19733d3fa75607d22cec0da661b324",
          "sha256": "0057c6c8cf7706e8eb0081e78c44d8213606fa85166701d6519a9affe8e05e29",
          "sha1": "128b2bd1f8256071ce12dfd6f68d52cf0b029d3b",
          "md5": "1b4c4a733b374e0e4d1a870f094ff132"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.19.0.220"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.8.8+1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "YIfqIJ8q"
          }
        }
      ],
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.3.1.jar",
          "url": "horseman-1.21.1-fabric-1.4.3.1.jar",
          "size": 205622,
          "sha512": "40c93fb237d692eb6381f4b176c80e09a432f7c17d2bcfc401f2d892236dc487660ac2f00d2b01f768c6a0e517aefbd51f19733d3fa75607d22cec0da661b324",
          "sha256": "0057c6c8cf7706e8eb0081e78c44d8213606fa85166701d6519a9affe8e05e29",
          "sha1": "128b2bd1f8256071ce12dfd6f68d52cf0b029d3b",
          "md5": "1b4c4a733b374e0e4d1a870f094ff132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.3.1-sources.jar",
          "url": "horseman-1.21.1-fabric-1.4.3.1-sources.jar",
          "size": 18450,
          "sha512": "a039a3840968b15551a31a881a346ae7ab3e7dd2cd604978337c50d6702359b6472eecce284e5c337dfad7b711d4d84949ddc783c51e0358989e6b9892afe5b7",
          "sha256": "4242d51c9b33fecc30bc6705f620b8442319075f1b23b3fca251687d3d41224e",
          "sha1": "0d80ef647bb0ac137457cf8515278506406e84d7",
          "md5": "5b936b56113ec13043afbff42888904c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horseman-1.21.1-fabric-1.4.3.1-dev-shadow.jar",
          "url": "horseman-1.21.1-fabric-1.4.3.1-dev-shadow.jar",
          "size": 203899,
          "sha512": "caac24d0623834e7914d4b1de28b87f2dfccc03dec42fdbfa1c69e03cc0d5d8a3e66ac81239e14b59700bd541e63276bbab8d1825afb593ca4233576be795fae",
          "sha256": "e1bbf5d8e18f99546c914ceb5487b6465a1b92df750332b2e9f1676b319462ef",
          "sha1": "45d7dfcf1886d2e069db263d67e288189a8eaf75",
          "md5": "e8a163786da8b11b29eee6db43c84718"
        }
      ]
    }
  ]
}
