{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars.envelope",
    "module": "envelope-1.21.1-neoforge",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-neoforge",
          "version": {
            "requires": "2101.7.2-build.353"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.1.jar",
          "url": "envelope-1.21.1-neoforge-0.7.1.jar",
          "size": 2195114,
          "sha512": "1f1fc220b656ec21604b872b6455f7a886370634863ba5759d7a29bbae29d3bca77cf07557f126f0e4720d9a51de68d3fdbdbe6ee530da415fcfcc1c47dc822f",
          "sha256": "021f2b73f39ea9a04478fe16631272f85a7a36f1a3189b9c759a5758f9b7b5d5",
          "sha1": "77b76a41ef486b532c0b31e46ee63f5fefac016a",
          "md5": "4d7fd19f74d18ed4997704f99f054b5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "dev.ryanhcode.sable-companion",
          "module": "sable-companion-common-1.21.1",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.1.jar",
          "url": "envelope-1.21.1-neoforge-0.7.1.jar",
          "size": 2195114,
          "sha512": "1f1fc220b656ec21604b872b6455f7a886370634863ba5759d7a29bbae29d3bca77cf07557f126f0e4720d9a51de68d3fdbdbe6ee530da415fcfcc1c47dc822f",
          "sha256": "021f2b73f39ea9a04478fe16631272f85a7a36f1a3189b9c759a5758f9b7b5d5",
          "sha1": "77b76a41ef486b532c0b31e46ee63f5fefac016a",
          "md5": "4d7fd19f74d18ed4997704f99f054b5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.1-sources.jar",
          "url": "envelope-1.21.1-neoforge-0.7.1-sources.jar",
          "size": 46937,
          "sha512": "13feb24cd35d09b8b3d567682fd48d0180d06a45280c415e85e752e139c2a0cffc2903c10e899db8f22c1d7b170f1ac640031ddeaf6ea2d77a854dd62d5d6485",
          "sha256": "b3377b2ef63ba1f376b7abba17bdba3f9422d39f6506bd60d2d7c3a31a4ecaa1",
          "sha1": "752ce9bc0d80a13eff990e3e9cb9b800d7cbbfe2",
          "md5": "aca6f2f8d3ee6c6f12d0a95bb6e5631a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "envelope-1.21.1-neoforge-0.7.1-dev-shadow.jar",
          "url": "envelope-1.21.1-neoforge-0.7.1-dev-shadow.jar",
          "size": 1945567,
          "sha512": "53451a8ccee24a1b919ca9a2aafeeb936beb8e82a489fbf8a274fcbf12580e90d798c47932a65bb3ab42dcc60e4a060082d83329fb2e1ffbfdcb990b120aeebc",
          "sha256": "cb0ac38d2079adc2741279f02df3581a8e2cd62531ef64bad930c7166d1e63e6",
          "sha1": "48c0c73d6fe90d7ea0bda1504d32bc5331269598",
          "md5": "4bca9d46eaa9656539c96c947d158ba7"
        }
      ]
    }
  ]
}
